### ISSUE TITLE
[Question] Installing Fallout 3

### ISSUE THREAD

**Issue by malkavi** [lutris/lutris#198] opened 2015-06-26 07:43 UTC
Hello,
I'm trying to start playing Fallout 3 (standar) in linux with lutris. (Opensuse 13.2 x64)
I'm using git version of lutris.

The first time I have try to run fallout was with wine x.x.39 from lutris, the default version. It works as expected, installations was correct but the menu of Fallout 3 was slow, but not the game! I had started the game,save at the start and exit.

The next day I try to play, I had some errors, but I'm not sure if they were exactly these, but similar:
```
fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
```

Yesterday I try to start from scratch. Remove ~/.local/share/lutris and reinstall wine from lutris. Then, Fallout 3 error, no sound device found.
Again from scratch but installing wine from system. Then, steamerrorreporter.exe error. 
With wine from lutris again. The same, steamerrorreporter.exe error. 

Log from lutris:
```
malkavi@linux-a4ba:~> lutris -d
DEBUG    2015-06-25 23:49:12,681 [lutris]:Welcome to Lutris
DEBUG    2015-06-25 23:49:12,882 [lutriswindow]:Getting game list
DEBUG    2015-06-25 23:49:13,416 [lutriswindow]:Switching view
DEBUG    2015-06-25 23:49:14,837 [lutriswindow]:Connecting signals
INFO     2015-06-25 23:49:15,467 [lutriswindow]:Connected as malkavi
DEBUG    2015-06-25 23:49:15,472 [jobs]:Async call: sync_all
DEBUG    2015-06-25 23:49:15,472 [sync]:Syncing game library
DEBUG    2015-06-25 23:49:15,473 [jobs]:Async call: update_runtime
DEBUG    2015-06-25 23:49:15,473 [sync]:350 games in local library
DEBUG    2015-06-25 23:49:15,474 [api]:Fetching game library
DEBUG    2015-06-25 23:49:15,474 [runtime]:Updating runtime
DEBUG    2015-06-25 23:49:15,678 [runtime]:Runtime already up to date
DEBUG    2015-06-25 23:49:16,228 [sync]:350 games in remote library (inc. unpublished)
DEBUG    2015-06-25 23:49:16,381 [sync]:0 games updated
DEBUG    2015-06-25 23:49:16,382 [sync]:Syncing local steam games
DEBUG    2015-06-25 23:49:17,089 [jobs]:Async call: sync_icons
DEBUG    2015-06-25 23:49:17,094 [resources]:Fetching icons
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
DEBUG    2015-06-25 23:49:58,156 [winesteam]:Checking Steam installation
DEBUG    2015-06-25 23:49:58,170 [wine]:Detected 32bit prefix in /home/malkavi/.local/share/lutris/runners/winesteam/prefix
DEBUG    2015-06-25 23:49:58,675 [wine]:Setting wine registry key : HKEY_CURRENT_USER\Software\Wine\Explorer\Desktops\Desktop_res to 800x600
DEBUG    2015-06-25 23:49:58,676 [wine]:Detected 32bit prefix in /home/malkavi/.local/share/lutris/runners/winesteam/prefix
DEBUG    2015-06-25 23:49:58,726 [wine]:Setting wine registry key : HKEY_CURRENT_USER\Software\Wine\Direct3D\StrictDrawOrdering to disabled
DEBUG    2015-06-25 23:49:58,726 [wine]:Detected 32bit prefix in /home/malkavi/.local/share/lutris/runners/winesteam/prefix
fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
DEBUG    2015-06-25 23:49:58,779 [wine]:Setting wine registry key : HKEY_CURRENT_USER\Software\Wine\DirectInput\MouseWarpOverride to enable
DEBUG    2015-06-25 23:49:58,780 [wine]:Detected 32bit prefix in /home/malkavi/.local/share/lutris/runners/winesteam/prefix
DEBUG    2015-06-25 23:49:58,835 [wine]:Setting wine registry key : HKEY_CURRENT_USER\Software\Wine\Explorer\Desktop to off
DEBUG    2015-06-25 23:49:58,836 [wine]:Detected 32bit prefix in /home/malkavi/.local/share/lutris/runners/winesteam/prefix
DEBUG    2015-06-25 23:49:58,873 [wine]:Setting wine registry key : HKEY_CURRENT_USER\Software\Wine\Direct3D\OffscreenRenderingMode to fbo
DEBUG    2015-06-25 23:49:58,873 [wine]:Detected 32bit prefix in /home/malkavi/.local/share/lutris/runners/winesteam/prefix
DEBUG    2015-06-25 23:49:58,912 [wine]:Setting wine registry key : HKEY_CURRENT_USER\Software\Wine\Direct3D\RenderTargetLockMode to readtex
DEBUG    2015-06-25 23:49:58,912 [wine]:Detected 32bit prefix in /home/malkavi/.local/share/lutris/runners/winesteam/prefix
DEBUG    2015-06-25 23:49:58,955 [wine]:Detected 32bit prefix in /home/malkavi/.local/share/lutris/runners/winesteam/prefix
DEBUG    2015-06-25 23:49:58,956 [game]:Launching Fallout 3: {'command': ['wine', '/home/malkavi/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/Steam.exe', '-no-dwrite', 'steam://rungameid/22300'], 'env': {'WINEPREFIX': '/home/malkavi/.local/share/lutris/runners/winesteam/prefix', 'WINEDEBUG': '-all', 'WINEARCH': 'win32'}}
DEBUG    2015-06-25 23:49:58,957 [thread]:Command env: LD_LIBRARY_PATH="/home/malkavi/.local/share/lutris/runtime/steam/lutris-override32:/home/malkavi/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/malkavi/.local/share/lutris/runtime/steam/i386/lib:/home/malkavi/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/malkavi/.local/share/lutris/runtime/steam/i386/usr/lib:/home/malkavi/.local/share/lutris/runtime/steam/lutris-override64:/home/malkavi/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/malkavi/.local/share/lutris/runtime/steam/amd64/lib:/home/malkavi/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/malkavi/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH" WINEARCH="win32" STEAM_RUNTIME="/home/malkavi/.local/share/lutris/runtime/steam" WINEPREFIX="/home/malkavi/.local/share/lutris/runners/winesteam/prefix" WINEDEBUG="-all"
DEBUG    2015-06-25 23:49:58,957 [thread]:Running command: "wine" "/home/malkavi/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/Steam.exe" "-no-dwrite" "steam://rungameid/22300"
16308   D       ntlm_auth
16306   D       ntlm_auth
fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
16340   S       Program
16350   R       ntlm_auth
16340   S       Program
16353   S       winedbg
16340   S       Program
16353   S       winedbg
16340   S       Program
16353   S       winedbg
16340   S       Program
16353   S       winedbg
16340   R       Program
16353   R       winedbg
16376   S       Program
16376   S       Program
16387   S       winedbg
```

Launching with system wine using the lutris prefix (I have copied the command from lutris debug output), It works!! and the menus isn't slow.

```
WINEPREFIX="/home/malkavi/.local/share/lutris/runners/winesteam/prefix" "wine" "/home/malkavi/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/Steam.exe" "-no-dwrite" "steam://rungameid/22300"
```

Why launching directly from cli works, but from lutris has stopped working?  (and the fisrt time with slow menu)

I miss something like a guide to install games with examples. :p 

Thanks for the work!

**Comment by Xodetaetl** [comment] 2015-08-05 10:27
Hi, Steam doesn't work with our current default Wine version (1.7.39) in the Lutris dev branch. It *should* work with your system version though, I'm not sure why you had issues with that too. Perhaps Steam was already running in the background or something (we also have issues with managing the Steam process). Can you confirm it still doesn't work with system Wine selected?

That said, I've seen the "mountmgr:harddisk_ioctl" errors on one occasion myself, I'll try to reproduce it.

Oh and sorry about the long response delay.

**Comment by strycore** [comment] 2015-08-05 17:45
I've deleted version 1.7.39 which didn't run any steam games, default is now 1.7.48.

Also, the "mountmgr:harddisk_ioctl" message isn't related to this issue, it's shown on recent versions of wine for unknown reasons but doesn't keep wine from working properly.

Closing this issue since 1.7.39 is no more.

**Closed by strycore** 2015-08-05 17:45 UTC
Labels: bug
