### ISSUE TITLE
Problems with deselecting or selecting different game when one is already running

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1747] opened 2019-02-11 01:32 UTC
A couple things happen:

- Stop button quits functioning. Have to use "Kill all Wine processes" button instead
- Game log gets wiped. Probably related to #1668 
- Stop button doesn't change back after killing Wine. Only changes back when deselecting and reselecting game

**Comment by tannisroot** [comment] 2019-02-17 06:26
This should be fixed in master by https://github.com/lutris/lutris/commit/6ad94adeb21ad353dc5903290c2ed8aba64476d8

**Comment by tannisroot** [comment] 2019-03-02 20:57
Yeah it was. Closing as I can't reproduce it in master.

**Closed by tannisroot** 2019-03-02 20:57 UTC
