### ISSUE TITLE
Tray icon not showing on Ubuntu 23.10 (Wayland session) and incorrect window size.

### ISSUE THREAD

**Issue by JMarcosHP** [lutris/lutris#5249] opened 2024-01-18 04:34 UTC
Lutris does not show the icon in the system tray when running in a Gnome Wayland session.

It threw this critical GTK error when running it from the terminal:

`2024-01-17 22:28:44,003: Starting Lutris 0.5.16
2024-01-17 22:28:44,004: Running AMD Mesa driver 23.2.1 on AMD Radeon Graphics (gfx1102, LLVM 15.0.7, DRM 3.56, 6.7.0-x64v3-xanmod1) (0x7480)
2024-01-17 22:28:44,004: GPU: 1002:7480 1462:5029 (amdgpu drivers)`

`(lutris:41540): Gtk-CRITICAL **: 22:28:56.522: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`

Wayland session screenshot:
![Captura desde 2024-01-17 22-29-08](https://github.com/lutris/lutris/assets/58377032/45225afa-e15f-4dfc-ba66-6780add8b971)

X11 session screenshot:
![Captura desde 2024-01-17 22-36-41](https://github.com/lutris/lutris/assets/58377032/1322671a-d4f6-4447-8278-5532786e1402)

**Comment by danieljohnson2** [comment] 2024-01-18 09:36
Does the tray icon show in X11? If so, this sounds like #4934 - you need to have the appindicators package installed, singe the GNOME status-icon stuff is deprecated and not likely to be updated to work in Wayland. The package needed was ``gir1.2-appindicator3-0.1``; you may  need to install that.

**Comment by danieljohnson2** [comment] 2024-01-18 09:44
I think the too-narrow preferences window is actually because the labels are too wide- that last option came out much longer than in English.

I have changed the code in master so that if the label here will wrap instead of scrolling; should look better.

**Comment by JMarcosHP** [comment] 2024-01-18 18:13
> Does the tray icon show in X11? If so, this sounds like #4934 - you need to have the appindicators package installed, singe the GNOME status-icon stuff is deprecated and not likely to be updated to work in Wayland. The package needed was `gir1.2-appindicator3-0.1`; you may need to install that.

Thanks, I installed `gir1.2-appindicator3-0.1` package and now it works, I don't know why Ubuntu doesn't include this for compatibility.

**Comment by danieljohnson2** [comment] 2024-01-19 00:35
I've made some more changes here; the 'Status Icon' preference will no longer appear on Wayland if AppInidicators are not available, and we won't even try Gtk.StatusIcon then. That should remove the Gtk-CRITICAL message you got.

I've put up a PR to actually add a dependency on AppIndicators, which is already the preferred way for Lutris to do the status icon. If that gets merged, then when you install Lutris you'll just get AppIndicators, and it should Just Work even on Wayland.

**Comment by strycore** [comment] 2024-01-20 02:25
It's not our job to fix tray icons in Gnome Wayland. Gnome has been actively trying to get rid of tray icons and there's always some weird trick to do to get them somewhat working (the Wine tray icons are still unusable, you can't click on them)

There is no documentation on how to properly implement tray icons in Gnome because Gnome just wants them gone.

If you want proper tray icon support, just switch to KDE.

**Closed by strycore** 2024-01-20 02:25 UTC

**Comment by JMarcosHP** [comment] 2024-01-20 02:49
> If you want proper tray icon support, just switch to KDE.

It's not as simple as you said, there is a workflow behind it that many people are already used to.

I have tested lutris in Gnome's implementation of Opensuse Tumbleweed and it works as it should, so there is no excuse not to solve it on the Debian side just by adding missing dependencies to the package.

Fix your shit instead of just throwing hate into a desktop environment, people use what works best for them and aren't willing to change it if it makes them money.

Saying things is easy but doing it is hard.

**Comment by strycore** [comment] 2024-01-20 02:58
We're willing to do the work on our part at the condition we have a stable working environment. 

The problem is: no  matter what we do, there always seem to be some kind of setup in which the tray icons won't work in Gnome. Maybe because it needs some Gnome Shell Extension, maybe because it's missing some dependencies. 

The thing is, no matter what the solution is, it's not our problem. When you install Gnome whether it's on SUSE or Debian **it should install whatever is needed to display tray icons correctly**. It's to the role of apps to add features to desktop environment.

What if enabling tray icons require a Gnome Shell extension? We can't add that as a Lutris dependency! That's entirely on Gnome's end to provide a workable environment.

And Gnome seems to be pretty serious about killing tray icons, so it's not really a battle we can win.

**Comment by strycore** [comment] 2024-01-20 02:59
I will do something about this when I know how this is dealt with with Steam, Discord and Nextcloud.

**Comment by danieljohnson2** [comment] 2024-01-20 10:41
Hang on there; does Gtk.StatusIcon work on KDE *on Wayland*? My read of [the docs](https://docs.gtk.org/gtk3/class.StatusIcon.html) is that they only work on X11, but they do work on GNOME/X11.

My code for this doesn't detect GNOME, it detects X11.

GNOME/GTK is a moving target; they love to move your cheese and hate compatibility. Some people hate that, but I see some virtues to it (though I think they go too far).

I don't *want* an eternity of Windows 95 UI, and the notification tray is one of the things we could afford to get rid of. We're using it as a another flavor of 'minimize'; GNOME has two of those already.
