### ISSUE TITLE
FEATURE: Game details view

### ISSUE THREAD

**Issue by cazzoo** [lutris/lutris#4667] opened 2022-12-21 23:21 UTC
It would be nice to have a view (sub-window or side-window) when selecting a game from the game list.
Indeed, having a small resumé scrapped from IGDB would be a killer-feature.

I didn't see any related feature like this one in the backlog but if any, feel free to close it as duplicate of the other one.

**Comment by danieljohnson2** [comment] 2022-12-21 23:53
There is the list view mode, which shows more information about the games. Not a lot.

What do you think Lutris should be showing?

And are you thinking this would be in the main windows, or the add-game search window?

**Comment by cazzoo** [comment] 2022-12-22 03:49
I'm not fully sure but getting to any often game page shows some game rankings (I don't know where this tank comes from), a pitch, the genre and why not some screenshot thumbnails. 
Just thinking about something that other front ends / platforms offeres to get lutris more the tool/manager to replace the others

**Comment by duarm** [comment] 2022-12-23 17:21
this feature can be a bridge to the 'better search' feature lutris will get some day, the "save more info from games" part of it at least, the open 'categories' PR too. My use case is to be able to search through my vast library of games for games of specific genres and such.

**Comment by cazzoo** [comment] 2022-12-23 17:51
How far are we from these features? Do you have a PR link?

**Comment by duarm** [comment] 2022-12-24 00:04
#4482 allows you to categorize your library entries. What I meant by "feature lutris will get some day" is that the feature in question is an obvious improvement, not that any work is being done on that front.

**Comment by strycore** [comment] 2023-06-02 00:32
I believe this is a duplicate of #1331

**Closed by strycore** 2023-06-02 00:32 UTC
