### ISSUE TITLE
DgVoodoo2, EAC runtimes and BattleEye runtimes are out of date.

### ISSUE THREAD

**Issue by LethalManBoob** [lutris/lutris#4751] opened 2023-02-16 00:56 UTC
### Bug description

DgVoodoo2, EAC runtimes and BattleEye runtimes are out of date. I do not think it would cause any issue to upgrade them. I used the runtimes from steam. They work perfectly fine on the division 2.

### How to Reproduce

;v

### Expected behavior

;v

### Log output

```shell
;v
```

### System Information

```shell
;v
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Smoukus** [comment] 2023-02-16 19:21
So are DXVK and VKD3D

**Comment by LethalManBoob** [comment] 2023-02-16 19:24
> So are DXVK and VKD3D

DXVK is an issue of compatability with new drivers are new versions only work with new drivers. Although having the option of selecting new drivers and runtimes would be greatly appreciated. I dont know why lutris hasent worked to include an option of installing runtimes manually. 

Vkd3d im not so sure has the compat problem but for eac and battleye runtimes. certainly not. At least replacing them is a one time affair. and vkd3d and dxvk can be supplimented with manual 3rd party programs.

**Comment by Smoukus** [comment] 2023-02-16 19:28
> I dont know why lutris hasent worked to include an option of installing runtimes manually.

You can easily manually install runtimes. That has been a thing for long time already.

DXVK for example:
Place the dxvk version that you want here: `/home/smokus/.local/share/lutris/runtime/dxvk/`
![image](https://user-images.githubusercontent.com/48409293/219467324-1b074fbc-cdde-4e34-a895-3caad8bc85c9.png)

In Lutris manually type in the name of the dxvk's directory that you wish to use:
![image](https://user-images.githubusercontent.com/48409293/219467295-fc934a94-a748-4915-a9ad-a3c8be737601.png)

Same applies for VKD3D

**Comment by LethalManBoob** [comment] 2023-02-17 00:43
> > I dont know why lutris hasent worked to include an option of installing runtimes manually.
> 
> You can easily manually install runtimes. That has been a thing for long time already.
> 
> DXVK for example: Place the dxvk version that you want here: `/home/smokus/.local/share/lutris/runtime/dxvk/` ![image](https://user-images.githubusercontent.com/48409293/219467324-1b074fbc-cdde-4e34-a895-3caad8bc85c9.png)
> 
> In Lutris manually type in the name of the dxvk's directory that you wish to use: ![image](https://user-images.githubusercontent.com/48409293/219467295-fc934a94-a748-4915-a9ad-a3c8be737601.png)
> 
> Same applies for VKD3D

Yes and this can also be done with protonup-qt but the point is that it should be as seamless as possible

**Comment by GloriousEggroll** [comment] 2023-03-22 23:50
closing, resolved, duplicate of https://github.com/lutris/lutris/issues/4723

**Closed by GloriousEggroll** 2023-03-22 23:50 UTC
