### ISSUE TITLE
Need better feedback that virtual desktop is not supported with wine-GE

### ISSUE THREAD

**Issue by y0nei** [lutris/lutris#5196] opened 2023-12-20 08:59 UTC
This is the latest [GloriousEggroll/wine-ge-custom](https://github.com/GloriousEggroll/wine-ge-custom) I got working with this game on Lutris. All further versions return error:
```
terminate called after throwing an instance of 'dxvk::DxvkError'
Monitored process exited.
Initial process has exited (return code: 768)
Exit with return code 768
```
I do have everything properly installed, all wine dependencies and 32 bit libs (`mesa` & `lib32-mesa` included)
`pacman -Qs vulkan`:
```
local/lib32-vulkan-icd-loader 1.3.269-1
    Vulkan Installable Client Driver (ICD) Loader (32-bit)
local/lib32-vulkan-intel 1:23.3.1-1
    Intel's Vulkan mesa driver (32-bit)
local/spirv-tools 2023.5-1 (vulkan-devel)
    API and commands for processing SPIR-V modules
local/vkd3d 1.9-1
    Direct3D 12 to Vulkan translation library By WineHQ
local/vulkan-headers 1:1.3.269-1 (vulkan-devel)
    Vulkan header files
local/vulkan-icd-loader 1.3.269-1
    Vulkan Installable Client Driver (ICD) Loader
local/vulkan-intel 1:23.3.1-1
    Intel's Vulkan mesa driver
local/vulkan-tools 1.3.269-1 (vulkan-devel)
    Vulkan Utilities and Tools
local/vulkan-validation-layers 1.3.268.0-1 (vulkan-devel)
    Vulkan Validation Layers
``` 
My iGPU is an `Intel UHD620`, the game was installed using the CD/DVD method

Help resolving this issue would be much appreciated

**Comment by appoloin** [comment] 2023-12-20 11:49
I get this 'dxvk::DxvkError' if I use the virtual desktop option, and it started happening after lutris-GE-Proton8-8

**Comment by y0nei** [comment] 2023-12-20 12:10
> I get this 'dxvk::DxvkError' if I use the virtual desktop option, and it started happening after lutris-GE-Proton8-8

Oh yea, disabling virtual desktop indeed fixes it for some reason.

**Comment by strycore** [comment] 2023-12-20 12:12
virtual desktop is not supported with wine-GE, we have to add a warning for this

**Comment by danieljohnson2** [comment] 2023-12-21 00:04
There's a PR for the warning. Warning phrasing open to suggestions of course.

But this makes we wonder if we can get more recent 'vanilla' Wine versions, I think we have none of those after Wine 7. Wine-GE is glorious and all, but I likes the virtual desktop feature.

**Comment by strycore** [comment] 2023-12-21 00:15
Wine-GE is the **ONLY** version of Wine supported by Lutris. I'll reword the message to reflect that.

**Comment by danieljohnson2** [comment] 2023-12-21 00:16
Lame!

**Comment by strycore** [comment] 2023-12-21 00:21
What use case do you have for the virtual desktop?

**Comment by danieljohnson2** [comment] 2023-12-21 00:28
For virtual desktop? For some games it enables closing the game with Alt-F4, when the game itself does not respect that, or when it won't even let you alt-tab away from it and back to Lutris.

There have also been games that would only run on a virtual desktop, though perhaps that's not true if you have GE's special sauce. I've not seen it lately.

For 'vanilla' wine? GOG installers work reliably on them, so far I can tell, and that's my workaround for the odd bug where the GOG installer window won't become visible. Though I don't really know if that's a GE thing or a Wine 8 thing, but I've seen it happen in the last two months.

**Comment by strycore** [comment] 2023-12-21 00:31
Lutris does not use vanilla Wine. Everything is supposed to work on Wine-GE. GOG installers work with Wine-GE. If they don't, file a bug report. 

Gamescope solves pretty much everything the virtual desktop was doing.

**Comment by danieljohnson2** [comment] 2023-12-21 00:33
Lame!

But its your show. If you make Lutris so pure it won't work for me, I'll just move to something else.

**Comment by strycore** [comment] 2023-12-21 00:39
The goal is not to make Lutris not work on some setups. The goal is to make every setup work with Lutris.

Is the GOG installer issue referenced anywhere?

**Comment by danieljohnson2** [comment] 2023-12-21 00:41
Ambitious!

I think #4764 is GOG invisibility issue. I don't know to repro it, but it happens.

**Comment by strycore** [comment] 2023-12-21 00:50
My plan is to make "using an older wine" or "using vanilla wine" a thing of the past.
I want to make it as hard as possible to use anything other than Wine-GE so the bugs are reported and fixed rapidly.

**Comment by danieljohnson2** [comment] 2023-12-21 00:52
It's your show, you do you. We'll see how it works.

I'm not trying to wrestle the direction of the project away from you, even though I don't always agree. I contribute; you lead.

**Comment by strycore** [comment] 2023-12-21 01:01
This cannot work if I don't get everyone on board. 
I can't be the only one wanting to push forward Wine-GE while everyone else is clinging to ancient Wine versions.
There is some preliminary code for tracking regressions on the Lutris website. Next step is to go through every installer with a pinned wine version and confirm regressions with a link to a bugtracker.

**Comment by danieljohnson2** [comment] 2023-12-21 01:01
Hmm. I'd like to suggest that we should not show the "virtual desktop = bad" warning unless the user has that setting turned on; warnings that users can't avoid get ignored.

Maybe this should be an advanced option too.

**Comment by danieljohnson2** [comment] 2023-12-21 01:01
I use the GE stuff whenever possible, I assure you.

**Comment by strycore** [comment] 2023-12-21 01:08
> I'd like to suggest that we should not show the "virtual desktop = bad" warning unless the user has that setting turned on; warnings that users can't avoid get ignored.

Everyone needs to know the virtual desktop is no longer supported even before they attempt enabling it.

**Comment by y0nei** [comment] 2023-12-21 06:13
> What use case do you have for the virtual desktop?

Window resizing and tiling works better on Wayland compositors for me.

**Comment by appoloin** [comment] 2023-12-21 09:53
> What use case do you have for the virtual desktop?

I have 3 games that need a virtual desktop, these are Dark Fall 1,2 and Metro  2033 remaster/release/money cow.  

Dark Fall uses Macromedia so one day it might end up in Scummvm but in the mean time I've tried dxwnd and dgvoodoo to fix the display problems but those didn't work only solution was drop down to wine8-8 and use the virtual desktop.   

Metro will crash if you try changing graphic settings without the virtual desktop


Ps
Some scripts switch on the virtual desktop ie Fallout 3

**Comment by strycore** [comment] 2023-12-21 11:59
I tested Metro 2033 and Dark Fall1, both worked without the virtual desktop. For Dark Fall, I got the game to display properly with Gamescope. 

We'll have to review scripts using the virtual desktop and disable it when not absolutely needed.

@y0nei if you have an Intel chipset, you are probably running into https://github.com/ValveSoftware/gamescope/issues/356
You can workaround this by setting INTEL_DEBUG=norbc but this comes at a performance cost.

**Comment by strycore** [comment] 2023-12-28 00:48
Since we're assured the game will crash when virtual desktops is enabled with Wine-GE, we should also have a warning dialog when launching the game.

**Comment by strycore** [comment] 2024-01-11 03:06
i didn't put a warning dialog (just a warning message on the command line) but virtual desktop setting won't be applied when used in conjunction with Wine-GE or Proton.

**Closed by strycore** 2024-01-11 03:06 UTC
Labels: bug

**Comment by manuth** [comment] 2024-01-16 15:27
I actually have a game (Rayman 3: Hoodlum's Havoc) that made use of the "Virtual Desktop" feature as tabbing out of the game and bringing the game back to focus causes it to crash otherwise.

With "Virtual Desktop" being disabled now, all I could try was activating Gamescope (which didn't even let me start the game).

Do you guys think this is worth a separate issue? Or should I rather make a post on some StackExchange website?

**Comment by strycore** [comment] 2024-01-24 04:14
I have Rayman 3. Here, on Nobara 39, Plasma Wayland and Wine-GE 8-25 Rayman 3 runs well and does not crash when alt-tabbing out of the game or when going back in.  The use  of gamescope isn't necessary.

Once again, I cannot find a game that genuinely needs virtual desktop. I thought I had one with Unreal Tournament 2003 but no, turns out it works fine with Proton after all.

Also please note that if a game crashes when alt-tabbing on Gnome but not on Plasma then this issue should be reported to Gnome. (Gnome is used as an example here but it's valid for XFCE, i3, etc) And if the crash happens on X11 and not Wayland, don't bother reporting it to anyone because no one is interested in fixing X11 bugs in 2024. Just switch to Wayland. If the crash is Nvidia exclusive then... just be patient I guess and stick with an older Wine build.

**Comment by manuth** [comment] 2024-01-27 14:48
Thank you so much for trying it out!
Sadly, alt-tabbing still doesn't work for me. I'm using plasma, wayland and the most recent Proton GE version.

But I'm 100% sure that I once had Rayman 3 x BetterRayman3 running with alt-tabbing working without having changed anything knowingly.

If I have any news, I'll update this issue. I don't think it's worth opening a new issue for an error that only seems to occur for me (?)
