### ISSUE TITLE
Winetricks not working

### ISSUE THREAD

**Issue by Ornim** [lutris/lutris#434] opened 2016-11-14 03:26 UTC
Steps,
Open > Select Winesteam runner > Right click on game (GTR Evolution) > click on Winetricks,  Nothing happens.

Ran it through the terminal, this is what happened

> ***@***-GA-78LMT-S2P:~$ lutris
INFO     2016-11-14 09:24:54,696 [service]:Welcome to Lutris
INFO     2016-11-14 09:24:56,360 [lutriswindow]:Connected to lutris.net as ***
Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-1.9.23
zenity: /home/***/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)
zenity: /home/***/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)
zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: sqlite3_errstr

**Comment by strycore** [comment] 2016-11-14 03:46
what happens when you rename /home/amdroy/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3 ?

**Comment by Ornim** [comment] 2016-11-14 04:25
this happens

> zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: sqlite3_errstr

**Comment by strycore** [comment] 2016-11-14 05:00
Works for me

**Comment by Brunfunstudios** [comment] 2016-11-14 14:32
I got the same Error:
```
DEBUG    2016-11-14 15:25:07,485 [system]:Executing which xdg-user-dir
DEBUG    2016-11-14 15:25:07,501 [system]:Executing which xdg-user-dir
DEBUG    2016-11-14 15:25:09,766 [thread]:Command env: WINEARCH="win32" LD_LIBRARY_PATH="/home/user/.local/share/lutris/runtime/lib32:/home/user/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/user/.local/share/lutris/runtime/steam/i386/lib:/home/user/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/user/.local/share/lutris/runtime/steam/i386/usr/lib:/home/user/.local/share/lutris/runtime/lib64:/home/user/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/user/.local/share/lutris/runtime/steam/amd64/lib:/home/user/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/user/.local/share/lutris/runtime/steam/amd64/usr/lib" WINEPREFIX="/home/user/Games/paladins" WINE="/home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine" 
DEBUG    2016-11-14 15:25:09,767 [thread]:Running command: "/usr/share/lutris/bin/winetricks" "-q"
DEBUG    2016-11-14 15:25:09,767 [thread]:Storing environment variable WINEARCH to win32
DEBUG    2016-11-14 15:25:09,768 [thread]:Storing environment variable LD_LIBRARY_PATH to /home/user/.local/share/lutris/runtime/lib32:/home/user/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/user/.local/share/lutris/runtime/steam/i386/lib:/home/user/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/user/.local/share/lutris/runtime/steam/i386/usr/lib:/home/user/.local/share/lutris/runtime/lib64:/home/user/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/user/.local/share/lutris/runtime/steam/amd64/lib:/home/user/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/user/.local/share/lutris/runtime/steam/amd64/usr/lib
DEBUG    2016-11-14 15:25:09,768 [thread]:Storing environment variable WINEPREFIX to /home/user/Games/paladins
DEBUG    2016-11-14 15:25:09,768 [thread]:Storing environment variable WINE to /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-1.9.5 (Staging)
DEBUG    2016-11-14 15:25:11,269 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:25:11,328 [thread]:6979  S   winetricks
DEBUG    2016-11-14 15:25:11,328 [thread]:7534  None    None
DEBUG    2016-11-14 15:25:11,328 [thread]:7023  S   HiPatchService.
zenity: /home/user/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)
zenity: /home/user/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)
zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: sqlite3_errstr
DEBUG    2016-11-14 15:25:12,770 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:25:12,838 [thread]:6979  Z   winetricks
DEBUG    2016-11-14 15:25:12,839 [thread]:7023  S   HiPatchService.
DEBUG    2016-11-14 15:25:14,271 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:25:14,331 [thread]:6979  Z   winetricks
DEBUG    2016-11-14 15:25:14,331 [thread]:7023  S   HiPatchService.
DEBUG    2016-11-14 15:25:15,772 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:25:15,826 [thread]:6979  Z   winetricks
DEBUG    2016-11-14 15:25:15,826 [thread]:All children terminated
DEBUG    2016-11-14 15:25:17,272 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:25:17,327 [thread]:No children left in thread
```

If i rename the file like suggested:
```
DEBUG    2016-11-14 15:30:41,630 [system]:Executing which xdg-user-dir
DEBUG    2016-11-14 15:30:41,646 [system]:Executing which xdg-user-dir
DEBUG    2016-11-14 15:30:44,067 [thread]:Command env: WINEARCH="win32" WINE="/home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine" LD_LIBRARY_PATH="/home/user/.local/share/lutris/runtime/lib32:/home/user/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/user/.local/share/lutris/runtime/steam/i386/lib:/home/user/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/user/.local/share/lutris/runtime/steam/i386/usr/lib:/home/user/.local/share/lutris/runtime/lib64:/home/user/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/user/.local/share/lutris/runtime/steam/amd64/lib:/home/user/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/user/.local/share/lutris/runtime/steam/amd64/usr/lib" WINEPREFIX="/home/user/Games/paladins" 
DEBUG    2016-11-14 15:30:44,067 [thread]:Running command: "/usr/share/lutris/bin/winetricks" "-q"
DEBUG    2016-11-14 15:30:44,067 [thread]:Storing environment variable WINEARCH to win32
DEBUG    2016-11-14 15:30:44,067 [thread]:Storing environment variable WINE to /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:30:44,068 [thread]:Storing environment variable LD_LIBRARY_PATH to /home/user/.local/share/lutris/runtime/lib32:/home/user/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/user/.local/share/lutris/runtime/steam/i386/lib:/home/user/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/user/.local/share/lutris/runtime/steam/i386/usr/lib:/home/user/.local/share/lutris/runtime/lib64:/home/user/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/user/.local/share/lutris/runtime/steam/amd64/lib:/home/user/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/user/.local/share/lutris/runtime/steam/amd64/usr/lib
DEBUG    2016-11-14 15:30:44,068 [thread]:Storing environment variable WINEPREFIX to /home/user/Games/paladins
Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-1.9.5 (Staging)
DEBUG    2016-11-14 15:30:45,569 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:30:45,630 [thread]:8317  R   winetricks
DEBUG    2016-11-14 15:30:45,631 [thread]:8361  S   HiPatchService.
zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: sqlite3_errstr
DEBUG    2016-11-14 15:30:47,070 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:30:47,140 [thread]:8317  Z   winetricks
DEBUG    2016-11-14 15:30:47,140 [thread]:8361  S   HiPatchService.
DEBUG    2016-11-14 15:30:48,571 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:30:48,640 [thread]:8317  Z   winetricks
DEBUG    2016-11-14 15:30:48,641 [thread]:8361  S   HiPatchService.
DEBUG    2016-11-14 15:30:50,072 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:30:50,131 [thread]:8317  Z   winetricks
DEBUG    2016-11-14 15:30:50,132 [thread]:All children terminated
DEBUG    2016-11-14 15:30:51,572 [system]:Executing fuser /home/user/.local/share/lutris/runners/wine/staging-1.9.5-i386/bin/wine
DEBUG    2016-11-14 15:30:51,640 [thread]:No children left in thread
```
But still no winetricks window
`

**Comment by strycore** [comment] 2016-11-14 17:51
Pasting the error is not enough, I can't do anything with this. As I said, I don't have that problem, otherwise it would already be fixed.

As I don't have access to your machines, I need more information.

Please read this: http://wiki.lutris.net/index.php/Runtime and provide the bug report with the appropriate info.

**Comment by Konfuz** [comment] 2016-11-17 10:13
I could not reproduce the exact error with lutris 0.4.2 – I however ran into a different problem with pango that prevented any text on the winetricks-window to be displayed correctly (its just boxes). 

```
DEBUG    2016-11-17 10:55:00,469 [thread]:Command env: WINE="/usr/bin/wine" WINEARCH="win64" WINEPREFIX="/home/redacted/.wine" LD_LIBRARY_PATH="/home/redacted/.local/share/lutris/runtime/lib32:/home/redacted/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/redacted/.local/share/lutris/runtime/steam/i386/lib:/home/redacted/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/redacted/.local/share/lutris/runtime/steam/i386/usr/lib:/home/redacted/.local/share/lutris/runtime/lib64:/home/redacted/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/redacted/.local/share/lutris/runtime/steam/amd64/lib:/home/redacted/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/redacted/.local/share/lutris/runtime/steam/amd64/usr/lib" 
DEBUG    2016-11-17 10:55:00,469 [thread]:Running command: "/usr/share/lutris/bin/winetricks" "-q"
DEBUG    2016-11-17 10:55:00,470 [thread]:Storing environment variable WINE to /usr/bin/wine
DEBUG    2016-11-17 10:55:00,470 [thread]:Storing environment variable WINEARCH to win64
DEBUG    2016-11-17 10:55:00,470 [thread]:Storing environment variable WINEPREFIX to /home/redacted/.wine
DEBUG    2016-11-17 10:55:00,471 [thread]:Storing environment variable LD_LIBRARY_PATH to /home/redacted/.local/share/lutris/runtime/lib32:/home/redacted/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/redacted/.local/share/lutris/runtime/steam/i386/lib:/home/redacted/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/redacted/.local/share/lutris/runtime/steam/i386/usr/lib:/home/redacted/.local/share/lutris/runtime/lib64:/home/redacted/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/redacted/.local/share/lutris/runtime/steam/amd64/lib:/home/redacted/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/redacted/.local/share/lutris/runtime/steam/amd64/usr/lib
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-1.9.22 (Staging)
(zenity:20676): Pango-CRITICAL **: No modules found:
No builtin or dynamically loaded modules were found.
PangoFc will not work correctly.
This probably means there was an error in the creation of:
  '/etc/pango/pango.modules'
You should create this file by running:
  pango-querymodules > '/etc/pango/pango.modules'
(zenity:20676): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='latin'
(zenity:20676): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='common'
``` 
I think this is a problem with lutris, since both running 
`/usr/bin/winetricks -q`
and 
`/usr/share/lutris/bin/winetricks -q`
works flawlessly

**Comment by strycore** [comment] 2016-11-22 02:25
I have added a script to generate a report on users configurations, it may not be complete yet but I will complete it overtime.

Here's the script, can you send me back the results? 

https://raw.githubusercontent.com/lutris/lutris/master/share/lutris/bin/desktop_info.sh

**Comment by Konfuz** [comment] 2016-11-22 14:40
Here are mine.

[lutris-desktop-info.txt](https://github.com/lutris/lutris/files/606664/lutris-desktop-info.txt)

**Comment by strycore** [comment] 2016-11-22 18:50
Ok, so it's clearly a runtime issue. Please apply the method explained in the last paragraph of this page: http://wiki.lutris.net/index.php/Runtime and I'll fix the runtime.

**Comment by Konfuz** [comment] 2016-11-22 22:37
It took me some time, but I found our suspect:  `~/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0`

It works flawlessly when I remove both
```
libpango-1.0.so.0
libpangoft2-1.0.so.0
```

When I only remove 
```
libpango-1.0.so.0
```
winetricks is bugged, as described

However when I just remove 
```
libpangoft2-1.0.so.0
```
winetricks will segfault, so I cannot test what role _libpango-1.0.so.0_ has in this.

**Comment by strycore** [comment] 2016-11-22 23:07
Alright, I have removed all libpango related libs from the Steam runtime. Restart your Lutris client and the new Steam runtime will be downloaded. You can then confirm if this fixes the issue.

**Comment by Konfuz** [comment] 2016-11-23 00:32
fix confirmed, nice work!

**Comment by strycore** [comment] 2016-11-23 03:17
cool :D

**Comment by bradgy** [comment] 2017-01-25 16:42
I know this is closed but it looks like OP's issue didn't get sorted and it appears to be affecting me too.

`$ lutris`
`INFO     2017-01-25 11:18:38,985 [lutriswindow]:Connected to lutris.net as $USER`
right click 'Dishonored', select Winetricks
`ERROR    2017-01-25 11:18:44,457 [http]:Unable to connect to server (https://lutris.net/api/games/library/$USER): The read operation timed out`
`Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-2.0 (Staging)`
`zenity: /home/$USER/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)`
`zenity: /home/$USER/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)`
`zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: sqlite3_errstr`

I renamed the /home/$USER/.local/share/lutris/runtime/steam folder to steam.bak, added blank steam folder

`$ lutris`
`INFO     2017-01-25 11:22:49,671 [lutriswindow]:Connected to lutris.net as bradgy`
`ERROR    2017-01-25 11:22:55,101 [http]:Unable to connect to server (https://lutris.net/api/games/library/bradgy): The read operation timed out`
`Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-2.0 (Staging)`
`zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: atk_value_get_value_and_text`

Reset original steam folder; renamed /home/$USER/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu to x86_64-linux-gnu.bak, added blank x86_64-linux-gnu

`$ lutris`
`INFO     2017-01-25 11:29:02,823 [lutriswindow]:Connected to lutris.net as bradgy`
`Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-2.0 (Staging)`
`zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: sqlite3_errstr`

Reset original x86_64-linux-gnu folder, moved libdbus-1.so.3 and libdbus-1.so.3.5.8

`$ lutris`
`INFO     2017-01-25 11:33:04,607 [lutriswindow]:Connected to lutris.net as bradgy`
`Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-2.0 (Staging)`
`zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: sqlite3_errstr`

Added libdbus-1.so.3.5.8 back in

`$ lutris`
`INFO     2017-01-25 11:34:54,113 [lutriswindow]:Connected to lutris.net as bradgy`
`Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-2.0 (Staging)`
`zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: sqlite3_errstr`

Added libdbus-1.so.3 back in

`$ lutris`
`INFO     2017-01-25 11:36:39,158 [lutriswindow]:Connected to lutris.net as bradgy`
`Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-2.0 (Staging)`
'zenity: /home/brad/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)`
`zenity: /home/brad/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)`
`zenity: symbol lookup error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: sqlite3_errstr`
 
Bit of a newb when it comes to writing bug reports but I want to be as helpful as possible. Would appreciate a bit of guidance on what to try next. Off topic, but thanks for Lutris, amazing piece of software that I use daily :D

**Comment by Konfuz** [comment] 2017-01-25 18:25
> I know this is closed but it looks like OP's issue didn't get sorted and it appears to be affecting me too.

Sorry for hijacking the thread then, in hindsight that was a bit impolite from me... :slightly_frowning_face:

**Comment by strycore** [comment] 2017-01-25 18:29
@Konfuz don't be sorry, you gave enough info to get the bug fixed on your side, OP didn't. There's only so much I can do without direct access to people's computers.

@everyone, can someone help @bradgy here?

**Comment by daniel-j** [comment] 2017-03-07 11:00
I get this if I try to run winetricks with Lutris Runtime.

**Comment by mdeguzis** [comment] 2017-03-07 13:21
I am using Arch Linux mainly. If there is anything I can do to help test, please let me know.

**Comment by strycore** [comment] 2017-03-07 20:51
As stated before, the procedure used to fix runtime is explained in the Wiki. I'll accept PRs on the buildbot repo and publish an updated runtime if needed.

**Comment by DonHugo69** [comment] 2017-03-23 07:58
I encountered the same issue on my system, trying to open winetricks for Guild Wars 2 (used the 64bit install script).

`Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-2.4 (Staging)
zenity: /home/roland/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/libatk-bridge-2.0.so.0)
zenity: /home/roland/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/libatspi.so.0)
zenity: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType
`

Renaming the libs 

- libdbus-1.so.3
- libpangoft2-1.0.so.0
- libpango-1.0.so.0

does not help and results in 

`Using winetricks 20160724 - sha1sum: 6391c4e01314efe2e6ae608e214ee0d26689ff47 with wine-2.4 (Staging)
zenity: error while loading shared libraries: libpango-1.0.so.0: cannot open shared object file: No such file or directory
`

I (have to) use the gallium nine patched wine from [AUR]https://aur.archlinux.org/packages/wine-gaming-nine/).
[Desktop_Info.txt](https://github.com/lutris/lutris/files/863977/Desktop_Info.txt)

**Comment by strycore** [comment] 2017-03-23 16:08
> Renaming the libs does not help

Keep in mind that if you're removing / renaming libs from the runtime, they have to be provided by the system. Note that Wine will use i386 version of librairies so having only the x86_64 version will not help. (For 64bit wine, you *also* need the 64bit version)

**Comment by DonHugo69** [comment] 2017-03-24 05:32
Seems like I did not search properly: The problem and a possible solution (deactivation of the runtime) was already described [here](https://forums.lutris.net/t/winetricks-not-working/300). I am using the same distro and DE.
Sorry the inconvenience.

**Comment by strycore** [comment] 2017-03-24 22:03
Disabling the runtime is not a proper solution. We don't want to ship a broken runtime to begin with. 
What *is* inconvenient is that so few people know about LD_LIBRARY_PATH and how libraries work on Linux because we need has many people as possible to test (and send fixes) for as many Linux platforms as possible.

**Comment by mdeguzis** [comment] 2017-03-27 12:03
[LD_LIBRARY_PATH](http://xahlee.info/UnixResource_dir/_/ldpath.html) isn't rocket science, and is more of an old-timer hack that is still used (even myself) in place of compile-time linking solutions. Though, one would argue this usage here is just fine, given the amount of distos supported. The error above, "undefined symbol", in my experience, indicates a lib is to old and missing functins/methods/etc making it not available. I'll take a look at the runtime PHP page linked above. This is inherently the problem with "one size fits all" runtimes. It may just be as simple as updating the affected libs.

**Comment by strycore** [comment] 2017-03-30 23:37
When I upgraded to Ubuntu 17.04, I have managed to reproduce Runtime issues. I'll push some updates and maybe it will fix this particular bug.

**Comment by strycore** [comment] 2017-04-15 00:42
Aaaaaand it's fixed.  🎉

**Closed by strycore** 2017-04-15 00:42 UTC
Labels: Can't reproduce, needs confirmation

**Comment by AccountOneOff** [comment] 2017-10-25 03:28
Happening with Ubuntu 17.10 now.

    You are running winetricks-20170517-next, latest upstream is winetricks-20171018!
    ------------------------------------------------------
    ------------------------------------------------------
    You should update using your distribution's package manager, --self-update, or manually.
    ------------------------------------------------------
    zenity: /home/cxf/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0)
    zenity: /home/cxf/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/lib/x86_64-linux-gnu/libatspi.so.0)
    zenity: relocation error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: symbol gcry_mpi_ec_decode_point, version GCRYPT_1.6 not defined in file libgcrypt.so.20 with link time reference
    DEBUG    2017-10-24 20:12:51,873 [system]:Executing /bin/fuser /home/cxf/.local/share/lutris/runners/wine/staging-2.19-x86_64/bin/wine
    DEBUG    2017-10-24 20:12:51,928 [system]:Executing /bin/fuser /home/cxf/.local/share/lutris/runners/wine/staging-2.19-x86_64/bin/wine64
    DEBUG    2017-10-24 20:12:51,983 [thread]:Processes: monitored: winetricks (7572:Z)
    DEBUG    2017-10-24 20:12:51,983 [thread]:Start process monitoring
    DEBUG    2017-10-24 20:12:51,983 [thread]:All children terminated

Renamed libdubs-1.so.3 and this is the output:

    zenity: relocation error: /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: symbol gcry_mpi_ec_decode_point, version GCRYPT_1.6 not defined in file libgcrypt.so.20 with link time reference
    DEBUG    2017-10-24 20:22:14,360 [system]:Executing /bin/fuser /home/cxf/.local/share/lutris/runners/wine/staging-2.19-x86_64/bin/wine
    DEBUG    2017-10-24 20:22:14,414 [system]:Executing /bin/fuser /home/cxf/.local/share/lutris/runners/wine/staging-2.19-x86_64/bin/wine64
    DEBUG    2017-10-24 20:22:14,469 [thread]:Processes: monitored: winetricks (9629:Z)
    DEBUG    2017-10-24 20:22:14,469 [thread]:Start process monitoring
    DEBUG    2017-10-24 20:22:14,469 [thread]:All children terminated

**Comment by Spurlos** [comment] 2019-11-21 12:09
The year is 2019, fresh lutris on 19.10 ubuntu, same behaviour - nothing happens
