### ISSUE TITLE
Game options in EditGameDialog contains no info for new game

### ISSUE THREAD

**Issue by Ryochan7** [lutris/lutris#2192] opened 2019-06-13 02:18 UTC
Version 0.5.2.1

**Describe the bug**

After installing a game and selecting the Configure menu option for the first time, the fields in the Game options tab will be at default values rather than populated with the information from a game's config file. From the debugging that I have done, it looks like the Game.load_config method is not launched sometimes so there is no game info to display. Adding a call to the method before displaying EditGameConfigDialog results in populated fields.

**Expected behavior**

The fields in the Game options tab should be populated with the information from the game's yaml file.

**Current behavior**

After installing a new game and launching Configure, the Game options tab does not contain the info from the game's config file (exe, arch, wine prefix). Upon cancelling and re-opening the EditGameDialog window, that tab will then be populated with the information from a game's config file as it should have been previously; cancelling forces the config file to get read.

Tested against Magic and Magic VII: Blood and Honor.

https://lutris.net/games/might-and-magic-vii-for-blood-and-honor/

**Steps to reproduce**

- Install Might and Magic 7 using the Wine install script
- Select the Configure menu option from the main window
- Navigate to Game options tab and see blank fields

**Screenshots**

![lutris_gametab_fail](https://user-images.githubusercontent.com/581968/59398086-75860f00-8d54-11e9-994b-b5263eb1d5e9.png)

**Comment by AccountOneOff** [comment] 2019-06-13 03:58
Thanks for reporting but this is a duplicate of #2066

**Closed by AccountOneOff** 2019-06-13 03:58 UTC

**Comment by Ryochan7** [comment] 2019-06-14 05:50
Thank you for mentioning that issue. I missed it in my search.
