### ISSUE TITLE
GOG sync fails and quits the app

### ISSUE THREAD

**Issue by LiamDawe** [lutris/lutris#3220] opened 2020-10-20 09:21 UTC
Latest 0.5.8 Beta as of today, logging into GOG works but when it gets into syncing the app crashes and exits.

Here's a log:   https://gist.github.com/LiamDawe/107599c213fa157716694571d82a681f

**Comment by strycore** [comment] 2020-10-21 03:05
I think this is a duplicate of #3221  
Please ask to reopen if you still experience crashes

**Closed by strycore** 2020-10-21 03:05 UTC
