### ISSUE TITLE
Add an option to disable CSD

### ISSUE THREAD

**Issue by CreamyCookie** [lutris/lutris#1719] opened 2019-02-04 11:05 UTC
There are [good reasons](https://pointieststick.com/2018/12/18/on-headerbars/) for not using them. I'm also on KDE, so headerbars look really out of place.

**Comment by strycore** [comment] 2019-02-04 15:48
This is not going to happen and Lutris look perfectly fine on KDE, as proven by many people including myself.

**Comment by soredake** [comment] 2019-02-04 15:55
@strycore dunno it's lutris bug or my kde system is broken, i can't resize the lutris window by dragging its borders (no resize icon is shown, only with pressed alt works)

**Comment by strycore** [comment] 2019-02-04 15:57
It is probably your KDE system. Multiple KDE users have confirmed that lutris runs nicely and with no issue at all. Same for me on OpenSUSE Leap

**Comment by soredake** [comment] 2019-02-04 16:08
@strycore thanks, seems like know [bug](https://www.reddit.com/r/kde/comments/85absv/anyone_else_notized_resize_problems_with_gtk_apps/dvyutep/), fixed by forcing borders for lutris in kwin

**Comment by CreamyCookie** [comment] 2019-02-04 19:24
It doesn't look fine at all:

![bla](https://user-images.githubusercontent.com/3063858/52231584-a3e17280-28ba-11e9-8708-8e280e84c109.png)

The above is Firefox, below is Lutris. Not to mention that the window has no shadows.

**Comment by daniel-j** [comment] 2019-02-04 20:05
@CreamyCookie do you have `GDK_SCALE=2` and `GDK_DPI_SCALE=0.75` (or some other fraction here) set?

**Comment by CreamyCookie** [comment] 2019-02-05 08:42
@daniel-j I don't think so. I'm using KDE's Scale Display (scale = 2), which works perfectly fine with 99% of apps, even Gnome / GTK+ ones. Of course the close, min, max icons look still out of place and the window isn't properly shaded when in background. Basically the app now looks like sth. that doesn't belong. 

It reminds me of those weird applications in Windows that had their own really weird and colorful window frames because the default ones aren't good enough. (I guess WinAmp was a good looking exception.)

This is what it looks like when I run it with `GDK_SCALE=2`:

![bla2](https://user-images.githubusercontent.com/3063858/52261617-3ec56580-292a-11e9-9edf-7e55e5ad66ea.png)

**Comment by strycore** [comment] 2019-02-05 15:22
Fix your KDE's y'all, this is not a Lutris issue. Your setups are entirely broken and you have to fix your stuff.

Source: I also use KDE.

**Comment by YamiYukiSenpai** [comment] 2019-02-05 18:03
@CreamyCookie if you want, switch the GTK theme to Breeze
@strycore perfectly aware we can change the theme to Breeze to make it similar to the Qt theme (or whatever theme that has both GTK & Qt support).  I just don't like CSD, which is why I, and others, made sure to install [gtk3-nocsd](https://packages.ubuntu.com/cosmic/libgtk3-nocsd0)

**Comment by AlexanderRavenheart** [comment] 2019-02-05 19:46
I'm really curious as to why some users dislike/hate CSD and want it disabled.
Can someone provide a link to an article or a post that describes why CSD is bad from a technical and usability point of view rather than from a stylistic perspective or just because it is a Gnome invention?

**Comment by CreamyCookie** [comment] 2019-02-05 20:51
>    Reduced drag space to move the window: Seriously? It's been many many years since desktop environments have provided the option to drag any window by any part of it using Alt Drag (Alt + mouse click and drag, or using Super key, also known as Windows/Apple/Meta key next to the Alt key on most keyboards). So yeah, that drag space was literally wasted space.

I still drag windows with the title bar. Sure I could do it with alt, but I'm simply used to doing it that way. Furthermore having a place for the actual window title (containing the file name, for example) is pretty useful.

>    Nowhere to put the menubar: Menus filled with tens of options are not good. A well designed headerbar that only displays options and menus relevant to the current window content, thus adapting to changes dinamically, is much better for usability and focusing on relevant actions.

How would you do that for something like Gimp? I don't see how. Most actions can be used in most contexts.

>    Not universally implementable even by all apps on the same platform: This comes from the wrong understanding that all the options and tools need to be available at all times and do not take into consideration the current window content. Other controls like side panels and action bars that would be context sensitive would be much better for situational actions and options.

Again, not an option for all apps. As the author mentioned, even Mac OSX hasn't managed to do so for certain apps. I also think it's a bad idea to require users to learn the meaning of a ton of different icons. And something like a [HUD](https://github.com/Zren/plasma-hud/) for searching in the menu becomes much harder to implement, if there's no text based menu to search in.

>    Reduced flexibility for users and developers: Again related to dragging. See first point.
    App name/window title/filename are omitted or else take up excessive space: If you don't know what app the current window belongs to or which page you are visiting, it's an application/page design problem and not a problem of the window decoration. There are other ways of showing the current document name or other such information by either using smart overlay controls, a statusbar or other ways depending on the application and scope of the information.

Why move it to a overlay / status bar if there's literally a common, consistent place where users expect the title to be?

>    Unimplementable in a cross-platform manner: This is just because of other platforms wanting to maintain control of their walled garden and a conservative mentality of why change something that's been the same since the beginning. Sticking with the same conventions for all eternity has never been what makes technology what it its, software or hardware wise. Innovation, iteration and constant evolution of concepts and designs are necessary in any field.

Well, sometimes there are good reasons for not changing. Changing things for the sake of change is a really bad idea. You've got to have good reasons, explanations and test that the new way is actually an improvement.

But maybe the author could address your points better (if he wants to): @Pointedstick

**Comment by Pointedstick** [comment] 2019-02-05 23:20
I'm not interested in an extended debate here. GTK+GNOME folks have their preferences regarding the way the UI should work and we have ours. That's fine; it's why GNOME and KDE both exist, and user choice is a good thing.

It's just a shame that we can't find a way to interoperate such that GTK CSD headerbar apps look and feel native on platforms that aren't using Mutter (or a fork of it). Right now that's very much not the case. Here are just a few of the issues we see with GTK3 apps in KDE Plasma with our KWin window manager:
- Can't resize GTK3 CSD windows: https://bugs.kde.org/show_bug.cgi?id=390550
- GTK3 CSD windows don't have shadows: https://bugs.kde.org/show_bug.cgi?id=379637
- GTK3 CSD headerbar is rendered dark, making many icons appear invisible: https://bugs.kde.org/show_bug.cgi?id=392104
- GTK windows' context menus don't have shadows: https://bugs.kde.org/show_bug.cgi?id=365924
- GTK windows don't respect the systemwide color scheme: https://bugs.kde.org/show_bug.cgi?id=356006

**Comment by Sunderland93** [comment] 2019-02-06 08:17
The only apps where CSD is a good thing, is a browsers, IMHO.

**Comment by TingPing** [comment] 2019-02-06 13:42
> I still drag windows with the title bar.

You can click and drag all headerbars in GTK.

> How would you do that for something like Gimp?

This isn't GIMP. Lutris has no complex menu needs.

**Comment by TingPing** [comment] 2019-02-06 13:46
> It's just a shame that we can't find a way to interoperate such that GTK CSD headerbar apps look and feel native on platforms that aren't using Mutter (or a fork of it). Right now that's very much not the case. Here are just a few of the issues we see with GTK3 apps in KDE Plasma with our KWin window manager:

The problem is that there is nothing an *application* can do about this. CSD windows have been around since before KDE existed they should work fine. GTK's specific CSD has been around for like 8 years now they should work fine. KWin (and maybe some GTK) is where these discussions need to happen. "CSD is broken on my WM, stop using CSD" is the complete wrong direction for that conversation to go.

**Comment by CreamyCookie** [comment] 2019-02-06 16:29
> This isn't GIMP. Lutris has no complex menu needs.

Hence the inconsistency issue. I personally also find it ugly and unintuitive to have some apps with and some without CSDs.

> You can click and drag all headerbars in GTK.

Which is why only a limited amount of options / buttons can reside in the headerbar. There needs to be space for the title.

> The problem is that there is nothing an application can do about this. CSD windows have been around since before KDE existed they should work fine. GTK's specific CSD has been around for like 8 years now they should work fine. KWin (and maybe some GTK) is where these discussions need to happen. "CSD is broken on my WM, stop using CSD" is the complete wrong direction for that conversation to go.

Nobody is saying you or anybody should stop using CSD. What was suggested is a way to disable it for desktop environments that don't use CSDs or for users that dislike it.

**Comment by TingPing** [comment] 2019-02-06 17:27
> > You can click and drag all headerbars in GTK.

Which is why only a limited amount of options / buttons can reside in the headerbar.

Not sure I follow. If you start a drag event on a button it counts as a window drag not a button press.

> There needs to be space for the title.

I don't see why Lutris needs a title personally.

**Comment by Pointedstick** [comment] 2019-02-06 17:56
> The only apps where CSD is a good thing, is a browsers, IMHO.

Actually browsers are probably one of the best examples of where CSDs are inappropriate, since browser tabs are draggable, so putting them in the CSD actually does reduce the room available to drag the window around. Also, having a wide titlebar provides a place for the web page's title to show up, With CSDs instead of a dedicated titlebar, that text is gone, or places inside tabs and reduced in size so much as to become useless.

**Comment by CreamyCookie** [comment] 2019-02-07 11:00
@TingPing 

> Not sure I follow. If you start a drag event on a button it counts as a window drag not a button press.

Sure, but I'd assume most users would know that's a thing, and others might accidentally click a button they don't want to click.

> I don't see why Lutris needs a title personally.

Maybe not Lutris, but other apps like file managers (title = path), browsers (current tab), image editor (file name). Also the title is useful as a dragging / right click space. And only having a title for some apps is, again, unintuitive

**Comment by TingPing** [comment] 2019-02-07 13:21
I think the idea that "All apps look the same" has never succeeded and never will. If you use gnome with only gnome apps or kde with only kde apps sure but the second you branch out even an inch and install a legacy gtk app, a mono app, a java app, an electron app, etc they all have entirely unique designs you either live with or don't.

**Comment by Pointedstick** [comment] 2019-02-07 16:39
The desire for a visually consistent style for apps is very strong, and macOS is a platform where for the most part it is actually successfully implemented. And it's a strong selling point of that platform.

Giving up on this doesn't seem like the best way to attract people to the FOSS world, regardless of what DE is chosen. If I use GNOME, I would like my apps--including 3rd-party apps--to generally look and feel GNOME-ish. If I use Plasma, I would like them to look and feel KDE-ish. And so on.

In the Mac world, you only have to make sure your app looks and feels "Mac-like". In the Linux world, to be a first-class citizen with the least amount of effort, you should implement a traditional titlebar-and-toolbar UI (menubar optional, can be omitted for simple apps) with whatever UI toolkit you like, which looks pretty good everywhere--even in GNOME, still. If you implement a GTK CSD headerbar, your app will look and feel terrible in KDE Plasma, Deepin, and quite a few other DEs, and some fraction of the users on those platforms will not use your app as a result. What that fractions is I don't have hard numbers. But it is more than zero, and every app developer who implements a GTK headerbar has to weigh the impact of losing those users against the extra work required to implement a traditional titlebar-and-toolbar UI and allow the CSD to be turned off.

**Comment by AlexanderRavenheart** [comment] 2019-02-07 17:40
> The desire for a visually consistent style for apps is very strong, and macOS is a platform where for the most part it is actually successfully implemented. And it's a strong selling point of that platform.
> 
> Giving up on this doesn't seem like the best way to attract people to the FOSS world, regardless of what DE is chosen. If I use GNOME, I would like my apps--including 3rd-party apps--to generally look and feel GNOME-ish. If I use Plasma, I would like them to look and feel KDE-ish. And so on.

Well, Headerbars are part of the GNOME HIG so using Headerbars and CSD is part of what a user on GNOME would expect to see. KDE has their own HIG that does not implement CSD or Headerbars. 
It stands to reason that 3rd party apps cannot follow more than one HIG without making a mess of the overall design, thus having to stick to a predefined one or make their own. So no matter what, any 3rd party app that would be following a particular DE design specification would look bad on others. That is not a valid excuse to start making apps DE neutral and ignore the strengths and weaknesses that each UI toolkit and DE inherently have.

> In the Mac world, you only have to make sure your app looks and feels "Mac-like". In the Linux world, to be a first-class citizen with the least amount of effort, you should implement a traditional titlebar-and-toolbar UI (menubar optional, can be omitted for simple apps) with whatever UI toolkit you like, which looks pretty good everywhere--even in GNOME, still. If you implement a GTK CSD headerbar, your app will look and feel terrible in KDE Plasma, Deepin, and quite a few other DEs, and some fraction of the users on those platforms will not use your app as a result. What that fractions is I don't have hard numbers. But it is more than zero, and every app developer who implements a GTK headerbar has to weigh the impact of losing those users against the extra work required to implement a traditional titlebar-and-toolbar UI and allow the CSD to be turned off.

Requesting developers to not use parts of the UI toolkit (GTK Headerbar) because some other UI toolkit (QT) does not implement equivalent controls or not using CSD because KDE does not want to implement it is bad.

**Comment by Pointedstick** [comment] 2019-02-07 18:41
The GNOME HIG does not mandate or require headerbars, and many GTK apps don't use them, including a few core apps like GNOME Terminal. It's repeatedly asserted out by GTK and GNOME folks  that headerbars are appropriate for apps of simple to moderate complexity, but it's perfectly acceptable to use the titlebar-menubar-toolbar paradigm for more complex apps, as indeed most do (for example, GIMP, Inkscape, Audacity, and LibreOffice).

But it's your choice of course. If you want your app to use a CSD headerbar and only a CSD headerbar, that's your prerogative. However, it will make me not want to use your app on Plasma. For reference, I'm a KDE developer and my favorite music player is Lollypop, which is a GTK3 headerbar app. Lollypop provides an option to turn off the CSD, replacing it with a toolbar and letting the window manager draw the titlebar. It looks like this:

![screenshot_20190207_112929](https://user-images.githubusercontent.com/1097249/52434029-a5ce5000-2acb-11e9-92dd-526af21fd9f7.png)

I have no idea how much effort it took to implement this feature. But I am very happy that it was done, because it's what keeps me using Lollypop on Plasma. If this feature ever gets removed, I won't bitch and moan and complain publicly, but I'll sadly stop using Lollypop and put more of my time into development of Elisa, KDE's own modern-UI-music-player app.

**Comment by strycore** [comment] 2019-02-07 19:50
I'll implement the CSD - toolbar switching option for $800.
What's your preferred website for funding open source work?

**Comment by YamiYukiSenpai** [comment] 2019-02-07 20:13
Like Patreon?

**Comment by strycore** [comment] 2019-02-07 21:25
Not really, more like BountySource or something similar, I don't really know what the options are.

**Comment by TingPing** [comment] 2019-02-07 21:49
BountySource is probably the best option for low goals like this. It kinda sucks though because its easy for people to throw money at random issues that never get solved (in the past BS kept that money, dunno if that changed) rather than limit it to specific goals you have.

**Comment by TingPing** [comment] 2019-02-07 21:51
I know this discussion is going in circles but I think that Lollypop picture is a perfect example of my point. It looks absolutely terrible and out of place there and the fact it has a toolbar or headerbar changed nothing in the scheme of things because the entire UX is different. Lutris using a toolbar will never make it a KDE app even if it works around some KDE bugs.

**Comment by Pointedstick** [comment] 2019-02-08 18:33
The fact that the buttons look like GNOME buttons is a bug somewhere else (this is a Flatpak app; I haven't got the theming set up properly yet). But it's absolutely wrong to say that The UX is totally different. The *UI* is *slightly* different, but the *UX* is pretty conventional and common for the most part. Multi-column list view apps with controls on top are about as boring and common as they come these days.

**Comment by strycore** [comment] 2019-03-20 18:17
It appears that there is no interest in funding this particular project, closing.

**Closed by strycore** 2019-03-20 18:17 UTC
Labels: lacks funding, low priority

**Comment by avahe-kellenberger** [comment] 2021-06-18 21:03
Any interest in re-opening this? I would think it'd be easy to implement a toggle button to hide the bar for someone familiar with the GUI code. It looks terrible in its current state

**Comment by ifohancroft** [comment] 2023-02-16 22:02
To further add to this - the CSD/GNOME-ish UI is the reason why I'm not using Lutris.
I'd love to use it, but please implement a universal GTK UI, not this GNOME-ish look.

**Comment by strycore** [comment] 2023-02-16 22:13
https://www.paypal.com/donate?token=pcxTF5IuOCVYNPyKy2oY5gENs7fKV0smSZ2eay8PpJ25lhL7LW1-P2H-7Vj1D_ktbvaXm-mUrJPSNGxu&locale.x=US

**Comment by danieljohnson2** [comment] 2023-02-16 22:15
I'd like to gently suggest that the most expedient way to get this sort of thing is to submit pull requests that implement it.

@strycore is very open minded about other people's code, I've found.

**Comment by ifohancroft** [comment] 2023-02-16 22:16
> https://www.paypal.com/donate?token=pcxTF5IuOCVYNPyKy2oY5gENs7fKV0smSZ2eay8PpJ25lhL7LW1-P2H-7Vj1D_ktbvaXm-mUrJPSNGxu&locale.x=US

Thank you!
By the way, since I can't fund this entirely by myself (or even afford to pay towards the bounty this month), with the PayPal link, how would we track the sum collected towards it?

**Comment by danieljohnson2** [comment] 2023-07-20 09:17
It is kind of amazing to me how people feel *so strongly* about this bit of the UI, but still won't pony up the *incredibly low* price @strycore is asking for this change.

Seriously; if @strycore gets the $800 and turns around and asks me to do the work for that, I'll say no: I'm not remotely that cheap to hire.

**Comment by strycore** [comment] 2023-07-20 21:16
Forget about that, it was in 2019. 
My rates are now: $8000 **per month**

**Comment by danieljohnson2** [comment] 2023-07-20 21:22
I charge least a billion per month... for removing header bars.

(But I add them for free!)

**Comment by strycore** [comment] 2023-07-20 21:34
> It is kind of amazing to me how people feel so strongly about this bit of the UI

Angry teenagers are not the type of users we want to receive suggestions from.

**Comment by I-Want-ToBelieve** [comment] 2023-09-03 21:46
```fish
devos on  main [$✘!+] via ❄️  impure (latest-env) 
❯ cat ~/.config/gtk-3.0/gtk.css 
.titlebar, .css, headerbar{
  background-image:none;
  background-color:transparent;
  margin-top:-100px;
  margin-bottom:50px;
}
```

**Comment by strycore** [comment] 2023-09-06 00:36
See? instead of being annoying and disrupting the development of  open source software made by volunteers, you could have done what Fox Mulder just did and leave us alone!!!!
