### ISSUE TITLE
'No file provided" after changing configuration

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1642] opened 2019-01-20 18:58 UTC
How to reproduce:
1. Open configuration of a game.
2. Save.
3. Laugh the game.

After doing that, all I get is this message:
![image](https://user-images.githubusercontent.com/10602045/51443719-64355b00-1cfe-11e9-97e0-06cb4f31a6c5.png)
No tracebacks in the terminal, all I get when I do this is: 
```
DEBUG    2019-01-20 21:55:48,073 [game_actions.on_game_run:156]:Lauching Overwatch (wine)
DEBUG    2019-01-20 21:55:48,073 [application.launch:339]:Adding game Overwatch (wine) (139876428240504) to running games
DEBUG    2019-01-20 21:55:48,080 [game.play:250]:Prelaunching <lutris.runners.wine.wine object at 0x7f37843e8748>
DEBUG    2019-01-20 21:55:48,124 [prefix.set_virtual_desktop:121]:Virtual desktop: None
DEBUG    2019-01-20 21:55:48,154 [display._get_vidmodes:15]:Retrieving video modes from XrandR
```

**Comment by strycore** [comment] 2019-01-22 07:31
Should be fixed now

**Comment by tannisroot** [comment] 2019-01-24 11:32
This has returned

**Comment by tannisroot** [comment] 2019-01-26 00:16
This seems to happen with not just Wine runner and work even if you don't change any option and just click save.

**Comment by strycore** [comment] 2019-01-26 00:47
no one said it was specfic to wine.

**Closed** 2019-01-26 22:51 UTC
Labels: bug

**Comment by Sebastian1978** [comment] 2019-02-04 00:08
I have this problem in Lutris 0.5.1 when I change Wine settings. Maybe it is problem of DXVK because when I installed Uplay with DXVK I got this message too. When I installed version without DXVK was fine

**Comment by felipsmartins** [comment] 2019-02-08 03:09
same on here

**Comment by tannisroot** [comment] 2019-02-08 03:12
Can you provide some steps that can reliably reproduce the issue? Because I can't reproduce it anymore.

**Comment by arzardk** [comment] 2019-02-08 18:07
Encountered same error when trying to play game which i added through "Add game...". Managed to fix it with running "Wine configuration" then changed Windows version to Windows 7(does not matter Windows 10 or Windows 7, result is always same). After this manipulation, my game was able to run.

Steps to reproduce:
1. Click "Add game..." and add info about game
2. After that, do "Wine configuration" for creating wineprefix, then close
3. Install game
4. Add game .exe path to Game Options - Executable
5. Run game by clicking "Play"

**Comment by TheSHEEEP** [comment] 2019-02-21 18:25
Had the same happen to me.
What I did specifically was to install MtG Arena - which fails as always -, then download the MtG Arena installer and configure the game in lutris to launch said installer instead of MTGA.exe (doing so usually fixes the installation, and then you change back to MTGA.exe). When I did that change, however, I also got that "No file provided" error, which was fixed by just restarting Lutris.

**Comment by Jayrgo** [comment] 2019-04-05 08:02
I have the same problem.
After I changed the configuration, I choose another game and then the other one again and it works. I do not have to restart Lutris.

1. Change configuration of game A
2. Select game B
3. Select game A
4. Play

**Comment by tannisroot** [comment] 2019-04-08 19:58
@Jayrgo let me know if the issue persists after release of 0.5.2

**Comment by strycore** [comment] 2019-04-08 20:26
I've manage to reproduce the issue and I pushed a fix yesterday.

**Comment by Jayrgo** [comment] 2019-04-11 15:22
> @Jayrgo let me know if the issue persists after release of 0.5.2

@tannisroot now it should work with version 0.5.2.1

**Comment by linuxninja39** [comment] 2019-04-23 21:59
I'm running 0.5.2.1 on arch, I just changed the wine version and got this error. Is there a work around?

**Comment by strycore** [comment] 2019-04-23 23:09
Do you have a reliable way of reproducing this or was it a one time thing only?

**Comment by KirkBushman** [comment] 2019-05-04 11:39
This happens to me for League of Legends on Fedora 29 Kernel 5.0.9.
Config kept as it comes.

**Comment by almindor** [comment] 2019-05-04 19:23
Same here with X-Wing Alliance from Gog.com (on arch linux x64). Installed and no profile provided, nothing helps, restarting lutris or changing config or going to other games and selecting this one again.

**Comment by matox01** [comment] 2019-05-16 23:33
i have just installed Dauntless the first launch went well but the fps was low so i went to enable the DXVK and ESYNC as was reommended in installer after saving i got this No file provided error . i am on Manjaro 18.0.4 Please help i dont want to reinstall the game it wont solve anything as the game run like shit without dxvk and esync which is turned off by default after instalation

**Comment by xXNiathXx** [comment] 2019-05-19 20:32
And here another example. :/ 
Installed league via lutris and started it 
then had an error when i tried to join a game. I then tried to do something in the configuration and start it again. what comes next you all know. :) "no file provided" and restarting or changing anything again dosen't work either. the only thing i got out of the terminal was this:

GtkDialog mapped without a transient parent. This is discouraged.
2019-05-19 22:18:11,899: Non existent path: /home/zebi/.local/share/lutris/runtime/lib64
2019-05-19 22:19:46,428: Non existent path: /home/zebi/.local/share/lutris/runtime/Ubuntu-18.04-x86_64
2019-05-19 22:19:53,995: Runtime updated
2019-05-19 22:25:37,078: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-05-19 22:25:37,079: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-05-19 22:25:37,093: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-05-19 22:25:37,182: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-05-19 22:25:37,183: Wine prefix not provided, defaulting to $WINEPREFIX then ~/.wine. This is probably not the intended behavior.
2019-05-19 22:25:37,296: The game doesn't have an executabe

i hope someone can fix this :)
