### ISSUE TITLE
Flatpak package update issue

### ISSUE THREAD

**Issue by Femto-godhand** [lutris/lutris#5712] opened 2024-11-08 13:46 UTC
### Bug description

Hello everyone, 
since few days I got this message during my flatpak update:

```
Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   net.lutris.Lutris

Info: runtime org.gnome.Platform.Compat.i386 branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this extension:
   net.lutris.Lutris

```
Best regards

### How to Reproduce

Run "flatpak update" from terminal.

### Expected behavior

Migrate Lutris app to a supported platform.

### Log output

```shell
No issue when Lutris is running.
```

### System Information

```shell
OS: Void Linux x86_64
Host: X570 AORUS ELITE -CF 
Kernel: 6.6.59_1
CPU: AMD Ryzen 9 3900X (24) @ 4.325GHz
GPU: AMD ATI Radeon RX 6700 XT
```

**Comment by strycore** [comment] 2024-11-08 16:18
Duplicate of #5700 
We have a new version that is about to be released using Gnome Runtime 47

You can safely ignore the warning above about Gnome Runtime 45.

**Closed by strycore** 2024-11-08 16:18 UTC
