### ISSUE TITLE
Mistake with icons for Wine runner

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#4061] opened 2022-02-14 08:42 UTC
Gear icon is used for both buttons
![image](https://user-images.githubusercontent.com/10602045/153829361-8f39418c-6c29-4142-b957-275db32fee54.png)

**Comment by runboy93** [comment] 2022-02-14 19:53
Looks ok here with v0.5.10-beta1

![ok](https://user-images.githubusercontent.com/21213705/153936370-7b62012a-5eb3-40aa-abd0-480683db9f03.png)

**Comment by danieljohnson2** [comment] 2022-02-14 20:55
This may be by design.

Wine, when installed, gets the icon 'preferences-other-symbolic' because it supports multiple versions, and that is the manage-versions button. Apparently this is a gear for you, and looks just like 'preferences-system-symbolic', the icon for the configuration button right next to it.

A non-installed runner gets 'system-software-install-symbolic', which looks different.

I see the same 'preferences-other-symbolic' that @runboy93  does, running Pop!_OS with gnome-session installed. I don't know why you get a gear like that, but it may not be a bug in Lutris at all.

**Comment by tannisroot** [comment] 2022-02-15 01:25
Perhaps this has something to do with my theme, Adwaita

**Comment by danieljohnson2** [comment] 2022-02-15 09:14
I'm using Adwaita too. The icon @runboy93 sees should be found at this path:

/usr/share/icons/Adwaita/scalable/categories/preferences-other-symbolic.svg

At least, I have it there. Do you?

**Comment by tannisroot** [comment] 2022-02-15 09:44
Yes, and for me, that icon is the same as the gear icon, not the one on @runboy93 's picture.
I will file a PR to change it to a different one, I guess

**Comment by danieljohnson2** [comment] 2022-02-15 09:54
Hmm. I've looked at the GNOME repo on gitlab, and it looks like they changed this icon to the gear in June 2021, but changed it back again just a few days ago. I am not sure what's going on there; maybe the gear was a temporary aberration, though that commit seems to be intentional.

If GNOME does go with everything-is-a-gear here, Lutris should probably switch to other icons, or ship it's own. I dunno.

**Comment by strycore** [comment] 2022-02-16 11:40
![Screenshot from 2022-02-16 03-39-29](https://user-images.githubusercontent.com/280336/154257506-248dff11-8e6e-4247-ae0d-77f4d9461f4b.png)

There are 2 icons that provide the box with a wrench, we can switch to the other one.

**Comment by danieljohnson2** [comment] 2022-02-16 21:53
This is odd; on the gitlab repo, applications-system-symbolic is a gear- and it always has been, as far as I can see. And that is what it is on my system, too. This is all very odd.

So anyway I'm against this change, as I'd rather @tannisroot have this bug than me!

**Comment by strycore** [comment] 2022-02-16 22:52
try the current version and see if you have a gear

**Comment by danieljohnson2** [comment] 2022-02-16 22:55
I totally do, though it is still different from the configuration icon. See
![Screenshot from 2022-02-16 17-54-26](https://user-images.githubusercontent.com/6507403/154371283-60516682-69f3-4432-be2a-55df18292afc.png)
:

**Comment by strycore** [comment] 2022-02-16 22:56
At least you're not getting the same icon twice so this works better. I'm open to other suggestions but the selection from the gnome stock icons is really limited imo...

**Comment by danieljohnson2** [comment] 2022-02-16 23:01
Umm, perhaps ''face-monkey-symbolic"? That's distinct! And so clearly evocative of, erm, monkeying around with WINE?

**Comment by strycore** [comment] 2022-02-16 23:07
that won't be confusing at all :sweat_smile: 

the button isn't really wine specific, it's for any runner offering multiple version (which is only wine at the moment). Something like "view-more-symbolic" would work.

**Comment by danieljohnson2** [comment] 2022-02-16 23:21
I think we can go with the gear. It's okay.

**Comment by strycore** [comment] 2022-02-17 11:41
alright, closing

**Closed by strycore** 2022-02-17 11:41 UTC
