### ISSUE TITLE
Lutris is starting window bug

### ISSUE THREAD

**Issue by JSbad** [lutris/lutris#3380] opened 2021-01-24 20:05 UTC
It seems that Lutris gets stuck on the launching window, once you close it it opens and runs fine.

these log consistently on every launch and once the init window is closed it stops logging and proceeds fine.

    2021-01-24 19:59:53,624:  Error while completing task <bound method Downloader.async_download of
    <lutris.util.downloader.Downloader object at 0x7f8f03fd44c0>>: ffi_prep_closure(): bad user_data (it seems that the version of 
    the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)

    2021-01-24 19:59:53,626: Download failed: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen
    at runtime is different from the 'ffi.h' file seen at compile-time)

[lutris-issue-report.txt](https://github.com/lutris/lutris/files/5863099/lutris-issue-report.txt)

Edit: just found the other issue reported recently, seems to be a problem with a recent Pop!_ update

**Comment by strycore** [comment] 2021-01-25 01:11
I exclusively use Pop and have never experienced such a thing. I do not have enough information to help you, sorry.

**Comment by leandercarey** [comment] 2021-01-27 19:08
I run Solus and my Lutris started doing this as well. After you click the "X" to close the loading window, Lutris loads. Then when you try to get it to login to your Lutris, or other, account it freezes again, only this time theres no unfreezing it. I would say that it's a recent issue since it never did this before. Before what being the question. A Python3 issue perhaps? A kernel issue? Since POP and Solus have little in common except the kernel, Lutris, and python3, I would think there has been an update in one of these 3 that has broken something. I can still coax Lutris into starting, like I said, and I can run the games but I cannot login to any of my accounts. The one exception being Steam, but it was already connected at startup.

**Comment by strycore** [comment] 2021-01-27 23:46
> A Python3 issue perhaps? A kernel issue? 

No. PEBKAC.

**Comment by strycore** [comment] 2021-01-29 18:30
I'm sorry but this issue is just too incomplete for me to work on it. There are plenty of users on Pop including myself who have experienced no issue at all. As such, I will close it as an OS quirk but if you do manage to find reproduction steps, please post them here so the issue can be re-opened.

**Closed by strycore** 2021-01-29 18:30 UTC

**Comment by JSbad** [comment] 2021-02-07 21:49
Just to let you know it was caused by obsolete python packages, I updated most of them according to requirements and got it working, probably previous programs I used kept them old(I use whoogle).

**Comment by atrauzzi** [comment] 2021-02-20 04:20
@JSbad - What do you mean by obsolete python packages and what did you do to update them?  I'm experiencing this on vanilla Ubuntu (not popos) though I have no idea why it's happening.

**Comment by atrauzzi** [comment] 2021-04-07 20:54
@JSbad - Yes, but how?
