### ISSUE TITLE
Lutris crashes when Indian formats are used

### ISSUE THREAD

**Issue by plasticadmiral** [lutris/lutris#2057] opened 2019-04-17 19:48 UTC
when i try launching it, i get this error
```
Traceback (most recent call last):
  File "./lutris", line 27, in <module>
    locale.setlocale(locale.LC_ALL, locale_name)
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./lutris", line 29, in <module>
    sys.stderr.write("Unsupported locale %s. Try running with LC_ALL=C.\n" % locale_name)
TypeError: not all arguments converted during string formatting
```

This same error persists even when i run the git clone version of it.

**Comment by AccountOneOff** [comment] 2019-04-17 23:50
>"Unsupported locale %s. Try running with LC_ALL=C.\n" % locale_name

You just gonna ignore this?

`LC_ALL=C lutris`

**Comment by strycore** [comment] 2019-04-18 00:09
There seems to be a double exception here so I'll take another look

**Comment by tannisroot** [comment] 2019-04-24 10:52
How to reliably reproduce this:
1. Use Ubuntu (18.04, 19.04 will do) but it probably affects every distro
2. Open this menu: 
![image](https://user-images.githubusercontent.com/10602045/56654131-07986200-6698-11e9-99ef-5607f28ca9c7.png)
3. Set "Formats" to `India`
4. Launch Lutris

**Comment by tannisroot** [comment] 2019-09-03 03:10
Should be fixed by https://github.com/lutris/lutris/commit/e0b39596bf16ee9c87f5f89875200350fee04c71

**Closed by tannisroot** 2019-09-03 03:10 UTC
Labels: bug
