### ISSUE TITLE
Postexit command doesn't work with arguments

### ISSUE THREAD

**Issue by foresto** [lutris/lutris#2224] opened 2019-07-03 22:22 UTC
The postexit command does not currently work if it is given any arguments, because it is [handled as an opaque string](https://github.com/lutris/lutris/blob/8bd7daa732dacef624e7c8cce787973f2a35536a/lutris/game.py#L630).

This means that anyone entering a command that requires arguments might be surprised (as I was) to discover that it silently fails to run, and that they have to write a script and copy its path into lutris even if they only need a single command. That's a bit of a hassle.

This could be made easier and more useful if lutris parsed the postexit command into arguments, perhaps with shlex.split() as it already does in various other places throughout the code. This would have the additional benefit of making lutris configuration more consistent.

**Comment by isugimpy** [comment] 2019-07-05 01:17
Duplicate of https://github.com/lutris/lutris/issues/2151

**Closed** 2019-08-08 18:51 UTC
Labels: duplicate
