### ISSUE TITLE
Can't install Arx Fatalis (Arx Libertatis) with GOG version

### ISSUE THREAD

**Issue by terzag** [lutris/lutris#2802] opened 2020-04-26 14:00 UTC
Hello,
I'm trying to install Arx Fatalis (Arx Libertatis) using the GOG version. The installer downloads the setup and then fails to extract it with the following message in loop:

```
Error: Could not extract setup_arx_fatalis_1.21_(21994).exe
Abort / [Retry] / Ignore
> innoextract: warning: unexpected setup data version: 5.5.7 (unicode)
warning: unexpected Auto Boolean value: 20
warning: unexpected Architecture flags: 10
warning: unexpected data while converting from CP1200 to UTF-8
stream error: basic_ios::clear
Done with 1 error and 4 warnings.
Extracting /mnt/data1/.cache/terzag/lutris/installer/arx-fatalis/gog/setup_arx_fatalis_1.21_(21994).exe using bsdtar
bsdtar: Error opening archive: Unrecognized archive format
unshield: Failed to open /mnt/data1/.cache/terzag/lutris/installer/arx-fatalis/gog/setup_arx_fatalis_1.21_(21994).exe as an InstallShield Cabinet File
```

I assume it's an issue with an older version of innoextract included in Lutris, as using innoextract 1.8 from my system can extract the setup with no issue.

Using Xubuntu 20.04 with Lutris 0.5.6 from the PPA.

**Comment by xordspar0** [comment] 2020-04-27 13:38
This is probably a duplicate of https://github.com/lutris/lutris/issues/2778

**Comment by strycore** [comment] 2020-05-28 02:46
yes, duplicate.

**Closed by strycore** 2020-05-28 02:46 UTC
