### ISSUE TITLE
Add network-tools from runtime to PATH

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#3837] opened 2021-11-19 09:07 UTC
We need to ship our own curl, wget and openssl due to an issue with gnutls from runtime (and it's just nice for installer creators to know it's always available to use). Plus, it would be very neat to have these in runtime and not depend on user to install them. To do that, Lutris needs to add the path `.local/share/lutris/runtime/network-tools` to PATH in the beginning so that they get prioritized over system wget, curl and openssl.

**Comment by strycore** [comment] 2022-02-17 20:23
duplicate of #4035

**Closed by strycore** 2022-02-17 20:23 UTC
