### ISSUE TITLE
Lutris 0.5.0.1, mesa_glthread set as True instead of true

### ISSUE THREAD

**Issue by fosspill** [lutris/lutris#1797] opened 2019-02-22 21:18 UTC
Hi!
After installing FFXIV:ARR the game wouldn't start. 

Checking logs revealed:
`Fatal error in __driConfigOptions line 10, column 0: illegal default value for mesa_glthread: True.`
Changing from True to true in the System Options - Environment variables fixed the issue.

This does not seem to be an issue with the install script itself as it defines it with a lowercase "true".

I presume lutris is somehow converting "true" to "True" during creation of the environment variables.

Note: It might be something else, of course, but that it what made my game start successfully.

![Image of potential issue](https://i.imgur.com/6wF0xAK.png)

**Comment by fosspill** [comment] 2019-02-24 13:14
If anyone could point me in the right direction of where this issue could be, please do and I'll gladly look into it!

**Comment by Astilex5** [comment] 2019-02-25 21:24
I am not sure myself but I have tested this one both Intel and Nvidia GPU's, and it sets the value to `true`

My guess lies in one of 3 places. AMD's amgpu X.org Driver, Mesa, or RADV. I can only reproduce this on my AMD system.

**Comment by fosspill** [comment] 2019-02-25 23:00
Which lutris version? Which installer?
This is likely an issue either with lutris or specific install scripts.

-------- Original Message --------

**Comment by Astilex5** [comment] 2019-02-25 23:04
Version: 0.5.0.1
Installer: FF XIV DXVK Standalone

The scripts could also be an issue, but why would it only happen with AMD graphics?
I would mention this to the script maintainer(s) and see what they think.

**Comment by fosspill** [comment] 2019-02-25 23:12
Interesting. Are you absolutely sure you run the same lutris version on your systems?

If so this issue is really confusing. Seems like a clear problem with converting between data formats.

**Comment by Astilex5** [comment] 2019-02-27 03:31
Yes They all use the same version.

I am Running Antergos Linux which is basically Arch Linux with a GUI Installer and an extra repo. (I use this on all my personal and development stations to ensure parity.(The only exception is my production servers are pure Arch Linux and FreeNAS, but that is irrelevant))

Everything is from the vanilla Arch Linux repos including Lutris with the exception of the antergos repo which has a few extra packages for quality of life.

**Comment by Astilex5** [comment] 2019-03-03 19:52
Does someone want to try this again. I had to do a system recovery that went bad and had an interesting development.

I Installed FF XIV via lutris copied the old data files over(Managed to at least recover that) and value was set to `true` rather than `True`.

This could be just from coping the old Data over or this might have been resolved on another front such as mesa or X.org.

**Comment by AccountOneOff** [comment] 2019-03-03 20:04
That's because I added quotes to it. Without them it gets set to `True` instead of `true`.

**Comment by fosspill** [comment] 2019-03-04 14:28
@AccountOneOff Thank you for doing that!
Would you consider this a lutris bug? (ie: Lutris should be able to save the boolean properly?) or just something all install scripts have to take into account? (ie: documentation issue, possibly)

**Comment by Astilex5** [comment] 2019-03-04 14:51
Huh thats interesting. It never ceases to amaze me how a simple syntax change can make all the difference.

I assume we can close this? Unless this is not fully implemented. (I only say that because this was added to the 5.1 milestone.)

**Comment by fosspill** [comment] 2019-03-04 14:56
I don't think it should be closed yet as it can and will affect other installers too. So either we'll have to make sure documentation points out that "flaw" or we'll have to make lutris deal with it differently. Considering it's added to a milestone I presume the idea is that lutris will deal with it going forward?

**Closed** 2019-03-19 03:36 UTC

**Comment by strycore** [comment] 2019-03-19 03:38
please note that the fix will only be effective once the website has switched to the BaseLoader YAML loader, this change will break installers for people who haven't updated to Lutris 0.5.1 so I'll probably hold a bit before deploying this change.
