### ISSUE TITLE
Cannot paste GoG login credentials into login helper window

### ISSUE THREAD

**Issue by Polynomial-C** [lutris/lutris#2132] opened 2019-05-13 13:06 UTC
Using `lutris-0.5.2.1` I cannot paste my GoG login credentials into the GoG login helper window. This is quite annoying as I have a password with 40+ characters and typing such a password is quite error-prone.
Neither Linux middle mouse button works nor CTRL+V but typing from keyboard works.

**Comment by isugimpy** [comment] 2019-05-17 19:06
I can duplicate this inconsistently.  It's strange.  The paste option appears when you right click, but nothing gets pasted.  Same with ctrl+v/middle click.  For testing, I made the WebView editable, and could paste into the box.  Disabled that again, because it makes the whole page editable.  However, I launched lutris with the debug flag, and could then paste into the field.  Then I closed it completely and launched again without debug, and could still paste.  There's something really fishy here, but I think it's a GTK problem.

**Comment by tuxayo** [comment] 2019-08-31 14:24
> I can duplicate this inconsistently. It's strange. The paste option appears when you right click, but nothing gets pasted.

Same. And I rerun Lutris and not paste works.

Then I alt tab to get my password from KeepassXC and the paste doesn't work anymore.

- Distro: Arch Linux
- lutris 0.5.2.2-1
- gtk2 2.24.32-1
- gtk3 1:3.24.10-1
- webkit2gtk 2.24.4-1
- qt5-webkit 5.212.0alpha3-3

**Comment by tuxayo** [comment] 2019-08-31 14:29
Ok I get it, it's when I go to KeepassXC, do ctrl-c on a text (it can even the text in the search field) that when I paste in Lutris's GOG window, that the empty string is pasted. Thus clearing the field if there was something else.

When I restart Lutris, open a GOG login window, then I can paste text that I copied from Firefox for example. But If I copy something from KeepassXC, then the GOG login window is broken (about pasting) for the rest of the session until Lutris's restart

**Comment by Polynomial-C** [comment] 2019-09-11 11:22
Yes, I can confirm this happens in combination with keepassxc. Sorry I didn't mention this in my initial report.

**Comment by tuxayo** [comment] 2019-10-26 03:47
Great that we nailed down how to reproduce :)

**Comment by jrtberlin** [comment] 2020-03-30 08:43
This is also the case with the new humble bundle integration.

**Closed** 2020-07-14 03:02 UTC
