### ISSUE TITLE
Epic games refresh pops open a blank window after entering username and password

### ISSUE THREAD

**Issue by VorpalBlade** [lutris/lutris#4844] opened 2023-05-06 15:22 UTC
### Bug description

I haven't used lutris for a while, when pressing refresh on Epic, the first time it crashed, the second time (when I ran it from a terminal to try to capture the log) it popped up a login prompt. After entering user + password, I get a grey window.

When starting the actual Epic store I would at this point either get a image CAPTCHA or a 2-factor authentication prompt.

While there are a few bugs about failing to sign in to Epic, they seem to freeze at different points. I did not find any bugs that got a grey window like I did. Thus I elected to open a new bug.

### How to Reproduce

1. Click refresh on an epic account that hasn't been used for a few months
2. Select sign in with "Epic Games", not google or anything like that.
3. Enter email + password
4. Be confronted with grey window that does nothing.

### Expected behavior

Be able to log into Epic.

### Log output

```shell
(lutris:23048): Gtk-WARNING **: 17:14:53.408: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(lutris:23048): Gtk-WARNING **: 17:14:53.408: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
INFO     2023-05-06 17:14:53,908 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-05-06 17:14:53,934 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-05-06 17:14:54,000 [startup.check_driver:57]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-05-06 17:14:54,000 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 1070
INFO     2023-05-06 17:14:54,000 [startup.check_driver:77]:GPU: 10DE:1B81 1043:8599 (nvidia drivers)
DEBUG    2023-05-06 17:14:54,107 [lutriswindow.update_store:448]:Showing 0 games
INFO     2023-05-06 17:14:54,111 [startup.update_runtimes:218]:Startup complete

(lutris:23048): Gtk-WARNING **: 17:14:54.171: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(lutris:23048): Gtk-WARNING **: 17:14:54.171: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
DEBUG    2023-05-06 17:14:56,974 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/arvid/Games/epic-games-store"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:LD_LIBRARY_PATH="/home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib:/home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib64:/usr/lib:/usr/lib32:/usr/lib/icecream/lib:/usr/lib/libfakeroot:/usr/lib64:/home/arvid/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/arvid/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/arvid/.local/share/lutris/runtime/steam/i386/lib:/home/arvid/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/arvid/.local/share/lutris/runtime/steam/i386/usr/lib:/home/arvid/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/arvid/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/arvid/.local/share/lutris/runtime/steam/amd64/lib:/home/arvid/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/arvid/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:DXVK_HUD="compiler"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:MESA_GL_VERSION_OVERRIDE="4.4COMPAT"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINEARCH="win64"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINE="/home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINE_MONO_CACHE_DIR="/home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/mono"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/gecko"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib64/gstreamer-1.0/:/home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINEPREFIX="/home/arvid/Games/epic-games-store"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINEESYNC="1"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/arvid/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:PROTON_EAC_RUNTIME="/home/arvid/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:game_name="Epic Games Store"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/lib/python3.11/site-packages"
DEBUG    2023-05-06 17:14:57,027 [command.start:141]:LUTRIS_GAME_UUID="91ae86a3-ba44-4a2a-9a3a-24dc8d1fefd0"
Discord ID: None
INFO     2023-05-06 17:14:57,028 [game.start_game:586]:Discord RPC Disabled or Discord APP ID Not Present
lutris-wrapper: Epic Games Store
Started initial process 23167 from gamemoderun /home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/bin/wine /home/arvid/Games/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
Start monitoring process.
gamemodeauto: 
fsync: up and running.
Initial process has exited (return code: 0)

(wine:23306): GStreamer-WARNING **: 17:14:59.208: Failed to load plugin '/home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib64/gstreamer-1.0/libgstflac.so': libFLAC.so.8: cannot open shared object file: No such file or directory

(wine:23306): GStreamer-WARNING **: 17:14:59.208: Failed to load plugin '/home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib/gstreamer-1.0/libgstflac.so': /home/arvid/.local/share/lutris/runners/wine/lutris-fshack-7.2-x86_64/lib/gstreamer-1.0/libgstflac.so: wrong ELF class: ELFCLASS32
Monitored process exited.
Exit with return code 0
DEBUG    2023-05-06 17:15:08,921 [command.on_stop:195]:Process 23124 has terminated with code 0
DEBUG    2023-05-06 17:15:13,039 [game.beat:693]:Game thread stopped
WARNING  2023-05-06 17:15:13,039 [game.on_game_quit:730]:Game still running (state: running)
INFO     2023-05-06 17:15:13,040 [game.stop:704]:Stopping Epic Games Store (wine)
DEBUG    2023-05-06 17:15:13,040 [game.stop_game:664]:Epic Games Store (wine) has run for 16 seconds
DEBUG    2023-05-06 17:15:13,040 [game.on_game_quit:748]:Epic Games Store stopped at lör, 06 maj 2023 17:15:13
DEBUG    2023-05-06 17:15:13,040 [game.save:299]:Saving Epic Games Store (wine) with config ID epic-games-store-standard-1654414709
DEBUG    2023-05-06 17:15:13,258 [lutriswindow.update_store:448]:Showing 0 games
DEBUG    2023-05-06 17:15:16,735 [base.login:332]:Connecting to Epic Games Store

(WebKitWebProcess:23636): Gtk-WARNING **: 17:15:16.797: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(WebKitWebProcess:23636): Gtk-WARNING **: 17:15:16.797: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name

(WebKitWebProcess:23636): Gtk-WARNING **: 17:15:16.813: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(WebKitWebProcess:23636): Gtk-WARNING **: 17:15:16.813: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.3.1-arch1-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            4.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 530.41.03
OpenGL Core:     4.6.0 NVIDIA 530.41.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 530.41.03
Vulkan:          Supported
```

### Media (optional)

![image](https://user-images.githubusercontent.com/3315306/236632602-b8d2d7f4-359a-4040-8d47-30fa6529512c.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by PalmTamino** [comment] 2023-05-07 09:42
same here.

**Comment by Partack** [comment] 2023-05-07 23:10
Same problem here. I'm using the flatpak version.

**Comment by strycore** [comment] 2023-05-27 21:21
Closing as duplicate of #4783

**Closed by strycore** 2023-05-27 21:21 UTC
