### ISSUE TITLE
Strong checksums for installer files

### ISSUE THREAD

**Issue by sorsasampo** [lutris/lutris#1383] opened 2018-12-02 10:42 UTC
Allow providing optional checksum for `files:`.

Python `hashlib`'s [`new(algo)`](https://docs.python.org/3/library/hashlib.html#hashlib.new) function could be leveraged here to support all existing and future checksum algorithms.

Example:

```
files:
- file1:
    url: https://vendor.com/installer-that-should-not-change-v1.0.exe
    checksum: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

**Comment by strycore** [comment] 2018-12-02 10:51
I think there's some half implemented function that allows that already in the code, not sure.
Either way, not very hard to implement

**Comment by sorsasampo** [comment] 2018-12-02 10:54
@strycore not familiar with the Lutris codebase - is there already a user friendly method for interrupting the install with an error?

**Comment by strycore** [comment] 2018-12-02 11:08
@sorsasampo yes, you raise a ScriptingError anywhere during the install process, there are lots of examples in the code if you lookup that type of error.

**Comment by MsMidnight** [comment] 2018-12-06 19:57
@strycore Can you close the issue?

**Comment by sorsasampo** [comment] 2018-12-06 20:36
77fb295 only supports sha256, right? How would it be upgraded to support other checksums later if/when necessary?

**Comment by camdenorrb** [comment] 2018-12-06 22:07
I was told by @strycore to only do SHA-256

**Comment by strycore** [comment] 2018-12-07 00:16
We don't do "what ifs" or "just in cases" in Lutris. We have a spec. We follow it. We implement it. We're done with it.

**Closed by strycore** 2018-12-07 00:16 UTC

**Comment by strycore** [comment] 2018-12-07 00:17
> How would it be upgraded to support other checksums later if/when necessary?

That would probably takes a grand total of 5 minutes if such a decision would be made.

**Comment by camdenorrb** [comment] 2018-12-07 06:49
More like 2 seconds

**Comment by strycore** [comment] 2018-12-07 06:55
Hey! Writing a good commit message takes time!

**Comment by camdenorrb** [comment] 2018-12-07 06:57
It's literally like 2 line changes

**Comment by camdenorrb** [comment] 2018-12-07 06:58
Honestly, we can make it default to SHA-256 if no type is specified if that helps

**Comment by strycore** [comment] 2018-12-07 07:03
if the problem is that SHA256 is not good enough, then change it too something better, the problem is about supporting more than one hash type which we have absolutely NO reason to do and complicates the code base since we have to account for variable hash types.

**Comment by camdenorrb** [comment] 2018-12-07 07:03
> It's literally like 2 line changes

**Comment by QmwJlHuSg9pa** [comment] 2023-09-01 06:52
Hi, was this feature intentionally removed at some point? The `check_hash()` method (formerly of `interpreter.py`, now `installer_file.py`) doesn't seem to get called anywhere in master.

**Comment by strycore** [comment] 2023-09-01 07:13
It was never fully completed, we also need to integrate with the checksums from GOG.
