### ISSUE TITLE
Close pre launch script when game exits

### ISSUE THREAD

**Issue by coderedart** [lutris/lutris#4739] opened 2023-02-09 18:49 UTC
The usecase is pretty simple. I use a small pre launch script to start a binary (addon/mod/plugin whatever) before the game starts. The problem is, how does the addon binary know when to quit?

So, i usually just leave the script alone, so that it never closes. But when i exit the game, lutris will still keep waiting for the pre-launch script to complete. This is not possible to do user side, so i am here to request the devs to enable force closing the script in lutris by default or provide a checkbox to opt-in to force closing pre launch script.

I tried these workarounds: 
1. post launch script launches another binary which will iterate all processes and kill the one matching the name of my addon binary. But, the problem is lutris waiting for pre-launch script -> never actually triggers the post-launch script.
2. adding my addon binary name to exclude processes. but lutris only checks for first 15 characters of child pid name and that often turns out to be "python3".. and not the actual binary name which is towards the end of the pid name.

**Comment by strycore** [comment] 2023-02-10 19:33
Closing the prelaunch script was the intended behavior but there was a bug preventing that from happening.

**Closed by strycore** 2023-02-10 19:33 UTC
