### ISSUE TITLE
On startup the game list is empty when side panel is deactivated

### ISSUE THREAD

**Issue by konzty** [lutris/lutris#4006] opened 2022-01-24 16:45 UTC
### Bug description

When "Show Side Panel" is deactivated Game Library is not shown, changing layout or activating "Show Side Panel" shows the library contents

![1 Screenshot_2022-01-24_17-30-12](https://user-images.githubusercontent.com/89305232/150824077-8ab5b1b3-603f-4699-a06e-6a9da7ab0ece.png)

### How to Reproduce

I've tried:
* Starting Lutris with the game list in "tile" layout => list area stays empty, changing the layout renders the list.
* Starting Lutris with the game list in the "list" layout => list area stays empty, changing the layout renders the list.
* Starting Lutris with any game list layout => list is empty, activating "show side panel" makes the list appear.
* **Starting Lutris with any game list layout AND "show side panel" activated => game list appears on startup.**

In the lutris -d output it can be clearly seen: the message "Showing 17 games" only appears after the view type was changed.

![2 Screenshot_2022-01-24_17-30-49](https://user-images.githubusercontent.com/89305232/150824228-3e81e80c-8b01-402e-a218-4b942397d7a6.png)

### Expected behavior

When "show side panel" is deactivated game list should appear on startup.

![3 Screenshot_2022-01-24_17-31-14](https://user-images.githubusercontent.com/89305232/150824172-986606d6-82ac-47ca-b21a-9b46e1d0756d.png)

### Log output

```shell
2022-01-24 17:37:17,841: Starting Lutris 0.5.9.1
2022-01-24 17:37:17,848: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,848: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,848: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,849: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,849: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,849: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,849: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,849: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,849: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,850: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,850: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,850: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,854: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,854: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,855: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,855: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,855: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,855: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,856: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,856: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,856: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,856: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,856: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,856: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,867: No cores found
2022-01-24 17:37:17,905: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,905: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,906: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:17,908: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:18,258: Failed to get url https://api.github.com/repos/lutris/dxvk/releases: HTTP Error 403: rate limit exceeded
2022-01-24 17:37:18,258: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:18,259: Loading of DXVK versions failed, defaulting to locally available versions
2022-01-24 17:37:18,343: Failed to get url https://api.github.com/repos/lutris/dxvk-nvapi/releases: HTTP Error 403: rate limit exceeded
2022-01-24 17:37:18,343: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:18,344: Loading of DXVK-NVAPI versions failed, defaulting to locally available versions
2022-01-24 17:37:18,428: Failed to get url https://api.github.com/repos/lutris/vkd3d/releases: HTTP Error 403: rate limit exceeded
2022-01-24 17:37:18,428: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:18,428: Loading of VKD3D versions failed, defaulting to locally available versions
2022-01-24 17:37:18,510: Failed to get url https://api.github.com/repos/lutris/d3d_extras/releases: HTTP Error 403: rate limit exceeded
2022-01-24 17:37:18,510: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:18,510: Loading of D3D Extras versions failed, defaulting to locally available versions
2022-01-24 17:37:18,510: Startup complete
INFO     2022-01-24 17:37:18,512 [startup.check_driver:53]:Using NVIDIA drivers 470.86 for x86_64
INFO     2022-01-24 17:37:18,513 [startup.check_driver:57]:GPU: NVIDIA GeForce GTX 1660 SUPER
INFO     2022-01-24 17:37:18,513 [startup.check_driver:73]:GPU: 10DE:21C4 10DE:21C4 (nvidia drivers)
DEBUG    2022-01-24 17:37:31,859 [lutriswindow.on_toggle_viewtype:716]:View type changed to list
DEBUG    2022-01-24 17:37:31,876 [lutriswindow.update_store:451]:Showing 17 games
INFO     2022-01-24 17:37:41,203 [application.do_shutdown:631]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Linux Mint 20.2 uma
Arch:            x86_64
Kernel:          5.13.0-27-generic
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600XT 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            16.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.86
OpenGL Core:     4.6.0 NVIDIA 470.86
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.86
Vulkan:          Supported
```

### Media (optional)

![Peek 2022-01-24 17-40](https://user-images.githubusercontent.com/89305232/150825730-7cf2816e-082f-4778-bf75-9abaf8ae80cd.gif)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment] 2022-02-04 09:17
I think this looks very like a duplicate of #3800 and several others. If so, a fix has been merged already.

**Closed** 2022-02-05 01:57 UTC
Labels: bug, needs triage
