### ISSUE TITLE
Built-in "search games on Lutris.net" does not work while installing a game

### ISSUE THREAD

**Issue by Dechcaudron** [lutris/lutris#1716] opened 2019-02-03 21:31 UTC
After installation is complete, the feature seems to work just fine, but in the meantime, a blank screen is presented when searching for games.

**Comment by tannisroot** [comment] 2019-03-02 20:55
Can't reproduce in latest master. Closing.
Please let me know if you can still experience this.

**Closed by tannisroot** 2019-03-02 20:55 UTC
