### ISSUE TITLE
Ubisoft Connect source doesn't show the list of games associated with an account

### ISSUE THREAD

**Issue by F-36** [lutris/lutris#5129] opened 2023-11-12 21:35 UTC
### Bug description

All sources show the list of games associated with their accounts, it is not the case with Ubisoft Connect even after connecting. 

I have to launch Ubisoft Connect and only then can I see my games within that launcher but still nothing in Lutris.

### How to Reproduce

1. Start Lutris
2. Click on 'Ubisoft Connect' tab in 'Sources'
3. 'No games found'

### Expected behavior

I'd like to see my games like I can see with GOG, Epic, EA App, etc. within Lutris.

### Log output

```shell
$ lutris -d
INFO     2023-11-12 22:32:04,560 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-11-12 22:32:04,561 [startup.get_drivers:70]:Running AMD Mesa driver 23.1.3 on AMD Radeon RX 6600 XT (navi23, LLVM 15.0.7, DRM 3.54, 6.5.6-76060506-generic) (0x73ff)
INFO     2023-11-12 22:32:04,561 [display.display_gpu_info:78]:GPU: 1002:73FF 1462:5021 (amdgpu drivers)
DEBUG    2023-11-12 22:32:05,788 [lutris.get_missing_game_ids:202]:Checking for missing games
```

### System Information

```shell
[System]
OS:              Pop!_OS 22.04 jammy
Arch:            x86_64
Kernel:          6.5.6-76060506-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           12th Gen Intel(R) Core(TM) i7-12700K
Physical cores:  12
Logical cores:   20

[Memory]
RAM:             31.1 GB
Swap:            20.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 XT (navi23, LLVM 15.0.7, DRM 3.54, 6.5.6-76060506-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.3-1pop0~1689084530~22.04~0618746
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.3-1pop0~1689084530~22.04~0618746
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.3-1pop0~1689084530~22.04~0618746
Vulkan Version:  1.3.204
Vulkan Drivers:  AMD Radeon RX 6600 XT (RADV NAVI23) (1.3.246)
```

**Comment by strycore** [comment] 2023-11-18 23:06
Make sure you're displaying all games, even uninstalled ones and if you still don't get anything, look the logs in the terminal when clicking refresh on Ubisoft.

**Comment by MadLittleMods** [comment] 2024-05-25 01:30
I can reproduce but this is my first time using Lutris so I'm not exactly sure of expectations. My account is connected and I can launch Ubisoft Connect and see my games in their launcher but not in Lutris itself.

I have the **Installed Games Only** filter unchecked and still see `No games found`

![](https://github.com/lutris/lutris/assets/558581/08423000-63a9-4ec9-b687-2d8ee744bcf1)


### Log output

```sh
$ lutris --debug
2024-05-24 20:19:51,444: Command 'vulkaninfo' not found on your system
2024-05-24 20:19:51,444: Command 'wine' not found on your system
2024-05-24 20:19:51,574: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-05-24 20:19:51,692 [application.do_command_line:479]:Starting Lutris 0.5.17
DEBUG    2024-05-24 20:19:51,693 [system._execute:109]:Executing lspci
INFO     2024-05-24 20:19:51,703 [startup.run_all_checks:120]:Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] (1002:744c 1849:5302 amdgpu) Driver 24.0.7
DEBUG    2024-05-24 20:19:51,810 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-05-24 20:19:51,815 [xrandr._get_vidmodes:18]:Retrieving 22 video modes from XrandR
DEBUG    2024-05-24 20:19:51,847 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-05-24 20:19:51,873 [api.check_stale_runtime_versions:52]:Modified at Fri 24 May 2024 07:33:05 PM , will update after Sat 25 May 2024 01:33:05 AM
ERROR    2024-05-24 20:19:51,898 [style_manager._call_cb:87]:Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
DEBUG    2024-05-24 20:19:51,899 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
```

### System information

```
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: NO
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO

[System]
OS: Manjaro Linux 24.0.0 Wynsdey
Arch: x86_64
Kernel: 6.6.30-2-MANJARO
Desktop: XFCE
Display Server: x11

[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 7800X3D 8-Core Processor
Physical cores: 8
Logical cores: 16

[Memory]
RAM: 62.5 GB
Swap: 16.0 GB

[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 17.0.6, DRM 3.54, 6.6.30-2-MANJARO)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.7 (git-cc175010c5)
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.7 (git-cc175010c5)
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.7 (git-cc175010c5)
Vulkan Version: 1.3.279
Vulkan Drivers: AMD Radeon RX 7900 XTX (RADV NAVI31) (1.3.274)
```

**Comment by Dan2077** [comment] 2024-06-13 11:44
Hi @MadLittleMods, I am also getting the same problem. No matter how many times I click the Connect button on the Ubisoft Connect source, it logs in, the little gear spins but my Ubisoft library doesn't sync my uninstalled games and doesn't appear to actually log in giving me the option to connect again. Any games I install through the  Ubisoft launcer does show up under the wine category but this is more of a work around then actually getting the Ubisoft Connect source working. This issue should be kept open until the source stay connected and displays games like the sources for EA App and Epic Games Store

**Comment by bmccord** [comment] 2024-07-20 03:34
I'm having exactly the same problem.  Has anyone here been able to solve it?

**Comment by italoghost** [comment] 2024-07-30 03:49
Same problem here as well

**Comment by taker1988** [comment] 2024-08-11 16:30
same problem with mint 22 and lutris 0.5.17

**Comment by Germanreddragon94** [comment] 2024-08-18 15:21
I have this problem too. GOG, Epic Games, EA App and Steam are working very well.
I am using Nobara 40 with Lutris 0.5017

**Comment by strycore** [comment] 2024-08-18 20:02
I have pushed a fix in the current master branch, it will be distributed in 0.5.18

**Closed by strycore** 2024-08-18 20:02 UTC
Labels: can't reproduce

**Comment by DOOMMARINE117** [comment] 2024-08-25 06:27
im having the same issue. no games found as well. im using zorin os.

**Comment by nex86** [comment] 2024-10-05 13:41
Same issue, was hoping for a solution but guess no body knows.

**Comment by italoghost** [comment] 2024-10-05 13:54
@strycore already said that it will be on 0.5.18. You can compile the program yourself if you want the fix now.

**Comment by nex86** [comment] 2024-10-05 14:00
> @strycore already said that it will be on 0.5.18. You can compile the program yourself if you want the fix now.

I need a flatpak version since I'm on steam os.

**Comment by nex86** [comment] 2024-10-05 14:46
its annoying because i have to launch ubisoft launcher first before I can launch the game.
how would I add it to steam?
