### ISSUE TITLE
Winemenubuilder isn't disabled by Lutris when using tkg-3.21 Wine

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/lutris#1488] opened 2019-01-03 14:08 UTC
I have created [a new install script](https://lutris.net/games/zdaemon/) for one game and tried to install the game using this script. Unfortunately, winemenubuilder wasn't disabled for some reason and Wine menu entries (`~/.local/share/applications/wine` and related icons) were created.

The Wine version used by the script is tkg-3.21 and Lutris version is 0.4.23 on Fedora 29.

**Comment by AsciiWolf** [comment] 2019-01-03 18:18
I have changed the Wine version used in the install script to regular 3.21 and everything is ok. So this issue happens only when using the tkg-3.21 build of Wine.

**Comment by tannisroot** [comment] 2019-01-04 00:08
Do you actually not see `winemenubuilder` in overrides after installing?

**Comment by AsciiWolf** [comment] 2019-01-04 11:18
Yeah, I think it was not there and I also saw in the installation log that winemenubuilder was not disabled. However, I already deleted the game and installed it again using the regular 3.21 Wine build (where everything works fine) so I cannot check the winecfg override.

**Comment by tannisroot** [comment] 2019-01-04 11:30
Would be nice if there was an actual comparison of installation logs with tkg-3.21 and regular. But, oh well.

**Comment by AsciiWolf** [comment] 2019-01-04 22:08
Hmm, did you use the tkg-3.21 Wine build? I tried it twice and was able to reproduce it both times. Unfortunately, I am currently not at home and I am quite busy. I'll try to reproduce it one more time in the following days if I get some free time.

**Comment by AsciiWolf** [comment] 2019-01-06 13:58
Hmm, I tried to reproduce this issue again and unfortunately no luck as well. Weird. It seems that this issue is really happening only sporadically and may not be related to the tkg Wine build after all.

Anyway, @strycore (or anyone else who has rights to do this) please review my ZDaemon installer, currently, the older version (that has the tkg Wine build) is used instead of the latest version for some reason.

**Comment by tannisroot** [comment] 2019-01-06 14:00
Now that i think about it, I am pretty sure I encountered this issue like, months ago.

**Comment by strycore** [comment] 2019-01-13 20:41
Pushing that to 0.5.1 since I have no idea what it is about and I cannot repro.

**Comment by tannisroot** [comment] 2019-03-02 21:30
Closing as it is still not reproducible.

**Closed by tannisroot** 2019-03-02 21:30 UTC
Labels: can't reproduce, needs confirmation, poor quality report
