### ISSUE TITLE
Add confirm dialog when removing a runner

### ISSUE THREAD

**Issue by WebFreak001** [lutris/lutris#1389] opened 2018-12-03 11:32 UTC
![screenshot of a lutris runner with remove and configure button, remove being highlighted](https://wfr.moe/fumdm0.png)

I accidentally pressed the Remove button when I wanted to Configure my wine steam runner and it just instantly removed wine steam without confirmation. It would be nice if it asked me if I really want to remove the runner before actually removing it.

**Comment by AlexanderRavenheart** [comment] 2018-12-03 14:55
Is a dialogue really needed or perhaps it would be better to change the style of the button and reposition it?

**Comment by WebFreak001** [comment] 2018-12-03 14:58
hm well you can tab over it so I would definitely put in a confirmation dialog, so if you don't expect the tab to go on a delete button you click it anyway if you use the keyboard to navigate. Especially because it's not directly reversible. But you always have to redownload everything it downloads which can take a while on a slow internet connection.

**Comment by strycore** [comment] 2018-12-07 08:48
We should add some extra checks for winesteam because removing it can potentially also remove games.

**Comment by AlexanderRavenheart** [comment] 2018-12-14 21:48
Fixed in #1401

**Comment by Medath** [comment] 2018-12-15 11:11
When I click delete, the pop-up appears as intended. When I then confirm the deletion, the runner gets deleted but the pop-up doesn't close and the terminal gets spammed with `(lutris:10854): Gtk-CRITICAL **: 12:08:38.561: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed`

**Comment by strycore** [comment] 2019-01-15 00:19
Fixed in a previous commit

**Closed by strycore** 2019-01-15 00:19 UTC
