### ISSUE TITLE
Use prime is greyed out.

### ISSUE THREAD

**Issue by Laezor** [lutris/lutris#1744] opened 2019-02-09 17:37 UTC
current only having lol on lutris when i go to configure > system options, Use PRIME (hybrid graphics on laptops) it is grey out, cant activate it.

**Comment by sonicpp** [comment] 2019-02-09 18:15
Hi Leazor,
this should be hopefully fixed in next version (0.5.1 maybe). Can you post output from `lspci` command here?
This is probably duplicate of bug #1732 - you can try apply patch f448d1bf4033850f6c78dfae4ac4d47e2a501b77 to check if this fixes your problem or not.

**Comment by Laezor** [comment] 2019-02-09 21:05
`00:00.0 Host bridge: Intel Corporation 3rd Gen Core processor DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
00:16.0 Communication controller: Intel Corporation 7 Series/C216 Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 1 (rev c4)
00:1c.1 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 2 (rev c4)
00:1c.2 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 3 (rev c4)
00:1d.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation HM76 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 7 Series/C216 Chipset Family SMBus Controller (rev 04)
01:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430] (rev ff)
07:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8188EE Wireless Network Adapter (rev 01)
08:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller (rev 07)
`
from the lspci command here you go.

**Comment by Laezor** [comment] 2019-02-09 21:26
also the patch you offered me, it did unlock "use prime" im testing it now.

**Comment by sonicpp** [comment] 2019-02-09 21:30
Thanks, important lines are:
```
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430] (rev ff)
```
I am pretty sure it is fixed by commit I mentioned above.

**Comment by Laezor** [comment] 2019-02-09 21:32
yes i have higher fps now, but games feels very laggy its not fluid.

**Comment by strycore** [comment] 2019-02-19 18:24
pretty sure I received PRs to fix that

**Closed by strycore** 2019-02-19 18:24 UTC
