### ISSUE TITLE
Esync toggle complains about incorrect limits

### ISSUE THREAD

**Issue by Enkouyami** [lutris/lutris#2568] opened 2020-01-03 07:53 UTC
OS: Linux Mint 19.3 64-bit
Linux Kernel: v5
Lutris version: 0.5.4

`$ ulimit -Hn` shows it's set to 
1048576, but when I try to toggle Esync in the settings, Lutris says "Your limits are not set correctly."

**Comment by tannisroot** [comment] 2020-01-09 15:43
Closing as it's a dupe of https://github.com/lutris/lutris/issues/1638

**Closed by tannisroot** 2020-01-09 15:43 UTC
Labels: duplicate, missing information
