### ISSUE TITLE
[Amazon] login window freezes

### ISSUE THREAD

**Issue by Vittelius** [lutris/lutris#4819] opened 2023-04-20 10:22 UTC
I can't login to my amazon prime gaming account. The login window opens but before I can enter any text the page freezes. The text cursor blinks once inside the email address field then it stops. I can't enter anything or click any of the links. If I resize the window it turns blank

Edit: I'm running arch (via endeavor OS) btw

**Comment by legluondunet** [comment] 2023-04-20 10:35
@danieljohnson2 that was the same issue I had on Arcolinux (Arch)

**Comment by danieljohnson2** [comment] 2023-04-20 20:45
I see that that may user name has become a curse word.

I feel proud of that. I think I earned it.

**Comment by rakklak** [comment] 2023-04-24 23:18
I am also facing this issue, fresh install of EOS, Amazon Games sign in hangs.

**Comment by Melon-Bread** [comment] 2023-05-18 22:49
Same issue sometimes it shows the login boxes but even then you can not enter anything. On Arch and the issues is there via the Arch package & Flatpak version. 

Is there a manual way of entering the token?

**Comment by strycore** [comment] 2023-05-27 21:23
Duplicate of #4783

**Closed by strycore** 2023-05-27 21:23 UTC
