### ISSUE TITLE
Winesteam freezes, "Never found the initial process' return code. Weird?"

### ISSUE THREAD

**Issue by dubcusb** [lutris/lutris#2563] opened 2020-01-01 18:17 UTC
**Describe the bug**
Launching any game logs the following:
> Never found the initial process' return code. Weird?
Exit with returncode 0

This doesn't cause any problems with non-winesteam games (at least in my experience). However, Trying to launch winesteam by any means, makes it unusable and seems to crash a few seconds after the message.

**Expected behavior**
Winesteam opens up normally and this error message isn't logged.

**Current behavior**
Winesteam opens up, and after a few seconds the UI freezes, and said error message is logged.

**Steps to reproduce**
Run a winesteam game with lutris from commit a178b89 or later.

**Lutris debugging output**
Example running Brawlhalla from winesteam ("Do not launch game, only open Steam" is on): last few lines of `lutris -d` I thought could be important:
```
System page size: 4096
Could not find page for trampoline in +/- 2GB range of function to hook
Error allocating trampoline memory (no memory within +/-2gb? prior failures?)
003d:fixme:ver:GetCurrentPackageId (0x23fd30 (nil)): stub
[0101/150806.479:ERROR:registration_protocol_win.cc(84)] TransactNamedPipe: Broken pipe. (0x6D)
0039:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
0039:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0039:fixme:ntdll:EtwEventRegister ({d2d578d9-2936-45b6-a09f-30e32715f42d}, 0x2341740, 0x6c44a28, 0x6cb1688) stub.
Never found the initial process' return code. Weird?
Exit with returncode 0
[0101/150806.486:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
0039:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x23ef44, (nil) 0x23ef40
0039:fixme:nls:get_dummy_preferred_ui_language (0x38 0x23ef44 (nil) 0x23ef40) returning a dummy value (current locale)
0039:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x23ef44, 0x23ef20 0x23ef40
0039:fixme:nls:get_dummy_preferred_ui_language (0x38 0x23ef44 0x23ef20 0x23ef40) returning a dummy value (current locale)
DEBUG    2020-01-01 15:08:06,554 [command.on_stop:165]:The process has terminated with code 0
DEBUG    2020-01-01 15:08:06,556 [command.stop:249]:Management process looks dead already.
DEBUG    2020-01-01 15:08:06,558 [command.stop:257]:Detaching logger
DEBUG    2020-01-01 15:08:07,710 [game.beat:641]:Game thread stopped
WARNING  2020-01-01 15:08:07,712 [game.on_game_quit:673]:Game still running (state: running)
INFO     2020-01-01 15:08:07,714 [game.stop:656]:Stopping Brawlhalla (winesteam)
DEBUG    2020-01-01 15:08:07,724 [command.stop:249]:Management process looks dead already.
DEBUG    2020-01-01 15:08:07,731 [command.stop:261]:logger already detached
DEBUG    2020-01-01 15:08:07,769 [game.on_game_quit:692]:Brawlhalla stopped at mié, 01 ene 2020 15:08:07
DEBUG    2020-01-01 15:08:07,770 [game.save:250]:Saving Brawlhalla (winesteam)
DEBUG    2020-01-01 15:08:07,807 [lutriswindow.on_game_updated:786]:Updating game Brawlhalla (winesteam)
```
This is my first report here, please forgive me if I missed something obvious or reported incorrectly.

**Comment by strycore** [comment] 2020-01-01 20:13
@AaronOpfer can you please look into that? I can reproduce this, Steam will launch but not the game. Also, there is an undefined `children` variable in the `hard_sig_handler` now. I don't know how you want to handle that but currently, that handler will not work.

**Comment by AaronOpfer** [comment] 2020-01-01 20:27
I can look into this. I think it's probably the issue I described in my email to you a few days ago; the `lutris-wrapper` doesn't handle the case well where the first process created is also considered "excluded".

**Comment by strycore** [comment] 2020-01-01 22:40
I pushed a workaround because Steam wouldn't start with the latest PR merged. The Steam process (or any main executable) should always be monitored.
I feel like there should be another monitor to track the status of Steam games, that way we don't add complexity to the process monitor by trying to handle that aspect.

**Comment by AaronOpfer** [comment] 2020-01-01 22:45
Hmm, that's odd, I launched a steam game and a wine game and it seemed to work with my PR, so long as Steam wasn't already open.

Excluded processes are starting to feel pretty weird, I think they were a holdover from when Lutris used to only be able to run one game at a time.

**Comment by strycore** [comment] 2020-01-01 22:54
I feel the same, maybe the fix really is to remove the concept of excluded processes.

**Comment by dubcusb** [comment] 2020-01-01 23:55
Just wanted to say that the current workaround is working for me, and that I can run winesteam with no problems with 5b12635. Thank you guys so much, I really appreciate your work on this!

**Comment by AaronOpfer** [comment] 2020-01-01 23:59
the lutris-wrapper would be much easier to write if we had reliable asynchronous signals for when processes are created or when they exit. RIght now we only have the latter, and only when we explicitly ask for it, and we have to poll for the former. If we had async signals then the wrapper script would be a lot easier to write and understand.

**Comment by strycore** [comment] 2020-01-02 01:30
By async, do you mean using the async/await features of Python? The oldest systems we support (Ubuntu 16.04/Debian 9) both ship with Python 3.5 so those features could be relied upon.

**Comment by strycore** [comment] 2020-01-02 02:01
I've removed the hardcoded list of processes and will close this issue since WineSteam is usable again.
There is still a concept of excluded processes that comes from the installers but I'm not sure if that needs to be kept or removed as well.

**Closed by strycore** 2020-01-02 02:01 UTC
