### ISSUE TITLE
[Feature Request] on window close scroll the app in tray.

### ISSUE THREAD

**Issue by matterai** [lutris/lutris#2450] opened 2019-11-08 16:03 UTC
**Why?**
I don't think it's a super priority idea, but I guess it would be quite cool if the app could be hidden in tray. Don't you think? :)

**Comment by tannisroot** [comment] 2019-11-13 10:58
Duplicate of https://github.com/lutris/lutris/issues/1953

**Closed by tannisroot** 2019-11-13 10:58 UTC
