### ISSUE TITLE
Better handling of default Wine version

### ISSUE THREAD

**Issue by rkben** [lutris/lutris#4337] opened 2022-06-22 16:25 UTC
Setting the Wine Version under the Wine runner is not respected when installing an executable.

Eg. `runners/wine.yml`
```yml
system:
  disable_compositor: false
wine:
  battleye: false
  eac: false
  esync: false
  fsr: false
  fsync: false
  version: lutris-GE-Proton7-15-x86_64
```

Will set any new prefix with Lutris' default (`lutris-fshack`) wine version instead of `lutris-GE-ProtonX-xx`.

- Lutris Version: 0.5.10.1

**Comment by strycore** [comment] 2023-06-06 03:49
There are several things we need to fix:

- Lutris defaults to whichever Wine version is the highest, this is not always desirable (ex: LoL build having a higher version than the normal build)
- The install process fetches the default Wine version for Lutris (as set by the dev team) but this default version isn't enforced anywhere else
- The wine version used during install can't easily be overridden.

**Comment by danieljohnson2** [comment] 2023-06-06 08:15
Is this reproducable still? I thought all this was working by 0.5.13.

It's not exactly the same as #4370, but the code for this looks solid to me.

**Comment by strycore** [comment] 2023-06-06 23:21
We haven't fixed what I mentioned in my comment.

**Comment by TormStorm** [comment] 2023-09-12 09:06
Any updates on this issue?

**Comment by danieljohnson2** [comment] 2023-09-12 09:16
The runner's default Wine version is now respected when installing (unless the script specifies a version); I needed that myself quite recently, and it worked.

The next Lutris release should download the latest Wine when installing a game, so that the default Wine for the new install can update (if not otherwise set) at that time. It's not "enforced" anywhere else, I guess, but I don't know what @strycore intends by that.

You can override the Wine version used for installs by configuring the runner, but maybe that is not "easily" enough.

You cannot override a script though - in Soviet Lutris, the script overrides you!

I have no plans for further work in this area, at least until I understand what @strycore wants to do here,

**Comment by strycore** [comment] 2023-09-13 00:11
I've made some further changes yesterday.
Lutris now gets all runtime and runner versions from a single API request. This request is saved to ~/.cache/lutris/versions.json

New Wine versions will be downloaded when Lutris starts. Not when installing a game, not when starting a game. 

We still need a widget to override the wine version used during installs but that's less urgent. We don't want people fiddling with that too much, game installs should work with our recommended build, otherwise they should report it as a bug. Or pin the wine version in the installer if the bug is already reported and awaiting a fix.

**Comment by strycore** [comment] 2023-09-13 01:01
I realized that I made this comment while I had a bunch of related changes still sitting on my computer.  This commit should make things clearer: https://github.com/lutris/lutris/commit/58dfa870fe5413fd90f0d9fb129cbc74357b1255

**Comment by strycore** [comment] 2023-09-13 01:03
Once I download the default wine on startup, I'll close the ticket. Adding the dropdown to select wine versions during installs is out of scope for this particular feature.

**Comment by strycore** [comment] 2023-09-14 18:07
yes, it does fix it since it will be much harder to not have the recommended wine version.

**Comment by strycore** [comment] 2023-09-15 23:55
Lutris now downloads the recommended Wine version on startup. This can be closed.

**Closed by strycore** 2023-09-15 23:55 UTC
