### ISSUE TITLE
TypeError: 1 parameters needed for signal error; 0 given

### ISSUE THREAD

**Issue by kettle256** [lutris/lutris#5751] opened 2024-11-26 23:01 UTC
### Bug description

Looks like a small bug in Lutris code

I've encountered and issue while installing a game due to low disk space

### How to Reproduce

1. Go to a game
2. Click on download
3. Wait until disk fills up
4. See the error

### Expected behavior

.

### Log output

```shell
Traceback (most recent call last):

  File "/app/lib/python3.11/site-packages/lutris/exception_backstops.py", line 108, in error_wrapper
    return handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/download_collection_progress_box.py", line 161, in _progress
    self.emit("error")

TypeError: 1 parameters needed for signal error; 0 given
```

### System Information

```shell
Linux Mint 21.3 (aka Ubuntu jammy)
```

### Media (optional)

![Screenshot from 2024-11-26 14-42-40](https://github.com/user-attachments/assets/eecbb837-2ee8-476d-8851-1efb57a6d922)

**Comment by danieljohnson2** [comment] 2024-11-26 23:04
This is a dupe of (part of) #5599. This part has been fixed in master, which will now report errors during downloads correctly.

Of course, you really need to buy a bigger disk. Better error reporting won't help with that.

**Closed by danieljohnson2** 2024-11-26 23:04 UTC
