### ISSUE TITLE
Lutris doesn't remove prefix when uninstalling Wine Steam game

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#2087] opened 2019-04-25 06:58 UTC

**Comment by tannisroot** [comment] 2019-05-17 12:09
Can you check whether it's a dupe of https://github.com/lutris/lutris/issues/2084 ?

**Comment by strycore** [comment] 2020-05-22 17:37
No, this is unrelated. When uninstalling a game through steam, it doesn't delete extra folders that could have been created.

**Comment by strycore** [comment] 2020-12-24 20:11
Closing this as we're deprecating the WineSteam runner at some point in the near future.

**Closed by strycore** 2020-12-24 20:11 UTC
Labels: needs confirmation
