### ISSUE TITLE
League of Legends after match client doesn't respond

### ISSUE THREAD

**Issue by pessoaneto** [lutris/lutris#2099] opened 2019-05-01 19:43 UTC
Hello, i installed league of legends on lutris and it works flawless in-game, however the inicial screen doesn't conect and after the match client doesn't respond.

```
Running /home/pessoaneto/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine /home/pessoaneto/Games/league-of-legends/drive_c/Riot Games/League of Legends/LeagueClient.exe
LeagueClient.exe(00000009): ALWAYS| Application Version:9.9.272.6103 - CL:2726103 - Build Date:Apr 29 2019 - Build Time:14:06:37
Waiting on children
Waiting on children
2019-05-01 13:32:59,634: Unable to read stat for process 6769
2019-05-01 13:32:59,634: Unable to read stat for process 6769
Waiting on children
Waiting on children
2019-05-01 13:49:49,943: Unable to read stat for process 6824
2019-05-01 13:49:49,968: Unable to read stat for process 6824
Waiting on children
2019-05-01 13:49:51,649: Unable to read stat for process 6801
2019-05-01 13:49:51,649: Unable to read stat for process 6801
Waiting on children
Waiting on children
AL lib: (WW) ReleaseThreadCtx: 0xeed08c30 current for thread being destroyed
AL lib: (WW) ReleaseContext: 0xeed08c30 released while current on thread
AL lib: (WW) ReleaseThreadCtx: 0xeed08c30 current for thread being destroyed
Waiting on children
2019-05-01 16:31:00,183: Unable to read stat for process 6751
2019-05-01 16:31:00,204: Unable to read stat for process 6751
Waiting on children
Caught signal 15
passing along signal to PID 8381
passing along signal to PID 8423
passing along signal to PID 8661
--terminated processes--
2019-05-01 16:40:06,979: Unable to read stat for process 8423
2019-05-01 16:40:06,979: Unable to read stat for process 8423
All children gone
Exit with returncode 0
```

**Comment by AccountOneOff** [comment] 2019-05-08 00:16
https://github.com/lutris/lutris/wiki/Getting-Help:-Providing-logs-&-System-Info#wine-debugging-output

**Comment by tannisroot** [comment] 2019-05-16 09:24
Riot broke the game in Wine after a recent update. Please follow the bug report regarding this on Wine's Bugzilla.
Closing as it's not a bug in Lutris client.

**Closed by tannisroot** 2019-05-16 09:24 UTC
Labels: missing information
