### ISSUE TITLE
League of legends : Bad file descriptor

### ISSUE THREAD

**Issue by RichardFevrier** [lutris/lutris#4931] opened 2023-07-14 18:26 UTC
### Bug description

Everytime I try to install LoL I get a `wine client error:4fc: write: Bad file descriptor`

### How to Reproduce

Open `lutris` (`flatpak` or `dnf`)
Search `League of legends`
Start install process
Accept to install mono if not already installed
Install the `LoL launcher`
Encounter the error at the end of the `LoL launcher` installation

### Expected behavior

Complete the installation successfully

### Log output

```shell
[richard@Computer-Richard ~]$ flatpak run net.lutris.Lutris -d
INFO     2023-07-14 20:19:33,619 [startup.init_lutris:237]:Starting Lutris 0.5.13
INFO     2023-07-14 20:19:33,621 [startup.check_driver:72]:Running AMD Mesa driver 23.1.1 on AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.12-200.fc38.x86_64) (0x73bf)
INFO     2023-07-14 20:19:33,621 [startup.check_driver:84]:GPU: 1002:73BF 1462:3953 (amdgpu drivers)
DEBUG    2023-07-14 20:19:36,337 [application.show_window:339]:Showing window AddGamesWindow{}
DEBUG    2023-07-14 20:19:42,515 [http._request:88]:GET https://lutris.net/api/games?search=league+of+legends&with-installers=True
DEBUG    2023-07-14 20:19:45,021 [api.get_game_installers:171]:Fetching installer https://lutris.net/api/installers/league-of-legends
DEBUG    2023-07-14 20:19:45,021 [http._request:88]:GET https://lutris.net/api/installers/league-of-legends
DEBUG    2023-07-14 20:19:46,218 [application.show_window:339]:Showing window InstallerWindowleague-of-legends
DEBUG    2023-07-14 20:19:46,219 [application.on_app_window_destroyed:357]:Removed window AddGamesWindow{}
DEBUG    2023-07-14 20:19:47,628 [displayconfig.get_current_resolution:643]:Retrieving current resolution
DEBUG    2023-07-14 20:19:51,140 [downloader.start:67]:⬇ https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.euw.exe
DEBUG    2023-07-14 20:19:53,279 [downloader.on_download_completed:170]:Finished downloading https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.euw.exe
INFO     2023-07-14 20:19:53,643 [file_box.on_download_complete:239]:Download completed
DEBUG    2023-07-14 20:19:53,643 [files_box.on_file_available:108]:lol_installer is available
INFO     2023-07-14 20:19:53,643 [files_box.on_file_available:114]:All files available
INFO     2023-07-14 20:19:53,644 [installerwindow.on_files_available:635]:All files are available, continuing install
DEBUG    2023-07-14 20:19:53,645 [interpreter.create_game_folder:218]:Creating destination path /var/mnt/data/Games/league-of-legends
DEBUG    2023-07-14 20:19:53,645 [interpreter._iter_commands:357]:Installer command: {'input_menu': {'id': 'LOCALE', 'options': [{'cs_CZ': 'Čeština'}, {'en_AU': 'English AUS'}, {'en_GB': 'English U.K.'}, {'en_US': 'English U.S.'}, {'fr_FR': 'Français'}, {'de_DE': 'Deutsch'}, {'es_ES': 'Español'}, {'es_MX': 'Español Mexicano'}, {'it_IT': 'Italiano'}, {'ja_JP': '日本語'}, {'hu_HU': 'Magyar'}, {'pl_PL': 'Polski'}, {'pt_BR': 'Português do Brasil'}, {'ro_RO': 'Romanian'}, {'ru_RU': 'русский'}, {'tr_TR': 'Türkçe'}], 'preselect': 'en_US'}}
DEBUG    2023-07-14 20:19:56,209 [interpreter._iter_commands:357]:Installer command: {'task': {'name': 'create_prefix', 'prefix': '$GAMEDIR'}}
INFO     2023-07-14 20:19:56,213 [wine.create_prefix:98]:Creating a win64 prefix in /var/mnt/data/Games/league-of-legends
DEBUG    2023-07-14 20:19:56,213 [system.execute:57]:Executing /var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wineboot
DEBUG    2023-07-14 20:19:56,213 [system.execute:63]:WINEARCH=win64 WINEPREFIX=/var/mnt/data/Games/league-of-legends WINEDLLOVERRIDES=winemenubuilder= WINE_MONO_CACHE_DIR=/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/mono WINE_GECKO_CACHE_DIR=/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/gecko
INFO     2023-07-14 20:20:05,654 [wine.create_prefix:153]:win64 Prefix created in /var/mnt/data/Games/league-of-legends
DEBUG    2023-07-14 20:20:05,679 [interpreter._iter_commands:357]:Installer command: {'task': {'args': '$lol_installer', 'executable': '$GAMEDIR/drive_c/windows/explorer.exe', 'include_processes': 'explorer.exe', 'name': 'wineexec'}}
DEBUG    2023-07-14 20:20:05,711 [wine.use_lutris_runtime:123]:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine is provided by Lutris, using runtime
WARNING  2023-07-14 20:20:05,718 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,718 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,718 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,718 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,718 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,718 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,718 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,718 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,719 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,720 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,720 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,720 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,720 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,720 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,720 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,720 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,720 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,720 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,721 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,721 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,721 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,721 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,721 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,721 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,741 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
WARNING  2023-07-14 20:20:05,742 [runner.game_config:141]:Accessing game config while runner wasn't given one.
ERROR    2023-07-14 20:20:05,748 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2023-07-14 20:20:05,748 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
DEBUG    2023-07-14 20:20:05,756 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-07-14 20:20:05,756 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/var/mnt/data/Games/league-of-legends"
DEBUG    2023-07-14 20:20:05,756 [command.start:141]:LD_LIBRARY_PATH="/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib64:/usr/lib/x86_64-linux-gnu:/app/lib/i386-linux-gnu:/app/lib:/app/lib32:/usr/lib/x86_64-linux-gnu/GL/default/lib:/app/lib/i386-linux-gnu/GL/default/lib:/app/lib/ffmpeg/.:/app/lib32/ffmpeg/.:/usr/lib/x86_64-linux-gnu/openh264/extra:/lib:/lib64:/usr/lib:/usr/lib64:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/Ubuntu-18.04-i686:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/lib/i386-linux-gnu:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/lib:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/i386/usr/lib:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/Ubuntu-18.04-x86_64:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/lib:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-07-14 20:20:05,756 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-07-14 20:20:05,756 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINEARCH="win64"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINE="/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINE_MONO_CACHE_DIR="/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/mono"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINE_GECKO_CACHE_DIR="/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/gecko"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib64/gstreamer-1.0/:/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINEPREFIX="/var/mnt/data/Games/league-of-legends"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINEESYNC="1"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/battleye_runtime"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:PROTON_EAC_RUNTIME="/var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runtime/eac_runtime"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d12core,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:DXVK_STATE_CACHE_PATH="/var/mnt/data/Games/league-of-legends"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:STAGING_SHARED_MEMORY="1"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:PYTHONPATH="/app/lib/lutris:/app/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/app/lib/python3.10/site-packages:/usr/lib/python3.10/site-packages"
DEBUG    2023-07-14 20:20:05,757 [command.start:141]:LUTRIS_GAME_UUID="c81173d8-1e03-4abd-8159-ee2767b417b4"
Started initial process 150 from /var/home/richard/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-ge-lol-8.7-1-x86_64/bin/wine /var/mnt/data/Games/league-of-legends/drive_c/windows/explorer.exe /var/home/richard/.var/app/net.lutris.Lutris/cache/lutris/installer/league-of-legends/lol_installer/live.euw.exe
Start monitoring process.
fsync: up and running.
Initial process has exited (return code: 0)
wine client error:4fc: write: Bad file descriptor
```

### System Information

```shell
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.3.12-200.fc38.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5950X 16-Core Processor
Physical cores:  16
Logical cores:   32

[Memory]
RAM:             31.2 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.12-200.fc38.x86_64)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.1 (git-fa55e3c026)
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.1 (git-fa55e3c026)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.1 (git-fa55e3c026)
Vulkan Version:  1.3.224
Vulkan Drivers:  AMD Radeon RX 6800 XT (RADV NAVI21) (1.3.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ppp7032** [comment] 2023-07-16 16:42
I can confirm I am experiencing the exact same issue.
System Information:

```
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          5.15.0-76-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.54.03
OpenGL Core:     4.6.0 NVIDIA 535.54.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.54.03
Vulkan Version:  1.3.224
Vulkan Drivers:  NVIDIA GeForce RTX 3070 (1.3.242)
```

When testing a deb version of lutris, however, Riot client managed to launch, and it download the league client. When closing riot client before logging in (as you're supposed to), I then get a similar `Bad file descriptor` error in my logs and the installation doesn't terminate unless i force close riot client. However, the riot client will permanently hang if you try to launch it from there. 

The good news is I managed to get around this issue by backing up my game folder after the league client was downloaded on the deb version, then copy-pasting the "Riot Games" folder (from within wine's C drive) from the backup into the corresponding location while trying to install the game on flatpak lutris (and just before pressing install on the riot client installer). This causes no downloads to be made and no installation of the riot or league clients as it is recognized that the files are already there. 

Note that I have not yet tested if I can get into the game, but I'm now in the league client and the game is downloading so I'm pretty sure I will be ingame soon.

**Comment by uwais-ix** [comment] 2023-07-16 23:35
Riot only supports 64 bit now. 

You could try the following
-  in riot client set close button behavior to close instead of minimize 
-  after install, in configure options change prefix architechture to x64

**Comment by strycore** [comment] 2023-07-17 11:53
@uwais-ix I don't see anywhere in this ticket a mention of running LoL in a 32bit prefix. 
In fact, I don't think anyone has done that since 1972.

**Comment by ppp7032** [comment] 2023-07-17 15:29
> @uwais-ix I don't see anywhere in this ticket a mention of running LoL in a 32bit prefix.
> In fact, I don't think anyone has done that since 1972.

Actually afaik league of legends was using a 32-bit wine prefix until a few months ago when Riot began to deprecate support for 32-bit clients. But the installation script has already been updated to account for this, and I believe this issue is relatively obscure. There’s only one or two posts about this in the [leagueoflinux community](https://kbin.social/m/leagueoflinux) and the official website [reports the game is currently playable](https://leagueoflinux.org/status/)  (which it is, but apparently not installable for everyone?)

**Comment by strycore** [comment] 2023-07-17 18:01
I've recently installed LoL on the Steam Deck (so the Flatpak version of Lutris) and it installed without issue. I didn't try any online matches but the training tool was working great.

**Comment by AtomToast** [comment] 2023-07-23 14:34
I have 2 bad file descriptor errors when installing league through the arch repos lutris. However the Game does fully install fine and run. Just past champ select the Game insta crashes, no matter how often I try to reconnect.

I now tried to install it through the flatpak version too and I get the exact same error as in the initial post. And ppp's workaround also works for me. However in the actual Game I keep having stutters, even though my fps and ping are stable. The game keeps briefly freezing and then teleporting back forward

**Comment by RichardFevrier** [comment] 2023-07-23 17:50
> However in the actual Game I keep having stutters, even though my fps and ping are stable. The game keeps briefly freezing every few seconds and then teleporting back forward

What is the wine version used to run the game?

**Comment by nmlynch94** [comment] 2023-07-24 04:24
I also get this behavior on Fedora 38
```
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.3.12-200.fc38.x86_64
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 3700X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.2 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.54.03
OpenGL Core:     4.6.0 NVIDIA 535.54.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.54.03
Vulkan Version:  1.3.224
Vulkan Drivers:  NVIDIA GeForce RTX 3070 (1.3.242)

```

**Comment by AtomToast** [comment] 2023-07-24 13:05
> What is the wine version used to run the game?

on lutris it's with lutris-ge-lol-8.7-1. However I also tried it with the aur leaguefoflegends-git package now, with both wine-lol (8.7_1-1), and wine-lol-staging (8.12-1) and it still occured.

I did figure out that this was suddenly caused by having movement prediction on, which is a setting that I haven't touched in forever but now all of a sudden it caused the teleports when clicking rapidly and moving back and forth.

I don't think it's necessarily related to this issue but it did start occurring at the same time for me

**Comment by tulilirockz** [comment] 2023-07-24 20:08
Guys, apparently killing the "RiotServices(something).exe" process when it goes to the tray is a proper workaround to this issue

**Comment by nmlynch94** [comment] 2023-07-24 21:39
I can confirm the above works for me. Thank you!

**Comment by AndreiTS** [comment] 2023-07-24 22:24
had the same issue

```
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          5.15.0-76-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.54.03
OpenGL Core:     4.6.0 NVIDIA 535.54.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.54.03
Vulkan Version:  1.3.224
Vulkan Drivers:  Intel(R) UHD Graphics 630 (CFL GT2) (1.3.246), NVIDIA GeForce GTX 1650 (1.3.242)
```

killing RiotClientServices.exe after the "bad file descriptor" error completed the instalation and I was able to open the launcher

**Comment by BrandonDalton** [comment] 2023-07-25 13:33
Had the same issue here is what I did to get it working after many attempts.

When the client finishes downloading and hangs on the minimize to tray.

I killed RiotClientCrash then the  RiotClientServices.Exe then the Client was able to boot and I can login.

**Comment by Gibbo83547** [comment] 2023-07-27 20:44
Sorry for the silly question, I'm having same problem, but what do you all mean you Killed RiotClientCrash and RiotClientServices.Exe , do you mean you just closed it>? I can see the little Riot games icon at the bottom of the screen but it's not taking me to log in page, can someone give a step by step easy to follow for a newbie. Plsssssssss Been looking at threads and fixes for the past 3 hours but I'm not an IT techy

**Comment by AndreiTS** [comment] 2023-07-27 21:05
> Sorry for the silly question, I'm having same problem, but what do you all mean you Killed RiotClientCrash and RiotClientServices.Exe , do you mean you just closed it>? I can see the little Riot games icon at the bottom of the screen but it's not taking me to log in page, can someone give a step by step easy to follow for a newbie. Plsssssssss Been looking at threads and fixes for the past 3 hours but I'm not an IT techy

Open your task manager, and kill the process.

**Comment by HeitorMC** [comment] 2023-08-05 16:53
Hey folks, I don't know why but my league client was very laggy and affecting the whole system performance. So I checked the league's Lutris page and I saw that a new release was available. I tried to install it and did everything you guys said above. I tried to play it after the installation, but then the game won't open and kept popping this warning 

![image](https://github.com/lutris/lutris/assets/34009891/8c975558-999b-4271-8a79-fc453395e85b)


Any ideas?

**Comment by AndreiTS** [comment] 2023-08-05 20:50
> Hey folks, I don't know why but my league client was very laggy and affecting the whole system performance. So I checked the league's Lutris page and I saw that a new release was available. I tried to install it and did everything you guys said above. I tried to play it after the installation, but then the game won't open and kept popping this warning
> 
> ![image](https://user-images.githubusercontent.com/34009891/258597984-8c975558-999b-4271-8a79-fc453395e85b.png)
> 
> Any ideas?

The "not responding" message is normal, but if the game is not opening there is something wrong. Honestly just try to reinstall it.

**Comment by HeitorMC** [comment] 2023-08-06 16:33
> > Hey folks, I don't know why but my league client was very laggy and affecting the whole system performance. So I checked the league's Lutris page and I saw that a new release was available. I tried to install it and did everything you guys said above. I tried to play it after the installation, but then the game won't open and kept popping this warning
> > ![image](https://user-images.githubusercontent.com/34009891/258597984-8c975558-999b-4271-8a79-fc453395e85b.png)
> > Any ideas?
> 
> The "not responding" message is normal, but if the game is not opening there is something wrong. Honestly just try to reinstall it.

I searched a little more, I don't know why but the wine version lutris-ge-lol-7-x somehow stopped working. So I installed the latest version available here: https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-LOL-p8-12 and worked fine! :grimacing:

**Comment by guswruck** [comment] 2023-08-10 00:33
had a little headache to kill this process on chromeOS, the default chrome task manager doesn't show the linux apps working on the crostini container, after a little research i found that going on the linux terminal and typing 'top' will show a more detailed vision of the running apps including the linux apps, after finding the RiotClientServices.exe on the list look for its service number and type "kill number"

may save some non programmer like me from a headache

**Comment by github-luciano** [comment] 2023-09-18 12:17
I confirm too that ending the process RiotClientSerivces.exe fixes the freeze during the installation, then it completes successfully.

**Comment by Ezzz-dev** [comment] 2023-10-22 20:17
I had this issue in Ubuntu where the installer would be stuck at 0.1 kb/s after finishing the first installation.
I closed the RiotServices.exe app from System Monitor, and still could not open the game, I downloaded the wine-ge-lol from Lutris in the runners window and set LOL to use it, disabled battleye and easyanticheat and the game opened fine afterwards.

**Comment by strycore** [comment] 2023-12-21 02:01
New LoL build is out and fixes the game once again.

@everyone: please ignore any message from wine saying "bad file descriptor" those are not relevant.

**Closed by strycore** 2023-12-21 02:01 UTC

**Comment by RichardFevrier** [comment] 2023-12-21 04:14
> New LoL build is out and fixes the game once again.

Are you talking about installing/running/both LoL @strycore Because this issue is about installing.

**Comment by strycore** [comment] 2023-12-23 01:17
@RichardFevrier I've tried a new install as well and it worked without an issue.
