### ISSUE TITLE
'No file provided' after installing battle.net

### ISSUE THREAD

**Issue by gituser823** [lutris/lutris#1770] opened 2019-02-16 15:32 UTC
hello,

battle.net seems to have been isntalled correctly, but when I want to launch battle.net/Overwatch, I get the Error 'no file provided'
It points to ~/Games/overwatch/drive_c/Program Files (x86)/Battle.net/Battle.net.exe but under /Program Files (x86) there is no folder called Battle.net. What can be the Issue here?

**Comment by tannisroot** [comment] 2019-02-16 19:11
Did you read through all of https://github.com/lutris/lutris/wiki/Game:-Blizzard-App ?

**Comment by tannisroot** [comment] 2019-03-02 20:52
I can't reproduce and neither can other people. Closing.

**Closed by tannisroot** 2019-03-02 20:52 UTC
Labels: invalid, poor quality report

**Comment by gituser823** [comment] 2019-03-08 18:06
I have re-isntalled Mint now and I am getting the same Error again.

How can I fix this?

**Comment by BuesiVenoM** [comment] 2019-04-11 15:11
I also got this error. When I removed the whole game from lutris and reinstalled it over the website it worked. I think the error was, that the battle.net installer somehow didn't started after the download.
I also installed the game over lutris. Not battle.net.

**Comment by ThornedRose** [comment] 2019-05-05 01:29
I have the same error. I checked all dependencies before installation and they are all installed. First time installing Lutris so fresh. And thus first install of Overwatch.
I'm on Arch Linux.
I tried as @BuesiVenoM did, however when installing via the website, BattleNet won't download. It takes about 30 seconds to even start downloading, gets part way through then stops and throws a "Connection reset by peer" error.
https://i.imgur.com/E2Et4FT.png

**Comment by ThornedRose** [comment] 2019-05-05 02:07
After doing an internet search, I found a large swath of BattleNet users who also could not download the installer regardless of method/route. A Blizzard CS suggested to use an alternate download link here: https://us.battle.net/forums/en/bnet/topic/20769826808#post-9
I downloaded the Lutris Overwatch Install Script and altered the lines with the download URL and filename to the ones supplied by the Blizzard CS.
i.e. Line 11 and 12
```
        "url": "https://battle.net/download/getInstaller?os=win&installer=Battle.net-Setup.exe",
        "filename": "Battle.net-Setup.exe"
```
get changed to:
```
        "url": "http://dist.blizzard.com/downloads/bna-installers/322d5bb9ae0318de3d4cde7641c96425/retail.1/Battle.net-Setup-enUS.exe",
        "filename": "Battle.net-Setup-enUS.exe"
```
I cannot, however, say whether this is what was causing the original issue of BattleNet being missing from the install directory when installing through the Lutris client. But at least this may be useful if anyone else experiences issues with 'Connection reset by peer' error.

**Comment by tannisroot** [comment] 2019-05-14 11:38
I will consider making an installer with this alternative link, thanks. But it's not the really what is causing these issues.

**Comment by DanielNoga** [comment] 2019-06-23 09:35
Same issue for me. I installed Lutris 0.5.2.1 on openSUSE Leap 15.1 and clicked to install Battle.net . I tried to run it and I see only "No file provided"

**Comment by tannisroot** [comment] 2019-06-23 19:16
@DanielNoga your issue is caused by https://github.com/lutris/lutris/issues/2066

**Comment by rsd** [comment] 2019-07-15 16:26
> i.e. Line 11 and 12
> 
> ```
>         "url": "https://battle.net/download/getInstaller?os=win&installer=Battle.net-Setup.exe",
>         "filename": "Battle.net-Setup.exe"
> ```
> 
> get changed to:
> 
> ```
>         "url": "http://dist.blizzard.com/downloads/bna-installers/322d5bb9ae0318de3d4cde7641c96425/retail.1/Battle.net-Setup-enUS.exe",
>         "filename": "Battle.net-Setup-enUS.exe"
> ```
> 

Had the same issue with Starcraft II.
Changing the link, solved it.

**Comment by ptkdev** [comment] 2019-07-19 10:37
Same problem

**Comment by smtheard** [comment] 2019-08-03 21:18
same issue here, followed all instructions and have correct versions of drivers, gfx card, and vulkan.

**Comment by mixedCase** [comment] 2019-08-19 00:21
@tannisroot I am facing the reported "Connection reset by peer" error, which I can reproduce with both a browser or wget where it downloads around ~15% of the installer and fails. Thankfully, the solution provided by @ThornedRose worked for me 3 months after his post, and 8 months after a Blizzard representative submitted those URLs as an alternative.

Whatever problem it is, whether it's ISP/CDN routing as some speculate or something else, it hasn't gone away and that alternative URL does work, it would be nice to have this available as a separate installer (or as an automatic workaround if possible) since this seems to be a common enough issue.

**Comment by Perlovka** [comment] 2019-12-02 14:11
Installed lutris, tried to install Wow Classic, got issue, found this topic closed as "not my problem" - removed lutris. Best support ever.

JFYI, Battle.net could be installed easily with plain wine without mystical "dependencies".

**Comment by tannisroot** [comment] 2019-12-03 01:44
@tannisroot this Github repository is just not for user support, we have a dedicated Discord server for that.

**Comment by Perlovka** [comment] 2019-12-03 11:30
Ah, I understood. No discord - no support. Good luck )

**Comment by strycore** [comment] 2019-12-04 02:05
No open source project offers support on old closed bug reports. What planet are you from that you believe otherwise?

**Comment by tannisroot** [comment] 2019-12-04 06:22
> Ah, I understood. No discord - no support. Good luck )
There's also an IRC channel to which we have a bridge on our Discord, but it gets far less attention unfortunately.

**Comment by strycore** [comment] 2019-12-04 16:37
We also have a forum on the website

**Comment by Perlovka** [comment] 2019-12-04 16:49
@strycore Old closed **not fixed** bug report. And I'm not seeking support, just tried to use the app.

**Comment by ChenYizhu97** [comment] 2019-12-04 23:06
I met the same issue. I installed league of legends and overwatch. Both of them shown 
>Some parts of the installation process may have not completed successfully
after installation. Sad to find this issue closed without any solution.

**Comment by strycore** [comment] 2019-12-05 03:32
This is very weird but also, bugs shouldn't be that hard to figure out.

This is seems to only happen to people who don't give additional details on the issue.
Being an open source project makes it really easy to find potential issues but here we have this weird bug where no one ever gives any kind of detail on what's happening.

While there might be a valid issue beneath all of this, it requires someone who is willing to put the kind of effort that lets us write and push a fix.

If you ship your computer to me, I will fix the bug in a matter of minutes But with what I'm given to work with, I'm at a loss. I lack divination powers.

**Comment by tannisroot** [comment] 2019-12-05 06:35
> Old closed not fixed bug report. And I'm not seeking support, just tried to use the app.

This is a garbage bug report though, it describes a generic message that Lutris gives when it can't find a file that the installer specifies and that's it. And I can promise it's almost certainly a setup issue (or, in rare cases, Gentoo being very special and just not working with Lutris while every other single distribution does). Dozens of people join the Lutris server with the same issue every day and it always gets solved by following one of the pre-made guides we have.

**Comment by Perlovka** [comment] 2019-12-05 10:21
@tannisroot This is not Gentoo related at all, users got this issue on Mint, OpenSUSE, Arch distros as well, as you can see from comments.

@strycore ok, I've installed lutris again just to reproduce the bug (clean lutris install, default settings):

1. Go to https://lutris.net/games/world-of-warcraft-classic/ and click Install
2. Upon installation you get the following message in the install window:
```
The executable at path /mnt/data/lutris/world-of-warcraft-classic/drive_c/Program Files (x86)/Battle.net/Battle.net.exe can't be found, please check the destination folder.
Some parts of the installation process may have not completed successfully.
```

Battle.net setup failed (There is nothing in Program Files)
Logs are attached.
[battle.net-setup-20191205T100831.864854.log](https://github.com/lutris/lutris/files/3926255/battle.net-setup-20191205T100831.864854.log)
[lutris.log](https://github.com/lutris/lutris/files/3926260/lutris.log)

As you can see in lutris log, it failed to extract something.

How it works without lutris:
1. Download Battle.net-Setup.exe from https://www.blizzard.com/en-us/apps/battle.net/desktop
2. WINEPREFIX=/some/directory/ wine /path/to/Battle.net-Setup.exe
3. Profit.

**Comment by tannisroot** [comment] 2019-12-05 11:43
> This is not Gentoo related at all, users got this issue on Mint, OpenSUSE, Arch distros as well, as you can see from comments.
this is not one single issue! Lutris is just telling you that it was expecting a file to be present after install and it isn't. There can be a million reasons for that.
And I can't reproduce your issue at all whatsoever, the installer works just fine.
In the logs you've provided, Lutris doesn't seem to be downloading its runtime, and it fails to extract the archive because, my guess is, it's damaged for whatever reason.
I would love you to help with that and I have a few guesses what could be the reason, but you will need to contact me through either IRC or Discord, not spam in this completely unrelated issue.
