### ISSUE TITLE
BUG: Lutris outputs multiple shortcuts for same game.

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#1826] opened 2019-03-02 15:15 UTC
Disclaimer: I didn't find any other issue in lutris's repo that is relevant and i've consulted this issue on discord with lutris's team on which i'm filing this issue.

Lutris outputs multiple shortcuts for one title for no reason when game is installed.
![image](https://user-images.githubusercontent.com/11302521/53683686-126fef80-3d04-11e9-8cf5-6221095b4bca.png)

afaik the shotcuts are same.

### Steps to reproduce
- Install league of legends
- Check lutris for duplicate shortcut.

**Comment by tannisroot** [comment] 2019-03-02 15:39
Duplicate of https://github.com/lutris/lutris/issues/1799

**Closed by tannisroot** 2019-03-02 15:39 UTC
