### ISSUE TITLE
get_winelib_paths in runtime.py prioritizes wine paths even when using system wine.

### ISSUE THREAD

**Issue by aTosser** [lutris/lutris#2008] opened 2019-04-08 15:31 UTC
Auto adds location of system wine libs therefore prioritizing those directories over any other library directories.

**Comment by strycore** [comment] 2019-04-10 02:06
yeah, that's by design, do you mean the lutris wine builds? if we don't do that then they won't work. it didn't seem to be an issue before so there's probably something different in your setup. Can you please run a `cat /etc/ld.so.conf.d/*` (or is may be `cat /etc/ld.so.conf`)

**Comment by aTosser** [comment] 2019-04-11 15:16
I will preface this only matters after I have patched with my proposed patch #2009. (this is the only way to get lutris running at all on with proprietary nvidia on my distro.)
I will also note that the only motivation for me using the ldconfig information for loading libs is because I am an edge case. I am a gentoo user using nvidia proprietary, and the primary issue is that gentoo must have mesa and nvidia implemetations of libGL.so.1 installed at the same time. (source based package manager and the mesa headers are required to build against) Note my ldconfig output:

libGL.so.1 (libc6,x86-64) => /usr/lib64/opengl/nvidia/lib/libGL.so.1
libGL.so.1 (libc6,x86-64) => /usr/lib64/libGL.so.1
libGL.so.1 (libc6) => /usr/lib32/opengl/nvidia/lib/libGL.so.1
libGL.so.1 (libc6) => /usr/lib32/libGL.so.1

The libGL.so.1  in /usr/lib32 and /usr/lib64 are the mesa implementations there is no symlink.

The code proposed in #2009 adequately provides the library paths in the correct order to allow applications to find libraries in the order as dictated by the linker. Please note my ld.so.conf

/usr/lib32/opengl/nvidia/lib
/usr/lib64/opengl/nvidia/lib
include ld.so.conf.d/*.conf
/usr/lib32/OpenCL/vendors/nvidia
/usr/lib64/OpenCL/vendors/nvidia
/usr/lib/llvm/8/lib32
/usr/lib/llvm/8/lib64
/usr/lib/llvm/7/lib32
/usr/lib/llvm/7/lib64
/usr/lib/llvm/6/lib32
/usr/lib/llvm/6/lib64
/lib64
/usr/lib64
/usr/local/lib64
/lib32
/usr/lib32
/usr/local/lib32
/lib
/usr/lib
/usr/local/lib
/usr/lib64/rust-1.33.0
/usr/games/lib64
/usr/games/lib32
/usr/games/lib
/usr/lib64/R/lib
/usr/lib64/fltk

(The include line is just gcc related so I did not expand them out.)

The current logic in lutris always applies the wine lib paths to the beginning of LD_LIBRARY_PATH. This is great behavior for the lutris provided wine libs. However when using system wine (on my system) "/usr/lib:/usr/lib64" gets appended to the front and if you notice that is the location for the mesa implementation of libGL.so.1 which sadly breaks everything because my nvidia drivers are being ignored. A simple fix imho, is to not append the winelib directory ONLY when using system wine.

Currently, I am digging through the code for a simple way to implement this idea; however, I admit that my knowledge of the entire code base is only around 20%.

I hope this explains my intentions and properly explains the issues I am having locally.

**Comment by strycore** [comment] 2019-11-04 00:28
I merged code from your branch in the last release, is this still an issue? Going to close this, please reopen it if still an issue (and how I can setup a system that can reproduce it)

**Closed by strycore** 2019-11-04 00:28 UTC
