### ISSUE TITLE
Incorrect parsing with "require-binaries:"? curl shows up as "c or u or r or l" in the client

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1045] opened 2018-08-19 07:59 UTC
>I was curious if it's what I thought it was, and it turns out it is - here they treat every dependency specification as a list of options, and join them with or. The documentation specifies it should be a comma-separated list (or just a list, in YAML notation), and the script only specifies curl, which is parsed as a single string, because YAML is a garbage format like that. So what ends up happening is instead of require-binaries being [['curl']], it becomes ['curl'], which is then looped over to produce the string 'curl', which is then passed to join, and since Python's str.join takes any iterable, 'c or u or r or l' happens.

![](https://i.redd.it/0brxsou69ic11.png)

**Comment by Medath** [comment] 2018-09-03 19:36
Duplicate of #913 which got fixed in cd8cfa2
It is still present on the current release but does not occur on master anymore.

**Closed** 2018-09-03 22:44 UTC
