### ISSUE TITLE
some steam games not showing in lutris 

### ISSUE THREAD

**Issue by p978** [lutris/lutris#4397] opened 2022-07-30 03:32 UTC
when i open lutris it only shows one of my steam games. output of lutris -d:
INFO     2022-07-30 09:18:20,104 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-07-30 09:18:20,312 [libretro.get_libretro_cores:24]:No folder at /home/enderman/.local/share/lutris/runners/retroarch/
DEBUG    2022-07-30 09:18:20,373 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-07-30 09:18:20,555 [startup.check_driver:65]:Running Intel Mesa driver 22.1.3 on Mesa Intel(R) HD Graphics 2000 (SNB GT1) (0x106)
INFO     2022-07-30 09:18:20,558 [startup.check_driver:77]:GPU: 8086:0106 1028:0504 (i915 drivers)
WARNING  2022-07-30 09:18:20,604 [startup.check_vulkan:136]:Vulkan is not available or your system isn't Vulkan capable
Fontconfig error: "/etc/fonts/local.conf", line 1: XML declaration not well-formed
INFO     2022-07-30 09:18:20,698 [startup.update_runtime:213]:Startup complete
DEBUG    2022-07-30 09:18:21,213 [lutriswindow.update_store:437]:Showing 1 games
DEBUG    2022-07-30 09:18:25,306 [base.wipe_game_cache:121]:Deleting games from service-games for steam
DEBUG    2022-07-30 09:18:25,871 [http.get:83]:GET https://lutris.net/api/games/service/steam
DEBUG    2022-07-30 09:18:26,196 [steam.add_installed_games:170]:9 Steam games detected and installed
DEBUG    2022-07-30 09:18:26,196 [steam.add_installed_games:171]:Games found in: /home/enderman/.local/share/Steam/steamapps
DEBUG    2022-07-30 09:18:26,206 [steam.add_installed_games:185]:0 Steam games removed
DEBUG    2022-07-30 09:18:26,208 [steam.add_installed_games:202]:0 Steam games deduplicated
DEBUG    2022-07-30 09:18:26,211 [lutriswindow.update_store:437]:Showing 1 games
INFO     2022-07-30 09:18:31,125 [application.do_shutdown:885]:Shutting down Lutris

**Comment by strycore** [comment] 2023-06-06 04:25
Duplicate of #4166

**Closed by strycore** 2023-06-06 04:25 UTC
Labels: open to community
