### ISSUE TITLE
Gamescope fails to run with mangohud

### ISSUE THREAD

**Issue by Casul51** [lutris/lutris#4042] opened 2022-02-08 21:23 UTC
### Bug description

If use mangohud with gamescope, game will fail to run. It is bug behind mangohud, and mangohud already made fix - `mangoapp` for using it in gamescope (mangohud pre-release 0.6.6, so it isn't in repos yet). Also there is workaround to get it working now.

`MANGOHUD=0 gamescope -- mangohud %command%`

https://github.com/Plagman/gamescope/issues/400#issue-1125182636

### How to Reproduce

1. Enable gamescope
2. Enable mangohud
3. Start game (some games work )
4. Game fails to run

### Expected behavior

Game runs well.

### Log output

```shell
INFO     2022-02-09 00:21:24,111 [startup.init_lutris:162]:Starting Lutris 0.5.10
WARNING  2022-02-09 00:21:24,134 [libretro.get_libretro_cores:48]:No cores found
DEBUG    2022-02-09 00:21:24,140 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-02-09 00:21:24,161 [startup.check_driver:63]:Running AMD Mesa driver 21.3.5 on AMD Radeon RX 6900 XT (SIENNA_CICHLID, DRM 3.44.0, 5.16.4-zen1-1-zen, LLVM 13.0.0) (0x73bf)
INFO     2022-02-09 00:21:24,161 [startup.check_driver:75]:GPU: 1002:73BF 1458:232C (amdgpu drivers)
DEBUG    2022-02-09 00:21:24,191 [http.get:84]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2022-02-09 00:21:24,662 [http.get:84]:GET https://lutris.net/api/runtimes/icons
DEBUG    2022-02-09 00:21:24,888 [http.get:84]:GET https://api.github.com/repos/lutris/dxvk/releases
DEBUG    2022-02-09 00:21:25,182 [http.write_to_file:137]:Writing to /home/casual/.local/share/lutris/runtime/dxvk/dxvk_versions.json
DEBUG    2022-02-09 00:21:25,183 [http.get:84]:GET https://api.github.com/repos/lutris/dxvk-nvapi/releases
DEBUG    2022-02-09 00:21:25,468 [http.write_to_file:137]:Writing to /home/casual/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi_versions.json
DEBUG    2022-02-09 00:21:25,469 [http.get:84]:GET https://api.github.com/repos/lutris/vkd3d/releases
DEBUG    2022-02-09 00:21:25,717 [http.write_to_file:137]:Writing to /home/casual/.local/share/lutris/runtime/vkd3d/vkd3d_versions.json
DEBUG    2022-02-09 00:21:25,718 [http.get:84]:GET https://api.github.com/repos/lutris/d3d_extras/releases
DEBUG    2022-02-09 00:21:25,917 [http.write_to_file:137]:Writing to /home/casual/.local/share/lutris/runtime/d3d_extras/d3d_extras_versions.json
DEBUG    2022-02-09 00:21:25,919 [http.get:84]:GET https://api.github.com/repos/lutris/dgvoodoo2/releases
DEBUG    2022-02-09 00:21:26,277 [http.write_to_file:137]:Writing to /home/casual/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2_versions.json
INFO     2022-02-09 00:21:26,277 [startup.update_runtime:190]:Startup complete
DEBUG    2022-02-09 00:21:26,432 [lutriswindow.update_store:431]:Showing 237 games
DEBUG    2022-02-09 00:21:32,256 [lutriswindow.update_store:431]:Showing 60 games
DEBUG    2022-02-09 00:21:36,803 [lutriswindow.update_store:431]:Showing 32 games
DEBUG    2022-02-09 00:21:51,098 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-02-09 00:21:51,164 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-02-09 00:21:51,167 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-02-09 00:21:51,169 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-02-09 00:21:51,284 [application.show_window:268]:Showing window EditGameConfigDialog50
DEBUG    2022-02-09 00:22:02,198 [game.save:257]:Saving H5_Game.exe (wine) with config ID my-game-installer-1641474826
DEBUG    2022-02-09 00:22:02,198 [config.save:222]:Saving LutrisConfig(level=game, game_config_id=my-game-installer-1641474826, runner=wine) config to /home/casual/.config/lutris/games/my-game-installer-1641474826.yml
DEBUG    2022-02-09 00:22:02,252 [application.on_app_window_destroyed:285]:Removed window EditGameConfigDialog50
INFO     2022-02-09 00:22:03,002 [runner.use_runtime:277]:Runtime disabled by system configuration
ERROR    2022-02-09 00:22:03,113 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2022-02-09 00:22:03,113 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
INFO     2022-02-09 00:22:03,118 [runner.use_runtime:277]:Runtime disabled by system configuration
DEBUG    2022-02-09 00:22:06,473 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-02-09 00:22:06,608 [application.show_window:268]:Showing window EditGameConfigDialog50
DEBUG    2022-02-09 00:22:16,679 [game.save:257]:Saving H5_Game.exe (wine) with config ID my-game-installer-1641474826
DEBUG    2022-02-09 00:22:16,679 [config.save:222]:Saving LutrisConfig(level=game, game_config_id=my-game-installer-1641474826, runner=wine) config to /home/casual/.config/lutris/games/my-game-installer-1641474826.yml
DEBUG    2022-02-09 00:22:16,733 [application.on_app_window_destroyed:285]:Removed window EditGameConfigDialog50
INFO     2022-02-09 00:22:17,593 [runner.use_runtime:277]:Runtime disabled by system configuration
ERROR    2022-02-09 00:22:17,693 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2022-02-09 00:22:17,694 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
INFO     2022-02-09 00:22:17,698 [runner.use_runtime:277]:Runtime disabled by system configuration
WARNING  2022-02-09 00:22:17,707 [runner_interpreter.get_launch_parameters:63]:libstrangle is not available on this system, FPS limiter disabled
INFO     2022-02-09 00:22:17,707 [runner.use_runtime:277]:Runtime disabled by system configuration
DEBUG    2022-02-09 00:22:17,708 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:MANGOHUD="1"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:__GL_SHADER_DISK_CACHE_PATH="/run/media/General_HDD/Games/Fix_me/Wine_Issues/HeroesofMightandMagic V/bin"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:DXVK_HUD="compiler"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:ENABLE_VKBASALT="0"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:RADV_DEBUG="novrsflatshading"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:RADV_FORCE_VRS="2x2"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:RADV_PERFTEST="rt"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:VKD3D_CONFIG="upload_hvv"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:WINE_FULLSCREEN_FSR_STRENGTH="1"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:WINEDEBUG="-all"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:DXVK_LOG_LEVEL="none"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:WINEARCH="win64"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:WINE="/home/casual/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/bin/wine"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/casual/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/lib64/gstreamer-1.0/:/home/casual/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/lib/gstreamer-1.0/"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:WINEPREFIX="/home/casual/Games/WineStuff/testing_prefix"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:WINEESYNC="1"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:WINEFSYNC="1"
DEBUG    2022-02-09 00:22:17,711 [command.start:139]:WINE_FULLSCREEN_FSR="1"
DEBUG    2022-02-09 00:22:17,712 [command.start:139]:DXVK_NVAPIHACK="0"
DEBUG    2022-02-09 00:22:17,712 [command.start:139]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2022-02-09 00:22:17,712 [command.start:139]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2022-02-09 00:22:17,712 [command.start:139]:game_name="H5_Game.exe"
DEBUG    2022-02-09 00:22:17,712 [command.start:139]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/home/casual/.local/lib/python3.10/site-packages:/usr/lib/python3.10/site-packages"
DEBUG    2022-02-09 00:22:17,712 [command.start:139]:LUTRIS_GAME_UUID="bc01c8c6-f06f-4968-be4c-4db661be4146"
Started initial process 1433296 from gamescope -w 2048 -h 1152 -W 2560 -H 1440 -f -- gamemoderun mangohud /home/casual/.local/share/lutris/runners/wine/lutris-fshack-6.21-6-x86_64/bin/wine /run/media/General_HDD/Games/Fix_me/Wine_Issues/HeroesofMightandMagic V/bin/H5_Game.exe
Start monitoring process.
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
[2022-02-09 00:22:17.791] [MANGOHUD] [info] [config.cpp:114] skipping config: '/usr/bin/MangoHud.conf' [ not found ]
[2022-02-09 00:22:17.791] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/casual/.config/MangoHud/gamescope.conf' [ not found ]
[2022-02-09 00:22:17.791] [MANGOHUD] [info] [config.cpp:119] parsing config: '/home/casual/.config/MangoHud/MangoHud.conf'
vulkan: selecting physical device 'AMD RADV SIENNA_CICHLID'
vulkan: physical device supports DRM format modifiers
[2022-02-09 00:22:17.937] [MANGOHUD] [info] [overlay.cpp:678] Uploading is disabled (permit_upload = 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
Monitored process exited.
Initial process has exited (return code: 139)
All processes have quit
Exit with return code 139
DEBUG    2022-02-09 00:22:18,270 [command.on_stop:193]:Process 1433294 has terminated with code 139
DEBUG    2022-02-09 00:22:19,726 [game.beat:590]:Game thread stopped
WARNING  2022-02-09 00:22:19,726 [game.on_game_quit:616]:Game still running (state: running)
INFO     2022-02-09 00:22:19,726 [game.stop:601]:Stopping H5_Game.exe (wine)
DEBUG    2022-02-09 00:22:19,727 [game.stop_game:556]:H5_Game.exe (wine) has run for 2 seconds
WARNING  2022-02-09 00:22:19,727 [game.stop_game:558]:The game has run for a very short time, did it crash?
DEBUG    2022-02-09 00:22:19,736 [game.on_game_quit:634]:H5_Game.exe stopped at Wed, 09 Feb 2022 00:22:19
DEBUG    2022-02-09 00:22:19,736 [game.save:257]:Saving H5_Game.exe (wine) with config ID my-game-installer-1641474826
INFO     2022-02-09 00:22:27,069 [application.do_shutdown:653]:Shutting down Lutris
```

### System Information

```shell
no need
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Casul51** [comment] 2022-02-08 21:23
There is people also encountered it https://github.com/lutris/lutris/issues/4001#issue-1108682353

**Comment by italoghost** [comment] 2022-04-19 22:43
Hi!

Is there any progress on this issue? I can confirm that the bug still persists!

**Comment by strycore** [comment] 2022-04-20 04:42
The workaround with MANGOHUD=0 seems to work fine. I've pushed a fix on the development branch.

**Closed by strycore** 2022-04-20 04:42 UTC
Labels: bug

**Comment by italoghost** [comment] 2022-04-20 11:16
I disabled the MangoHud option and added "mangohud --dlsym" to the ENV. It worked as well!

**Comment by strycore** [comment] 2022-04-20 17:15
I don't even understand how that would work. Putting shell commands in environment variables is certainly something. Not the right thing, but something. As long as it works...

**Comment by boltronics** [comment] 2022-09-08 16:53
I was trying to play Heroes of Might and Magic V under the Wine runner (using System Wine) with gamescope to fix resolution issues (since otherwise the game only works properly in windowed mode), and was having no luck getting mangohud to work using Lutris 0.5.11.

For example, I tried using System options to set MANGOHUD to 0 in the Environment variables section and added `mangohud` as a prefix. I tried added MANGOHUD_DLSYM with a value of 1. I tried removing magohud from the Command prefix section and enabling `FPS counter (MangoHud)` instead, and then re-testing with the previous combinations. Still nothing.

In the end, I reverted everything back to the defaults (deleted all the environment variables I had added, removed the Command prefix, had `FPS counter (MangoHud)` disabled) and instead changed the Wine version to Custom and pointed it to a script containing the following:

```
#!/bin/bash

wine "${@}" &
WINE_PID=${!}
mangoapp &
MANGOAPP_PID=${!}
wait "${WINE_PID}"
kill "${MANGOAPP_PID}"
```

After that, it worked perfectly.

I don't know if I have misunderstood something mentioned above (if there's a way to get it working, it's certainly not intuitive), or if perhaps there has been a regression?
