### ISSUE TITLE
Unable to log into GOG

### ISSUE THREAD

**Issue by aidalgol** [lutris/lutris#3965] opened 2021-12-31 05:38 UTC
### Bug description

Logging into GOG is impossible, as the login window is blank.

### How to Reproduce

1. Run `lutris`
2. Click on the login button on the "GOG" entry in the sidebar.
3. A blank window comes up.

### Expected behavior

I expected to get a login prompt of some form, similar to the Humble Bundle login prompt, which is working for me.

### Log output

```console
2021-12-31 18:33:24,439: Starting Lutris 0.5.9.1
2021-12-31 18:33:24,466: No cores found
2021-12-31 18:33:26,435: Startup complete
INFO     2021-12-31 18:33:26,436 [startup.check_driver:53]:Using NVIDIA drivers 495.44 for x86_64
INFO     2021-12-31 18:33:26,436 [startup.check_driver:57]:GPU: Unknown
INFO     2021-12-31 18:33:26,436 [startup.check_driver:73]:GPU: 10DE:2206 1043:87B0 (nvidia drivers)
DEBUG    2021-12-31 18:33:26,604 [lutriswindow.update_store:451]:Showing 0 games
DEBUG    2021-12-31 18:33:52,813 [base.login:253]:Connecting to GOG
CONSOLE SECURITY ERROR The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
https://static-login.gog-statics.com/js/ddb202c-7939ff0.js:1683:23: CONSOLE WARN Unknown case [object Object]
https://static-login.gog-statics.com/js/ddb202c-7939ff0.js:1683:23: CONSOLE WARN Unknown case [object Object]
CONSOLE SECURITY ERROR The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
CONSOLE SECURITY ERROR The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
https://static-login.gog-statics.com/js/ddb202c-7939ff0.js:1683:23: CONSOLE WARN Unknown case [object Object]
https://static-login.gog-statics.com/js/ddb202c-7939ff0.js:1683:23: CONSOLE WARN Unknown case [object Object]
https://static-login.gog-statics.com/js/ddb202c-7939ff0.js:1683:23: CONSOLE WARN Unknown case [object Object]
```

### System Information

```text
[System]
OS:              NixOS 22.05 quokka
Arch:            x86_64
Kernel:          5.10.90
Desktop:         Not found
Display Server:  tty

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 3950X 16-Core Processor
Physical cores:  16
Logical cores:   32

[Memory]
RAM:             31.4 GB
Swap:            16.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 495.46
OpenGL Core:     4.6.0 NVIDIA 495.46
OpenGL ES:       OpenGL ES 3.2 NVIDIA 495.46
Vulkan:          Supported
```

### Media
![image](https://user-images.githubusercontent.com/2313201/147805476-432ccac9-0c96-42a5-83b4-a604e97b7003.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment] 2021-12-31 09:09
Seems like a dupe of #3757, which @tannisroot closed as a dupe of #3832 though that one involved a crash not a blank window. @3757 does seem like an exact match though.

If so, this is a Wayland issue, and you should try running on X11, or maybe run with the environment variable GDK_BACKEND=x11.

**Comment by aidalgol** [comment] 2021-12-31 09:11
I am running on X11, so I do not think it is the same issue.  I did see #3757 before raising this issue.

**Comment by tannisroot** [comment] 2022-01-23 09:52
You did not copy system info field, you just copied terminal output again, that's needed here to understand the issue.
Please fix that.

**Comment by aidalgol** [comment] 2022-01-23 10:50
Sorry, I don't know how I managed to do that.  I have edited the original comment to fix that.

**Comment by tannisroot** [comment] 2022-02-05 13:23
> Desktop:         Not found
Display Server:  tty
that does not seem right. What sort of DE are you running?
Have you tried using Lutris with something like KDE or Gnome?

**Comment by aidalgol** [comment] 2022-02-05 20:12
That is correct.  I am running on [i3wm](https://i3wm.org/) with xorg started via [sx](https://github.com/Earnestly/sx).  I have not tried running Lutris under KDE or Gnome.

**Comment by tannisroot** [comment] 2022-02-05 21:45
It's possible webkitgtk (which the window is rendered with) does not like this sort of set up.
We don't really support this sort of configuration so closing.

**Closed by tannisroot** 2022-02-05 21:45 UTC
Labels: bug, need more info

**Comment by aidalgol** [comment] 2022-02-05 21:59
Fair enough if this is an unsupported setup, but what about the desktop environment would affect the behaviour of Lutris, so I can at least try troubleshooting it on my own?

**Comment by ia3crt** [comment] 2022-02-27 14:44
Kde and Xfce, same problem. Devs seem to like to do "not my problem, closing up, fuck you". Will try removing and reinstalling. If I found a solution, will post it.

**Comment by emptyflask** [comment] 2022-04-17 15:48
I was running into this bug as well (running NixOS with xmonad). The solution is to set this env var when starting lutris, though I'm not sure why hardware acceleration would be a problem in the first place.

```
WEBKIT_DISABLE_COMPOSITING_MODE=1 lutris
```

**Comment by jessestricker** [comment] 2022-05-01 20:53
Please consider re-opening this issue.

I have the same problem on my system:

```
[System]
OS:              NixOS 22.05 Quokka
Arch:            x86_64
Kernel:          5.17.3
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 2600X Six-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.6 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 510.60.02
OpenGL Core:     4.6.0 NVIDIA 510.60.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.60.02
Vulkan:          Supported

```

**Comment by clementine-of-whitewind** [comment] 2023-06-12 15:15
> I was running into this bug as well (running NixOS with xmonad). The solution is to set this env var when starting lutris, though I'm not sure why hardware acceleration would be a problem in the first place.
> 
> ```
> WEBKIT_DISABLE_COMPOSITING_MODE=1 lutris
> ```
> 
> For reference, here's my system info:
> 
> ```
> [System]
> OS:              NixOS 21.11 porcupine
> Arch:            x86_64
> Kernel:          5.10.109
> Desktop:         xterm
> Display Server:  x11
> 
> [CPU]
> Vendor:          GenuineIntel
> Model:           Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
> Physical cores:  6
> Logical cores:   12
> 
> [Memory]
> RAM:             31.3 GB
> Swap:            8.0 GB
> 
> [Graphics]
> Vendor:          NVIDIA Corporation
> OpenGL Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
> OpenGL Version:  4.6.0 NVIDIA 510.60.02
> OpenGL Core:     4.6.0 NVIDIA 510.60.02
> OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.60.02
> Vulkan:          Supported
> ```

thanks dawg that fixed it

**Comment by JanSimek** [comment] 2023-10-25 06:46
This bug is still present in Lutris 0.5.13. Thank you for a workaround @emptyflask 

```
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.5.7-arch1-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 1800X Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             62.8 GB
Swap:            4.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.113.01
OpenGL Core:     4.6.0 NVIDIA 535.113.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.113.01
Vulkan Version:  1.3.264
Vulkan Drivers:  NVIDIA GeForce GTX 1060 6GB (1.3.242)
```

**Comment by RaulDelary** [comment] 2023-11-06 19:11
> I was running into this bug as well (running NixOS with xmonad). The solution is to set this env var when starting lutris, though I'm not sure why hardware acceleration would be a problem in the first place.
> 
> ```
> WEBKIT_DISABLE_COMPOSITING_MODE=1 lutris
> ```
> 
> For reference, here's my system info:
> 
> ```
> [System]
> OS:              NixOS 21.11 porcupine
> Arch:            x86_64
> Kernel:          5.10.109
> Desktop:         xterm
> Display Server:  x11
> 
> [CPU]
> Vendor:          GenuineIntel
> Model:           Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
> Physical cores:  6
> Logical cores:   12
> 
> [Memory]
> RAM:             31.3 GB
> Swap:            8.0 GB
> 
> [Graphics]
> Vendor:          NVIDIA Corporation
> OpenGL Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
> OpenGL Version:  4.6.0 NVIDIA 510.60.02
> OpenGL Core:     4.6.0 NVIDIA 510.60.02
> OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.60.02
> Vulkan:          Supported
> ```

Hey man, thanks, this solve my problem too. Can i ask how you figured it out the problem and the solution?

**Comment by emptyflask** [comment] 2023-11-06 19:22
> Hey man, thanks, this solve my problem too. Can i ask how you figured it out the problem and the solution?

It's been a while since I wrote that comment, but I recall finding some other program that had a similar problem and was resolved by setting the env var. :shrug:
