### ISSUE TITLE
disable desktop effects doesn't work

### ISSUE THREAD

**Issue by R3D9477** [lutris/lutris#2596] opened 2020-01-12 18:40 UTC
Hello. I configured launcher with option "disable desktop effects", but I still can see enabled compositing effects in my KDE when game is running in windowed mode.
Lutris 0.5.4
KDE Neon 5.17

**Comment by r3d9u11** [comment] 2020-01-14 15:29
as a workaround I'm calling commands to start/stop compositing manually from my [launcher](https://forums.lutris.net/t/how-do-avoid-desktop-chaos-after-launching-game-in-fullscreen-mode/8087).

**Comment by Nano-Ocelot** [comment] 2020-02-12 21:42
Desktop effects aren't getting disabled for me as well.
Lutris 0.5.4
Plasma 5.17.5
openSUSE Tumbleweed

**Comment by strycore** [comment] 2022-02-03 19:12
Closing because Lutris shouldn't be messing with desktop effects and this is a feature that should be removed in a future version.

**Closed by strycore** 2022-02-03 19:12 UTC

**Comment by Lalarian** [comment] 2022-04-10 23:21
I got the same problem, and Wine is utterly useless with the extreme lag caused by the desktop compositor. Otherwise the compositor ist pretty useful ourside of Wine-applictions, because for example I can zoom in the desktop anytime, anywhere. It's not just a matter of fanciness. It's about productivity and usability. And I am pretty sure it's completely against the concept of Lutris to intentionally NOT make things easily available for users. At least that's how I got to know Lutris, and what I hope will remain it's primary directive.

**Comment by strycore** [comment] 2022-04-12 01:26
@Lalarian your compositor shouldn't have any noticeable effect on your games. A friendlier approach that doesn't require Lutris messing with your DE would be to use gamescope which isolates the game from your desktop entirely. 
It's a bit new so it's not available on every distro but this is what we're aim to support in the future.
