### ISSUE TITLE
UI: Wrong game selected after editing game settings

### ISSUE THREAD

**Issue by MarJMue** [lutris/lutris#3477] opened 2021-03-19 20:46 UTC
After editing the settings of a game and clicking 'save', the bar in the bottom switches to the last game in the list. 
On clicking 'cancel' it shows the expected behavior of staying on the selected game.

First time using the new UI, so i can't say if it's a regression or not.

Distro: EndeavourOS / Arch
Version: lutris-git as of 03-18-21

**Comment by briaguya-ai** [comment] 2021-03-22 01:14
i was able to reproduce this issue on 5.8.3 on debian sid

suggested tags:
improvement
user experience
configure menu

# user story
As a user, when I save updated settings for a game I have installed, I would like the game to remain selected.

## technical considerations
seems like the technical solution for this is non-obvious. the game list gets refreshed on save, this is important for stuff like filtered lists and icons updating when game info is modified.

when saving
https://github.com/lutris/lutris/blob/216604b7af802945d1feade9c847de9dd9348902/lutris/game.py#L285

looks like that gets picked up here
https://github.com/lutris/lutris/blob/b4234878f0a4df75fdb1e3a6ab65d231fa952ef3/lutris/gui/lutriswindow.py#L126

then
https://github.com/lutris/lutris/blob/b4234878f0a4df75fdb1e3a6ab65d231fa952ef3/lutris/gui/lutriswindow.py#L790

which brings us here
https://github.com/lutris/lutris/blob/b4234878f0a4df75fdb1e3a6ab65d231fa952ef3/lutris/gui/lutriswindow.py#L451

so this possibly involves finding a way to update the game list without clearing the store, or just manually setting the selected game after rebuilding it

## use cases where this becomes a pain point
keyboard nav, after clicking save pressing an arrow key brings you to to the top of the list/grid

**Comment by AppleSeed2010** [comment] 2021-04-08 23:09
Hi,

The same behavior appear too when simply quitting a game, adding it to favorites, killing it (Kill all Wine processes) and more...
In my case, there is even an UI freeze for ~4 seconds before switching to the last application 😕
(For me, this bug has come with the UI redesign)

**Comment by AppleSeed2010** [comment] 2021-07-24 11:55
Hello,
With the lutris version 0.5.9, this bug and the 4 secconds delay are no more for me.
Best regards,

**Comment by AppleSeed2010** [comment] 2021-07-24 16:02
Additional information, it seems the problem appear only while in list view.
In banner view, this bug disappear.

**Comment by strycore** [comment] 2022-02-18 18:27
this has been fixed in a recent patch

**Closed by strycore** 2022-02-18 18:27 UTC
