### ISSUE TITLE
Lutris ignores Gnomes night light

### ISSUE THREAD

**Issue by Lucki** [lutris/lutris#587] opened 2017-06-12 14:32 UTC
Lutris resets Gnome3's night light (also known as redshift - more red on screen at night) on game start to normal red and blue, but doesn't deactivate it or activate it at game stop.
To get it back you have to disable night light and turn it back on.

![https://www.gnome.org/news/2017/03/gnome-3-24-released/attachment/night-light/](https://www.gnome.org/wp-content/uploads/2017/03/night-light.png)

**Comment by AccountOneOff** [comment] 2018-05-09 08:16
Related to #767?

**Comment by AccountOneOff** [comment] 2019-04-09 05:26
This is still an issue. Lutris doesn't mess with the night light until game exit. It gets reset even with the XVidMode option enabled.

**Comment by tannisroot** [comment] 2019-11-15 14:41
I can't reproduce this.
Can somebody who experiences this share your game settings?

**Comment by xordspar0** [comment] 2020-04-21 13:33
So the problem is that Lutris disables night light when the game starts, but then it leaves it never enables it again? Maybe "Lutris ignores Gnomes night light" is not accurate then. It's more like Lutris is aware of night light, but it doesn't clean up after itself.

Is this an X11-only feature? Lutris never changes my night light settings on Gnome/Wayland. I expect that this would require a Dbus API, since only the compositor can change the color settings on Wayland.

**Comment by xordspar0** [comment] 2020-04-21 13:36
Is this fixed by https://github.com/lutris/lutris/issues/1010?

**Comment by strycore** [comment] 2021-01-23 07:04
De-prioritizing since I don't know how to control night light. I issue is open to contributions.

**Comment by tannisroot** [comment] 2021-11-17 00:46
The issue was related to the wine runner and how it handled X11, closing since it's not an issue anymore afaik.

**Closed by tannisroot** 2021-11-17 00:46 UTC
Labels: PR friendly

**Comment by Foxomat** [comment] 2023-05-23 20:58
still having this issue

**Comment by strycore** [comment] 2023-05-24 01:41
I'm encouraging anyone having this issue to use Gamescope,
