### ISSUE TITLE
Translations in Lutris 0.5.0 is lacking.

### ISSUE THREAD

**Issue by pyroxar** [lutris/lutris#1489] opened 2019-01-04 00:14 UTC
Translations in Lutris 0.5.0 is lacking.
*.pot file in 'po' directory has been modified 6 years ago, why nothing changed in translations?

Would Lutris want to support multi languages?

![obraz](https://user-images.githubusercontent.com/23406555/50668234-13172e80-0fbe-11e9-957d-2ab63129192c.png)

**Comment by tannisroot** [comment] 2019-01-04 01:03
Duplicate of https://github.com/lutris/lutris/issues/728.
Proper internalization is in plans.

**Closed by tannisroot** 2019-01-04 01:03 UTC
