### ISSUE TITLE
Gnome branch 45 EOL

### ISSUE THREAD

**Issue by KrisZane** [lutris/lutris#5700] opened 2024-11-04 10:03 UTC
### Bug description

Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   net.lutris.Lutris

Info: runtime org.gnome.Platform.Compat.i386 branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this extension:
   net.lutris.Lutris

### How to Reproduce

Info message when running an update

### Expected behavior

No info message with outdated platforms

### Log output

```shell
Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   net.lutris.Lutris

Info: runtime org.gnome.Platform.Compat.i386 branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this extension:
   net.lutris.Lutris
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: NO
Gamemode: YES
Steam: NO
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.11.5-200.fc40.x86_64
Desktop: GNOME
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 4500U with Radeon Graphics
Physical cores: 6
Logical cores: 6
[Memory]
RAM: 15.0 GB
Swap: 8.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.59, 6.11.5-200.fc40.x86_64)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.2.5 (git-3b9fcb7e4d)
OpenGL Core: 4.6 (Core Profile) Mesa 24.2.5 (git-3b9fcb7e4d)
OpenGL ES: OpenGL ES 3.2 Mesa 24.2.5 (git-3b9fcb7e4d)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon Graphics (RADV RENOIR) (1.3.289)
```

**Comment by danieljohnson2** [comment] 2024-11-04 10:23
I wish that warning told people to check the issue tracker!

This is a dupe of #5690.

**Closed by danieljohnson2** 2024-11-04 10:23 UTC
