### ISSUE TITLE
Completely broken on Fedora 32

### ISSUE THREAD

**Issue by Crazily** [lutris/lutris#2688] opened 2020-03-28 02:18 UTC
**Describe the bug**

The program displays the first time dialogue only and there is no other graphical display. Rendering the program useless.

This repository isn't for reporting game bugs or game related issues. Feel free to contact us on [Discord](https://discordapp.com/invite/Pnt5CuY), the [Forums](https://forums.lutris.net), or the IRC channel #lutris on freenode.org for that. We'll try and help as best we can.

**Expected behavior**

The program works.

**Current behavior**

It doesn't work.

**Steps to reproduce**
Install on Fedora 32.
Open.

**Lutris debugging output**

The terminal output of `lutris -d`.

It outputs nothing atall.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

{
  "comment": "",
  "system": {
    "gpus": [
      {
        "DRIVER": "amdgpu",
        "PCI_ID": "1002:699F",
        "PCI_SUBSYS_ID": "1043:0513",
        "PCI_CLASS": "30000",
        "PCI_SLOT_NAME": "0000:07:00.0",
        "MODALIAS": "pci:v00001002d0000699Fsv00001043sd00000513bc03sc00i00"
      }
    ],
    "env": {
      "IMSETTINGS_INTEGRATE_DESKTOP": "yes",
      "SHELL": "/bin/bash",
      "SESSION_MANAGER": "local/unix:@/tmp/.ICE-unix/1259,unix/unix:/tmp/.ICE-unix/1259",
      "XDG_SESSION_PATH": "/org/freedesktop/DisplayManager/Session0",
      "HISTCONTROL": "ignoredups",
      "GNOME_DESKTOP_SESSION_ID": "this-is-deprecated",
      "HISTSIZE": "1000",
      "HOSTNAME": "localhost.localdomain",
      "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh",
      "CINNAMON_VERSION": "4.4.8",
      "XMODIFIERS": "@im=none",
      "DESKTOP_SESSION": "cinnamon",
      "SSH_AGENT_PID": "1436",
      "XDG_SEAT": "seat0",
      "PWD": "/home/william",
      "XDG_SESSION_DESKTOP": "cinnamon",
      "LOGNAME": "william",
      "XDG_SESSION_TYPE": "x11",
      "XAUTHORITY": "/run/lightdm/william/xauthority",
      "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS": "0",
      "XDG_GREETER_DATA_DIR": "/var/lib/lightdm-data/william",
      "GJS_DEBUG_TOPICS": "JS ERROR;JS LOG",
      "HOME": "/home/william",
      "LANG": "en_US.UTF-8",
      "XDG_CURRENT_DESKTOP": "X-Cinnamon",
      "XDG_SEAT_PATH": "/org/freedesktop/DisplayManager/Seat0",
      "IMSETTINGS_MODULE": "none",
      "STEAM_FRAME_FORCE_CLOSE": "1",
      "GJS_DEBUG_OUTPUT": "stderr",
      "XDG_SESSION_CLASS": "user",
      "TERM": "dumb",
      "GTK_OVERLAY_SCROLLING": "0",
      "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
      "USER": "william",
      "DISPLAY": ":0",
      "SHLVL": "0",
      "QT_IM_MODULE": "xim",
      "XDG_VTNR": "1",
      "XDG_SESSION_ID": "2",
      "XDG_RUNTIME_DIR": "/run/user/1000",
      "PATH": "/home/william/.local/bin:/home/william/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin",
      "GDMSESSION": "cinnamon",
      "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
      "MAIL": "/var/spool/mail/william",
      "GIO_LAUNCHED_DESKTOP_FILE_PID": "14926",
      "GIO_LAUNCHED_DESKTOP_FILE": "/usr/share/applications/net.lutris.Lutris.desktop"
    },
    "missing_libs": {
      "OPENGL": [
        [],
        []
      ],
      "VULKAN": [
        [],
        []
      ],
      "WINE": [
        [],
        []
      ],
      "GAMEMODE": [
        [],
        []
      ],
      "RADEON": [
        [],
        []
      ]
    },
    "cpus": [
      {
        "processor": "0",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "1",
        "model name": "AMD Ryzen 5 1500X Quad-Core Processor",
        "stepping": "1",
        "microcode": "0x8001138",
        "cpu MHz": "3231.741",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "0",
        "cpu cores": "4",
        "apicid": "0",
        "initial apicid": "0",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6985.97",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate eff_freq_ro [13] [14]"
      },
      {
        "processor": "1",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "1",
        "model name": "AMD Ryzen 5 1500X Quad-Core Processor",
        "stepping": "1",
        "microcode": "0x8001138",
        "cpu MHz": "2969.883",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "1",
        "cpu cores": "4",
        "apicid": "2",
        "initial apicid": "2",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6985.97",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate eff_freq_ro [13] [14]"
      },
      {
        "processor": "2",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "1",
        "model name": "AMD Ryzen 5 1500X Quad-Core Processor",
        "stepping": "1",
        "microcode": "0x8001138",
        "cpu MHz": "3241.156",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "4",
        "cpu cores": "4",
        "apicid": "8",
        "initial apicid": "8",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6985.97",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate eff_freq_ro [13] [14]"
      },
      {
        "processor": "3",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "1",
        "model name": "AMD Ryzen 5 1500X Quad-Core Processor",
        "stepping": "1",
        "microcode": "0x8001138",
        "cpu MHz": "2985.131",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "5",
        "cpu cores": "4",
        "apicid": "10",
        "initial apicid": "10",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6985.97",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate eff_freq_ro [13] [14]"
      },
      {
        "processor": "4",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "1",
        "model name": "AMD Ryzen 5 1500X Quad-Core Processor",
        "stepping": "1",
        "microcode": "0x8001138",
        "cpu MHz": "3251.449",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "0",
        "cpu cores": "4",
        "apicid": "1",
        "initial apicid": "1",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6985.97",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate eff_freq_ro [13] [14]"
      },
      {
        "processor": "5",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "1",
        "model name": "AMD Ryzen 5 1500X Quad-Core Processor",
        "stepping": "1",
        "microcode": "0x8001138",
        "cpu MHz": "3141.703",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "1",
        "cpu cores": "4",
        "apicid": "3",
        "initial apicid": "3",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6985.97",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate eff_freq_ro [13] [14]"
      },
      {
        "processor": "6",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "1",
        "model name": "AMD Ryzen 5 1500X Quad-Core Processor",
        "stepping": "1",
        "microcode": "0x8001138",
        "cpu MHz": "3166.381",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "4",
        "cpu cores": "4",
        "apicid": "9",
        "initial apicid": "9",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6985.97",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate eff_freq_ro [13] [14]"
      },
      {
        "processor": "7",
        "vendor_id": "AuthenticAMD",
        "cpu family": "23",
        "model": "1",
        "model name": "AMD Ryzen 5 1500X Quad-Core Processor",
        "stepping": "1",
        "microcode": "0x8001138",
        "cpu MHz": "2952.023",
        "cache size": "512 KB",
        "physical id": "0",
        "siblings": "8",
        "core id": "5",
        "cpu cores": "4",
        "apicid": "11",
        "initial apicid": "11",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "13",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca",
        "bugs": "sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass",
        "bogomips": "6985.97",
        "TLB size": "2560 4K pages",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "43 bits physical, 48 bits virtual",
        "power management": "ts ttp tm hwpstate eff_freq_ro [13] [14]"
      }
    ],
    "drives": [
      {
        "name": "sda",
        "fstype": null,
        "fsver": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null
      },
      {
        "name": "sdb",
        "fstype": null,
        "fsver": null,
        "label": null,
        "uuid": null,
        "fsavail": null,
        "fsuse%": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sdb1",
            "fstype": null,
            "fsver": null,
            "label": null,
            "uuid": null,
            "fsavail": null,
            "fsuse%": null,
            "mountpoint": null
          },
          {
            "name": "sdb2",
            "fstype": "xfs",
            "fsver": null,
            "label": null,
            "uuid": "9fa125e7-99a4-4fad-bbd9-3c09bbbab86d",
            "fsavail": "194.7G",
            "fsuse%": "16%",
            "mountpoint": "/"
          }
        ]
      }
    ],
    "ram": {
      "mem": {
        "total": "12271756",
        "used": "3336528",
        "free": "1097488",
        "shared": "262888",
        "buff/cache": "7837740",
        "available": "8353696"
      },
      "swap": {
        "total": "0",
        "used": "0",
        "free": "0"
      }
    },
    "dist": [
      "Fedora",
      "32",
      ""
    ],
    "glxinfo": {
      "opengl_core_profile_shading_language_version": "4.60",
      "direct_rendering": "Yes",
      "screen": "0",
      "opengl_es_profile_version": "OpenGL ES 3.2 Mesa 20.0.2",
      "opengl_es_profile_shading_language_version": "OpenGL ES GLSL ES 3.20",
      "opengl_vendor": "X.Org",
      "opengl_core_profile_context_flags": "(none)",
      "name_of_display": ":0",
      "display": ":0",
      "opengl_renderer": "Radeon 550 Series (POLARIS12, DRM 3.36.0, 5.6.0-0.rc7.git0.2.fc32.x86_64, LLVM 10.0.0)",
      "opengl_profile_mask": "compatibility profile",
      "opengl_core_profile_profile_mask": "core profile",
      "opengl_version": "4.6 (Compatibility Profile) Mesa 20.0.2",
      "opengl_shading_language_version": "4.60",
      "opengl_context_flags": "(none)",
      "opengl_core_profile_version": "4.6 (Core Profile) Mesa 20.0.2"
    }
  }
}

**Screenshots**

**Comment by joshontech** [comment] 2020-03-28 02:24
I can confirm this issue on fedora 32. I am using an Nvidia graphics card and same thing is happening. The upgrade from fedora 31 kept lutris working but a fresh install of fedora 32 and than installing lutris renders it useless.

**Comment by strycore** [comment] 2020-03-28 17:27
Duplicate of whatever that gtk bug is.
Fixed in master.

**Closed by strycore** 2020-03-28 17:27 UTC
