### ISSUE TITLE
Installed duplicate game overrides previous entry

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1595] opened 2019-01-14 07:06 UTC
Already had Cemu installed with it's own library entry and when I went to install another version it got replaced by the newer one instead of making a duplicate entry like previous versions of Lutris did.

Removed duplicate but the original doesn't get added back.

**Comment by strycore** [comment] 2019-01-15 10:56
![screenshot from 2019-01-15 02-55-42](https://user-images.githubusercontent.com/280336/51176180-21dccb80-1871-11e9-8292-9ea04216a028.png)

can't reproduce

**Comment by AccountOneOff** [comment] 2019-01-15 23:39
One entry shown:

![screenshot from 2019-01-15 15-19-00](https://user-images.githubusercontent.com/15083452/51216683-12459d00-18da-11e9-9312-41010a566c5c.png)

This is the third install:

![screenshot from 2019-01-15 15-19-07](https://user-images.githubusercontent.com/15083452/51216717-330df280-18da-11e9-9f75-753602953c3a.png)

You can see I have multiple installs:

![screenshot from 2019-01-15 15-22-38](https://user-images.githubusercontent.com/15083452/51216693-1c679b80-18da-11e9-8273-fbbe1dd4c70b.png)

Fourth install (this time it didn't change the prefix folder):

![screenshot from 2019-01-15 15-23-11](https://user-images.githubusercontent.com/15083452/51216765-5f297380-18da-11e9-99bc-90bf936b4e6d.png)

![screenshot from 2019-01-15 15-25-42](https://user-images.githubusercontent.com/15083452/51216758-5a64bf80-18da-11e9-83ce-292123dff385.png)

Try to browse files:

```
Traceback (most recent call last):
  File "/home/cxf/.lutris/lutris/game_actions.py", line 232, in on_browse_files
    path = self.game.get_browse_dir()
  File "/home/cxf/.lutris/lutris/game.py", line 125, in get_browse_dir
    return self.runner.browse_dir
  File "/home/cxf/.lutris/lutris/runners/runner.py", line 93, in browse_dir
    path = os.path.join(self.game_path, path)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

When I removed it it showed cemu464646 and removed that. Now there's no entry in my library.

![screenshot from 2019-01-15 15-26-26](https://user-images.githubusercontent.com/15083452/51216834-9730b680-18da-11e9-84fe-19a697c90503.png)

**Comment by AccountOneOff** [comment] 2019-01-16 01:21
https://www.youtube.com/watch?v=fbu6kOMNc-A

**Comment by strycore** [comment] 2019-01-16 03:41
i didn't try with installing the game from the website

**Comment by AccountOneOff** [comment] 2019-01-16 03:48
It also happens through the terminal. `./bin/lutris -d cemu`

Could it be a Wine runner problem? I've only tried installing Cemu.

**Comment by strycore** [comment] 2019-01-16 03:58
Can you reproduce it with the "Install another version" button? I used that, I had Fez for Steam installed and installed 2 versions of Fez from GOG alongside with no issue.

**Comment by AccountOneOff** [comment] 2019-01-16 04:11
Yes, I was using that button in the video I posted.

**Comment by strycore** [comment] 2019-01-17 07:13
I couldn't reproduce because as long as you install a version for a *different* runner than the first version installed, you can install as many version as you want.
I made the behavior consistent and now the install process *always* creates a new game, to avoid overwriting a previous config.

**Comment by strycore** [comment] 2019-01-22 16:21
Now fixed for good

**Closed by strycore** 2019-01-22 16:21 UTC
