### ISSUE TITLE
Lutris won't start

### ISSUE THREAD

**Issue by WakanaYuki** [lutris/lutris#4316] opened 2022-06-11 20:51 UTC
I installed lutris on manjaro through
`sudo pacman -S lutris`

but when I try to start lutris I get:
```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
ModuleNotFoundError: No module named 'lutris'
```
I have already tried reinstalling it multiple times. I have also tried the AUR git package.

Edit:
Python version:
3.10.4

Also tried python version:
3.8.13

Manjaro verion:
21.2.6

Update:
So I have now tried running it from the git repo with `./bin/lutris -d`. That results in this error:
```
Traceback (most recent call last):
  File "/home/yuki/Downloads/lutris/./bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/home/yuki/Downloads/lutris/lutris/gui/application.py", line 28, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by WakanaYuki** [comment] 2022-06-11 21:23
Another update:
I somehow got it working by typing in: `python ./bin/lutris -d` 
I have no idea how it works now. Is there any way to resolve this issue anyways, because my pacman lutris installation still broken :/

**Comment by Username404-59** [comment] 2022-06-20 17:47
I have this issue on openSUSE Tumbleweed too, and it only happens when running lutris with python 3.9 or higher

**Comment by Username404-59** [comment] 2022-06-21 05:06
Lutris started to work again after an update, so I don't think this issue is caused by lutris

**Comment by wjcsz** [comment] 2022-07-12 15:11
I still have this problem.

**Comment by wjcsz** [comment] 2022-07-12 15:14
I solved this by reinstalling `python-gobject`

**Comment by dannkunt** [comment] 2022-08-07 20:44
+1

**Comment by SandiCat** [comment] 2023-02-27 16:51
It didn't work for me (also on Manjaro) because my python version was being provided by [`asdf`](https://asdf-vm.com/) via the global `.tool-versions`, rather than the python from pacman (`/usr/bin/python`). You can check that this is the case by running `which python`, which will display `/home/sandi/.asdf/shims/python` if you're using `asdf`.

You can fix it by putting the following in your `~/.tool-versions`:
```
python system
```
Then run:
```
$ asdf install
$ asdf reshim
```
`which python` will still point to `/home/sandi/.asdf/shims/python` but it is in fact ultimately running `/usr/bin/python`.

**Comment by regymm** [comment] 2023-05-17 13:58
Same here on Archlinux, solved by upgrading the system. Python was on 3.10, but newly installed lutris is already using 3.11 packages. `find /usr | grep site-packages/lutris` for diagnosis.

**Comment by maplepy** [comment] 2023-05-18 20:48
`

> find /usr | grep site-packages/lutris

```/usr/lib/python3.11/site-packages/lutris/gui/config/base_config_box.py
/usr/lib/python3.11/site-packages/lutris/gui/config/add_game.py
/usr/lib/python3.11/site-packages/lutris/gui/config/preferences_box.py
/usr/lib/python3.11/site-packages/lutris/gui/config/sysinfo_box.py
/usr/lib/python3.11/site-packages/lutris/gui/config/common.py
/usr/lib/python3.11/site-packages/lutris/gui/config/runner_box.py
/usr/lib/python3.11/site-packages/lutris/gui/installer
/usr/lib/python3.11/site-packages/lutris/gui/installer/__init__.py
/usr/lib/python3.11/site-packages/lutris/gui/installer/files_box.py
/usr/lib/python3.11/site-packages/lutris/gui/installer/file_box.py
/usr/lib/python3.11/site-packages/lutris/gui/installer/script_box.py
/usr/lib/python3.11/site-packages/lutris/gui/installer/widgets.py
/usr/lib/python3.11/site-packages/lutris/gui/installer/script_picker.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets
/usr/lib/python3.11/site-packages/lutris/gui/widgets/log_text_view.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/status_icon.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/cellrenderers.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/__init__.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/game_bar.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/window.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/notifications.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/download_progress_box.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/contextual_menu.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/gi_composites.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/searchable_combobox.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/utils.py
/usr/lib/python3.11/site-packages/lutris/gui/widgets/common.py
/usr/lib/python3.11/site-packages/lutris/gui/installerwindow.py
/usr/lib/python3.11/site-packages/lutris/runner_interpreter.py
/usr/lib/python3.11/site-packages/lutris/game.py
/usr/lib/python3.11/site-packages/lutris/exceptions.py```

That still does not solve the issue

**Comment by regymm** [comment] 2023-05-19 01:21
The results show that lutris should be run using python3.11. You can run python and check the version.

**Comment by danieljohnson2** [comment] 2023-05-19 21:28
Lutris should work on anything back to Python 3.7, but things go wrong if you mix packages from different versions of Python. If it's 3.11 it needs to be all 3.11.

**Comment by strycore** [comment] 2023-06-06 02:50
This should be fixed now. If not, reach out to your distro's package maintainer.

**Closed by strycore** 2023-06-06 02:50 UTC
Labels: open to community
