### ISSUE TITLE
GOG integration

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#154] opened 2015-01-17 01:05 UTC
https://github.com/Sude-/lgogdownloader

Once authenticated, can facilitate downloading GOG titles.

**Comment by RobLoach** [comment] 2016-07-08 22:00
https://github.com/eddie3/gogrepo

```
./gogrepo login
./gogrepo update
./gogrepo download -d bio_menace
```

**Comment by strycore** [comment] 2016-07-08 22:59
For info, we're not going to use any of those projects directly but yes, I'm going to read the source code of all of them and we will have our own implementation that will most likely borrow some code from those projects. The gogrepo one will be the most useful since it's also written in Python.

If possible, I'll try to make something reusable that can be used by other projects (kinda like humblebundle-python).

**Comment by RobLoach** [comment] 2016-07-08 23:35
Since it's Python, could probably take some of its API, or re-factor some of it to be able to be used directly through Lutris.

**Comment by strycore** [comment] 2016-07-09 00:16
Yes, that's most likely what will happen, we want to migrate from a tool to an API so there's a bunch of things that can be removed, the rest might stay the same.

**Comment by RobLoach** [comment] 2016-08-04 20:49
Going to close this until something happens.

**Comment by strycore** [comment] 2016-08-04 21:08
Reopening, we're going to use that issue to keep track of the GOG integration.

**Comment by RobLoach** [comment] 2016-08-04 22:05
sexy times.

**Comment by sixsixfive** [comment] 2016-09-04 20:38
may it be useful:

https://github.com/eddie3/gogrepo

**Comment by Yepoleb** [comment] 2016-12-04 05:51
I've hacked together a quick wrapper around the GOG APIs. It seems to be the first one to use token auth instead of cookies or the deprecated downloader API. Support for delta updates for Windows games should be coming soon, but you probably want to start with Linux games only anyway. Documentation is also being worked on. You can find the project here: https://github.com/Yepoleb/pygogapi

If you're interested in the Linux installer format, I've looked into that as well. A short summary is on my blog: http://yepoleb.github.io/blog/2016/10/09/how-the-gog-linux-installers-work/

I'm open to helping with research or implementation, if you need it.

**Comment by strycore** [comment] 2016-12-04 20:15
@Yepoleb that's really cool! 
Is there a reason to go with auth tokens instead of cookies? Most of the GOG tools I've seen are CLI only but Lutris is a GUI and I like that we can show an official login screen from the GOG website (this is already implemented in the "next" branch)
But at the end of the day, I'm really looking for what's more maintainable and future proof. 

Also, the GOG Linux installer post is very good but keep in mind that we're targeting the whole GOG library, not just the Linux supported games. Most games can be extracted with innoextract and I've recently (2 days ago) discovered that innoextract has a --gog option to support more recent installers. Given all that, I think we're in a good place to have a very solid GOG implementation :D

**Comment by Yepoleb** [comment] 2016-12-04 20:57
Some Galaxy methods don't work with cookies and require an auth token. I haven't noticed this the other way around. Showing the official login page is the only way to reliably implement the authorization process, because CAPTCHAs don't work with a CLI client. The browser callback was specifically made for using an internal browser.

Innoextract is actually the second project I'm working on at the moment. In particular on a way to to write the registry entries, shortcuts and other metadata to a file. I pushed my first attempts just an hour ago to https://github.com/Yepoleb/innoextract/tree/script. The format is the same as used by the Inno Setup Compiler itself. I got the idea from innounp, a similar project to innoextract, that already supports writing these files.

I'm very confident as well about the future of GOG support, as long as there is the motivation to actually implement it. Being the first native GUI client for Linux would be a huge step forward for Lutris.

**Comment by strycore** [comment] 2017-03-02 04:03
@Yepoleb that documentation will be very helpful, thanks!

With Lutris 0.4.5 almost ready, I may be able to put some work in the GOG integration soon :D

**Comment by mdeguzis** [comment] 2017-05-14 16:29
Any update on gog integration?

**Comment by strycore** [comment] 2017-05-14 17:22
@mdeguzis I've been working a lot on the 0.4.x branch lately but with the 0.4.10 release, it should be pretty solid, I should resume the work on GOG and the 0.5.x branch after that.

**Comment by chadberg** [comment] 2017-11-30 15:31
I'm going to ask for a followup here. How's it going with GOG and the 0.5.x branch? You might consider the work done in https://github.com/yancharkin/games_nebula and look at integrating it with Lutris.

**Comment by strycore** [comment] 2017-11-30 17:52
@chadberg games nebula relies on lgogdownloader, which we do not and will not. We have pretty much all necessary API interaction implemented now, the rest is mostly UI stuff and hooking it up together with Lutris. As far as the GOG specific stuff is concerned, the development is done (and the login system is *much* better than lgogdownloader's)

**Comment by CartoonFan** [comment] 2017-12-15 04:25
Great job on the GOG integration! I can now login, however when I click "Get games" in the import section, I see a list of games in the terminal but it seems like nothing is added to the library. Is this normal? Thanks again!

**Comment by strycore** [comment] 2017-12-15 04:58
@CartoonFan you're using a development branch, what did you expect? YES, this is normal, it is caused by the fact that code does not write itself and that's pretty much where we left off development. Now, there are 2 options to change that: wait or send patches :D

**Comment by CartoonFan** [comment] 2017-12-15 05:07
Oh, OK. Just wondering. I don't have that much coding expertise, so yeah... :D

**Comment by NicoVIII** [comment] 2018-08-01 11:33
Sorry, I don't want to annoy you, but I wondered how far the GOG integration is today.

I looked at the development version and found the possibility to connect to GOG. But I couldn't figure out if installing and downloading files from GOG automatically through an installer script is possible or not.

If it is not implemented for now, I would like to try and help to implement that specific possibility.

**Comment by strycore** [comment] 2018-08-01 18:02
@NicoVIII  good to hear, help is always welcome. 

What is needed now is to plug the GOG api and Lutris itself together. Check the gogwindow.py file on the next branch, you'll see we have everything needed to download GOG games. 

Now we have to find a way to plug this in the install process itself. It may require some changes on the website as well.

**Comment by NicoVIII** [comment] 2018-08-02 13:12
@strycore Alright, thank you!
I looked into some code and will try to implement something useful. If I'm able to create something, that works, I will create a pull request.

**Comment by strycore** [comment] 2018-08-02 17:25
@NicoVIII  I would strongly advise against doing so. This needs to be designed and conceptualized, if you just go and code stuff without prior confirmation, you might end up throwing away a lot of your work.

You can start by exposing your development plans here but if you want to discuss this in more detail over Discord or IRC, I'm all open for it (challenge would be to find an open time slot)

**Comment by NicoVIII** [comment] 2018-08-03 04:17
@strycore Productivitywise you are totally right. On the other hand I'm not very familiar with the code of the project, so I wouli guess, that I can improve the quality of my code by expermenting.

I think, I will try to get best of both worlds by privately expermenting with the code to see which possibilities I have and on the other hand try to think about a concept (which should work better, if I got a deeper understanding on existing concepts) and speak about that with you at first in this thread.

Does this sound like a reasonable plan to you?

**Comment by NicoVIII** [comment] 2018-08-03 05:09
I do have some first thoughts though:
My first suggestion would be to extend the installation scripts in e.g. such a way:
`game:
  gog:
    appid: 1234567890
    installer: en3installer12`

With this data (maybe additionally with os?) it should be possible to automatically download the game installer. If the os is linux, I think it would be cool, if lutris would automatically install the game in the usual way (extract etc.).

Another possibility (which would need restructuring I guess) would be to introduce another "class" next to runners which could be called "providers". Although with steam runner and provider are nearly almost the same, this could be interesting if you plan to introduce other providers like humblebundle, itch.io etc.

I think it could look like that in the installation script:
`runner: wine
provider: gog

script:
  game:
    appid: 1234567890
    installer: en1installer12`

**Comment by NicoVIII** [comment] 2018-08-15 11:43
After my merged PR:
How do we proceed from here? What do you think of my idea to generalize more by introducing a provider class?
And is there some way for scripts on the website to determine the needed version of lutris to use them? I could start to write some scripts for the installation from gog, if this would not affect users of the current released version of lutris.

**Comment by AlexanderRavenheart** [comment] 2018-09-15 21:31
https://www.gogdb.org/
Could this site be used for the GOG integration?

**Comment by AlexanderRavenheart** [comment] 2018-09-16 09:57
What about linking to it on game pages, like the links in the See also section, where Wikipedia, SteamDb, WineHQ and other links are posted for games?
![image](https://user-images.githubusercontent.com/7274337/45595151-0e4b5200-b9b0-11e8-9da1-7ab89dc77d49.png)

**Comment by jubalh** [comment] 2018-10-05 10:15
It would be very nice if it could display all the games available from my gog library even if i didn't install them. I would like to have an overview of all games that belong to me, so i can see which ones i can potentially play, even if not yet installed.

**Comment by strycore** [comment] 2018-12-14 10:01
https://www.youtube.com/watch?v=X7iBakLOrjA

It it also possible to import the GOG library to Lutris but this is still a bit buggy

**Closed by strycore** 2018-12-14 10:01 UTC
