### ISSUE TITLE
No way to retrieve log once game is switched

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1668] opened 2019-01-25 22:06 UTC
Log button greys out.

**Comment by strycore** [comment] 2019-01-26 00:49
I mean, yeah, we're not going to keep every log around forever, we got to get rid of them at some point.

**Comment by strycore** [comment] 2019-01-26 00:50
wait, while it's running or after?

**Comment by strycore** [comment] 2019-01-26 00:51
Confirmed, this is working as expected.

**Comment by AccountOneOff** [comment] 2019-01-26 01:19
But getting rid of them when no other game has launched?

**Comment by strycore** [comment] 2019-01-26 01:42
That doesn't apply to 0.5.0, only to 0.4.x where one game at a time can be launched

**Comment by AccountOneOff** [comment] 2019-01-26 01:52
What's your take on adding an option to save logs to a file then?

**Comment by tannisroot** [comment] 2019-01-26 05:49
I think there is some confusion here because the issue is not very well described.
I believe what @AccountOneOff doesn't like here is that the log gets deleted after you just select a different game in the library or unselect it.
This is not a very good design and it annoyed me as well as I lost logs with crashes many times simply because I accidentally clicked in the empty spot in library. 
Personally I think the logs should only be deleted after you close the client.

**Comment by tannisroot** [comment] 2019-02-17 06:24
Current behavior has proven to be extremely annoying as deselecting games (which is very easy to do by mistake) permamently erases very valuable debugging data, and after release of 0.5.0 I've received numerous complains about it from some users.
I will reopen the issue and add it to 0.5.1 milestone (so that it doesn't get lost) in hopes you might reconsider and change the design to erase logs only after closing Lutris, as I don't see the drawbacks of such approach.

**Comment by tannisroot** [comment] 2019-04-01 01:30
Also, I find it very annoying that there is no way to retrieve the log from the *still running* game once it's switched.
Personally, I think the best way to handle this is to clear the log after a certain period of time (5 minutes) after the game had stopped.

**Closed** 2020-10-06 05:06 UTC
