### ISSUE TITLE
Difficulty with xboxdrv integration

### ISSUE THREAD

**Issue by treymerkley** [lutris/lutris#1052] opened 2018-08-21 20:04 UTC
So I'm trying to set up the xboxdrv option so when I play a game it automagically maps me. I have the following options for the command line that work:

```--evdev /dev/input/event14 --evdev-absmap ABS_X=x1,ABS_Y=y1 --evdev-absmap ABS_RY=y2,ABS_RX=x2 --evdev-absmap ABS_Z=lt,ABS_RZ=rt --evdev-absmap ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y --evdev-keymap BTN_A=a,BTN_B=b --evdev-keymap BTN_NORTH=y,BTN_WEST=x --evdev-keymap BTN_TL=lb,BTN_TR=rb --evdev-keymap BTN_SELECT=back,BTN_START=start --evdev-keymap BTN_TL2=lt,BTN_TR2=rt --evdev-keymap BTN_MODE=guide --evdev-keymap BTN_THUMBL=tl,BTN_THUMBR=tr --axismap -y1=y1,-y2=y2 --mimic-xpad --silent```
But when I try to use this as the xboxdrv config option, no luck. Is it expecting a file? if so, how would I go about converting this to a config file? I'm new to both, but I'm excited to give it a try.

**Comment by basxto** [comment] 2018-08-26 07:27
No, it should work.

Lutris starts `xboxdrv --daemon --detach-kernel-driver --dbus session --silent <xboxdrv config>`

https://github.com/lutris/lutris/blob/d1c77a1cefe9b2fc1e43cba20e00943de9e26236/lutris/game.py#L374-L382

**Comment by billywade** [comment] 2018-08-26 12:29
I just tested it again, but left off the extra ```--silent``` at the end, and no luck. Are there any log files you need?

**Comment by Medath** [comment] 2018-08-26 13:27
It might be useful if you try `lutris -d` and paste the logs here

**Comment by billywade** [comment] 2018-08-26 14:30
You got it @Medath.
```
DEBUG    2018-08-26 09:26:14,102 [game]:Launching Stardew Valley: {'command': ['/home/trey/GOG Games/Stardew Valley/start.sh', '']}
DEBUG    2018-08-26 09:26:14,103 [display]:Switching resolution to 1360x768
INFO     2018-08-26 09:26:17,108 [runner]:Runtime disabled by system configuration
DEBUG    2018-08-26 09:26:17,109 [thread]:Command env: SDL_VIDEO_FULLSCREEN_DISPLAY="0" DRI_PRIME="0" 
DEBUG    2018-08-26 09:26:17,109 [thread]:Running command: "/home/trey/GOG Games/Stardew Valley/start.sh" ""
DEBUG    2018-08-26 09:26:17,109 [game]:[xboxdrv] pkexec xboxdrv --daemon --detach-kernel-driver --dbus session --silent --evdev /dev/input/event14 --evdev-absmap ABS_X=x1,ABS_Y=y1 --evdev-absmap ABS_RY=y2,ABS_RX=x2 --evdev-absmap ABS_Z=lt,ABS_RZ=rt --evdev-absmap ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y --evdev-keymap BTN_A=a,BTN_B=b --evdev-keymap BTN_NORTH=y,BTN_WEST=x --evdev-keymap BTN_TL=lb,BTN_TR=rb --evdev-keymap BTN_SELECT=back,BTN_START=start --evdev-keymap BTN_TL2=lt,BTN_TR2=rt --evdev-keymap BTN_MODE=guide --evdev-keymap BTN_THUMBL=tl,BTN_THUMBR=tr --axismap -y1=y1,-y2=y2 --mimic-xpad
DEBUG    2018-08-26 09:26:17,110 [thread]:Storing environment variable SDL_VIDEO_FULLSCREEN_DISPLAY to 0
DEBUG    2018-08-26 09:26:17,110 [thread]:Storing environment variable DRI_PRIME to 0
DEBUG    2018-08-26 09:26:17,113 [thread]:Command env: 
DEBUG    2018-08-26 09:26:17,113 [thread]:Running command: "pkexec" "xboxdrv" "--daemon" "--detach-kernel-driver" "--dbus" "session" "--silent" "--evdev" "/dev/input/event14" "--evdev-absmap" "ABS_X=x1,ABS_Y=y1" "--evdev-absmap" "ABS_RY=y2,ABS_RX=x2" "--evdev-absmap" "ABS_Z=lt,ABS_RZ=rt" "--evdev-absmap" "ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y" "--evdev-keymap" "BTN_A=a,BTN_B=b" "--evdev-keymap" "BTN_NORTH=y,BTN_WEST=x" "--evdev-keymap" "BTN_TL=lb,BTN_TR=rb" "--evdev-keymap" "BTN_SELECT=back,BTN_START=start" "--evdev-keymap" "BTN_TL2=lt,BTN_TR2=rt" "--evdev-keymap" "BTN_MODE=guide" "--evdev-keymap" "BTN_THUMBL=tl,BTN_THUMBR=tr" "--axismap" "-y1=y1,-y2=y2" "--mimic-xpad"
INFO     2018-08-26 09:26:17,122 [runner]:Runtime disabled by system configuration
DEBUG    2018-08-26 09:26:17,123 [game]:Launching Stardew Valley: {'command': ['/home/trey/GOG Games/Stardew Valley/start.sh', '']}
DEBUG    2018-08-26 09:26:17,123 [display]:Switching resolution to 1360x768
INFO     2018-08-26 09:26:20,128 [runner]:Runtime disabled by system configuration
DEBUG    2018-08-26 09:26:20,129 [thread]:Command env: SDL_VIDEO_FULLSCREEN_DISPLAY="0" DRI_PRIME="0" 
DEBUG    2018-08-26 09:26:20,129 [game]:[xboxdrv] pkexec xboxdrv --daemon --detach-kernel-driver --dbus session --silent --evdev /dev/input/event14 --evdev-absmap ABS_X=x1,ABS_Y=y1 --evdev-absmap ABS_RY=y2,ABS_RX=x2 --evdev-absmap ABS_Z=lt,ABS_RZ=rt --evdev-absmap ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y --evdev-keymap BTN_A=a,BTN_B=b --evdev-keymap BTN_NORTH=y,BTN_WEST=x --evdev-keymap BTN_TL=lb,BTN_TR=rb --evdev-keymap BTN_SELECT=back,BTN_START=start --evdev-keymap BTN_TL2=lt,BTN_TR2=rt --evdev-keymap BTN_MODE=guide --evdev-keymap BTN_THUMBL=tl,BTN_THUMBR=tr --axismap -y1=y1,-y2=y2 --mimic-xpad
DEBUG    2018-08-26 09:26:20,129 [thread]:Running command: "/home/trey/GOG Games/Stardew Valley/start.sh" ""
DEBUG    2018-08-26 09:26:20,129 [thread]:Storing environment variable SDL_VIDEO_FULLSCREEN_DISPLAY to 0
DEBUG    2018-08-26 09:26:20,129 [thread]:Storing environment variable DRI_PRIME to 0
DEBUG    2018-08-26 09:26:20,131 [thread]:Command env: 
DEBUG    2018-08-26 09:26:20,132 [thread]:Running command: "pkexec" "xboxdrv" "--daemon" "--detach-kernel-driver" "--dbus" "session" "--silent" "--evdev" "/dev/input/event14" "--evdev-absmap" "ABS_X=x1,ABS_Y=y1" "--evdev-absmap" "ABS_RY=y2,ABS_RX=x2" "--evdev-absmap" "ABS_Z=lt,ABS_RZ=rt" "--evdev-absmap" "ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y" "--evdev-keymap" "BTN_A=a,BTN_B=b" "--evdev-keymap" "BTN_NORTH=y,BTN_WEST=x" "--evdev-keymap" "BTN_TL=lb,BTN_TR=rb" "--evdev-keymap" "BTN_SELECT=back,BTN_START=start" "--evdev-keymap" "BTN_TL2=lt,BTN_TR2=rt" "--evdev-keymap" "BTN_MODE=guide" "--evdev-keymap" "BTN_THUMBL=tl,BTN_THUMBR=tr" "--axismap" "-y1=y1,-y2=y2" "--mimic-xpad"
DEBUG    2018-08-26 09:26:20,138 [thread]:Start process monitoring
DEBUG    2018-08-26 09:26:20,138 [thread]:Processes monitored: start.sh (7890:S), StardewValley (7911:S), StardewValley.b (7916:D), pkexec (7892:Z), start.sh (7984:S), None (7987:None), pkexec (7986:R)
Running Stardew Valley
DEBUG    2018-08-26 09:26:20,140 [thread]:Start process monitoring
DEBUG    2018-08-26 09:26:20,140 [thread]:Processes monitored: start.sh (7890:S), StardewValley (7911:S), StardewValley.b (7916:D), pkexec (7892:Z), start.sh (7984:S), None (7990:None), None (7991:None), None (7992:None), None (7993:None), pkexec (7986:S)
Running Stardew Valley
xboxdrv 0.8.8 - http://pingus.seul.org/~grumbel/xboxdrv/ 
Please use SDL 2.0.5 or higher.
DEBUG    2018-08-26 09:26:22,135 [thread]:Start process monitoring
DEBUG    2018-08-26 09:26:22,136 [thread]:Processes external: start.sh (7890:S), StardewValley (7911:S), StardewValley.b (7916:R), pkexec (7892:Z)
DEBUG    2018-08-26 09:26:22,136 [thread]:Processes monitored: start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R)
DEBUG    2018-08-26 09:26:22,136 [thread]:Processes excluded: xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:22,137 [thread]:Processes monitored: start.sh (7890:S), StardewValley (7911:S), StardewValley.b (7916:R), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R)
DEBUG    2018-08-26 09:26:22,137 [thread]:Processes excluded: xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:22,139 [thread]:Processes monitored: start.sh (7890:S), StardewValley (7911:S), StardewValley.b (7916:R), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:22,140 [thread]:Start process monitoring
DEBUG    2018-08-26 09:26:22,140 [thread]:Processes external: start.sh (7890:S), StardewValley (7911:S), StardewValley.b (7916:D), pkexec (7892:Z)
DEBUG    2018-08-26 09:26:22,141 [thread]:Processes monitored: start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:24,161 [thread]:Processes external: start.sh (7890:S), StardewValley (7911:S), StardewValley.b (7916:D), pkexec (7892:Z)
DEBUG    2018-08-26 09:26:24,162 [thread]:Processes monitored: start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:D)
DEBUG    2018-08-26 09:26:24,164 [thread]:Processes monitored: start.sh (7890:S), StardewValley (7911:S), StardewValley.b (7916:D), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:D)
DEBUG    2018-08-26 09:26:24,166 [thread]:Processes monitored: start.sh (7890:S), StardewValley (7911:S), StardewValley.b (7916:D), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:D), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:24,167 [thread]:Processes monitored: start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:D), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:26,970 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:D)
Please use SDL 2.0.5 or higher.
DEBUG    2018-08-26 09:26:26,979 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:D), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:26,981 [thread]:Processes external: start.sh (7890:Z), pkexec (7892:Z)
DEBUG    2018-08-26 09:26:26,983 [thread]:Processes external: start.sh (7890:Z), pkexec (7892:Z)
./StardewValley: line 38:  7916 Killed                  ./StardewValley.bin.x86_64 $@
DEBUG    2018-08-26 09:26:28,965 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R)
DEBUG    2018-08-26 09:26:28,966 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:28,968 [thread]:Processes monitored: start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R)
DEBUG    2018-08-26 09:26:28,969 [thread]:Processes monitored: start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R), xboxdrv (7986:S)
setGameMode( 'titleScreenGameMode (0)' )
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
DEBUG    2018-08-26 09:26:30,970 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:S)
DEBUG    2018-08-26 09:26:30,975 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:S), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:30,976 [thread]:Processes monitored: start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:S)
DEBUG    2018-08-26 09:26:30,977 [thread]:Processes monitored: start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:S), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:34,971 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R)
Galaxy.Api.GalaxyInstance+RuntimeError: Could not retrieve GalaxyPeer library location
  at Galaxy.Api.GalaxyInstance.Init (System.String clientID, System.String clientSecret) <0x40210c10 + 0x00033> in <filename unknown>:0 
  at StardewValley.SDKs.GalaxyHelper.Initialize () <0x40210740 + 0x00027> in <filename unknown>:0 
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
DEBUG    2018-08-26 09:26:36,970 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:S)
DEBUG    2018-08-26 09:26:48,975 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:R)
DEBUG    2018-08-26 09:26:50,976 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:S), StardewValley (8004:S), StardewValley.b (8009:S)
./StardewValley: line 38:  8009 Killed                  ./StardewValley.bin.x86_64 $@
DEBUG    2018-08-26 09:26:54,975 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:Z)
DEBUG    2018-08-26 09:26:54,978 [thread]:Processes monitored: start.sh (7890:Z), pkexec (7892:Z), start.sh (7984:Z), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:54,981 [thread]:Processes monitored: start.sh (7984:Z)
DEBUG    2018-08-26 09:26:54,982 [thread]:Processes monitored: start.sh (7984:Z), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:56,977 [thread]:Waiting for processes to exit
DEBUG    2018-08-26 09:26:56,977 [thread]:Thread is no longer running
DEBUG    2018-08-26 09:26:56,977 [thread]:Restoring environment
DEBUG    2018-08-26 09:26:56,980 [thread]:Processes monitored: pkexec (7892:Z), start.sh (7984:Z), xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:56,983 [thread]:Processes external: pkexec (7892:Z)
DEBUG    2018-08-26 09:26:56,983 [thread]:Waiting for processes to exit
DEBUG    2018-08-26 09:26:56,983 [thread]:Thread is no longer running
DEBUG    2018-08-26 09:26:56,983 [thread]:Restoring environment
DEBUG    2018-08-26 09:26:56,983 [thread]:Processes external: pkexec (7892:Z)
DEBUG    2018-08-26 09:26:56,983 [thread]:Processes monitored: xboxdrv (7986:S)
DEBUG    2018-08-26 09:26:58,974 [game]:Game thread stopped
DEBUG    2018-08-26 09:26:58,974 [game]:Game thread still running, stopping it (state: running)
DEBUG    2018-08-26 09:26:58,974 [game]:Stopping xboxdrv
DEBUG    2018-08-26 09:27:01,317 [thread]:Restoring environment
DEBUG    2018-08-26 09:27:01,318 [game]:Stardew Valley stopped at Sun, 26 Aug 2018 09:27:01
DEBUG    2018-08-26 09:27:01,318 [thread]:Killing all remaining processes
ERROR    2018-08-26 09:27:01,320 [system]:Could not kill process 7986
ERROR    2018-08-26 09:27:01,320 [system]:Could not kill process 7986
DEBUG    2018-08-26 09:27:01,320 [thread]:Killed processes: pkexec (7892:Z), xboxdrv (7986:Z)
DEBUG    2018-08-26 09:27:01,348 [display]:Switching to 1360x768+0+0 on HDMI-0
DEBUG    2018-08-26 09:27:01,445 [thread]:Processes monitored: pkexec (7892:Z), xboxdrv (7986:Z)
DEBUG    2018-08-26 09:27:01,445 [game]:Game thread stopped
DEBUG    2018-08-26 09:27:01,445 [game]:Game thread still running, stopping it (state: running)
DEBUG    2018-08-26 09:27:01,445 [game]:Stopping xboxdrv
Traceback (most recent call last):
  File "/usr/bin/xboxdrvctl", line 81, in <module>
    daemon = bus.get_object("org.seul.Xboxdrv", '/org/seul/Xboxdrv/Daemon')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.seul.Xboxdrv was not provided by any .service files
DEBUG    2018-08-26 09:27:03,555 [thread]:Restoring environment
DEBUG    2018-08-26 09:27:03,556 [thread]:Killing all remaining processes
DEBUG    2018-08-26 09:27:03,556 [game]:Stardew Valley stopped at Sun, 26 Aug 2018 09:27:03
ERROR    2018-08-26 09:27:03,559 [system]:Could not kill process 7986
ERROR    2018-08-26 09:27:03,559 [system]:Could not kill process 7986
DEBUG    2018-08-26 09:27:03,559 [thread]:Killed processes: pkexec (7892:Z), xboxdrv (7986:Z)
DEBUG    2018-08-26 09:27:03,593 [display]:Switching to 1360x768+0+0 on HDMI-0
DEBUG    2018-08-26 09:27:03,604 [thread]:Processes monitored: xboxdrv (7986:Z)
DEBUG    2018-08-26 09:27:03,605 [thread]:Waiting for processes to exit
DEBUG    2018-08-26 09:27:03,605 [thread]:Thread is no longer running
DEBUG    2018-08-26 09:27:03,606 [thread]:Restoring environment
DEBUG    2018-08-26 09:27:03,606 [thread]:Waiting for processes to exit
DEBUG    2018-08-26 09:27:03,606 [thread]:Removing stdout monitor
DEBUG    2018-08-26 09:27:03,606 [thread]:Thread is no longer running
DEBUG    2018-08-26 09:27:03,606 [thread]:Restoring environment
INFO     2018-08-26 09:27:05,167 [application]:Shutting down Lutris
```
The part that really interests me is
```
DEBUG    2018-08-26 09:26:20,132 [thread]:Running command: "pkexec" "xboxdrv" "--daemon" "--detach-kernel-driver" "--dbus" "session" "--silent" "--evdev" "/dev/input/event14" "--evdev-absmap" "ABS_X=x1,ABS_Y=y1" "--evdev-absmap" "ABS_RY=y2,ABS_RX=x2" "--evdev-absmap" "ABS_Z=lt,ABS_RZ=rt" "--evdev-absmap" "ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y" "--evdev-keymap" "BTN_A=a,BTN_B=b" "--evdev-keymap" "BTN_NORTH=y,BTN_WEST=x" "--evdev-keymap" "BTN_TL=lb,BTN_TR=rb" "--evdev-keymap" "BTN_SELECT=back,BTN_START=start" "--evdev-keymap" "BTN_TL2=lt,BTN_TR2=rt" "--evdev-keymap" "BTN_MODE=guide" "--evdev-keymap" "BTN_THUMBL=tl,BTN_THUMBR=tr" "--axismap" "-y1=y1,-y2=y2" "--mimic-xpad"
```
It looks like it's trying to run each of these as an individual command, if I'm reading it right.

**Comment by basxto** [comment] 2018-08-26 18:49
I just stumbled upon here, because I was unsure whether I used that field correctly.
Have you tried it with xboxdrv outside of lutris before? Maybe even with something like [jstest-gtk](https://github.com/Grumbel/jstest-gtk/)?
`sudo xboxdrv --daemon --detach-kernel-driver --dbus session --silent --evdev /dev/input/event14 --evdev-absmap ABS_X=x1,ABS_Y=y1 --evdev-absmap ABS_RY=y2,ABS_RX=x2 --evdev-absmap ABS_Z=lt,ABS_RZ=rt --evdev-absmap ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y --evdev-keymap BTN_A=a,BTN_B=b --evdev-keymap BTN_NORTH=y,BTN_WEST=x --evdev-keymap BTN_TL=lb,BTN_TR=rb --evdev-keymap BTN_SELECT=back,BTN_START=start --evdev-keymap BTN_TL2=lt,BTN_TR2=rt --evdev-keymap BTN_MODE=guide --evdev-keymap BTN_THUMBL=tl,BTN_THUMBR=tr --axismap -y1=y1,-y2=y2 --mimic-xpad`
What behavior did you expect? What happened instead?

I never have worked with `--evdev`.  It might be that "mimic-xpad" must go first. My gamepad works basically, I just change button positions for games.

Lutris uses the arguments correctly, a shell would do it similarly. At least in your case. This is how arguments work on a low level, this then gets interpreted by the called program.
The program’s syntax for option, command, argument etc., which gets explained in helps and man pages, is on a higher level.

**Comment by basxto** [comment] 2018-08-26 21:41
You could try starting xboxdrv with `--verbose` or `--debug` through lutris.
To me it looks like lutris starts xboxdrv without problems and with your configurations.

**Comment by billywade** [comment] 2018-08-29 07:19
Running it like you said,
```
Running Stardew Valley
xboxdrv 0.8.8 - http://pingus.seul.org/~grumbel/xboxdrv/ 
Copyright © 2008-2011 Ingo Ruhnke <grumbel@gmail.com> 
Licensed under GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> 
This program comes with ABSOLUTELY NO WARRANTY. 
This is free software, and you are welcome to redistribute it under certain 
conditions; see the file COPYING for details. 

[INFO]  XboxdrvDaemon::init_uinput(): starting with UInput
[INFO]  XboxdrvDaemon::init_uinput(): creating slot: 0
[INFO]  XboxdrvDaemon::init_uinput(): created 1 controller slots
[INFO]  XboxdrvDaemon::connect(): connecting slot to thread
Please use SDL 2.0.5 or higher.
setGameMode( 'titleScreenGameMode (0)' )
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
Galaxy.Api.GalaxyInstance+RuntimeError: Could not retrieve GalaxyPeer library location
  at Galaxy.Api.GalaxyInstance.Init (System.String clientID, System.String clientSecret) <0x4178ff70 + 0x00033> in <filename unknown>:0 
  at StardewValley.SDKs.GalaxyHelper.Initialize () <0x4178faf0 + 0x00027> in <filename unknown>:0 
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
./StardewValley: line 38:  2891 Killed                  ./StardewValley.bin.x86_64 $@
ERROR    2018-08-29 02:14:50,307 [system]:Could not kill process 2868
ERROR    2018-08-29 02:14:50,308 [system]:Could not kill process 2868
[INFO]  XboxdrvDaemon::connect(): controller connected: 003:008 054c:0268 'PLAYSTATION(R)3 Controller'
[INFO]  XboxdrvDaemon::connect(): launched Controller for 003:008 in slot 0, free slots: 0/1
[INFO]  xboxdrv_g_daemon_shutdown(): D-Bus: xboxdrv_g_daemon_shutdown(0x56515912a080)
INFO     2018-08-29 02:15:55,938 [runner]:Runtime disabled by system configuration
INFO     2018-08-29 02:15:55,997 [runner]:Runtime disabled by system configuration

```
It looks like Lutris might be executing xboxdrv only on close of the original software.

**Comment by basxto** [comment] 2018-08-29 10:35
I used ` --verbose  --ui-axismap dpad_x=ABS_HAT0Y,dpad_y=ABS_HAT0X` with steam stardew valley in drm-free mode. I switched X and Y axis for the dpad, because that’s quite easy to test.

I get similar output:
```
xboxdrv 0.8.8 - http://pingus.seul.org/~grumbel/xboxdrv/
Copyright © 2008-2011 Ingo Ruhnke <grumbel@gmail.com>
Licensed under GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions; see the file COPYING for details.                                     

[INFO]  XboxdrvDaemon::init_uinput(): starting with UInput
[INFO]  XboxdrvDaemon::init_uinput(): creating slot: 0
[INFO]  XboxdrvDaemon::init_uinput(): created 1 controller slots
[INFO]  XboxdrvDaemon::connect(): connecting slot to thread
Please use SDL 2.0.5 or higher.
setGameMode( 'titleScreenGameMode (0)' )
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.                                                 
System.InvalidOperationException: Steamworks is not initialized.
  at Steamworks.InteropHelp.TestIfAvailableClient () <0x41819860 + 0x0004f> in <filename unknown>:0                                                           
  at Steamworks.SteamUser.BLoggedOn () <0x41819830 + 0x0000b> in <filename unknown>:0                                                                         
  at StardewValley.SDKs.SteamHelper.Initialize () <0x41818f90 + 0x00047> in <filename unknown>:0                                                              
loadPreferences(); begin - languageCode=en
savePreferences(); async=False, languageCode=en
ERROR    2018-08-29 12:26:30,698 [system]:Could not kill process 10375
ERROR    2018-08-29 12:26:30,699 [system]:Could not kill process 10375
[INFO]  XboxdrvDaemon::connect(): controller connected: 001:003 045e:028e 'Controller'                                                                        
[INFO]  XboxdrvDaemon::connect(): launched Controller for 001:003 in slot 0, free slots: 0/1                                                                  
[INFO]  xboxdrv_g_daemon_shutdown(): D-Bus: xboxdrv_g_daemon_shutdown(0x55e203f89c80)
```

It’s nearly identical to your output.
`xboxdrv 0.8.8 - http://pingus.seul.org/~grumbel/xboxdrv/ ` in actually where the output of xboxdrv starts.
I don’t think this explains why you can play stardew valley with an externally started xboxbdrv, but not when launched by lutris.

**Comment by basxto** [comment] 2018-08-30 06:33
_What controller do you use?_
It looks like you are using a PS3 controller, which is both supported by xpad and xboxdrv.

_What do you try to do and what does not work?_
Did I get it right, that just the button mapping was off, but everything else worked?
Just --buttonmap and --axismap / --ui-buttonmap and --ui-axismap is not enough?
Starting xboxdrv manually and then playing stardew valley maps the keys how you expect it?
`--verbose --ui-axismap dpad_x=ABS_HAT0Y,dpad_y=ABS_HAT0X` does not invert the dpad?

Do you know if `--evdev /dev/input/event14` is a reliable path? I wouldn’t be surprised if the order changes every boot.

**Comment by basxto** [comment] 2018-08-30 06:55
I think, I got it.

Does this work for you?
`sudo xboxdrv --daemon --detach-kernel-driver --dbus session --silent --evdev /dev/input/event14 --evdev-absmap ABS_X=x1,ABS_Y=y1 --evdev-absmap ABS_RY=y2,ABS_RX=x2 --evdev-absmap ABS_Z=lt,ABS_RZ=rt --evdev-absmap ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y --evdev-keymap BTN_A=a,BTN_B=b --evdev-keymap BTN_NORTH=y,BTN_WEST=x --evdev-keymap BTN_TL=lb,BTN_TR=rb --evdev-keymap BTN_SELECT=back,BTN_START=start --evdev-keymap BTN_TL2=lt,BTN_TR2=rt --evdev-keymap BTN_MODE=guide --evdev-keymap BTN_THUMBL=tl,BTN_THUMBR=tr --axismap -y1=y1,-y2=y2 --mimic-xpad`
Check with stardew valley or jstest-gtk.
It’s not working for me, it does not change anything. It does’t even fail my gamepad is event10, not event14. No errors when I give a path to file that does not exist. Event10 also shows no remapping.

Running it without `--daemon` behaves differently. It needs no sudo, the newly created `/dev/input/js1` is completely dead when I give it a wrong input device.
If the file does not exist, it gives me `/dev/input/by-id`

To me it looks like `--daemon` skips all evdev arguments.

**Comment by billywade** [comment] 2018-08-30 12:30
@basxto you are a machine! Alright, so I am using a PS3 controller, and yo verify my evdev events I'm using evtest. Additionally, if you can think of a better way of going about it that doesn't require me to check the event every time, let me know.

Neither config you listed, copied and pasted to the xboxdrv field works for me, unfortunately.

**Comment by rezzafr33** [comment] 2018-09-20 02:31
I edit game.py, change `xboxdrv_start` and `xboxdrv_stop` method, so i can use xboxdrv with non xbox or non ps3/4 joystick.

```python
...
    def xboxdrv_start(self, config):
        command = [
            "xboxdrv", "--detach-kernel-driver", "--silent", "--quiet"
        ] + config.split()
        logger.debug("[xboxdrv] %s", ' '.join(command))
        self.xboxdrv_thread = LutrisThread(command, include_processes=['xboxdrv'])
        self.xboxdrv_thread.set_stop_command(self.xboxdrv_stop)
        self.xboxdrv_thread.start()

    def get_xboxdrv_pid(self):
        return system.get_pid('xboxdrv$')

    def xboxdrv_stop(self):
        pid = self.get_xboxdrv_pid()
        system.kill_pid(pid)
        #os.system("pkexec xboxdrvctl --shutdown")
        if os.path.exists("/usr/share/lutris/bin/resetxpad"):
            os.system("pkexec /usr/share/lutris/bin/resetxpad")
...
```

**Comment by tannisroot** [comment] 2020-01-09 15:41
This is a very old bug that haven't had any activity in over a year, and strider can't reproduce it, so closing.

**Closed by tannisroot** 2020-01-09 15:41 UTC
Labels: can't reproduce

**Comment by strycore** [comment] 2020-01-12 00:03
xboxdrv is unmaintained and good controller support in Wine means it's nearly useless. Should we remove xboxdrv support entirely?

**Comment by rezzafr33** [comment] 2020-01-12 00:41
I agree, people who need xboxdrv can use pre-launch script instead

**Comment by treymerkley** [comment] 2020-01-12 16:41
I think at the time I was wanting to use xboxdrv to map for games that don't have controller input, but I haven't tried to use Lutris as a launcher since I submitted this issue.

**Comment by strycore** [comment] 2020-02-06 05:39
Ended up removing the xboxdrv option since our PolicyKit rules that permitted running xboxdrv without asking for the root password caused Lutris to be removed from OpenSuse.
