### ISSUE TITLE
Can't login to Humble Bundle with version 0.5.11

### ISSUE THREAD

**Issue by tiagobugarin** [lutris/lutris#4459] opened 2022-08-29 01:43 UTC
Arch Linux (up to date as of 20220829 01:45 UTC)
Linux Kernel 5.19.4-arch1-1
Gnome 42
Lutris 0.5.11 (flatpak but also tested with arch community package)
Nvidia Geforce GTX 960M (515.65.01)

What happens: After clicking to connect to the Humble Bundle service the modal web login pops up letting me type my email and password for the service. When I press the "LOG IN" blue button for a very brief moment the spinning wheel shows up and comes back to the email and password screen. No messages appears on the login screen.

Running Lutris with the `-d` option from the command line returns no message at all when connecting to Humble Bundle.

When I tryed to see the console log for that screen the web dev screen would not respond to any clicks so I was not able to read the JS console log.

When trying to access Humble Bundle with Gnome Web (Epiphany) I was able to recreate a situation that looks exactly like the Lutris embedded one by enabling "Smart Tracking Prevention".
This is the console log error at Gnome Web:

```
[Info] Content blocker prevented frame displaying https://www.humblebundle.com/login?hmb_source=navbar&goto=%2F from loading a resource from https://www.mczbf.com/tags/11509/tag.js (login, line 432)
[Info] Content blocker prevented frame displaying https://www.humblebundle.com/login?hmb_source=navbar&goto=%2F from loading a resource from https://connect.facebook.net/en_US/fbevents.js (login, line 461)
[Warning] Unable to track. Missing "offer_id" or "transaction_id" parameter. (everflow.js, line 1)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (processlogin, line 0)
```

Disabling that feature always works for login in to Humble Bundle with Gnome Web.

_Originally posted by @tiagobugarin in https://github.com/lutris/lutris/issues/4448#issuecomment-1229210957_

**Comment by SethFalco** [comment] 2022-09-17 17:33
I have the same problem on Debian 11.

<details>
  <summary><code>$ uname -a</code></summary>

```
Linux seth-pc-tux 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
```

</details>

When I copy the request as cURL and paste it into an HTTP client, it takes me to access denied page from Cloudflare which is probably where the 403 comes from.

![image](https://user-images.githubusercontent.com/22801583/190869370-5b02fc29-8aad-4e22-9f16-3b2e7ec3d6dd.png)

> If you encounter the error [1020](https://community.cloudflare.com/t/community-tip-fixing-error-1020-access-denied/66439), you’re violating a firewall rule the site owner has put in place, the error has nothing to do with Cloudflare Access.
> 
> — https://community.cloudflare.com/t/community-tip-access-was-denied-error-code-1020/66439

**Comment by AriaanBruinsma** [comment] 2022-12-10 11:27
```
[System]
OS:              Fedora Linux 37 Workstation Edition
Arch:            x86_64
Kernel:          6.0.11-300.fc37.x86_64
Desktop:         GNOME
Display Server:  wayland
```
I have the same problem. The login panel loads, but the moment I hit "Login" it seems to do a call or refresh, but then nothing happens. I also noticed it does not remember the cookie-settings that keep popping up. (Not sure if that's relevant though)

![image](https://user-images.githubusercontent.com/539121/206852619-82c6fa60-e609-43df-980f-5fd10e84d2de.png)
![image](https://user-images.githubusercontent.com/539121/206852680-03ac7bab-49c8-4e0c-9424-b51921923def.png)

**Comment by strycore** [comment] 2023-01-26 21:33
Closing as duplicate of #4099

**Closed by strycore** 2023-01-26 21:33 UTC
