### ISSUE TITLE
Lutris v5.13.0 not showing game art

### ISSUE THREAD

**Issue by lucscamps** [lutris/lutris#4929] opened 2023-07-11 20:36 UTC
### Bug description

Lutris v5.13.0 isn't showing game art (banner/icon).
Older versions works just fine.

### How to Reproduce

1. Open Lutris 5.13.0 with wine games installed
Optional:
2. Try to insert game art on games

### Expected behavior

It should show game art properly

### Log output in 5.13.0

```shell
INFO     2023-07-11 17:28:08,065 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-07-11 17:28:08,066 [startup.check_driver:65]:Using NVIDIA drivers 535.54.03 for x86_64
INFO     2023-07-11 17:28:08,066 [startup.check_driver:69]:GPU: NVIDIA GeForce GTX 1650
INFO     2023-07-11 17:28:08,066 [startup.check_driver:85]:GPU: 10DE:1F99 1025:1447 (nvidia drivers)
INFO     2023-07-11 17:28:08,066 [startup.check_driver:85]:GPU: 1002:1636 1025:1455 (amdgpu drivers)
DEBUG    2023-07-11 17:28:08,323 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-07-11 17:28:08,366 [lutris.get_missing_game_ids:191]:Checking for missing games
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
DEBUG    2023-07-11 17:28:11,103 [application.show_window:339]:Showing window EditGameConfigDialog6
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
DEBUG    2023-07-11 17:28:17,934 [game.save:423]:Saving Webbed 2 (wine) with config ID webbed-1689107279
DEBUG    2023-07-11 17:28:17,934 [config.save:229]:Saving LutrisConfig(level=game, game_config_id=webbed-1689107279, runner=wine) config to /home/lucas/.config/lutris/games/webbed-1689107279.yml
DEBUG    2023-07-11 17:28:17,998 [lutris.add_to_path_cache:158]:Adding Webbed 2 (wine) to path cache
DEBUG    2023-07-11 17:28:18,012 [application.on_app_window_destroyed:357]:Removed window EditGameConfigDialog6
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
INFO     2023-07-11 17:28:27,776 [application.do_shutdown:960]:Shutting down Lutris
```

### Log output in 5.12.0

```shell
INFO     2023-07-11 17:37:05,638 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-07-11 17:37:05,664 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-07-11 17:37:05,694 [startup.check_driver:57]:Using NVIDIA drivers 535.54.03 for x86_64
INFO     2023-07-11 17:37:05,694 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 1650
INFO     2023-07-11 17:37:05,694 [startup.check_driver:77]:GPU: 10DE:1F99 1025:1447 (nvidia drivers)
INFO     2023-07-11 17:37:05,695 [startup.check_driver:77]:GPU: 1002:1636 1025:1455 (amdgpu drivers)
DEBUG    2023-07-11 17:37:05,909 [lutriswindow.update_store:448]:Showing 3 games
INFO     2023-07-11 17:37:05,918 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-07-11 17:37:10,909 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-07-11 17:37:10,968 [system.execute:57]:Executing / u s r / b i n / l s p c i
DEBUG    2023-07-11 17:37:10,981 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-07-11 17:37:10,990 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-07-11 17:37:10,999 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-07-11 17:37:11,205 [application.show_window:328]:Showing window EditGameConfigDialog3
DEBUG    2023-07-11 17:37:17,167 [game.save:299]:Saving Webbed (wine) with config ID webbed-setup-1689043150
DEBUG    2023-07-11 17:37:17,167 [config.save:229]:Saving LutrisConfig(level=game, game_config_id=webbed-setup-1689043150, runner=wine) config to /home/lucas/.config/lutris/games/webbed-setup-1689043150.yml
DEBUG    2023-07-11 17:37:17,230 [application.on_app_window_destroyed:346]:Removed window EditGameConfigDialog3
INFO     2023-07-11 17:38:33,383 [application.do_shutdown:898]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Ubuntu 22.04 Jammy Jellyfish
Arch:            x86_64
Kernel:          5.19.0-46-generic
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 4800H with Radeon Graphics
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.0 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: RENOIR (renoir, LLVM 15.0.7, DRM 3.47, 5.19.0-46-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
OpenGL Core:     4.6 (Core Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
OpenGL ES:       OpenGL ES 3.2 Mesa 22.2.5-0ubuntu0.1~22.04.3
Vulkan:          Supported
```

### Media (optional)

v.0.13.0:
https://postimg.cc/CdF1zJn3
https://postimg.cc/tYcCvjvb

v0.12.0 or older:
https://postimg.cc/cKy1ZcN5

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment] 2023-07-11 20:55
Pretty sure this is a duplicate of #4857; fixed in master.

The workaround is to manually install the package ``python3-gi-cairo``.

**Closed by danieljohnson2** 2023-07-11 20:55 UTC
