### ISSUE TITLE
d9vk lutris 0.5.2.1 steam/bnet hang

### ISSUE THREAD

**Issue by Bednar87** [lutris/lutris#2127] opened 2019-05-11 14:11 UTC
hey,

I have created a d9vk folder in /home/bednar/.local/share/lutris/runtime/dxvk/d9vk and copied the *.dll files as shown here: https://www.youtube.com/watch?v=q2zEQ5Jm28A

I then tried to launch Starcraft 2 and Need For Speed Hot Pursuit but both steam and bnet seem to hang. In runner options I enabled DXVK, set the version to manual and renamed it to d9vk.

Any ideas?

**Comment by AccountOneOff** [comment] 2019-05-11 20:18
https://github.com/lutris/lutris/wiki/Getting-Help:-Providing-logs-&-System-Info#lutris-debugging-output

Read that and everything below it.

**Comment by Bednar87** [comment] 2019-05-11 20:28
thanks.

lutris -d when lunching starcraft 2. The bnet tray icon appears but the application itself seems frozen:

https://gist.github.com/Bednar87/6e8c45393ea960b753b28570add68b01

lutris --submit-issue

https://gist.github.com/Bednar87/1e2932ce9e31bc2941fff2d2dfef5d48

**Comment by Zeioth** [comment] 2019-05-11 20:35
You need Lutris 0.5.2.2 to use d9vk putting it in /home/bednar/.local/share/lutris/runtime/dxvk/

**Comment by Zeioth** [comment] 2019-05-11 20:37
You have two options:

1) Install Lutris 0.5.2.2
2) Put the content of d9vk/x64 in your wineprefix's windows/system32 folder.

Btw are you using arch? I'm still not getting 0.5.2.2 from the repos either.

**Comment by Bednar87** [comment] 2019-05-11 20:38
Yeah, I am on arch. I don't see 0.5.2.2 as a tagged release though. https://github.com/lutris/lutris/tags

**Comment by Zeioth** [comment] 2019-05-11 20:43
If you wanna try Lutris 0.5.2.2 do this:

    git clone git@github.com:lutris/lutris.git
    cd lutris/bin && python lutris

**Comment by tannisroot** [comment] 2019-05-16 08:33
D9VK is an experimental project and still has some bugs and unimplemented stuff.
Closing as this is not a bug in the Lutris client. Consider using wined3d instead.

**Closed by tannisroot** 2019-05-16 08:33 UTC
Labels: missing information
