### ISSUE TITLE
Some lutris games don't load until steam is opened after NVIDIA Driver update

### ISSUE THREAD

**Issue by mercifulboss** [lutris/lutris#4283] opened 2022-05-15 20:57 UTC
### Bug description

I have two games on my Lutris (GoW and GWT) that won't launch after the update to the NVIDIA 515 drivers on archlinux. Whenever I click on the games, I will get the following error for GWT:
(seen below)

This error will persist until I launch steam and this suddenly allows the game to load (I don't see how lutris is related to steam).

Trying to launch God of War will briefly go to a black screen then crash with the following output in the terminal:
(seen below)

### How to Reproduce

1. Go to 'lutris main client'
2. Click on 'GOW or GWT'
4. See 'games fail to launch until steam is opened'

### Expected behavior

I expected lutris to launch the games like normal without opening steam like it did before the NVIDIA driver update.

### Log output

```shell
`NFO     2022-05-15 16:53:42,650 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-05-15 16:53:42,761 [libretro.get_libretro_cores:24]:No folder at /home/andrew2/.local/share/lutris/runners/retroarch/
DEBUG    2022-05-15 16:53:42,790 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
INFO     2022-05-15 16:53:43,051 [startup.check_driver:57]:Using NVIDIA drivers 515.43.04 for x86_64
INFO     2022-05-15 16:53:43,051 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 2060
INFO     2022-05-15 16:53:43,052 [startup.check_driver:77]:GPU: 10DE:1F15 17AA:3F8C (nvidia drivers)
INFO     2022-05-15 16:53:43,052 [startup.check_driver:77]:GPU: 8086:9BC4 17AA:3F8C (i915 drivers)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

INFO     2022-05-15 16:53:43,223 [startup.update_runtime:213]:Startup complete
DEBUG    2022-05-15 16:53:43,335 [lutriswindow.update_store:437]:Showing 9 games
DEBUG    2022-05-15 16:53:45,853 [grid.on_item_activated:57]:Item activated: 5
ERROR    2022-05-15 16:53:46,341 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:53:46,341 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:53:46,341 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:53:46,341 [wine.get_overrides_env:441]:Invalid override value /home/andrew2/.gow/
ERROR    2022-05-15 16:53:46,341 [wine.get_overrides_env:441]:Invalid override value dxr11
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

ERROR    2022-05-15 16:53:46,393 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:53:46,393 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:53:46,393 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:53:46,393 [wine.get_overrides_env:441]:Invalid override value /home/andrew2/.gow/
ERROR    2022-05-15 16:53:46,393 [wine.get_overrides_env:441]:Invalid override value dxr11
DEBUG    2022-05-15 16:53:46,393 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
DEBUG    2022-05-15 16:53:46,878 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2022-05-15 16:53:46,878 [command.start:141]:MANGOHUD="1"
DEBUG    2022-05-15 16:53:46,878 [command.start:141]:MANGOHUD_DLSYM="1"
DEBUG    2022-05-15 16:53:46,878 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/hdd/Games/GodOfWar"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:DRI_PRIME="1"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:LD_LIBRARY_PATH="/usr/lib:/usr/lib64:/usr/lib:/usr/lib32:/usr/lib/openmpi:/usr/lib/libfakeroot:/usr/lib64:/home/andrew2/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/andrew2/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/andrew2/.local/share/lutris/runtime/steam/i386/lib:/home/andrew2/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/andrew2/.local/share/lutris/runtime/steam/i386/usr/lib:/home/andrew2/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/andrew2/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/andrew2/.local/share/lutris/runtime/steam/amd64/lib:/home/andrew2/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/andrew2/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:DXVK_ASYNC="1"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:DXVK_HUD="1"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:STEAM_COMPAT_DATA_PATH="/home/andrew2/.gow/"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:VKD3D_CONFIG="dxr11"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINEDEBUG="-all"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINEARCH="win64"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINE="/usr/bin/wine"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINE_MONO_CACHE_DIR="/home/andrew2/.local/share/lutris/runners/wine/system/mono"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/andrew2/.local/share/lutris/runners/wine/system/gecko"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINEPREFIX="/home/andrew2/.gow/"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINEESYNC="1"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINEFSYNC="1"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2022-05-15 16:53:46,879 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2022-05-15 16:53:46,880 [command.start:141]:game_name="God of War"
DEBUG    2022-05-15 16:53:46,880 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/home/andrew2/.local/lib/python3.10/site-packages:/usr/lib/python3.10/site-packages"
DEBUG    2022-05-15 16:53:46,880 [command.start:141]:LUTRIS_GAME_UUID="6ed964c0-d747-4f78-8ef7-1c5a3df33b70"
Started initial process 9294 from /usr/bin/xterm -e /home/andrew2/.cache/lutris/run_in_term.sh
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2022-05-15 16:53:51,962 [command.on_stop:195]:Process 9291 has terminated with code 0
DEBUG    2022-05-15 16:53:54,900 [game.beat:664]:Game thread stopped
WARNING  2022-05-15 16:53:54,901 [game.on_game_quit:690]:Game still running (state: running)
INFO     2022-05-15 16:53:54,901 [game.stop:675]:Stopping God of War (wine)
DEBUG    2022-05-15 16:53:54,902 [game.stop_game:628]:God of War (wine) has run for 8 seconds
DEBUG    2022-05-15 16:53:54,956 [game.on_game_quit:708]:God of War stopped at Sun, 15 May 2022 16:53:54
DEBUG    2022-05-15 16:53:54,956 [game.save:268]:Saving God of War (wine) with config ID god-of-war-1650691434`

`ERROR    2022-05-15 16:54:53,516 [wine.get_overrides_env:441]:Invalid override value /run/media/andrew/Seagate2/Ghostwire.Tokyo.Steam.Rip/GhostwireTokyo/dxvk.conf
ERROR    2022-05-15 16:54:53,516 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:54:53,516 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:54:53,516 [wine.get_overrides_env:441]:Invalid override value /home/andrew2/.GWT/
ERROR    2022-05-15 16:54:53,516 [wine.get_overrides_env:441]:Invalid override value dxr
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

ERROR    2022-05-15 16:54:53,559 [wine.get_overrides_env:441]:Invalid override value /run/media/andrew/Seagate2/Ghostwire.Tokyo.Steam.Rip/GhostwireTokyo/dxvk.conf
ERROR    2022-05-15 16:54:53,559 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:54:53,559 [wine.get_overrides_env:441]:Invalid override value 1
ERROR    2022-05-15 16:54:53,559 [wine.get_overrides_env:441]:Invalid override value /home/andrew2/.GWT/
ERROR    2022-05-15 16:54:53,559 [wine.get_overrides_env:441]:Invalid override value dxr
DEBUG    2022-05-15 16:54:53,559 [xrandr._get_vidmodes:15]:Retrieving video modes from XrandR
WARNING  2022-05-15 16:54:53,804 [game.start_prelaunch_command:374]:Command /run/media/andrew/Seagate not found
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:MANGOHUD="1"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:MANGOHUD_DLSYM="1"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/run/media/andrew/Seagate 2/Ghostwire.Tokyo.Steam.Rip/Ghostwire Tokyo"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:DRI_PRIME="1"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:LD_LIBRARY_PATH="/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/lib:/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/lib64:/usr/lib:/usr/lib32:/usr/lib/openmpi:/usr/lib/libfakeroot:/usr/lib64:/home/andrew2/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/andrew2/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/andrew2/.local/share/lutris/runtime/steam/i386/lib:/home/andrew2/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/andrew2/.local/share/lutris/runtime/steam/i386/usr/lib:/home/andrew2/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/andrew2/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/andrew2/.local/share/lutris/runtime/steam/amd64/lib:/home/andrew2/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/andrew2/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:DXVK_CONFIG_FILE="/run/media/andrew/Seagate 2/Ghostwire.Tokyo.Steam.Rip/Ghostwire Tokyo/dxvk.conf"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2022-05-15 16:54:53,805 [command.start:141]:STEAM_COMPAT_DATA_PATH="/home/andrew2/.GWT/"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:VKD3D_CONFIG="dxr"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINEDEBUG="-all"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINEARCH="win64"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINE="/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/wine"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINE_MONO_CACHE_DIR="/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/mono"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/gecko"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/lib64/gstreamer-1.0/:/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/lib/gstreamer-1.0/"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINEPREFIX="/home/andrew2/.GWT/"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINEESYNC="1"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINEFSYNC="1"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:game_name="Ghostwire Tokyo"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/home/andrew2/.local/lib/python3.10/site-packages:/usr/lib/python3.10/site-packages"
DEBUG    2022-05-15 16:54:53,806 [command.start:141]:LUTRIS_GAME_UUID="0c2835d5-b733-40ea-9e6b-e3e261d4c558"
Started initial process 9813 from gamemoderun gamemoderun mangohud /home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/wine /run/media/andrew/Seagate 2/Ghostwire.Tokyo.Steam.Rip/Ghostwire Tokyo/GWT.exe
Start monitoring process.
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
gamemodeauto: 
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
gamemodeauto: 
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
[2022-05-15 16:54:54.064] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine-explorer.conf' [ not found ]
[2022-05-15 16:54:54.064] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/MangoHud.conf' [ not found ]
[2022-05-15 16:54:54.064] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2022-05-15 16:54:54.064] [MANGOHUD] [info] [config.cpp:117] parsing config: '/home/andrew2/.config/MangoHud/MangoHud.conf'
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
[2022-05-15 16:54:54.305] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine-explorer.conf' [ not found ]
[2022-05-15 16:54:54.305] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/MangoHud.conf' [ not found ]
[2022-05-15 16:54:54.305] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2022-05-15 16:54:54.305] [MANGOHUD] [info] [config.cpp:117] parsing config: '/home/andrew2/.config/MangoHud/MangoHud.conf'
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
[2022-05-15 16:54:54.528] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine-explorer.conf' [ not found ]
[2022-05-15 16:54:54.528] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/MangoHud.conf' [ not found ]
[2022-05-15 16:54:54.528] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2022-05-15 16:54:54.528] [MANGOHUD] [info] [config.cpp:117] parsing config: '/home/andrew2/.config/MangoHud/MangoHud.conf'
[2022-05-15 16:54:54.540] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine-explorer.conf' [ not found ]
[2022-05-15 16:54:54.540] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/MangoHud.conf' [ not found ]
[2022-05-15 16:54:54.540] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2022-05-15 16:54:54.540] [MANGOHUD] [info] [config.cpp:117] parsing config: '/home/andrew2/.config/MangoHud/MangoHud.conf'
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
[2022-05-15 16:54:54.730] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine-explorer.conf' [ not found ]
[2022-05-15 16:54:54.730] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/MangoHud.conf' [ not found ]
[2022-05-15 16:54:54.730] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2022-05-15 16:54:54.730] [MANGOHUD] [info] [config.cpp:117] parsing config: '/home/andrew2/.config/MangoHud/MangoHud.conf'
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
[2022-05-15 16:54:54.945] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine-explorer.conf' [ not found ]
[2022-05-15 16:54:54.945] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/MangoHud.conf' [ not found ]
[2022-05-15 16:54:54.945] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2022-05-15 16:54:54.945] [MANGOHUD] [info] [config.cpp:117] parsing config: '/home/andrew2/.config/MangoHud/MangoHud.conf'
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
[2022-05-15 16:54:56.443] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine-GWT.conf' [ not found ]
[2022-05-15 16:54:56.443] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/MangoHud.conf' [ not found ]
[2022-05-15 16:54:56.443] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2022-05-15 16:54:56.443] [MANGOHUD] [info] [config.cpp:117] parsing config: '/home/andrew2/.config/MangoHud/MangoHud.conf'
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
WINE VERSION = wine-5.12-14211-gbb0a68d2993 (Staging)

0100:info:vkd3d_config_flags_init_once: VKD3D_CONFIG='dxr'.
0100:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.6.0.
0100:info:vkd3d_instance_init: vkd3d-proton - build: 3e5aab6fb3e18f8.
[2022-05-15 16:54:56.549] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine-GWT.conf' [ not found ]
[2022-05-15 16:54:56.549] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.local/share/lutris/runners/wine/lutris-GE-Proton7-10-x86_64/bin/MangoHud.conf' [ not found ]
[2022-05-15 16:54:56.549] [MANGOHUD] [info] [config.cpp:112] skipping config: '/home/andrew2/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2022-05-15 16:54:56.549] [MANGOHUD] [info] [config.cpp:117] parsing config: '/home/andrew2/.config/MangoHud/MangoHud.conf'
libGL error: failed to create dri screen
libGL error: failed to load driver: nouveau
WINE VERSION = wine-5.12-14211-gbb0a68d2993 (Staging)

0100:err:vkd3d_create_vk_device: Failed to create Vulkan device, vr -3.
0100:fixme:hresult_from_vk_result: Unhandled VkResult -3.
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
DEBUG    2022-05-15 16:54:58,178 [command.on_stop:195]:Process 9810 has terminated with code 0
DEBUG    2022-05-15 16:54:59,820 [game.beat:664]:Game thread stopped
WARNING  2022-05-15 16:54:59,820 [game.on_game_quit:690]:Game still running (state: running)
INFO     2022-05-15 16:54:59,821 [game.stop:675]:Stopping Ghostwire Tokyo (wine)
DEBUG    2022-05-15 16:54:59,821 [game.stop_game:628]:Ghostwire Tokyo (wine) has run for 6 seconds
DEBUG    2022-05-15 16:54:59,832 [game.on_game_quit:708]:Ghostwire Tokyo stopped at Sun, 15 May 2022 16:54:59
DEBUG    2022-05-15 16:54:59,832 [game.save:268]:Saving Ghostwire Tokyo (wine) with config ID ghostwire-tokyo-1650697926`
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.17.7-arch1-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             23.3 GB
Swap:            16.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.0.3
OpenGL Core:     4.6 (Core Profile) Mesa 22.0.3
OpenGL ES:       OpenGL ES 3.2 Mesa 22.0.3
Vulkan:          Supported
```

### Media (optional)

![image](https://user-images.githubusercontent.com/90151527/168493180-23140829-c7c3-4ba2-b4d0-20197ae5a429.png)

![image](https://user-images.githubusercontent.com/90151527/168493274-f61218fd-ea42-407f-bce6-32a663aed4f5.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment] 2022-05-17 06:08
first don't use CLI mode, this is for ascii games.
also, if the game is not detecting DX12 then it's likely selecting the driver update changed something in the handling of Optimus.

**Comment by mercifulboss** [comment] 2022-05-17 06:19
> first don't use CLI mode, this is for ascii games. also, if the game is not detecting DX12 then it's likely selecting the driver update changed something in the handling of Optimus.

Thank you for your reply!

The game is not detecting DX12 until steam is launched. If steam is launched (without launching any games), then DX12 is once again detected. Is this a Optimus handling issue?

**Comment by strycore** [comment] 2022-05-17 07:24
Maybe there is something that Steam does and Lutris doesn't that makes the game run on the Nvidia GPU.

**Comment by gilmorem560** [comment] 2023-02-10 02:13
Just bouncing some info over here as it may or may not be related, but it smells of some of the same stuff. Over in #4287, one of the potential root causes of a discrepancy between launching via CLI and launching via desktop mechanisms in a great variety of applications is environment variables.

In the case of the referenced ticket, one of the culprits is not having XDG_DATA_DIR defined. Some shells and launching environments will provide XDG paths by convention, others won't. Can't entirely say that's what is happening here, but you might investigate, if you can, what environment variables are present in your shell (via export) vs available in the environment launching the application. For the latter, you may have to peek into documentation from your distro and/or desktop environment.

Of course, no guarantees this is what you're seeing, but typically environment variables are implicated in discrepancies between launching from different places on the same machine.

**Comment by Milor123** [comment] 2023-08-20 18:02
I have the same problem with AMD RX6750, i try reinstall all my drivers but some games like Insurgency sandstorm or Remnat 2 shows Directx12 error dont support. What should I do guys? 
 I am in ubuntu 22.04

**Comment by strycore** [comment] 2024-01-16 05:54
Closing this since it is quite outdated.

The most common cause of having DirectX 12 not supported errors is the Wine prefix not being set to Windows 10. 
In some cases, it might be preferred to recreate the Wine prefix. I could not get rid of the DirectX 12 not supported error for Avatar Frontiers of Pandora until I installed Ubisoft Connect in a new prefix.

**Closed by strycore** 2024-01-16 05:54 UTC
Labels: open to community
