### ISSUE TITLE
Lutris doen't support python 3.10+

### ISSUE THREAD

**Issue by kacperpaczos** [lutris/lutris#4887] opened 2023-06-03 18:30 UTC
### Bug description

After update of my system, i can't run lutris.

### How to Reproduce

Install Lutris from deb or flathub. Uubntu 22.04/Linux Mint 21 should be updated.

### Expected behavior

Lutris should start.

### Log output

```shell
Gtk-Message: 19:50:17.655: Failed to load module "xapp-gtk3-module"
2023-06-03 19:50:21,011: Command /app/bin/lspci after 3 seconds
Traceback (most recent call last):
  File "/app/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/app/lib/python3.10/site-packages/lutris/gui/application.py", line 44, in <module>
    from lutris.gui.installerwindow import InstallerWindow, InstallationKind
  File "/app/lib/python3.10/site-packages/lutris/gui/installerwindow.py", line 19, in <module>
    from lutris.installer import InstallationKind, get_installers, interpreter
  File "/app/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/app/lib/python3.10/site-packages/lutris/installer/installer.py", line 14, in <module>
    from lutris.services import SERVICES
  File "/app/lib/python3.10/site-packages/lutris/services/__init__.py", line 6, in <module>
    from lutris.services.battlenet import BNET_ENABLED, BattleNetService
  File "/app/lib/python3.10/site-packages/lutris/services/battlenet.py", line 19, in <module>
    from lutris.util.battlenet.product_db_pb2 import ProductDb
  File "/app/lib/python3.10/site-packages/lutris/util/battlenet/product_db_pb2.py", line 10, in <module>
    from google.protobuf import reflection as _reflection
  File "/home/pyroxar/.local/lib/python3.10/site-packages/google/protobuf/reflection.py", line 58, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/home/pyroxar/.local/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 69, in <module>
    from google.protobuf.internal import containers
  File "/home/pyroxar/.local/lib/python3.10/site-packages/google/protobuf/internal/containers.py", line 182, in <module>
    MutableMapping = collections.MutableMapping
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

### System Information

```shell
I use Linux Mint 21.x/Ubuntu 22.04.
More system info here: https://termbin.com/mltkw
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment] 2023-06-03 23:14
I can assure you Lutris supports Python 3.10.
Looks like there is an issue with Protobuf, likely caused by the fact we're still stuck an old version of protobuf.

This is also going to be a problem on Arch.

@kacperpaczos if you want a quick workaround, uninstall the python-protobuf package from your distro and install protobuf with pip:

`pip install protobuf==3.20.3`

@danieljohnson2 @telanus do you see what I mean when I say "not everything the user says is true"?

**Comment by Kandelai** [comment] 2023-06-08 15:27
I can confirm from the latest stable Arch updates, this is an issue. Neither Lutris stable or git version will start.

> $ lutris
2023-06-08 08:26:15,933: Starting Lutris 0.5.13
2023-06-08 08:26:15,935: Running AMD Mesa driver 23.1.1 on AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.3.6-zen1-1-zen) (0x73df)
2023-06-08 08:26:15,935: GPU: 1002:73DF 148C:2310 (amdgpu drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 40, in get_installed_apps
    name, appid, version, branch, origin, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 6, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 291, in do_activate
    self.window = LutrisWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 123, in __init__
    self.sidebar.initialize_rows()
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
    self.update_rows()
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
    self.installed_runners = [runner.name for runner in runners.get_installed()]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 102, in get_installed
    if runner.is_installed():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 476, in is_installed
    return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 60, in is_app_installed
    for app in get_installed_apps():
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 43, in get_installed_apps
    name, appid, version, branch, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 1)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 657, in do_command_line
    self.window.present()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'

**Comment by danieljohnson2** [comment] 2023-06-09 08:48
@Kandelai, that looks like an entirely different issue. You should post it as its own issue.

When you do, maybe you can include the output of this command:
```
flatpak list > list.txt
```
That will create a file 'list.txt', and I'd like to see the content of that file. It looks like it's not what Lutris is expecting it to be.

**Comment by Kandelai** [comment] 2023-06-09 19:43
@danieljohnson2 Hi Daniel, it is not a flatpak though. I don't even use flatpacks. I am on Arch/Garuda Linux, tried both stable version in Arch and git version in AUR, both the same issue.

**Comment by strycore** [comment] 2023-06-09 23:06
Ok, I just want to make something very clear. The amount of bugs that were caused by a version of Python over the course of the project is very close to zero.
There is no "Python 3.10" issue or "Python 3.11" issue. Not in Lutris, not anywhere else. 
Programming bugs and oversights are not "Python issues". 

At this point, I just wish users could refrain making any type of diagnosis, post their crash logs and be done with it because this can confuse Lutris contributors.

Now, I think @danieljohnson2 pushed a fix for that crash so it should be all good.

**Closed by strycore** 2023-06-09 23:06 UTC

**Comment by danieljohnson2** [comment] 2023-06-09 23:09
I hope so.

Until the next Lutris comes out, there's a workaround- install any flatpak. Lutris bugs out if there are none at all.
