### ISSUE TITLE
Getting error : ValueError("invalid literal for int() with base 10: ''") when trying to download any game

### ISSUE THREAD

**Issue by Inveritus** [lutris/lutris#4218] opened 2022-04-14 01:12 UTC
### Bug description

Lutris is not allowing me to install any game. It seems like a python dependency but I cannot seem to figure out with dependency it is. Installed lutris through dnf on Fedora 35

Gives error: ValueError("invalid literal for int() with base 10: ''")  when trying to install any game.

### How to Reproduce

1. Go to download any game
2. Click on Install
3. See ValueError("invalid literal for int() with base 10: ''") 

### Expected behavior

Game should install.

### Log output

```shell
INFO 2022-04-13 13:10:17,716 [startup.init_lutris:173]:Starting Lutris 0.5.10WARNING

2022-04-13 13:10:17,731 [libretro.get_libretro_cores:24]:No folder at /home/veri/.local/share/lutris/runners/retroarch/INFO

2022-04-13 13:10:17,748 [startup.check_driver:57]:Using NVIDIA drivers 510.60.02 for x86_64INFO

2022-04-13 13:10:17,748 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 3060 Laptop GPUINFO

2022-04-13 13:10:17,748 [startup.check_driver:77]:GPU: 10DE:2560 17AA:3801 (nvidia drivers)INFO 2022-04-13 13:10:17,748 [startup.check_driver:77]:GPU: 1002:1638 17AA:380C (amdgpu drivers)INFO

2022-04-13 13:10:17,821 [startup.update_runtime:213]:Startup complete


DEBUG

2022-04-13 13:10:17,879 [lutriswindow.update_store:437]:Showing 0 games

2022-04-13 13:10:49,992: Starting Lutris 0.5.10

2022-04-13 13:10:50,005: Using NVIDIA drivers 510.60.02 for x86_64

2022-04-13 13:10:50,005: GPU: NVIDIA GeForce RTX 3060 Laptop GPU

2022-04-13 13:10:50,005: GPU: 10DE:2560 17AA:3801 (nvidia drivers)

2022-04-13 13:10:50,005: GPU: 1002:1638 17AA:380C (amdgpu drivers)

2022-04-13 13:10:50,052: Startup complete

2022-04-13 13:10:50,054: Fetching installer https://lutris.net/api/installers/final-fantasy-xiv-online-xivlauncher

2022-04-13 13:10:50,054: GET https://lutris.net/api/installers/final-fantasy-xiv-online-xivlauncher

2022-04-13 13:10:50,316: Showing window InstallerWindowfinal-fantasy-xiv-online

2022-04-13 13:10:52,934: Retrieving current resolution

2022-04-13 13:10:52,934: Could not retrieve the current display mode

2022-04-13 13:11:01,331: Checking if service provide extra files

2022-04-13 13:11:01,332: No service to retrieve files from

2022-04-13 13:11:02,592: ⬇ https://kamori.goats.dev/Proxy/Update/Release/Setup.exe

2022-04-13 13:11:03,631: Finished downloading https://kamori.goats.dev/Proxy/Update/Release/Setup.exe

2022-04-13 13:11:04,095: Download completed

2022-04-13 13:11:04,095: launchersetup is available

2022-04-13 13:11:04,095: All files available

2022-04-13 13:11:04,095: All files are available, continuing install

2022-04-13 13:11:04,096: Installer command: {'task': {'arch': 'win64', 'install_gecko': False, 'install_mono': False, 'name': 'create_prefix', 'prefix': '$GAMEDIR'}}

2022-04-13 13:11:04,104: Error while completing task <bound method CommandsMixin.task of <interpreter.ScriptInterpreter object at 0x7fa4d83aa540 (lutris+installer+interpreter+ScriptInterpreter at 0x561dec5156c0)>>: <class 'ValueError'> invalid literal for int() with base 10: '' File "/usr/lib/python3.10/site-packages/lutris/util/jobs.py", line 34, in target result = self.function(*args, **kwargs) File "/usr/lib/python3.10/site-packages/lutris/installer/commands.py", line 432, in task value = self._substitute(data[key]) File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 420, in _substitute return system.substitute(template_string, self._get_string_replacements()) File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 400, in _get_string_replacements "RESOLUTION_WIDTH_HEX": hex(int(self.current_resolution[0])),

2022-04-13 13:11:04,105: Last install command failed, show error

2022-04-13 13:11:18,402: Cancelling installation of FINAL FANTASY XIV OnlineTraceback (most recent call last): File "/usr/lib/python3.10/site-packages/lutris/gui/installerwindow.py", line 525, in on_destroy if self.confirm_cancel(): File "/usr/lib/python3.10/site-packages/lutris/gui/installerwindow.py", line 571, in confirm_cancel self.interpreter.revert(remove_game_dir=remove_checkbox.get_active()) File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 376, in revert self.task({"name": "winekill"}) File "/usr/lib/python3.10/site-packages/lutris/installer/commands.py", line 432, in task value = self._substitute(data[key]) File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 420, in _substitute return system.substitute(template_string, self._get_string_replacements()) File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 400, in _get_string_replacements "RESOLUTION_WIDTH_HEX": hex(int(self.current_resolution[0])),ValueError: invalid literal for int() with base 10:

''2022-04-13 13:11:18,431: Removed window InstallerWindowfinal-fantasy-xiv-online
```

### System Information

```shell
[System]
OS:              Fedora Linux 35 
Arch:            x86_64
Kernel:          5.16.18-200.fc35.x86_64
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800H with Radeon Graphics
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             38.6 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD RENOIR (DRM 3.44.0, 5.16.18-200.fc35.x86_64, LLVM 13.0.0)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.3.8
OpenGL Core:     4.6 (Core Profile) Mesa 21.3.8
OpenGL ES:       OpenGL ES 3.2 Mesa 21.3.8
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment] 2022-04-14 08:22
I see it; your system has either DBUS nor the GnomeDesktop library, so Python falls back on a LegacyDisplayManger class that isn't much good. It tries to run xrandr but for some reason finds no resolution in this output. I don't know why that is; perhaps you could post the output of running "xrandr"?

Anyway, in this case Lutris has no resolution and represents this as a resolution of "" by "" which is a bit odd, but in most places this results in "x" turning up here and there, which probably doesn't work but can be overridden.

However, the new string-replacements (for installers) for resolution blows up trying to convert "" to a hex form. It needs to defect against this input or you crash with no recourse. I'll put something together.

**Comment by Inveritus** [comment] 2022-04-14 14:03
[veri@fedora ~]$ xrandr
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
eDP connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1920x1080    165.01*+
   1680x1050    165.01  
   1280x1024    165.01  
   1440x900     165.01  
   1280x800     165.01  
   1280x720     165.01  
   1024x768     165.01  
   800x600      165.01  
   640x480      165.01  
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-1 disconnected (normal left inverted right x axis y axis)
DP-1-0.1 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 + 143.85   119.88   100.00    84.62    60.00    59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x720      59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-1-0.2 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 + 143.85   119.88   100.00    84.62    60.00    59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x720      59.94    50.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94    59.93  
DP-1-0 disconnected (normal left inverted right x axis y axis)
DP-1-1 disconnected (normal left inverted right x axis y axis)
DP-1-2 disconnected (normal left inverted right x axis y axis)
DP-1-3 disconnected (normal left inverted right x axis y axis)
DP-1-4 disconnected (normal left inverted right x axis y axis)

**Comment by Inveritus** [comment] 2022-04-14 15:19
So I ended up switch from Gnome to KDE and everything seems to be working now for some reason

**Comment by cryptic3481** [comment] 2022-04-14 21:37
I'm having this exact issue with an installation of League of Legends. I haven't tried any other installations yet. I keep getting the same error. I've used terminal via lutris -d to read the output;

2022-04-14 16:30:11,972: Error while completing task <bound method CommandsMixin.input_menu of <interpreter.ScriptInterpreter object at 0x7f1e5c709ec0 (lutris+installer+interpreter+ScriptInterpreter at 0x5643fda1a820)>>: <class 'ValueError'> invalid literal for int() with base 10: ''
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 208, in input_menu
    preselect = self._substitute(data.get("preselect", ""))
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 420, in _substitute
    return system.substitute(template_string, self._get_string_replacements())
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 400, in _get_string_replacements
    "RESOLUTION_WIDTH_HEX": hex(int(self.current_resolution[0])),


I'm running Pop! OS 22.04 beta. Not sure what I should do to resolve this issue. Any help would be appreciated.

**Comment by danieljohnson2** [comment] 2022-04-14 21:48
I think there is to be a point release soon, and I'm trying to get a fix for this into it. Could you post the output of 'xrandr' for you?

The underlying issue seems to be that Lutris can't interpret this properly for some reason. A second sample of 'bad xrandr' output might help me figure this out.

**Comment by danieljohnson2** [comment] 2022-04-14 22:31
OK, I've done some testing using the xrandr output from @Inveritus, and I've updated my PR to tweak the xrandr code in Lutris to be more tolerant, and also  make it de-duplicate resolutions, as all the other display managers do.

As far as I can tell, the only reason it doesn't read that is that the resolution lines do not start with two spaces; Lutris is expecting that they should. If I add spaces, Lutris can read that data.

My tweaked version no longer requires the spaces; it allows leading white-space, but instead checks to see if the resolution is the first non-white-space thing on the line.

*But* I have a nasty feeling that your xrandr output actually *did* contain those initial spaces before the resolutions, and GitHub's markdown implementation stripped them. If that's right, the real problem remains a mystery.

Maybe @cryptic3481 can provide xrandr output that will shed light on this.

**Comment by strycore** [comment] 2022-04-15 06:32
> But I have a nasty feeling that your xrandr output actually did contain those initial spaces before the resolutions, and GitHub's markdown implementation stripped them. 

That's correct, the xrandr output isn't in a code block. As such we shouldn't have code that parses output that xrandr can't produce.

> also make it de-duplicate resolutions, as all the other display managers do.

that's been an issue so it's good to see it resolved. Those duplicates are cause by other monitors so ideally, we would only get the resolutions of the primary monitor which shouldn't contain duplicates.

> I expect KDE is providing DBUS so that it no longer tries to use xrandr.

The only support for a DBus backend interface we have is with Mutter, that's also the only backend we have for Wayland. I don't know if there is something to get the list of resolutions in KDE/Wayland now but there wasn't one when I coded the Mutter backend.

**Comment by danieljohnson2** [comment] 2022-04-15 08:48
Hmm. That's... *unconventional*. I think xrandr is a case for "Be liberal in what you accept, and conservative in what you send" 

I tried to find some documentation or a spec for what xrandr produces, and found nothing. Do you know where I can find that? Maybe I could see where the parse went wrong that way.

Or maybe @cryptic3481 can provide a clue as well. We'll see what transpires.

At this point I have no alternative scheme here, so I'll leave it until I get some new information.

**Closed** 2022-04-16 23:47 UTC
Labels: needs triage

**Comment by Benehiko** [comment] 2022-04-17 16:43
This still seems to be a problem on the latest commit on master d2e1715839f2334b75817904cdf79593c5e0b722

```shell
➜  lutris git:(master) python3 ./bin/lutris -d
INFO     2022-04-17 18:35:14,901 [startup.init_lutris:173]:Starting Lutris 0.5.10
WARNING  2022-04-17 18:35:14,941 [libretro.get_libretro_cores:24]:No folder at /home/benehiko/.local/share/lutris/runners/retroarch/
INFO     2022-04-17 18:35:14,970 [startup.check_driver:57]:Using NVIDIA drivers 510.54 for x86_64
INFO     2022-04-17 18:35:14,970 [startup.check_driver:61]:GPU: Unknown
INFO     2022-04-17 18:35:14,970 [startup.check_driver:77]:GPU: 10DE:2489 1462:3903 (nvidia drivers)
INFO     2022-04-17 18:35:15,096 [startup.update_runtime:213]:Startup complete
DEBUG    2022-04-17 18:35:15,187 [lutriswindow.update_store:437]:Showing 0 games
DEBUG    2022-04-17 18:35:18,284 [application.show_window:332]:Showing window AddGamesWindow{}
DEBUG    2022-04-17 18:35:24,146 [http.get:83]:GET https://lutris.net/api/games?search=league+of+le&with-installers=True
DEBUG    2022-04-17 18:35:25,152 [http.get:83]:GET https://lutris.net/api/games?search=league+of+legends&with-installers=True
DEBUG    2022-04-17 18:35:26,878 [api.get_game_installers:160]:Fetching installer https://lutris.net/api/installers/league-of-legends
DEBUG    2022-04-17 18:35:26,879 [http.get:83]:GET https://lutris.net/api/installers/league-of-legends
DEBUG    2022-04-17 18:35:27,048 [application.show_window:332]:Showing window InstallerWindowleague-of-legends
DEBUG    2022-04-17 18:35:27,048 [application.on_app_window_destroyed:350]:Removed window AddGamesWindow{}
DEBUG    2022-04-17 18:35:28,622 [displayconfig.get_current_resolution:624]:Retrieving current resolution
ERROR    2022-04-17 18:35:28,623 [displayconfig.get_current_resolution:627]:Could not retrieve the current display mode
DEBUG    2022-04-17 18:35:30,217 [interpreter.get_extras:159]:Checking if service provide extra files
DEBUG    2022-04-17 18:35:30,218 [installer.prepare_game_files:146]:No service to retrieve files from
DEBUG    2022-04-17 18:35:31,996 [downloader.start:65]:⬇ https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe
DEBUG    2022-04-17 18:35:31,999 [downloader.start:65]:⬇ https://lutris.nyc3.digitaloceanspaces.com/games/league-of-legend/launchhelper.sh
DEBUG    2022-04-17 18:35:32,002 [downloader.start:65]:⬇ https://lutris.nyc3.digitaloceanspaces.com/games/league-of-legend/syscall_check.sh
DEBUG    2022-04-17 18:35:32,287 [downloader.download_cb:125]:Finished downloading https://lutris.nyc3.digitaloceanspaces.com/games/league-of-legend/syscall_check.sh
DEBUG    2022-04-17 18:35:32,292 [downloader.download_cb:125]:Finished downloading https://lutris.nyc3.digitaloceanspaces.com/games/league-of-legend/launchhelper.sh
INFO     2022-04-17 18:35:32,501 [file_box.on_download_complete:252]:Download completed
DEBUG    2022-04-17 18:35:32,501 [files_box.on_file_available:93]:script1 is available
INFO     2022-04-17 18:35:32,503 [file_box.on_download_complete:252]:Download completed
DEBUG    2022-04-17 18:35:32,504 [files_box.on_file_available:93]:script2 is available
DEBUG    2022-04-17 18:35:36,219 [downloader.download_cb:125]:Finished downloading https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe
INFO     2022-04-17 18:35:36,503 [file_box.on_download_complete:252]:Download completed
DEBUG    2022-04-17 18:35:36,503 [files_box.on_file_available:93]:lol_installer is available
INFO     2022-04-17 18:35:36,503 [files_box.on_file_available:99]:All files available
INFO     2022-04-17 18:35:36,503 [installerwindow.on_files_available:463]:All files are available, continuing install
DEBUG    2022-04-17 18:35:36,505 [interpreter._iter_commands:317]:Installer command: {'input_menu': {'id': 'LOCALE', 'options': [{'cs_CZ': 'Čeština'}, {'en_AU': 'English AUS'}, {'en_GB': 'English U.K.'}, {'en_US': 'English U.S.'}, {'fr_FR': 'Français'}, {'de_DE': 'Deutsch'}, {'es_ES': 'Español'}, {'es_MX': 'Español Mexicano'}, {'it_IT': 'Italiano'}, {'ja_JP': '日本語'}, {'hu_HU': 'Magyar'}, {'pl_PL': 'Polski'}, {'pt_BR': 'Português do Brasil'}, {'ro_RO': 'Romanian'}, {'ru_RU': 'русский'}, {'tr_TR': 'Türkçe'}], 'preselect': 'en_US'}}
ERROR    2022-04-17 18:35:36,506 [jobs.target:36]:Error while completing task <bound method CommandsMixin.input_menu of <interpreter.ScriptInterpreter object at 0x7f7e5a883040 (lutris+installer+interpreter+ScriptInterpreter at 0x15c24c0)>>: <class 'ValueError'> invalid literal for int() with base 10: ''
  File "/home/benehiko/Downloads/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/home/benehiko/Downloads/lutris/lutris/installer/commands.py", line 208, in input_menu
    preselect = self._substitute(data.get("preselect", ""))
  File "/home/benehiko/Downloads/lutris/lutris/installer/interpreter.py", line 420, in _substitute
    return system.substitute(template_string, self._get_string_replacements())
  File "/home/benehiko/Downloads/lutris/lutris/installer/interpreter.py", line 400, in _get_string_replacements
    "RESOLUTION_WIDTH_HEX": hex(int(self.current_resolution[0])),
ERROR    2022-04-17 18:35:36,507 [interpreter._iter_commands:302]:Last install command failed, show error
```

--- 

System information:

```shell
➜  ~ screenfetch
                          ./+o+-       benehiko@benehiko
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.13.0-39-generic
           .++ .:/++++++/-.+sss/`      Uptime: 9d 30m
         .:++o:  /++++++++/:--:/-      Packages: 2006
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.8
       .:+o:+o/.          `+sssoo+/    Disk: 265G / 1,9T (15%)
  .++/+:+oo+o:`             /sssooo.   CPU: AMD Ryzen Threadripper 3970X 32-Core @ 64x 3,7GHz
 /+++//+:`oo+o               /::--:.   GPU: NVIDIA GeForce RTX 3060 Ti
 \+/+o+++`o++o               ++////.   RAM: 18283MiB / 128665MiB
  .++.o+++oo+:`             /dddhhh.  
       .+.o+oo:.          `oddhhhh+   
        \+.++o+o``-````.:ohdhhhhh+    
         `:o+++ `ohhhhhhhhyo++os:     
           .o:`.syhhhhhhh/.oo++o`     
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++.      
➜  ~ 
```

```shell
➜  ~ xrandr 
Screen 0: minimum 8 x 8, current 2560 x 1440, maximum 32767 x 32767
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 connected (normal left inverted right x axis y axis)
   3840x2160     60.00 +  30.00  
   2560x1440     59.95  
   1920x1080     60.00    59.94  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94  
   1152x864      59.96  
   1024x768      60.00  
   800x600       60.32  
   720x480       59.94  
   640x480       59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     60.00 +  30.00  
   2560x1440     59.95* 
   1920x1080     60.00    59.94  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94  
   1152x864      59.96  
   1024x768      60.00  
   800x600       60.32  
   720x480       59.94  
   640x480       59.94    59.93  
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
```

**Comment by danieljohnson2** [comment] 2022-04-17 17:16
I think you aren't actually using xrandr. That "Could not retrieve the current display mode" message comes from MutterDisplayManager.

Maybe it too should return a fake resolution in this case. But I do not understand why it does not recognize your current resolution.

My immediate guess is that you have a multiple-monitor setup, and Lutris is not handling this right. It appears to try to get the resolution of the first monitor; your xrandr seems to show that your primary monitor is the second (or third?).

To test this, perhaps you could make your other monitor primary and see if Lutris likes that better?

**Comment by Benehiko** [comment] 2022-04-18 10:22
Yeah it seems like lutris doesn't work when using multiple monitors. Strangely enough it also doesn't work when only the screen is enabled on DP-2, but works on DP-0.

![image](https://user-images.githubusercontent.com/18033717/163794707-c3ae0b6a-071b-4d92-8a43-39ea64f5bb73.png)

**Comment by danieljohnson2** [comment] 2022-04-18 20:53
I thought it might be like that; the code just uses monitors[0] all over. I think it should use the primary monitor, but this DBUS code is obscure to me and I haven't found the documentation yet, so I'm not at all sure how to actually do this.

**Comment by danieljohnson2** [comment] 2022-04-18 22:10
I've been poking around but I don't have multiple monitors. @Benehiko, can you try out a branch I am working on? It's

[Monitoring the Monitors](https://github.com/danieljohnson2/lutris/tree/dj/monitoring_the_monitors)

This tries to make the MutterDisplayManager choose its one-true-monitor consistently. It will no longer sometimes pick the first monitor on the list, and sometimes look for the primary monitor. Instead, it picks the first physical monitor attached to the primary logical monitor.

I don't really know what all those words *mean*, exactly, but generally consistency works better.

My hope is that this branch will now pay attention to your selection of primary monitor, and by using the current-mode of that monitor, it will find an actual resolution.

**Comment by strycore** [comment] 2022-04-19 01:00
Don't go looking too much for documentation as you won't find any. The current MutterDisplayManager is adapted from some script I found on reddit. The whole display management in Mutter / Gnome / Wayland is really obscure and undocumented.
It's handled by this library called libgnomedesktop, which confuses everyone and is really support to be sorta private to Gnome itself.

I've said it before, but the future is Gamescope. I know it's not ready yet, but the concept of Linux applications having easy access to display configurations is over. The framework currently in place wants apps to be adaptive, responsive and unaware of the environment they run in.

The release of 22.04 based distros is imminent, which will increase availability of gamescope. That said, fixes to the MutterDisplayManager are still welcome. I'm aware that there are some places in the code that read information for the monitor with index 0 which causes issues in multi monitor.

**Comment by danieljohnson2** [comment] 2022-04-19 08:26
Heavens to Betsy!

At least it didn't come from stackoverflow.com.

I hope we can get somebody with a multi-monitor setup to test that branch I referenced; that should be checking the primary monitor, and that *should* be better. But I can't really test it properly, so I don't want to pop a PR for it yet.

**Comment by Benehiko** [comment] 2022-04-19 11:18
Hi @danieljohnson2 
I will test it out a bit later today :)

**Comment by danieljohnson2** [comment] 2022-04-19 12:19
Thank you!

**Comment by Benehiko** [comment] 2022-04-19 17:48
@danieljohnson2 your branch (https://github.com/danieljohnson2/lutris/tree/dj/monitoring_the_monitors) seems to be working as expected. I could reproduce the problem lutris has with this setup (only 1 monitor is being used but it is on a DP port other than 0).

![image](https://user-images.githubusercontent.com/18033717/164064332-dd8d776e-4280-498f-8c52-77e8756a8761.png)

**Comment by danieljohnson2** [comment] 2022-04-19 20:26
Maybe I should ask what you expected! It looks like there's still a warning there, but it's something else. I'll go ahead an pop a PR.

**Comment by alec-lefors** [comment] 2022-05-01 04:18
Hi, just popping in here from this [Reddit post](https://www.reddit.com/r/Lutris/comments/u2twk9/comment/i5hs7nc/?utm_source=share&utm_medium=web2x&context=3) to say this fix worked for me!

**Comment by Grzanka99** [comment] 2022-05-20 22:34
So I still have same issue with lutris 0.5.10.1 but... only if I disabled second screen. When I enabled second monitor, everything started to work properly. It looks like some weird issue that requires from me to gave both connected monitors enabled or smth?

**Comment by danieljohnson2** [comment] 2022-05-20 23:14
That sounds like this issue; Lutris may have been trying to read the resolution information for that second monitor. The PR (#4228) makes it use your primary monitor, which is probably enabled.

Try the PR and see if it works for you. Or just enable that second monitor, I guess.

**Comment by Husky110** [comment] 2022-07-17 15:32
Hi - this still seems to be an issue... Setup is that I have my laptop with it's monitor (DP-0) and got 2 monitors attached (DP-2 and HDMI-0 weirdly enough... it's an HP Omen Laptop with Pop_OS 22.04), whereas I got the laptop-display offline since it is too dark (and I wanna keep my keyboard clean). I still get the error on everything I try to install. Lutris is Version 0.5.10.1.

**Comment by danieljohnson2** [comment] 2022-07-17 15:49
Could you try it with the master branch? Maybe its been fixed.

No need to install; clone the repo and run the script 'bin/lutris' inside it. Does that work for you?

**Comment by Husky110** [comment] 2022-07-17 16:32
Nope - still the same error-message: ValueError("invalid literal for int() with base 10: ''")

**Comment by OldGregggg** [comment] 2022-08-16 13:20
I am also getting this error now as well.
I am running Ubuntu 22.04 on 5.15.0-46-generic
```
VinStein:~$ lutris -d
INFO     2022-08-16 09:14:30,379 [startup.init_lutris:173]:Starting Lutris 0.5.10.1
WARNING  2022-08-16 09:14:30,399 [libretro.get_libretro_cores:24]:No folder at /home/exercore/.local/share/lutris/runners/retroarch/
INFO     2022-08-16 09:14:30,420 [startup.check_driver:57]:Using NVIDIA drivers 515.65.01 for x86_64
INFO     2022-08-16 09:14:30,420 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 3080 Ti
INFO     2022-08-16 09:14:30,420 [startup.check_driver:77]:GPU: 10DE:2208 3842:3967 (nvidia drivers)
INFO     2022-08-16 09:14:30,468 [startup.update_runtime:213]:Startup complete
DEBUG    2022-08-16 09:14:30,524 [lutriswindow.update_store:437]:Showing 1 games
DEBUG    2022-08-16 09:14:38,749 [application.show_window:332]:Showing window AddGamesWindow{}
DEBUG    2022-08-16 09:14:44,370 [http.get:83]:GET https://lutris.net/api/games?search=path+of+building&with-installers=True
DEBUG    2022-08-16 09:14:45,490 [api.get_game_installers:160]:Fetching installer https://lutris.net/api/installers/path-of-building
DEBUG    2022-08-16 09:14:45,490 [http.get:83]:GET https://lutris.net/api/installers/path-of-building
DEBUG    2022-08-16 09:14:45,731 [application.show_window:332]:Showing window InstallerWindowpath-of-building
DEBUG    2022-08-16 09:14:45,732 [application.on_app_window_destroyed:350]:Removed window AddGamesWindow{}
DEBUG    2022-08-16 09:14:47,099 [displayconfig.get_current_resolution:624]:Retrieving current resolution
ERROR    2022-08-16 09:14:47,099 [displayconfig.get_current_resolution:627]:Could not retrieve the current display mode
INFO     2022-08-16 09:14:48,698 [runner.get_runner_version:324]:Getting runner information for wine
DEBUG    2022-08-16 09:14:48,698 [http.get:83]:GET https://lutris.net/api/runners/wine
DEBUG    2022-08-16 09:14:48,892 [interpreter.get_runners_to_install:223]:Default wine version is lutris-7.2-2
DEBUG    2022-08-16 09:14:48,893 [interpreter.get_extras:159]:Checking if service provide extra files
DEBUG    2022-08-16 09:14:48,894 [installer.prepare_game_files:146]:No service to retrieve files from
DEBUG    2022-08-16 09:14:49,954 [downloader.start:65]:⬇ https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.9.0/PathOfBuildingCommunity-Portable-2.9.0.zip
DEBUG    2022-08-16 09:14:57,775 [downloader.download_cb:125]:Finished downloading https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.9.0/PathOfBuildingCommunity-Portable-2.9.0.zip
INFO     2022-08-16 09:14:57,967 [file_box.on_download_complete:252]:Download completed
DEBUG    2022-08-16 09:14:57,968 [files_box.on_file_available:93]:pob_zip is available
INFO     2022-08-16 09:14:57,968 [files_box.on_file_available:99]:All files available
INFO     2022-08-16 09:14:57,968 [installerwindow.on_files_available:463]:All files are available, continuing install
DEBUG    2022-08-16 09:14:57,969 [interpreter._iter_commands:317]:Installer command: {'extract': {'dst': '$GAMEDIR', 'file': 'pob_zip'}}
ERROR    2022-08-16 09:14:57,969 [jobs.target:36]:Error while completing task <bound method CommandsMixin.extract of <interpreter.ScriptInterpreter object at 0x7f0af552ddc0 (lutris+installer+interpreter+ScriptInterpreter at 0x557840b88da0)>>: <class 'ValueError'> invalid literal for int() with base 10: ''
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/installer/commands.py", line 188, in extract
    dest_path = self._substitute(data["dst"])
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 420, in _substitute
    return system.substitute(template_string, self._get_string_replacements())
  File "/usr/lib/python3/dist-packages/lutris/installer/interpreter.py", line 400, in _get_string_replacements
    "RESOLUTION_WIDTH_HEX": hex(int(self.current_resolution[0])),
ERROR    2022-08-16 09:14:57,971 [interpreter._iter_commands:302]:Last install command failed, show error
```

**Comment by danieljohnson2** [comment] 2022-08-16 22:14
@OldGregggg, that appears to be an issue in 0.5.10.1 that is fixed in master. Could you try the master branch? It may not be able to to figure out the current resolution, but it should now faill back to 1280x720, and not crash.
