### ISSUE TITLE
Lutris won't boot with GTK+ version 3.24.13

### ISSUE THREAD

**Issue by warmerspy** [lutris/lutris#2546] opened 2019-12-27 16:21 UTC
So I am running Gentoo and yesterday I upgraded GTK+ to 3.24.13 and Lutris stopped working to fix this I I downgraded back to version 3.24.11. Could be a good thing to look into it. In any case I felt it was a good thing to report it.

**Comment by strycore** [comment] 2019-12-27 16:23
You don't give any details on what crashes there could be. Furthermore, upgrading from x.11 to x.13 should not affect GTK software. I'm going to close this as a Gentoo quirk

**Closed by strycore** 2019-12-27 16:23 UTC

**Comment by Neo2003** [comment] 2020-01-01 11:43
I have the same problem on Gentoo with GTK+ 3.24.13, and I plan to go back to 3.24.11.
But since I still have the offending version, I may try to help debug this.
There is not much to report since lutris does not launch at all, it exit immediately and running lutris -d hangs it with not a single output.
Running it as root does not even trigger the root warning popup.
What can I provide to help?

**Comment by strycore** [comment] 2020-01-01 17:43
This bug report is likely a duplicate of https://github.com/lutris/lutris/issues/2554
Please add any additional info there.
