### ISSUE TITLE
Epic games no longer works

### ISSUE THREAD

**Issue by jaspa7** [lutris/lutris#2716] opened 2020-04-05 02:30 UTC
Hi,
Apologies if this is the wrong format for issue reports.. but The epic games stores no longer works and neither do any of the games in it. Worked fine for months prior and just this morning - dead :(
EDIT: Sorry, bit more info for context:
OS: Manjaro xfce
Kernel: linux419
CPU:
> Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           60
Model name:                      Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
Stepping:                        3
CPU MHz:                         1471.301
CPU max MHz:                     3900.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7000.05
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        6 MiB

GPU: GTX1070
Driver: video-nvidia-430xx

Running on manjaro 

Log when firing up epic games:

> Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.8/io.py", line 52, in <module>
  File "/usr/lib/python3.8/abc.py", line 106
    print(f"Class: {cls.__module__}.{cls.__qualname__}", file=file)
                                                      ^
SyntaxError: invalid syntax

UPDATE: Since it seems python related, I'm installing python3.8 (would've thought I had it already, esp. if it's a dependency for lutris.. but apparently not?)
UPDATE2: Yes, did have python3.8, did an update and that didn't fix it either

When trying to launch it directly from terminal (don't think you're meant to), this is the output:

> ./EpicGamesLauncher.exe 
0014:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
000d:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
001e:fixme:ole:CoInitializeSecurity (0000000000000000,-1,0000000000000000,0000000000000000,0,3,0000000000000000,0,0000000000000000) - stub!
001e:err:winediag:wined3d_dll_init The GLSL shader backend has been disabled. You get to keep all the pieces if it breaks.
001e:fixme:wbemprox:client_security_SetBlanket 00007FEAEECC3700, 0000000000A2A890, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
001e:fixme:wbemprox:client_security_Release 00007FEAEECC3700
001e:fixme:ole:CoInitializeSecurity (0000000000000000,-1,0000000000000000,0000000000000000,0,3,0000000000000000,0,0000000000000000) - stub!
001e:fixme:wbemprox:client_security_SetBlanket 00007FEAEECC3700, 0000000000A2D530, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
001e:fixme:wbemprox:client_security_Release 00007FEAEECC3700
001e:fixme:ole:CoInitializeSecurity (0000000000000000,-1,0000000000000000,0000000000000000,0,3,0000000000000000,0,0000000000000000) - stub!
001e:fixme:wbemprox:client_security_SetBlanket 00007FEAEECC3700, 0000000000A2D530, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
001e:fixme:wbemprox:client_security_Release 00007FEAEECC3700
0026:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
001e:fixme:ole:CoInitializeSecurity (0000000000000000,-1,0000000000000000,0000000000000000,0,3,0000000000000000,0,0000000000000000) - stub!
001e:fixme:wbemprox:client_security_SetBlanket 00007FEAEECC3700, 0000000000A2A770, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
001e:fixme:wbemprox:client_security_Release 00007FEAEECC3700
001e:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
001e:fixme:ole:CoInitializeSecurity (0000000000000000,-1,0000000000000000,0000000000000000,0,3,0000000000000000,0,0000000000000000) - stub!
001e:fixme:wbemprox:client_security_SetBlanket 00007FEAEECC3700, 0000000000A2A770, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
001e:fixme:wbemprox:client_security_Release 00007FEAEECC3700
003e:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION

**Comment by jaspa7** [comment] 2020-04-05 03:03
UPDATE: It's working - sort of. Had to right-click then "install another version".. then the thing fired up all by itself? The "Installing Epic Games Store" window still sits in the background.. but can live with that. Just happy I can play my games again

**Comment by strycore** [comment] 2020-04-06 16:54
Closing because the original report lacks reproducibility steps.

**Closed by strycore** 2020-04-06 16:54 UTC
