### ISSUE TITLE
Lutris 0.5.14 won't start on Steam Deck

### ISSUE THREAD

**Issue by tadejcek007** [lutris/lutris#5095] opened 2023-10-23 19:30 UTC
### Bug description

When i launch Lutris in desktop mode it show icon for few seconds and then closes. Also any game that was previously added doesn't work.

### How to Reproduce

1. Go to 'Desktop mode on Steam deck'
2. Click on 'Lutris icon'

### Expected behavior

Lutris should start.

### Log output

```shell
Gtk-Message: 21:12:09.273: Failed to load module "canberra-gtk-module"
2023-10-23 21:12:09,456: Command 'fluidsynth' not found on your system
2023-10-23 21:12:10,190: Starting Lutris 0.5.14
2023-10-23 21:12:10,193: Running AMD Mesa driver 23.2.1 on AMD Custom GPU 0405 (vangogh, LLVM 16.0.6, DRM 3.45, 5.13.0-valve37-1-neptune) (0x163f)
2023-10-23 21:12:10,194: GPU: 1002:163F 1002:0123 (amdgpu drivers)
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/util/flatpak.py", line 41, in get_installed_apps
    name, appid, version, branch, origin, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 6)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 310, in do_activate
    self.window = LutrisWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 126, in __init__
    self.sidebar.initialize_rows()
  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
    self.update_rows()
  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
    self.installed_runners = [runner.name for runner in runners.get_installed()]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/runners/__init__.py", line 102, in get_installed
    if runner.is_installed():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/runners/runner.py", line 414, in is_installed
    return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/flatpak.py", line 61, in is_app_installed
    for app in get_installed_apps():
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/flatpak.py", line 44, in get_installed_apps
    name, appid, version, branch, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 5)
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 699, in do_command_line
    self.window.present()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'
```

### System Information

```shell
Operating System: SteamOS 3.4.11
KDE Plasma Version: 5.26.1
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 5.13.0-valve37-1-neptune (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
Manufacturer: Valve
Product Name: Jupiter
System Version: 1
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment] 2023-10-25 22:06
That doesn't seem right. The OS says SteamOS 3.4.11 when it should be GNOME 45 Flatpak runtime. 
Are you running Lutris natively on SteamOS? This absolutely not tested or supported.

I also thought we had a patch for the discrepancies between different Flatpak versions but guess it wasn't good enough.

**Comment by RazorClaw81** [comment] 2023-10-26 18:49
This "bug" does not only affect the Steam Deck, it seems. I've got the Flatpak version of Lutris 5.14 running on my desktop, with the same issues.
I've got a Steam Deck, but Lutris is ,luckily, not updated(yet).

**Bug description**
Updated to Lutris 5.14(Flatpak) 

**How to reproduce**
Install the 5.14 Flatpak version of Lutris and start it.

**Expected behavior**
It should start.

**Additional information**
At the first start it seems to create  

- two instances of xdg-dbus-proxy
- two instances of python3
- six instances of bwrap

After killing those instances i started net.lutris.Lutris again. This time the above mentioned instances were reduced to half and the output below was created.
This behavior seems only to occur after a fresh system start.

**Log output**
```

2023-10-26 19:54:42,968: Command 'fluidsynth' not found on your system
2023-10-26 19:54:43,569: Starting Lutris 0.5.14
2023-10-26 19:54:43,571: Using NVIDIA drivers 535.113.01 for x86_64
2023-10-26 19:54:43,571: GPU: NVIDIA GeForce GTX 1080 Ti
2023-10-26 19:54:43,572: GPU: 10DE:1B06 1043:85EA (nvidia drivers)
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/util/flatpak.py", line 41, in get_installed_apps
    name, appid, version, branch, origin, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 310, in do_activate
    self.window = LutrisWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 126, in __init__
    self.sidebar.initialize_rows()
  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
    self.update_rows()
  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
    self.installed_runners = [runner.name for runner in runners.get_installed()]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/runners/__init__.py", line 102, in get_installed
    if runner.is_installed():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/runners/runner.py", line 414, in is_installed
    return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/flatpak.py", line 61, in is_app_installed
    for app in get_installed_apps():
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/flatpak.py", line 44, in get_installed_apps
    name, appid, version, branch, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 5)
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 699, in do_command_line
    self.window.present()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'

```

**System Information**
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.5.5-1-MANJARO (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen Threadripper 1950X 16-Core Processor
Memory: 62.8 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7B09
System Version: 1.0
```

**Comment by RazorClaw81** [comment] 2023-10-26 19:45
> That doesn't seem right. The OS says SteamOS 3.4.11 when it should be GNOME 45 Flatpak runtime. Are you running Lutris natively on SteamOS? This absolutely not tested or supported.

Those are the specs of the Steam Deck itself. Why should they list a Flatpak app dependency?

**Comment by tadejcek007** [comment] 2023-10-26 20:20
> > That doesn't seem right. The OS says SteamOS 3.4.11 when it should be GNOME 45 Flatpak runtime. Are you running Lutris natively on SteamOS? This absolutely not tested or supported.
> 
> Those are the specs of the Steam Deck itself. Why should they list a Flatpak app dependency?

As he says. This is what it is. If any other sys info helps let me know. I just can't get them through Lutris like in FAQ because i can't even get Lutris to open.

**Comment by RazorClaw81** [comment] 2023-10-27 09:26
One thing i want to add, just because i forgot about it.
I'm using a script to call some games with their game id, for some daily login stuff. To speed things up i always got an Lutris window open, so it won't get started and closed with every game.
I just forgot that his script uses the Flatpak version of Lutris to start the games. This still works, at least i can start games over the cli with the Flatpak version while using the game id of the game. It will show me the above mentioned error and some game related warnings and i'll have to strg+c out after the game finishes but i can start and play the game.
But the noticeable part is that i installed the native version (5.13-8) along side with the Flatpak version of Lutris, because of the problem. With the native version up and running i can start games with their id, even while calling _net.lutris.Lutris_ , and won't get any error messages except the one about fluidsynth.

**Comment by strycore** [comment] 2023-10-27 19:43
There seems to be some misconceptions about Flatpak. 
Flatpak creates sandboxed applications. Native apps and Flatpak apps are not able to see each other or interfere with each other.
But also, Lutris uses dbus to keep one instance of the client running. So if you start up a native Lutris and then launch the Flatpak version then the native version will gain focus. The Flatpak will not be used at all. 

You can only run one instance of the client at a time and it all depends on which is started first. 

I am currently on a Steam Deck and Lutris works fine.

**Comment by RazorClaw81** [comment] 2023-10-28 12:58
> There seems to be some misconceptions about Flatpak. Flatpak creates sandboxed applications. Native apps and Flatpak apps are not able to see each other or interfere with each other. 

Yes i know that, of course. That's the hole reason i wan't the Flatpak to work.

>But also, Lutris uses dbus to keep one instance of the client running. So if you start up a native Lutris and then launch the Flatpak version then the native version will gain focus. 

Could have think about it myself, because it's the same reason i open up Lutris before using my script.

>The Flatpak will not be used at all.

At least just until it has checked for a  already running instance. In which case it will still give the 'Command 'fluidsynth' not found on your system', what the native version won't give me.

> I am currently on a Steam Deck and Lutris works fine.

Hmm, i'm really curious what is causing all this. Untill i know i'll leave it as it is, because i need it in the next weeks. At least without a way to check if it may break or not.

>Lutris is crashing while trying to get the List of installed Flatpaks.
It already handles 2 types of Flatpak outputs and I just added another handler for when it fails to read either formats.

Saw it. I just installed from the AUR. Sadly got still errors. Of course i first checked that's the correct version and that the patch is applied to the flatpak.py.

```
2023-10-28 14:06:14,312: Starting Lutris 0.5.14
2023-10-28 14:06:14,313: Migrating games field sortname
2023-10-28 14:06:14,318: Using NVIDIA drivers 535.113.01 for x86_64
2023-10-28 14:06:14,318: GPU: NVIDIA GeForce GTX 1080 Ti
2023-10-28 14:06:14,318: GPU: 10DE:1B06 1043:85EA (nvidia drivers)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 41, in get_installed_apps
    name, appid, version, branch, origin, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 45, in get_installed_apps
    name, appid, version, branch, installation = package.split("\t")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 310, in do_activate
    self.window = LutrisWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 126, in __init__
    self.sidebar.initialize_rows()
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
    self.update_rows()
  File "/usr/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
    self.installed_runners = [runner.name for runner in runners.get_installed()]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/__init__.py", line 102, in get_installed
    if runner.is_installed():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/runners/runner.py", line 420, in is_installed
    return self.flatpak_id and flatpak.is_app_installed(self.flatpak_id)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 65, in is_app_installed
    for app in get_installed_apps():
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/util/flatpak.py", line 48, in get_installed_apps
    logger.error("Not able to parse Flatpak output: %s", package)
    ^^^^^^
NameError: name 'logger' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/gui/application.py", line 699, in do_command_line
    self.window.present()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'
```
So i'll stick to my 5.13-8 version for the time being. Are there any information we could gather to help?

**Comment by danieljohnson2** [comment] 2023-10-28 14:55
Oh, that last one is just a missing import. I'll supply that, and we should do a little better- if you have the patience to try again.

**Comment by RazorClaw81** [comment] 2023-10-28 15:43
Of course. Now it starts without any big issues.

The only messages i get are the following but at least it's not crashing anymore.
```
2023-10-28 17:36:18,900: Starting Lutris 0.5.14
2023-10-28 17:36:18,902: Using NVIDIA drivers 535.113.01 for x86_64
2023-10-28 17:36:18,902: GPU: NVIDIA GeForce GTX 1080 Ti
2023-10-28 17:36:18,902: GPU: 10DE:1B06 1043:85EA (nvidia drivers)
2023-10-28 17:36:19,063: Not able to parse Flatpak output: DOSBox-X	com.dosbox_x.DOSBox-X	2023.10.06	stable	x86_64	flathub	system
2023-10-28 17:36:19,063: Not able to parse Flatpak output: Aqueducts	com.endlessnetwork.aqueducts	1.2.2	stable	x86_64	flathub	system
2023-10-28 17:36:19,063: Not able to parse Flatpak output: Clapper	com.github.rafostar.Clapper	0.5.2	stable	x86_64	flathub	system
2023-10-28 17:36:19,064: Not able to parse Flatpak output: Flatseal	com.github.tchx84.Flatseal	2.1.0	stable	x86_64	flathub	system
#same over and over again
2023-10-28 17:36:20,695: Not able to parse Flatpak output: Gecko	org.winehq.Wine.gecko		stable-23.08	x86_64	flathub	system
2023-10-28 17:36:20,695: Not able to parse Flatpak output: Mono	org.winehq.Wine.mono		stable-23.08	x86_64	flathub	system
2023-10-28 17:36:20,695: Not able to parse Flatpak output: Zoom	us.zoom.Zoom	5.16.2.8828	stable	x86_64	flathub	system
2023-10-28 17:36:20,695: Not able to parse Flatpak output: RazerGenie	xyz.z3ntu.razergenie	1.1.0	stable	x86_64	flathub	system
2023-10-28 17:36:30,137: Shutting down Lutris
```
The original output was around 2138 lines. I shortened it a bit, because it seems only to repeat itself.

**Comment by danieljohnson2** [comment] 2023-10-28 15:51
That's better. I see the flatpak output is listing the architecture; not sure why you get that and I don't on my system. But we can handle that output.

I've committed an update that should take care of this and get it working for you.

**Comment by RazorClaw81** [comment] 2023-10-28 16:01
Here the new output, nice and clean. Nothing unusual i can observe so far.

```
2023-10-28 17:57:08,531: Starting Lutris 0.5.14
2023-10-28 17:57:08,533: Using NVIDIA drivers 535.113.01 for x86_64
2023-10-28 17:57:08,533: GPU: NVIDIA GeForce GTX 1080 Ti
2023-10-28 17:57:08,533: GPU: 10DE:1B06 1043:85EA (nvidia drivers)
2023-10-28 17:57:12,657: Shutting down Lutris
```
Maybe those extra information in my Flatpak listing is some Arch or Manjaro configuration thing. Hopefully that will fix the Flatpak to.

**Comment by RazorClaw81** [comment] 2023-10-28 16:55
Hmm, im just curious. Was all that just because on some systems  _flatpak list_  will give more or less columns depending on the configuration?
Wouldn't then be more useful to expand the 

  `command = get_command() + ["list"]`

to
````
  command = get_command() + ["list --columns=name,application,version,branch,arch,origin,installation"]
````
or something that gives you more control?

**Comment by tadejcek007** [comment] 2023-10-29 20:42
Thanks everyone. I will give it a try tomorrow and let you know. Hope it will be fixed in next flatpak version.

**Comment by strycore** [comment] 2023-10-29 21:56
> Was all that just because on some systems flatpak list will give more or less columns depending on the configuration?

Yes, that's exactly what's happening!

>   `command = get_command() + ["list --columns=name,application,version,branch,arch,origin,installation"]`

thanks! that should make the output more consistent indeed.

**Comment by strycore** [comment] 2023-10-29 22:00
I pushed a patch to make the flatpak output more consistent. 
A small bugfix release should be released soon.

**Closed by strycore** 2023-10-29 22:00 UTC
