### ISSUE TITLE
cant connect to Epic Games Store

### ISSUE THREAD

**Issue by Itsredsect** [lutris/lutris#4617] opened 2022-11-27 12:46 UTC
When I try to link Epic Games to Lutris, nothing happens. You are first asked to download Epic Games, which I did. But when I then try to link the store to Lutris, it doesn't do it. I log in normally, get the message on my phone with the code and then just enter it in the login window. After that the window closes and nothing happens. The button to connect is still displayed. Also, no games are displayed in Lutris.

**Comment by muznyo** [comment] 2022-11-29 18:05
I have similar issue, but my login is stuck on this button 
![image](https://user-images.githubusercontent.com/24987471/204610685-7b5f3179-53f6-45bb-acf8-f6d06729dcd0.png)

I can't even click it, also the whole login window is slowly loading

**Comment by strycore** [comment] 2023-05-27 21:27
Gonna say it's a duplicate of #4783

**Closed by strycore** 2023-05-27 21:27 UTC
