### ISSUE TITLE
[Feature Request] Give feedback to user if install fails when the automagical installer fails

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#3964] opened 2021-12-30 23:06 UTC
Was messing around, and tried to install the game, it failed silently. I got this on the terminal:

```
Fetching installer https://lutris.net/api/installers/ancient-rush-2
DEBUG    2021-12-31 00:50:44,916 [http.get:81]:GET https://lutris.net/api/installers/ancient-rush-2
DEBUG    2021-12-31 00:50:45,493 [application.on_game_install:517]:Should generate automagical installer here but....
DEBUG    2021-12-31 00:50:45,493 [application.on_game_install:518]:Wait? how did you get here?
```

Without running Lutris from the terminal, with the debug option, there is no feedback that there was any error, thus leaving the user dumbfounded as to what's going on. Maybe we should give feedback to the user.

@strycore @danieljohnson2

**Comment by danieljohnson2** [comment] 2021-12-30 23:10
You called?

This looks like a dupe of #3939 to me. PR #3940 provides an error dialog for this. You can try the branch: [danieljohnson2:dj/error_for_no_installers2](https://github.com/danieljohnson2/lutris/tree/dj/error_for_no_installers2) to see if that helps.

**Closed** 2021-12-30 23:11 UTC
