### ISSUE TITLE
Lutris syncs STEAM games when sync is turned off (library)

### ISSUE THREAD

**Issue by BloodyIron** [lutris/lutris#962] opened 2018-07-06 01:38 UTC
I didn't turn sync on, and so far as I can tell, it's off (the slider is set to off) to sync with STEAM.

But Lutris keeps syncing my STEAM library with its library, and I don't want it to!

I'm on 0.4.18.

I've heard this happening to other people too. Thanks! :D

**Comment by strycore** [comment] 2018-08-16 06:43
I think what's happening is that Lutris is syncing your Lutris library, which contains all your Steam games if your have synced your library on the website. The game Lutris sees as installed as likely to be marked as such.

**Comment by NicoVIII** [comment] 2018-08-21 10:12
As far as I know, Lutris does not delete a game from the library on the lutris homepage, if you delete it in the lutris application. Therefore this game will always show up again, if you don't delete it on the webseite.

You could test, if this is your problem by deleting a game you think is imported through steam on the lutris website and then delete it in the lutris application and restart.

**Comment by BloodyIron** [comment] 2018-08-21 13:07
I don't have the program logged into my account. It's pulling from the native STEAM library I have on the same system.

**Comment by KonomiKitten** [comment] 2018-08-21 18:00
> I don't have the program logged into my account. It's pulling from the native STEAM library I have on the same system.

I also have the same problem and I'm also not logged into any account that has to do with Lutris.

**Comment by keturn** [comment] 2018-08-22 01:15
I was going to take a shot at this one, as I've seen it myself.

After a little testing, it seems like the entry isn't imported when Lutris starts, it's imported when the local Steam client starts.

Ah, okay, I got it to trigger again:

`LutrisWindow.__init__` sets up a `SteamWatcher`, with callback `LutrisWindow.on_steam_game_changed`, and that will do a `mark_as_installed`, and it doesn't seem to be checking any sort of "should I sync?" in the process.

When is it the right time for it to check that? Should it not start the SteamWatcher at all, if it's not set up to sync?

Or does the first part of `on_steam_game_changed`, the part that works with `running_game`, still need to get updated, but it should stop after that if sync isn't on?

**Comment by NicoVIII** [comment] 2018-08-22 13:18
After @keturn s work I could reproduce as well. If steam and lutris are open and I install a game, lutris adds it.

I guess that lutris removes a game if it is uninstalled from steam is useful even without enabled syncing because it can not be used from lutris anymore. But if live syncing is fixed, we should change the text as well. For now it justs says that libraries are synced when lutris starts.

Just to put my two cents in. :smile:

**Comment by BloodyIron** [comment] 2018-08-22 22:47
I don't want it to sync with sync set to off, whether I'm logged in or not. It creates too much clutter!

**Comment by tannisroot** [comment] 2018-08-24 00:04
Can confirm that this is an issue for me ass well. Very annoying.

**Comment by KonomiKitten** [comment] 2018-10-01 04:38
I noticed the milestone was set to 0.4.20 which recently released but I don't see anything in the release notes about this problem, can I presume it will now be bumped as a milestone for the next version? Little disappointing.

**Comment by BloodyIron** [comment] 2018-10-01 15:41
Yeah, I really want this extremely frustrating behaviour to stop. When is it going mainline?

**Comment by BloodyIron** [comment] 2018-10-04 00:17
Okay it's now syncing games that are already installed.

**Comment by BloodyIron** [comment] 2018-10-05 02:48
Today it synced 17 games that were already installed. I didn't tell it to do this. I have to manually go and remove these each time they do this. This is ridiculous can we PLEASE get this fixed???

**Comment by tannisroot** [comment] 2018-10-06 13:07
I see that Lutris still watches the steam library folder, even when the syncing is turned off. 
Perhaps stopping that behavior would solve this issue.

**Comment by moll** [comment] 2018-10-06 13:19
https://github.com/lutris/lutris/issues/962#issuecomment-414873663 described the problem technically and I found the same root cause in the source code. I suppose those that can code can remove the watcher initialization in https://github.com/lutris/lutris/blob/bc197dbbc36ee9648097e7d787a066dee36ac305/lutris/gui/lutriswindow.py#L158 from their local install until a permanent solution is put in place.

**Comment by Medath** [comment] 2018-10-06 21:40
What is everyone here talking about? It doesn't seem to me like Lutris even has an option to disable syncing (At least I couldn't find it). So how can it be bugged if it doesn't even exist? What everyone here is probably talking about is the option to disable sync *when Lutris starts*, which seems to work just as it should.

That being said, it's not very clear and can be easily confused as an option to disable sync entirely. I think it would be better to rename this issue to something like "Add option to fully disable game sync".

**Comment by BloodyIron** [comment] 2018-10-06 21:57
Syncing _SHOULD_ be disabled by default, but clearly it isn't. My understanding is that syncing with the STEAM install on the same computer typically relies on logging into a Lutris account and then enabling/disabling per runner. But the thing is Lutris is syncing for me, without logging in, and without telling it to, and I have ZERO way to tell it to stop.

I want it to NOT sync by default, and for this shit to just stop already.

I've had Lutris sync games while it was running, I did not have to re-run it for syncing to happen.

Again, I want it _OFF BY DEFAULT_ AND the ability to turn it off/on.

**Comment by moll** [comment] 2018-10-06 21:59
@Medath, there's a toggle under "Import games" that I'd say justifiably creates confusion if it only partly configures Steam syncing.

![screenshot from 2018-10-06 21-57-01](https://user-images.githubusercontent.com/156837/46576145-ee0d2280-c9b2-11e8-9ff6-fc62ff1b6155.png)

**Comment by BloodyIron** [comment] 2018-10-06 22:03
@moll that's what I'm talking about! I guess I forgot you don't need to login to a Lutris account to get it. But it IS turned OFF for me, and it still syncs! Whether Lutris is running, or starting up. :(

**Comment by moll** [comment] 2018-10-06 22:14
@BloodyIron, yep, and as I described in https://github.com/lutris/lutris/issues/962#issuecomment-427573254, it's definitely a bug (or a missing feature, depending on your view :P). If I were you and bothered about it syncing, I'd edit that `lutriswindow.py` file on my computer to disable the watcher until it gets fixed. :)

**Comment by BloodyIron** [comment] 2018-10-06 22:33
@moll and what's to prevent an update from undoing that? I'd rather a proper fix get pulled mainline, and I'm hoping this is bringing more attention to this ;P

**Comment by tannisroot** [comment] 2018-10-18 17:01
As this is now fixed in master, the issue should be now closed.

**Comment by BloodyIron** [comment] 2018-10-18 22:48
Is there a target release for this?

**Comment by tannisroot** [comment] 2018-10-18 22:50
Yes. 0.4.21 is due by October 20th. You can try it out with a Lutris-git package from AUR or by downloading master as an archive.

**Comment by tannisroot** [comment] 2018-10-19 02:51
So can you close it?

**Closed** 2018-10-19 03:03 UTC
