### ISSUE TITLE
 [Environment variables] Per-game options do not supersede base runner and global options if variables are removed

### ISSUE THREAD

**Issue by CPioGH2002** [lutris/lutris#5115] opened 2023-11-02 15:29 UTC
### **SOLVED** 
- find the solution in the last few posts, including a screenshot.

### Bug description

I haven't found anything concerning this "non-superseding" behaviour in the other issue reports, on the web or in the forums so far.

Once you set an environment variable like "VKD3D_CONFIG dxr11,dxr" in the global and/or runner options, you can expect it to show up in the pre-game options, which is the desired outcome. It gets inherited. 

**Now, if you want a single game to _not_ incorporate this global/runner setting**, you would delete it from the game's profile and expect it to be gone. This, however, does not take place as the existing environment variable remains present and active in the game profile, even after altering and saving it.

### How to Reproduce

Steps to reproduce the behaviour: (find my log output below)
1. Set an environment variable in **runner options** or above (example for Wine runner: "VKD3D_CONFIG dxr11,dxr")
2. Check if the setting now is present in all the corresponding per-game profiles
3. Open a **game profile** and _remove_ the "Environment variables" line you set up before
4. Save the game profile and open it again to check if the setting is gone

From my testing and log output below, it is not. The Env variable line remains present and active in the game's profile.

### Expected behavior

Since values get inherited from Global>Runner>Game, their presence is expected. But deleting one of those inherited environment variable lines from a single game profile should lead to this inheritance being stopped, either concerning this single deleted line or the "Environment variables" section as a whole.

Workaround:
So far, if a single game has trouble with your global setting concerning the environment variables (while all others may benefit from it), you can remove mentioned setting from the global or runner options and only add it manually to games which need it.

This is more work when it comes to generally applicable settings which only break one or two games as it causes you to having to edit all the game profiles where you want the value to be present.

### Log output

```shell
flatpak run net.lutris.Lutris -d
2023-11-02 15:53:09,154: Command 'fluidsynth' not found on your system
INFO     2023-11-02 15:53:09,482 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-11-02 15:53:09,484 [startup.get_drivers:57]:Using NVIDIA drivers 545.29.02 for x86_64
INFO     2023-11-02 15:53:09,484 [startup.get_drivers:61]:GPU: NVIDIA GeForce RTX 2080 SUPER
INFO     2023-11-02 15:53:09,484 [display.display_gpu_info:78]:GPU: 10DE:1E81 1458:3FE9 (nvidia drivers)
DEBUG    2023-11-02 15:53:09,717 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-02 15:53:10,080 [lutris.get_missing_game_ids:202]:Checking for missing games
DEBUG    2023-11-02 15:53:34,912 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-02 15:53:34,945 [application.show_window:359]:Showing window RunnerConfigDialogwine
DEBUG    2023-11-02 15:53:36,135 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-02 15:53:36,140 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-02 15:53:36,149 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-02 15:53:36,155 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-02 15:53:36,160 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-11-02 15:53:40,153 [config.save:227]:Saving LutrisConfig(level=runner, game_config_id=None, runner=wine) config to /home/user/.var/app/net.lutris.Lutris/config/lutris/runners/wine.yml
DEBUG    2023-11-02 15:53:40,161 [application.on_app_window_destroyed:377]:Removed window RunnerConfigDialogwine
DEBUG    2023-11-02 15:53:42,694 [application.show_window:359]:Showing window EditGameConfigDialog32
DEBUG    2023-11-02 15:53:50,428 [game.save:429]:Saving Starfield (wine) with config ID starfield-1698162690
DEBUG    2023-11-02 15:53:50,428 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=starfield-1698162690, runner=wine) config to /home/user/.var/app/net.lutris.Lutris/config/lutris/games/starfield-1698162690.yml
DEBUG    2023-11-02 15:53:50,933 [lutris.add_to_path_cache:160]:Adding Starfield (wine) to path cache
DEBUG    2023-11-02 15:53:50,942 [application.on_app_window_destroyed:377]:Removed window EditGameConfigDialog32
DEBUG    2023-11-02 15:53:56,197 [application.show_window:359]:Showing window EditGameConfigDialog32
DEBUG    2023-11-02 15:54:00,802 [application.on_app_window_destroyed:377]:Removed window EditGameConfigDialog32
```

### System Information

```shell
[System]
OS:              GNOME 45 Flatpak runtime
Arch:            x86_64
Kernel:          6.5.0-10-generic
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 7700X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.1 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 545.29.02
OpenGL Core:     4.6.0 NVIDIA 545.29.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 545.29.02
Vulkan Version:  1.3.261
Vulkan Drivers:  NVIDIA GeForce RTX 2080 SUPER (1.3.260)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment] 2023-11-13 22:38
Well, I finally got around to looking at this, and I think this is the intended behavior- there is a bunch of special case just for the environment variables so you get the variables from the system, runner, and game all together. It sure does not look like a bug.

I would expect just removing this will break people's Lutris installs. Perhaps there's some another way. Can you set the variable to blank in the game configuration, would that work for your case?

**Comment by danieljohnson2** [comment] 2023-11-14 23:20
That's strange. I just tried it myself and the blank entry did save and did replace the runner-level selection. I do not understand what I am supposed to see in your log output either. What are you seeing? Can you save a blank env-var value at all?

Adding a checkbox would be trickier than it seems, since the env-var settings are in the global options, runner options, and environment options also. These levels could all have different values, and it's a question how they would interact.

**Comment by danieljohnson2** [comment] 2023-11-15 00:02
Oh, I see. Try blanking out the 'Value' column *only*. It needs to know which variable you are trying to block, you see.

**Comment by danieljohnson2** [comment] 2023-11-15 00:09
But make sure to remember to close the issue, so they won't find it! :smile:

**Closed as completed** 2023-11-15 00:09 UTC
