### ISSUE TITLE
Layers of Fear 2 breaks when using HDMI surround sound

### ISSUE THREAD

**Issue by mrmatteastwood** [lutris/lutris#4426] opened 2022-08-14 10:36 UTC
This bug is probably the same one that happens to Styx: Shards of Darkness on Proton:
https://github.com/ValveSoftware/Proton/issues/964#issuecomment-1138436039

## System Information
- GPU: GTX 1080 Ti
- Driver/LLVM version: 515.65.01
- Kernel version: 5.17.0-1015-oem
- Full system info by Linux Mint: https://termbin.com/g7yg
- Wine version: lutris-7.2-2-x86_64

## Symptoms
When launching Layers of Fear 2 using the PC's HDMI-out for sound, the game runs without any sound, intro movies play overlaid by a pink screen and then everything just stops. Need to Alt-Tab out of the game and kill the game via system monitor. Issue does not occur when using another sound device, e.g. USB headphones.

## Reproduction
1. Set up a PC and home theatre system by running an HDMI cable from the graphics card to the AVR
2. Install LOF2 (e.g. GOG version) using Lutris on Linux Mint 21
3. Open Linux Mint's sound settings
4. Select HDMI device and set it to any profile (stereo, 5.1...)
5. Launch game

## Notes
- Video showing the issue here: https://youtu.be/FymbHpVps5I
- When running the game with another sound device and then switching to HDMI while the game is running, you can get stereo sound, but no surround.
- fwiw, this issue does not occur on Windows 10.

## My screen setup:
**Screen 1:** PC => DisplayPort cable > Screen (2560x1440)
**Screen 2:** PC => DVI cable > Screen (1280x1024)
**Screen 3:** PC => HDMI cable > AVR > HDMI cable > Screen (1920x1080)
The game runs on **screen 1**.

**Comment by mrmatteastwood** [comment] 2022-08-14 10:38
Output of lutris-d, taken while reproducing the issue:
[lutris-debug.txt](https://github.com/lutris/lutris/files/9333197/lutris-debug.txt)

**Comment by mrmatteastwood** [comment] 2022-08-17 13:58
I did some more testing. The following things do _not_ fix the issue:

- Enabling/disabling full-screen from the in-game video menu
- Launching the game in a virtual desktop (set in Winecfg > Graphics > Emulate a virtual desktop)

**Comment by strycore** [comment] 2023-06-06 05:06
I tested the game using the current lutris-GE-Proton8, with the sound output set to HDMI and the game ran without any issue.

This ran the game using my monitor's speakers, I guess this is specific to surround sound setups then?

**Comment by mrmatteastwood** [comment] 2023-06-06 07:26
Actually, I wouldn't be surprised if this was fixed now. Styx - Shards of Darkness (which I have on Steam) had the exact same issue and it stopped occurring about half a year ago. Thing is, I reinstalled my whole PC in late 2022 and I never reinstalled Lutris or LoF2, so I can't say for sure.

**Comment by strycore** [comment] 2023-06-06 23:24
Good to know the issue is fixed in another games.
Since there is an open ticket in the Proton repo and we base our Wine builds from Proton, this issue can be closed.

**Closed by strycore** 2023-06-06 23:24 UTC
