### ISSUE TITLE
Long names cause window expansion

### ISSUE THREAD

**Issue by Enteneller2017** [lutris/lutris#3517] opened 2021-04-20 19:24 UTC
Lutris 0.5.8.3
Very long names cause the window to expand far to the right, even outside of the screenspace, when you set the name in configure and then click on the game icon to activate it (zoom level max, toggle view to four rectangles).

**Comment by tannisroot** [comment] 2021-08-01 02:28
can you demonstrate?

**Comment by danieljohnson2** [comment] 2021-12-05 17:38
This is easily repro-ed; just set any game to a very long name that won't in the game bar. The game bar- and window- expand to fix, even if this is very long.

The right thing, I think, is to use the ellipsize_mode to truncate the name to fit the window. The problem is that the game-box is a Gtk.Fixed, and this limits our layout options quite a bit. GTK really wants to use a dynamic layout; a fixed one can break if the font is changed or the like.

I've worked a PR to change the game-box to using Gtk.Box. The layout is close to the original, but not quite the same, and some elements move a bit when changing selection. I think it's worthwhile, and it lets me set the ellipsize-mode and have it work.

**Closed** 2021-12-14 22:13 UTC
