### ISSUE TITLE
Lutris fails to terminate processes and shows game as running after having exited

### ISSUE THREAD

**Issue by txtsd** [lutris/lutris#2539] opened 2019-12-23 07:03 UTC
**Lutris is unable to terminate processes**

After quitting GW2, Lutris still displays a `Stop` button instead of `Play`. `htop` shows 4 wine processes sill running.

**Expected behavior**
After the game quits, Lutris should display a `Play` button on the game entry instead of `Stop`.

**Current behavior**
See bug description.

**Steps to reproduce**

- Launch GW2.
- Load any map.
- Quit game.
- Lutris still shows `Stop` button, is unable to terminate the processes, and therefore unable to launch the game again.

**Lutris debugging output**

```
INFO     2019-12-23 12:18:53,049 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2019-12-23 12:18:53,050 [startup.check_driver:62]:Using X.Org
INFO     2019-12-23 12:18:53,050 [startup.check_driver:64]:Running Mesa driver 19.3.1 on AMD RAVEN (DRM 3.35.0, 5.4.5-1-ck-zen, LLVM 9.0.0) (0x15dd)
INFO     2019-12-23 12:18:53,050 [startup.check_driver:77]:GPU: 1002:15DD 1462:7A34 using amdgpu drivers
INFO     2019-12-23 12:18:53,095 [startup.check_vulkan:132]:Vulkan is supported
INFO     2019-12-23 12:18:53,096 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2019-12-23 12:18:53,389 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2019-12-23 12:18:53,390 [store.get_missing_media:193]:Requesting missing icons from API for 15 games
DEBUG    2019-12-23 12:18:53,390 [http.get:65]:GET https://lutris.net/api/games
INFO     2019-12-23 12:18:53,399 [lutriswindow.toggle_connection:590]:Connected to lutris.net as txtsd
DEBUG    2019-12-23 12:18:53,407 [http.get:65]:GET https://lutris.net/api/games/library/txtsd
DEBUG    2019-12-23 12:18:53,415 [gog.get_library:176]:Returning cached GOG library
DEBUG    2019-12-23 12:18:53,420 [http.get:65]:GET https://lutris.net/api/games
INFO     2019-12-23 12:18:53,817 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2019-12-23 12:18:53,986 [api.get_game_api_page:132]:Loaded 32 games from page 1
DEBUG    2019-12-23 12:18:54,462 [api.get_game_api_page:132]:Loaded 9 games from page 1
DEBUG    2019-12-23 12:18:57,046 [application.launch:339]:Launching Guild Wars 2 (wine) (139900158963200)
DEBUG    2019-12-23 12:18:57,097 [game.play:297]:Prelaunching <lutris.runners.wine.wine object at 0x7f3d0b435bb0>
INFO     2019-12-23 12:18:57,427 [dxvk.disable_dxvk_dll:179]:Removing DXVK dll /home/txtsd/1TB/Games/guild-wars-2/drive_c/windows/system32/d3d9
INFO     2019-12-23 12:18:57,431 [dxvk.disable_dxvk_dll:179]:Removing DXVK dll /home/txtsd/1TB/Games/guild-wars-2/drive_c/windows/syswow64/d3d9
INFO     2019-12-23 12:18:57,432 [dxvk.enable_dxvk_dll:156]:Replacing /home/txtsd/1TB/Games/guild-wars-2/drive_c/windows/system32/d3d9 with D9VK version
INFO     2019-12-23 12:18:57,432 [dxvk.enable_dxvk_dll:156]:Replacing /home/txtsd/1TB/Games/guild-wars-2/drive_c/windows/syswow64/d3d9 with D9VK version
DEBUG    2019-12-23 12:18:57,432 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2019-12-23 12:18:57,459 [game.configure_game:331]:Launching Guild Wars 2: {'env': {'__GALLIUM_HUD': '.y30.c100GPU-load+cpu+fps', '__GALLIUM_HUD_PERIOD': '0.07', 'runtime': '-assetsrv:54.230.191.149', 'STEAM_RUNTIME': '/home/txtsd/.local/share/lutris/runtime/steam', 'LD_LIBRARY_PATH': '/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/lib:/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/lib64:/usr/lib/libfakeroot:/usr/lib/libupnp-1.8:/usr/lib/opencollada:/usr/lib32/libva1:/usr/lib/libva1:/usr/lib32:/usr/lib:/usr/lib64:/home/txtsd/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/txtsd/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/i386/lib:/home/txtsd/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/i386/usr/lib:/home/txtsd/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/txtsd/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/amd64/lib:/home/txtsd/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH', 'WINEDEBUG': '-all', 'WINEARCH': 'win64', 'WINE': '/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/bin/wine', 'WINEPREFIX': '/home/txtsd/1TB/Games/guild-wars-2', 'WINEESYNC': '1', 'WINEDLLOVERRIDES': 'd3d9=n', 'WINE_LARGE_ADDRESS_AWARE': '1'}, 'command': ['/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/bin/wine', '/home/txtsd/1TB/Games/guild-wars-2/drive_c/Program Files/Guild Wars 2/Gw2-64.exe', '-autologin', '-forwardrenderer', '-clientport:443']}
DEBUG    2019-12-23 12:18:57,459 [game.configure_game:332]:Game info: {
  "env": {
    "__GALLIUM_HUD": ".y30.c100GPU-load+cpu+fps",
    "__GALLIUM_HUD_PERIOD": "0.07",
    "runtime": "-assetsrv:54.230.191.149",
    "STEAM_RUNTIME": "/home/txtsd/.local/share/lutris/runtime/steam",
    "LD_LIBRARY_PATH": "/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/lib:/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/lib64:/usr/lib/libfakeroot:/usr/lib/libupnp-1.8:/usr/lib/opencollada:/usr/lib32/libva1:/usr/lib/libva1:/usr/lib32:/usr/lib:/usr/lib64:/home/txtsd/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/txtsd/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/i386/lib:/home/txtsd/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/i386/usr/lib:/home/txtsd/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/txtsd/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/amd64/lib:/home/txtsd/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH",
    "WINEDEBUG": "-all",
    "WINEARCH": "win64",
    "WINE": "/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/bin/wine",
    "WINEPREFIX": "/home/txtsd/1TB/Games/guild-wars-2",
    "WINEESYNC": "1",
    "WINEDLLOVERRIDES": "d3d9=n",
    "WINE_LARGE_ADDRESS_AWARE": "1"
  },
  "command": [
    "/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/bin/wine",
    "/home/txtsd/1TB/Games/guild-wars-2/drive_c/Program Files/Guild Wars 2/Gw2-64.exe",
    "-autologin",
    "-forwardrenderer",
    "-clientport:443"
  ]
}
DEBUG    2019-12-23 12:18:57,459 [command.start:112]:Running /usr/bin/lutris-wrapper 0 0 /home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/bin/wine /home/txtsd/1TB/Games/guild-wars-2/drive_c/Program Files/Guild Wars 2/Gw2-64.exe -autologin -forwardrenderer -clientport:443
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: SDL_VIDEO_FULLSCREEN_DISPLAY="off"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: __GALLIUM_HUD=".y30.c100GPU-load+cpu+fps"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: __GALLIUM_HUD_PERIOD="0.07"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: runtime="-assetsrv:54.230.191.149"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: STEAM_RUNTIME="/home/txtsd/.local/share/lutris/runtime/steam"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: LD_LIBRARY_PATH="/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/lib:/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/lib64:/usr/lib/libfakeroot:/usr/lib/libupnp-1.8:/usr/lib/opencollada:/usr/lib32/libva1:/usr/lib/libva1:/usr/lib32:/usr/lib:/usr/lib64:/home/txtsd/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/txtsd/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/i386/lib:/home/txtsd/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/i386/usr/lib:/home/txtsd/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/txtsd/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/amd64/lib:/home/txtsd/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/txtsd/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: WINEDEBUG="-all"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: WINEARCH="win64"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: WINE="/home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/bin/wine"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: WINEPREFIX="/home/txtsd/1TB/Games/guild-wars-2"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: WINEESYNC="1"
DEBUG    2019-12-23 12:18:57,460 [command.start:114]:ENV: WINEDLLOVERRIDES="d3d9=n"
DEBUG    2019-12-23 12:18:57,461 [command.start:114]:ENV: WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2019-12-23 12:18:57,461 [command.start:114]:ENV: game_name="Guild Wars 2"
DEBUG    2019-12-23 12:18:57,461 [command.start:114]:ENV: PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/lib/python3.8/site-packages"
Running /home/txtsd/.local/share/lutris/runners/wine/lutris-4.21-x86_64/bin/wine /home/txtsd/1TB/Games/guild-wars-2/drive_c/Program Files/Guild Wars 2/Gw2-64.exe -autologin -forwardrenderer -clientport:443
esync: up and running.
info:  Game: Gw2-64.exe
info:  DXVK: d9vk-0.40.1-croakacola-zero
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  AMD RADV RAVEN (LLVM 9.0.0):
info:    Driver: 19.3.1
info:    Vulkan: 1.1.107
info:    Memory Heap[0]: 
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x7
info:    Memory Heap[1]: 
info:      Size: 3072 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x7
info:      Memory Type[2]: Property Flags = 0xf
info:  Process set as DPI aware
info:  Game: Gw2-64.exe
info:  DXVK: d9vk-0.40.1-croakacola-zero
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  AMD RADV RAVEN (LLVM 9.0.0):
info:    Driver: 19.3.1
info:    Vulkan: 1.1.107
info:    Memory Heap[0]: 
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x7
info:    Memory Heap[1]: 
info:      Size: 3072 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x7
info:      Memory Type[2]: Property Flags = 0xf
info:  Process set as DPI aware
info:  Game: Gw2-64.exe
info:  DXVK: d9vk-0.40.1-croakacola-zero
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  AMD RADV RAVEN (LLVM 9.0.0):
info:    Driver: 19.3.1
info:    Vulkan: 1.1.107
info:    Memory Heap[0]: 
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x7
info:    Memory Heap[1]: 
info:      Size: 3072 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x7
info:      Memory Type[2]: Property Flags = 0xf
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : AMD RADV RAVEN (LLVM 9.0.0)
info:    Driver version   : 19.3.1
info:  Enabled device extensions:
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_conditional_rendering
info:    conditionalRendering                   : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 0
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
info:  DXVK: Read 12604 valid state cache entries
info:  DXVK: Using 4 compiler threads
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1912
info:      - Height:             1026
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1912x1026
info:    Image count:  3
info:    Exclusive FS: 0
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1080
info:    Image count:  3
info:    Exclusive FS: 0
mesa: for the   --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the   --global-isel-abort option: may only occur zero or one times!
DEBUG    2019-12-23 12:20:39,511 [game_actions.on_stop:172]:Removed game with ID 14 from running games
Caught signal 15
passing along signal to PID 196787
passing along signal to PID 196885
--terminated processes--
DEBUG    2019-12-23 12:20:41,497 [game_actions.on_stop:172]:Removed game with ID 14 from running games
Caught another signal, sending SIGKILL.
--killed processes--
DEBUG    2019-12-23 12:20:43,608 [game_actions.on_stop:172]:Removed game with ID 14 from running games
Caught another signal, sending SIGKILL.
--killed processes--
DEBUG    2019-12-23 12:20:45,491 [game_actions.on_stop:172]:Removed game with ID 14 from running games
Caught another signal, sending SIGKILL.
--killed processes--
DEBUG    2019-12-23 12:20:47,356 [game_actions.on_stop:172]:Removed game with ID 14 from running games
Caught another signal, sending SIGKILL.
--killed processes--
DEBUG    2019-12-23 12:20:52,964 [game_actions.on_stop:172]:Removed game with ID 14 from running games
Caught another signal, sending SIGKILL.
--killed processes--
```

**System information**
https://www.mediafire.com/file/lzece1kcp3sh9eo/lutris-issue-report.json/file

**Comment by mihawk90** [comment] 2019-12-26 21:59
The way you describe it this is actually the expected behaviour, because:

> `htop` shows 4 wine processes sill running.

Lutris is not responsible for killing the WINE process. It only checks if the process is still there, and if not changes its status from playing to not playing.

WINE should terminate on its own when the Game is closed, so there's something going on on your system, but it's not Lutris.

On a sidenote: I can not reproduce this with GW2 either (neither the "normal" nor the D9VK version). It changes the status right when the game quits.

**Comment by txtsd** [comment] 2019-12-26 23:30
It doesn't happen every time, just more often than not. How would I go about debugging this? I'm not using custom wine or DLLs, it's whatever comes with lutris and the latest runners.

**Comment by AaronOpfer** [comment] 2019-12-27 16:45
Which game processes are still open when this happens?

**Comment by txtsd** [comment] 2019-12-28 13:48
Just these. They have to be `SIGKILL`'d to terminate.

![2019-12-28-191438_639x237_scrot](https://user-images.githubusercontent.com/768728/71544514-828fe600-29a6-11ea-8da4-1582107bb9d5.png)

**Comment by txtsd** [comment] 2020-01-04 05:09
It's not happening anymore so I'll close this, but I'll reopen and post the processes if it happens again.

**Comment by txtsd** [comment] 2020-01-05 09:53
Here we go!

![2020-01-05-152145_1424x237_scrot](https://user-images.githubusercontent.com/768728/71778096-3dd00480-2fcf-11ea-8d8e-196f999e4d95.png)

**Comment by strycore** [comment] 2020-01-06 00:12
I've reproduced this as well.

**Comment by AaronOpfer** [comment] 2020-01-06 00:29
Hmm, not sure where to go with this. The fact that only wine processes are left suggests a wine bug. If there's no more wine clients then it should exit.

**Comment by txtsd** [comment] 2020-01-06 06:56
Bisecting between wine versions won't really work because the bug only occurs sometimes, not all the time.

**Comment by txtsd** [comment] 2020-01-06 06:57
@strycore Did it happen to you with GW2 + D9VK? Or just GW2? Or another game?

**Comment by byte1024** [comment] 2020-04-07 19:26
I've seen this. Then I kill Wine as the only working quick way to get it to stop and Lutris can't play anything again until a reboot.

Though, I've not looked into beyond that. Just figured it would have been fixed by now.

**Comment by byte1024** [comment] 2020-04-07 20:21
I notice that if you can still see a little wine popup window in the corner, can click on the icon icon site (in my test case its the Origin application icon) and the Wine process couldn't terminate because of a child window or (separate window from the main application window) that's still open.

Clicking on that anyway, if the other window shows up, you can close it and the Wine process will finish.

Wine should be closing all sub windows if the main window is closed.

**Comment by txtsd** [comment] 2020-04-08 16:21
I haven't had this problem since the wine version I used in this report.

**Comment by strycore** [comment] 2020-04-11 17:15
I'm going to close this issue then since it does not provide me with material I can work on and just stresses me out.

**Closed by strycore** 2020-04-11 17:15 UTC
