### ISSUE TITLE
Lutris fails to run in latest Debian Testing

### ISSUE THREAD

**Issue by jimj316** [lutris/lutris#2679] opened 2020-03-23 17:52 UTC
**Describe the bug**

On the latest Debian Testing, when Lutris is started, the GUI never appears and the process runs forever. No output is generated, and it doesn't crash.

**Expected behavior**

Lutris should run as normal.

**Current behavior**

Lutris hangs forever and produces no output, even when started with -d. `lutris --help` still works; `lutris --version` returns nothing and finishes with code 0; `lutris --submit-issue` works as normal. It also ignores SIGINT, so can't be stopped with ctrl-C, but dies to SIGTERM and SIGKILL.

**Steps to reproduce**

- Launch Lutris, from the window or the command line.

**Lutris debugging output**

None.

**System information**

[lutris-issue-report.zip](https://github.com/lutris/lutris/files/4361447/lutris-issue-report.zip)

I first noticed this about three days ago; I think Lutris was last working about a week ago, but I'm not exactly sure. Lutris itself hasn't been updated since November, but there were some python packages updated recently which might be related. I've attached the end of my [apt-history.log](https://github.com/lutris/lutris/files/4371070/apt-history.log) so you can see which ones.

I'm happy to provide whatever other information is needed, including using debugging tools if someone tells me how to use them! :)

**Comment by Vinjul1704** [comment] 2020-03-24 01:32
Same issue here, but on Debian Unstable/Sid. I already tried to reinstall both lutris and python3, but it didn't help. It launches fine with _sudo_ in my case, but as a normal user nothing happens. Nothing opens, no console output and it doesn't react to ctrl+c. Running _strace_ gives me the following at the end:
```
  File "/usr/bin/lutris", line 37, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 44, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 251, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
```

**Comment by jimj316** [comment] 2020-03-24 17:50
Apparently after doing a full reinstall (I swear I did one before!) it now produces output:
```
jimj316@deskneko:~$ lutris -d
INFO     2020-03-23 17:56:25,615 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-03-23 17:56:25,615 [startup.check_driver:62]:Using X.Org
INFO     2020-03-23 17:56:25,615 [startup.check_driver:67]:Running Mesa driver 19.3.3 on AMD Radeon (TM) RX 460 Graphics (POLARIS11, DRM 3.35.0, 5.4.0-4-amd64, LLVM 9.0.1) (0x67ef)
INFO     2020-03-23 17:56:25,616 [startup.check_driver:79]:GPU: 1002:67EF 1682:9460 using amdgpu drivers
INFO     2020-03-23 17:56:25,663 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-03-23 17:56:25,667 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 321, in get_store
    self.show_installed_first,
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
INFO     2020-03-23 17:56:26,488 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
```
It still hangs forever on "Updating D9VK versions", but now responds to SIGINT.

**Comment by Vinjul1704** [comment] 2020-03-24 17:58
That one can actually be fixed using this workaround: https://github.com/lutris/lutris/issues/2657#issuecomment-600447443
The issue I am having appears after doing that though.

**Comment by jimj316** [comment] 2020-03-24 18:30
I just applied that workaround and Lutris now works fine, so I guess reinstalling fixed it.
To clarify, I reinstalled by doing `apt purge lutris` and then installing the latest .deb from the Lutris website.

**Comment by surmeier** [comment] 2020-03-24 21:14
I am getting the same errors on Debian sid with `strace` as @Vinjul1704, with `KeyboardInterrupt` (w/o inputting ctrl-C) being the last output before the output hangs.

**Comment by tannisroot** [comment] 2020-03-26 23:57
Duplicate of https://github.com/lutris/lutris/issues/2554 .
Just use master until 0.5.5 comes out.
Also, please don't launch Lutris as sudo - it fucks up with permissions.

**Closed by tannisroot** 2020-03-26 23:57 UTC

**Comment by FireCulex** [comment] 2020-03-28 15:35
@tannisroot I think there's some confusion. I'm using the master and this error is happening.

**Comment by strycore** [comment] 2020-03-28 17:18
> @tannisroot I'm using the latest git and this error is happening.

No it's not.

**Comment by FireCulex** [comment] 2020-03-28 18:10
@strycore your right I must have somehow gotten confused.
