### ISSUE TITLE
Update tools download with InnoExtract 1.8

### ISSUE THREAD

**Issue by hydrian** [lutris/lutris#2813] opened 2020-04-29 17:54 UTC
GoG released a new version of the Inno installer. The current version of Innoextract is tool old. The only version in the tools dir are from 2015 or 2018. The 1.8 version of InnoExtract was released Sept. of 2019. 

Would you please upload InnoExtract 1.8 to https://lutris.net/files/tools/

Source Location: 
https://constexpr.org/innoextract/files/innoextract-1.8/

**Comment by xordspar0** [comment] 2020-04-29 18:13
This is a duplicate of https://github.com/lutris/lutris/issues/2778

**Closed** 2020-04-30 17:41 UTC
