### ISSUE TITLE
Battle.net being killed when running with process monitor

### ISSUE THREAD

**Issue by kiljacken** [lutris/lutris#973] opened 2018-07-20 14:53 UTC
I'm having issues with the Battle.net launcher being killed by lutris (0.4.18) when running with process monitor enabled (the default).

**Comment by duhow** [comment] 2018-07-21 09:15
Are you using the Lutris Battle.net installer, or just doing it manually?
Be sure that `Agent.exe "Battle.net Helper.exe"` are excluded processes so they won't close.

**Comment by L3vi47h4N** [comment] 2018-08-07 22:07
I also experience this issue and I suspect it is to blame for my install failing. Is there any way to easily modify and run the script?

**Comment by strycore** [comment] 2018-08-16 06:36
Can someone check if this still an issue on the current master branch?

**Comment by tannisroot** [comment] 2018-08-17 14:13
I don’t experience this with Battle.Net launcher personally. Can’t test other launchers.

**Comment by L3vi47h4N** [comment] 2018-08-21 03:59
Can we just like, get an option to edit the provisioning script locally on
our machine? Like being able to add or modify things to get it working
shouldn't have to be this hard. Like come on, a local script import or
something mates.

I'm getting the same issues. Debian unstable. Nvidia proprietary drivers.

**Comment by tannisroot** [comment] 2018-08-21 04:01
Please check if switching the wine version to 3.14 helps.

**Comment by duhow** [comment] 2018-08-21 10:00
Tested with `esync-3.14` and `staging-3.14`, the launcher still closes. Also having more FPS drops (trying to load models?), staying with `pba-firerat-3.11` works better.

**Comment by tannisroot** [comment] 2018-08-21 17:29
What about using Lutris 4.19 from master (from this merge request to fix DXVK dlls https://github.com/lutris/lutris/pull/1046)

**Comment by robzombie91** [comment] 2018-08-26 14:43
i can confirm for whatever reason whenever i try to enable dxvk while launching the blizzard launcher the agent.exe always fails until i disable dxvk, then it starts working again

**Comment by joeknock90** [comment] 2018-08-30 19:38
Confirming same thing on Arch Linux.

**Comment by camdenorrb** [comment] 2018-09-03 21:57
I'm experiencing this, Ubuntu 18.04

**Comment by camdenorrb** [comment] 2018-09-05 05:40
Appears to be fixed in latest Lutris

**Comment by kiljacken** [comment] 2018-09-07 13:43
The issue _STILL_ occurs as of the latest commit to master.

**Comment by kiljacken** [comment] 2018-09-09 08:16
@strycore Would you mind re-opening the issue? It is still not solved. Thank you

**Comment by L3vi47h4N** [comment] 2018-09-10 11:55
Issue is still present on Debian with latest lutris from both repo and git.

**Comment by strycore** [comment] 2018-09-10 18:35
this bug report is low quality, please provide better information to get a proper resolution.

**Comment by kiljacken** [comment] 2018-09-11 13:51
@strycore Okay, here is an info dump, please do ask if more is needed, as I can't read minds :)

* Arch Linux on kernel 4.18.6
* Lutris from git commit d984f64
* Installed via Dox's World of Warcraft installation script (so wine esync-3.14-x86_64 by default)
* Installing Battle.net, when you reach the login dialog, Lutris kills the entire thing, unless you disable the process monitor
* If you login with process monitor disabled, you can succefully do that, but enabling it again afterwards kills the launcher itself

**Comment by tannisroot** [comment] 2018-09-13 15:03
@kiljacken what if you add this to "Include processes"?
`Battle.net Laun, Battle.net.exe`
![screenshot from 2018-09-13 18-02-14](https://user-images.githubusercontent.com/10602045/45496980-43bd2900-b77f-11e8-8363-4e3955488534.png)

**Comment by kiljacken** [comment] 2018-09-13 16:46
@tannisroot That does not seem to help, no.

For people having the problem: Launching `Battle.net.exe` directly instead of `Battle.net Launcher.exe` seems to alleviate the problem, at least this process can run with process monitor enabled.

**Comment by tannisroot** [comment] 2018-09-13 17:07
Do you do anything out of the ordinary when you install the game? Like maybe install the prefix on an NTFS drive or any kind of separate partition, or anything else?

**Comment by kiljacken** [comment] 2018-09-13 17:53
@tannisroot Subvolume on a btrfs partition. No weird settings changed, just the defaults in Dox's installer.

**Comment by tannisroot** [comment] 2018-09-13 17:55
Can you try installing it on an ext4 partition, preferably at $HOME (if your home partition is in ext4 ofc)?

**Comment by kiljacken** [comment] 2018-09-13 17:56
Home is btrfs, but I can take a backup and do an install on ext4 during the weekend.

**Comment by joeknock90** [comment] 2018-09-13 17:59
@tannisroot I've got Dox's DXVK installed on an ext home folder and am having the same issue.

**Comment by strycore** [comment] 2018-11-01 23:00
Please open a specific issue if there is indeed a problem with special filesystems. I've tested a Battle.net install on the current master and experienced no problem.

**Comment by zatricky** [comment] 2018-11-03 14:29
@strycore, did you really close this just because the OP happened later to mention what filesystem he's using?

**Comment by strycore** [comment] 2018-11-03 22:30
@zatricky no, mostly due to the fact that I couldn't reproduce the issue and that this ticket a complete mess that is impossible to get anything useful out of. 

That, plus I think the commit I've pushed the fix to this issue yesterday.

**Comment by kiljacken** [comment] 2018-11-04 15:10
@strycore I would sincerely appreciate if you left the issue open. As per the latest commit as of writing, the issue still occurs: https://www.youtube.com/watch?v=0fM7We0rRJ4

I've been available to help with whatever is needed all along, I just have no idea how Lutris is structured, so I need one of the developers who understand the code to take the lead. Thanks.

**Comment by strycore** [comment] 2018-11-04 22:49
@kiljacken your video doesn't have console output so I can't reopen the ticket.

**Comment by kiljacken** [comment] 2018-11-06 16:16
@strycore Newly recorded video (kinda unnecessary i guess): https://www.youtube.com/watch?v=WV4doreG6us

The Lutris log for the filmed run: https://gist.github.com/kiljacken/ccf009a0dd62d0b86cd41a0f80da1a05

Hopefully that is enough to get the ball rolling.

**Comment by strycore** [comment] 2018-11-06 17:46
Thanks! 
Also, I pushed a fix for the monitor in 0.4.22 which was supposed to help with Warframe and I can still reproduce the issue so my fix was incomplete. I think those are related and fixing the issue in Warframe will likely solve it for Battle.net

**Comment by kiljacken** [comment] 2018-11-07 16:37
In 0.4.23 the launcher stays open a noticable bit longer, but is still killed. I would guess that maybe Lutris fails to properly identify the child processes.

I'm not sure if I ever  got around to asking: @strycore if you try installing with https://lutris.net/games/world-of-warcraft/ does it just work for you? You don't actually need the game or an account, as the issue occurs really early in the process.

**Comment by kharin** [comment] 2018-11-10 21:38
Can confirm. Arch, Lutris 0.4.23: launcher's getting killed in 5-10 seconds regardless of my actions. Weirdly enough, mine is also on a btrfs subvolume. Checking "Disable system monitor" does fix the issue. (thanks @kiljacken!)

**Comment by StefanTT** [comment] 2018-11-12 07:00
The same happens for the lord of the rings online launcher. Not at first start but during some later stage of installing the game. Installing the base packages works but after then the issue occurs every time.

Disabling the system monitor also fixes the issue here.

**Comment by vafrederico** [comment] 2018-11-16 07:52
Can also confirm that Lutris 0.4.23 continues to have problem with the process monitor on Arch (Antergos). I moved my home from ext4 to btrfs, and the problem happened. Note that the game was already in a btrfs subvolume, prior to moving the home.
Adding "Battle.net Laun" to exclude processes helps with the issue.
This also affects other games, e.g: LoL. On this case, adding "LeagueClient.ex" to exclude processes fixes the issue.
I will try tomorrow to debug the cause, but looks like the processes names being truncated to 15 characters are the problem.

**Comment by vafrederico** [comment] 2018-11-16 18:30
After some more tests, the problem is not truncating, as it is truncated. What is weird is having to add "Battle.net Launcher.exe" and "LeagueClient.exe" as excluded processes when it wasn't needed before.

**Comment by vafrederico** [comment] 2018-11-16 18:52
The problem, at least in regards to battle.net, the problem seems to be related to detecting child processes when the launcher start new processes and exits. Changing to run "Battle.net.exe" directly fix the issue as well.

**Comment by bjoern-tantau** [comment] 2018-11-20 08:48
The issue exists for Star Wars: The Old Republic as well. The launcher works, but the game silently quits as soon as the actual game should start. Launching the game without Lutris or disabling the process monitor works.
I couldn't get any usable output or logs. Thanks to this issue at least I know that it has something to do with the process monitor.

**Comment by StefanTT** [comment] 2018-11-20 09:57
I would really appreciate if there was an option to disable the warning dialog about disabled process monitoring as long as this problem exists.

**Comment by strycore** [comment] 2018-11-20 23:07
Not going to happen, this is a serious issue and the process monitor shouldn't kill processes like that. The only proper solution is to fix the monitor, the warning is not going anywhere.

**Comment by StefanTT** [comment] 2018-11-21 08:54
This constantly annoys the users meanwhile that have the problem.
But hey, it's your choice of course.

Looking forward to getting it fixed :-)

**Comment by strycore** [comment] 2018-12-18 07:43
I'm going to close this issue.

* The disable monitor option is removed (so is the annoying message)
* The process monitor code has been extracted into its own module, hopefully making it easier for contributors to debug issues
* A new option monitor_max_cycles has been added, the default value is 5 meaning Lutris will wait 5 *  2 second cycles : 10 seconds before considering a game as exited. You can increase this value as much as you want and use it in scripts.
* A new PR was merged in that solved other, potentially related monitoring issues.

If you are using btrfs and are still experiencing issues when running the *current* `next` branch, then please open an issue specifically about that.

**Closed by strycore** 2018-12-18 07:43 UTC
Labels: needs confirmation, poor quality report

**Comment by kiljacken** [comment] 2018-12-18 18:40
I can confirm that #1415 solves the issue for me.
