### ISSUE TITLE
Sorting menu is broken

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2532] opened 2019-12-21 23:55 UTC
See:
![Screenshot from 2019-12-22 02-53-32](https://user-images.githubusercontent.com/10602045/71315088-4a4c4d00-2466-11ea-8545-7a1a958ba3a2.png)

**Comment by tannisroot** [comment] 2019-12-21 23:56
@Appadeia not sure but I think it regressed due to your PR

**Comment by Appadeia** [comment] 2019-12-22 00:11
This doesn't look like it would have been caused by my PR, but I'll investigate.

**Comment by Appadeia** [comment] 2019-12-22 00:25
Looks like the bug is caused by [this](https://gitlab.gnome.org/GNOME/gtk/issues/939), but I wonder why it's only surfacing now.

**Comment by Appadeia** [comment] 2019-12-22 00:46
Actually, it does seem that the action targets got dropped in my PR somehow. Fixing that, then I'll open a new one.

**Comment by strycore** [comment] 2019-12-22 01:13
PR merged

**Closed by strycore** 2019-12-22 01:13 UTC
