### ISSUE TITLE
Could we have clearly marked Wine releases back?

### ISSUE THREAD

**Issue by fosspill** [lutris/lutris#2169] opened 2019-05-29 18:26 UTC
Apologies if this is the wrong place to request this.

**Describe the issue**

Lutris used to have pretty clearly marked wine releases available, as seen in the attached screenshot.

Now it's hard to know what each contains and what it is meant for. It also seems like the consistency of naming has been dropped.

***An example***
Look at the attached screenshot and figure out which build is the most recent which contains the FFXIV launcher patch.

Correct answer, seems to be: _ge-faudio-protonified-4.8_

**How it should(could?) be**
Everything from 4.6 and down in the screenshot is decently and consistently named. I believe this was a good standard and should be followed.

**Screenshots**

![Screenshot from 2019-05-29 20-18-21](https://user-images.githubusercontent.com/1491401/58581104-0a661400-824f-11e9-9ba9-25ad2fb0a941.png)

**Comment by AccountOneOff** [comment] 2019-06-02 03:31
Duplicate of https://github.com/lutris/lutris/issues/613

Ignore the closed tag. I don't know how far along @AlexanderRavenheart got or if it's close to being finished.

**Closed by AccountOneOff** 2019-06-02 03:31 UTC
Labels: suggestion

**Comment by fosspill** [comment] 2019-06-04 08:11
Sort of a duplicate indeed, but the suggestion here is to continue doing what was done with the naming of the tkg- builds. That should be quicker to (re)implement than waiting for a proper dialog.

**Comment by AlexanderRavenheart** [comment] 2019-06-04 13:26
Sorry for not posting any more updates on this topic. I've been very busy with my studies and too stressed and tired to make any further development. I will have more time for contributing to this 2 weeks from now.
