### ISSUE TITLE
Lutris won't launch; stuck updating D9VK

### ISSUE THREAD

**Issue by YamiYukiSenpai** [lutris/lutris#2685] opened 2020-03-27 02:59 UTC
**Describe the bug**
When I try launching Lutris from the terminal:
```
2020-03-26 22:35:15,986: Running Lutris 0.5.4
2020-03-26 22:35:15,987: Using NVIDIA drivers 440.64 for x86_64
2020-03-26 22:35:15,987: GPU: GeForce GTX 1060 6GB
2020-03-26 22:35:15,987: GPU: 10DE:1C03 19DA:1438 using nvidia drivers
2020-03-26 22:35:16,052: Vulkan is supported
2020-03-26 22:35:16,057: Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2020-03-26 22:35:16,695: Updating D9VK versions


```

**Expected behavior**
Lutris should launch.

**Current behavior**
Nothing pops up

**Steps to reproduce**

- Launch Lutris

**Lutris debugging output**

The terminal output of `lutris -d`.

```
INFO     2020-03-26 22:49:14,558 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-03-26 22:49:14,559 [startup.check_driver:54]:Using NVIDIA drivers 440.64 for x86_64
INFO     2020-03-26 22:49:14,559 [startup.check_driver:60]:GPU: GeForce GTX 1060 6GB
INFO     2020-03-26 22:49:14,559 [startup.check_driver:77]:GPU: 10DE:1C03 19DA:1438 using nvidia drivers
INFO     2020-03-26 22:49:14,613 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-03-26 22:49:14,614 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
INFO     2020-03-26 22:49:14,975 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
2020-03-26 22:55:25,410: Running Lutris 0.5.4
2020-03-26 22:55:25,410: Using NVIDIA drivers 440.64 for x86_64
2020-03-26 22:55:25,410: GPU: GeForce GTX 1060 6GB
2020-03-26 22:55:25,411: GPU: 10DE:1C03 19DA:1438 using nvidia drivers
2020-03-26 22:55:25,447: Vulkan is supported
2020-03-26 22:57:49,752: Running Lutris 0.5.4
2020-03-26 22:57:49,753: Using NVIDIA drivers 440.64 for x86_64
2020-03-26 22:57:49,753: GPU: GeForce GTX 1060 6GB
2020-03-26 22:57:49,753: GPU: 10DE:1C03 19DA:1438 using nvidia drivers
2020-03-26 22:57:49,798: Vulkan is supported
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'

```

**System information**
Attached the JSON file as TXT file.
[lutris-issue-report.txt](https://github.com/lutris/lutris/files/4391243/lutris-issue-report.txt)

**Comment by YamiYukiSenpai** [comment] 2020-03-27 03:00
[lutris-issue-report.txt](https://github.com/lutris/lutris/files/4391239/lutris-issue-report.txt)
Attached the JSON file as text file.

**Comment by tannisroot** [comment] 2020-03-27 05:24
Duplicate of https://github.com/lutris/lutris/issues/2554

**Closed by tannisroot** 2020-03-27 05:24 UTC
