### ISSUE TITLE
AttributeError: 'Application' object has no attribute 'add_main_option' on start

### ISSUE THREAD

**Issue by Konfuz** [lutris/lutris#471] opened 2017-01-12 09:30 UTC
Starting lutris does not work on my system anymore for a while now.  I suspect my GTK-Version is not up to date, but the bodhi-linux I am using is not providing any newer. 

The error I receive when trying to start lutris:
```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 27, in <module>
    app = Application()
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 48, in __init__
    self.add_main_option('debug',
AttributeError: 'Application' object has no attribute 'add_main_option'
```

A quick google search found me the same problem on different github-hosted python-projects that was fixed. You might be able to 'steal' a solution there.

I have the following GTK Versions installed
```
ii  libgtk-3-0:amd64                  3.10.8-0ubuntu1.6     amd64                 GTK+ graphical user interface library
ii  libgtk-3-0:i386                   3.10.8-0ubuntu1.6     i386                  GTK+ graphical user interface library
ii  libgtk2.0-0:amd64                 2.24.23-0ubuntu1.4    amd64                 GTK+ graphical user interface library
ii  libgtk2.0-0:i386                  2.24.23-0ubuntu1.4    i386                  GTK+ graphical user interface library
```

**Comment by TingPing** [comment] 2017-01-12 10:22
Duplicate of #464

**Comment by Konfuz** [comment] 2017-01-12 10:27
> Duplicate of #464 

Oh, sorry! 

I did not search properly :frowning_face:

**Closed** 2017-01-12 10:27 UTC
Labels: duplicate
