### ISSUE TITLE
[Bug] Flatpack running on old version

### ISSUE THREAD

**Issue by Benjamin-Berger** [lutris/lutris#4632] opened 2022-12-04 14:06 UTC
The latest version of Lutris is 5.12, but the flatpack still has version 5.11. https://flathub.org/apps/details/net.lutris.Lutris

**Comment by JoshStrobl** [comment] 2022-12-04 17:29
Duplicate of #4624

**Comment by danieljohnson2** [comment] 2022-12-04 17:30
It sure is. And #4624 is the cool one. Closing.

**Closed by danieljohnson2** 2022-12-04 17:30 UTC
