### ISSUE TITLE
Retroarch has runtime issues on some systems

### ISSUE THREAD

**Issue by odce1206** [lutris/lutris#545] opened 2017-03-19 00:37 UTC
I tried playing a couple of emulated games with different runners (libretro, mednafen, desmume, snes9x. mupen64) and I wasnt able to play any of them, the only console Im able to play with is n64. Here is what is returned if I run 2 different games.

## Example 1 - _Chrono Trigger w libretro_:

`DEBUG    2017-03-18 18:35:49,930 [system]:Executing which steam
DEBUG    2017-03-18 18:35:53,464 [config_dialogs]:Saved Chrono Trigger
DEBUG    2017-03-18 18:35:53,479 [system]:Executing which steam
WARNING  2017-03-18 18:35:54,612 [libretro]:Unable to find retroarch config. Except erratic behavior
DEBUG    2017-03-18 18:35:54,770 [game]:Launching Chrono Trigger: {'command': ['/home/sudojar/.local/share/lutris/runners/retroarch/retroarch', '--config=/home/sudojar/.local/share/lutris/runners/retroarch/retroarch.cfg', '--libretro=/home/sudojar/.local/share/lutris/runners/retroarch/cores/snes9x_libretro.so', '/home/sudojar/Documents/ROMS/snes/Chrono Trigger (USA).sfc']}
DEBUG    2017-03-18 18:35:54,772 [thread]:Command env: LD_PRELOAD="" LD_LIBRARY_PATH="/home/sudojar/.local/share/lutris/runtime/lib32:/home/sudojar/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/i386/lib:/home/sudojar/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/i386/usr/lib:/home/sudojar/.local/share/lutris/runtime/lib64:/home/sudojar/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/amd64/lib:/home/sudojar/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH" SDL_VIDEO_FULLSCREEN_DISPLAY="off" STEAM_RUNTIME="/home/sudojar/.local/share/lutris/runtime/steam" 
DEBUG    2017-03-18 18:35:54,773 [thread]:Running command: "/home/sudojar/.local/share/lutris/runners/retroarch/retroarch" "--config=/home/sudojar/.local/share/lutris/runners/retroarch/retroarch.cfg" "--libretro=/home/sudojar/.local/share/lutris/runners/retroarch/cores/snes9x_libretro.so" "/home/sudojar/Documents/ROMS/snes/Chrono Trigger (USA).sfc"
DEBUG    2017-03-18 18:35:54,773 [thread]:Storing environment variable LD_PRELOAD to 
DEBUG    2017-03-18 18:35:54,774 [thread]:Storing environment variable LD_LIBRARY_PATH to /home/sudojar/.local/share/lutris/runtime/lib32:/home/sudojar/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/i386/lib:/home/sudojar/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/i386/usr/lib:/home/sudojar/.local/share/lutris/runtime/lib64:/home/sudojar/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/amd64/lib:/home/sudojar/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH
DEBUG    2017-03-18 18:35:54,775 [thread]:Storing environment variable SDL_VIDEO_FULLSCREEN_DISPLAY to off
DEBUG    2017-03-18 18:35:54,775 [thread]:Storing environment variable STEAM_RUNTIME to /home/sudojar/.local/share/lutris/runtime/steam
/home/sudojar/.local/share/lutris/runners/retroarch/retroarch: symbol lookup error: /lib64/libXv.so.1: undefined symbol: _XEatDataWords
DEBUG    2017-03-18 18:35:56,277 [thread]:18239	Z	retroarch
DEBUG    2017-03-18 18:35:56,278 [thread]:All children terminated
DEBUG    2017-03-18 18:35:57,776 [thread]:No children left in thread
DEBUG    2017-03-18 18:35:59,274 [game]:Game thread stopped
DEBUG    2017-03-18 18:35:59,275 [game]:Chrono Trigger stopped at Sat, 18 Mar 2017 18:35:59
DEBUG    2017-03-18 18:35:59,371 [display]:Switching to 1366x768+0+0 on LVDS1
`
## Example 2 - _LOZ A Link to the Past w snes9x_:

`DEBUG    2017-03-18 18:37:31,244 [system]:Executing which steam
DEBUG    2017-03-18 18:37:35,582 [game]:Launching The Legend of Zelda: A Link to the Past: {'command': ['/home/sudojar/.local/share/lutris/runners/snes9x/bin/snes9x-gtk', '/home/sudojar/Documents/ROMS/snes/Legend of Zelda, The - A Link to the Past (USA).sfc']}
DEBUG    2017-03-18 18:37:35,585 [thread]:Command env: LD_PRELOAD="" LD_LIBRARY_PATH="/home/sudojar/.local/share/lutris/runtime/lib32:/home/sudojar/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/i386/lib:/home/sudojar/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/i386/usr/lib:/home/sudojar/.local/share/lutris/runtime/lib64:/home/sudojar/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/amd64/lib:/home/sudojar/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH" SDL_VIDEO_FULLSCREEN_DISPLAY="off" STEAM_RUNTIME="/home/sudojar/.local/share/lutris/runtime/steam" 
DEBUG    2017-03-18 18:37:35,586 [thread]:Running command: "/home/sudojar/.local/share/lutris/runners/snes9x/bin/snes9x-gtk" "/home/sudojar/Documents/ROMS/snes/Legend of Zelda, The - A Link to the Past (USA).sfc"
DEBUG    2017-03-18 18:37:35,586 [thread]:Storing environment variable LD_PRELOAD to 
DEBUG    2017-03-18 18:37:35,587 [thread]:Storing environment variable LD_LIBRARY_PATH to /home/sudojar/.local/share/lutris/runtime/lib32:/home/sudojar/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/i386/lib:/home/sudojar/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/i386/usr/lib:/home/sudojar/.local/share/lutris/runtime/lib64:/home/sudojar/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/amd64/lib:/home/sudojar/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/sudojar/.local/share/lutris/runtime/steam/amd64/usr/lib:$LD_LIBRARY_PATH
DEBUG    2017-03-18 18:37:35,588 [thread]:Storing environment variable SDL_VIDEO_FULLSCREEN_DISPLAY to off
DEBUG    2017-03-18 18:37:35,589 [thread]:Storing environment variable STEAM_RUNTIME to /home/sudojar/.local/share/lutris/runtime/steam
/home/sudojar/.local/share/lutris/runners/snes9x/bin/snes9x-gtk: symbol lookup error: /lib64/libpangoft2-1.0.so.0: undefined symbol: FcWeightToOpenType
DEBUG    2017-03-18 18:37:37,089 [thread]:18292	Z	snes9x-gtk
DEBUG    2017-03-18 18:37:37,090 [thread]:All children terminated
DEBUG    2017-03-18 18:37:38,590 [thread]:No children left in thread
DEBUG    2017-03-18 18:37:40,089 [game]:Game thread stopped
DEBUG    2017-03-18 18:37:40,090 [game]:The Legend of Zelda: A Link to the Past stopped at Sat, 18 Mar 2017 18:37:40
DEBUG    2017-03-18 18:37:40,171 [display]:Switching to 1366x768+0+0 on LVDS1
`

I'm on Fedora 25. 6 GB RAM, intel i5

**Comment by strycore** [comment] 2017-03-19 00:57
Run this script: /usr/share/lutris/bin/desktop_info.sh and send it back here to see what system you're running. FYI, Snes9x, Mednafen and Mupen64 are all going to be removed soon in favor of retroarch.

The problem you're having is with the Lutris runtime, you can try figuring out which library is causing issues by following the instructions provided here: http://wiki.lutris.net/index.php/Runtime

**Comment by strycore** [comment] 2017-04-04 02:58
The libpangotf2 issue occuring with Snes9x has now been fixed. There seems to be another runtime error related to Xorg libs with Retroarch (which I can't reproduce). 

Try with the updated runtime and tell me if you still have issues with retroarch (no manual intervention needed, the new runtime will download next time you start lutris)

**Comment by strycore** [comment] 2017-04-04 03:18
I tried running Retroarch on an Arch VM (where it was most likely to cause problems) and I had issues running Retroarch on Gnome/Wayland but in Gnome/Xorg, it launched fine.

Please note that running Lutris with Wayland is currently not supported. (Although I don't think you are since you get a libXv error).

**Comment by strycore** [comment] 2017-04-07 10:23
I've setup a Fedora 25 VM and managed to reproduce the issue with RetroArch. Should be trivial to fix, I'll take care of it tomorrow.

**Comment by odce1206** [comment] 2017-05-18 17:26
Thanks, sorry for not replying, I had some irl issues. Yes, I was using Gnome/Xorg but I tried.

**Comment by strycore** [comment] 2017-05-18 17:56
sooo, the Lutris runtime has pretty much changed entirely since the bug report was submitted. Is this still reproductible?

**Comment by strycore** [comment] 2017-09-14 20:26
Closing, the runtime has changed too much since then.

**Closed by strycore** 2017-09-14 20:26 UTC

**Comment by nonchip** [comment] 2018-03-03 11:39
this is still an issue, see also https://github.com/lutris/lutris/issues/226#issuecomment-370140651
