### ISSUE TITLE
Lutris does not manage to terminate wineserver after quitting a wine game

### ISSUE THREAD

**Issue by akien-mga** [lutris/lutris#176] opened 2015-04-06 10:32 UTC
Disclaimer: I'm not an expert in process management, so maybe this bug report is invalid, I'll let you see.

I've noticed that wineserver is still running after I quit a wine game in Lutris.
I've done the following test:

Before starting the game:
```
$ pidof wineserver
(nothing)
```

I start the game, Lutris shows a empires2.EXE process with PID 14815, while wineserver is on 14818.
```
$ pidof wineserver
14818
```

After I quit the game properly from the game's main menu, the Lutris console output is frozen on:
```
14815   S       empires2.EXE
14815   S       empires2.EXE
14815   Z       empires2.EXE
```
wineserver is still running with PID 14818 as above.
After a while wineserver jumps to PID 14917.

If I click the "Stop game" button in Lutris, I get this addition to the lutris terminal output:
```
ERROR    2015-04-06 12:27:00,099 [process]:Could not kill process 14952
```

wineserver is still running, I need to kill it manually.

HTH :-)

**Comment by akien-mga** [comment] 2015-04-06 10:33
Note that this was using my system wine, but I've observed the final error message also when using wine 1.7.29 and 1.7.39 downloaded by lutris.

**Comment by orbea** [comment] 2015-04-12 16:57
I noticed this when I left wine running with debug output after playing around with getting skyrim to work in winesteam, I think it might be relevant.
~~~
DEBUG    2015-04-12 09:48:21,390 [thread]:Game quit
eap section" wait timed out in thread 0081, blocked by 0015, retrying (60 sec)
err:ntdll:RtlpWaitForCriticalSection section 0x110060 "/home/wine/wine-git/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0081, blocked by 0015, retrying (60 sec)
err:ntdll:RtlpWaitForCriticalSection section 0x110060 "/home/wine/wine-git/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0081, blocked by 0015, retrying (60 sec)
err:ntdll:RtlpWaitForCriticalSection section 0x110060 "/home/wine/wine-git/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0081, blocked by 0015, retrying (60 sec)
err:ntdll:RtlpWaitForCriticalSection section 0x110060 "/home/wine/wine-git/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0081, blocked by 0015, retrying (60 sec)
err:ntdll:RtlpWaitForCriticalSection section 0x110060 "/home/wine/wine-git/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0081, blocked by 0015, retrying (60 sec)
err:ntdll:RtlpWaitForCriticalSection section 0x110060 "/home/wine/wine-git/dlls/ntdll/heap.c: main process heap section" wait timed out in thread 0081, blocked by 0015, retrying (60 sec)
~~~

As you described, the wineserver is still running despite steam being closed.

**Comment by strycore** [comment] 2015-11-05 07:43
Can this be reproduced in the current master branch? I've played some Skyrim and other Wine games lately and I haven't noticed anything weird with the wineserver. We've made quite a few modifications to the process manager so it might have solved the issue.

**Comment by strycore** [comment] 2015-11-17 16:57
On Lutris 0.3.6, the wine process management wasn't working properly, on lutris 0.3.7, there was an option set to true by default to leave Steam open after the game quits. On Unity I have no way to access steam to close it (it's not in the system tray) and since Steam is restarted anyway when starting a new game, this option is almost useless. Might as well shut down steam systematically. For now, I've just defaulted the option to False so Steam quits with the game.

**Closed by strycore** 2015-11-17 16:57 UTC
Labels: bug

**Comment by Xodetaetl** [comment] 2015-11-23 19:24
> and since Steam is restarted anyway when starting a new game, this option is almost useless. Might as well shut down steam systematically.

Antagonistic scenario: You want to chat with a friend after a game. I can imagine you'd prefer Steam to stay up. :)

**Comment by strycore** [comment] 2015-11-23 21:07
Thing is, most of the time I don't even have access to Steam, the client is minimized and for some reason, the steam icon does not appear in the notification area (does it do the same on XFCE?)

In my latest tests, I noticed that the client would be visible but that's quite new.

**Comment by Xodetaetl** [comment] 2015-11-23 22:22
> does it do the same on XFCE?

No, I have the icon.
