### ISSUE TITLE
Files are installed read-only and patch application fails

### ISSUE THREAD

**Issue by Salamandar** [lutris/lutris#2944] opened 2020-06-15 20:04 UTC
I'm trying to install Rayman 2 (the great escape). 
Files are installed :
* read-write if a directory is installed
* read-only if a file only is installed

The patch application fails because of those read-only files.
I think the files should **always** be installed with read-and-write permissions.

**Comment by xordspar0** [comment] 2020-06-16 15:29
Are the permissions stored in the archive with the files? Maybe the script just needs to be updated to set the permissions correctly before running sed. Could you please report this as an issue with the installer?

https://lutris.net/games/rayman-2-the-great-escape/

**Comment by byte1024** [comment] 2020-06-18 17:49
Looks like you can report the issue with the script author here: https://github.com/legluondunet/MyLittleLutrisScripts/issues

**Comment by strycore** [comment] 2020-06-19 04:09
@legluondunet that seems to be an issue with one of your scripts.

Is there anything we can do to report this better in the client or is this only a matter of fixing the install script?

**Comment by legluondunet** [comment] 2020-06-19 06:03
I just tried the script, two times, one time with 16/9 patch and second time with 16/10 patch and I can not reproduce this issue. I looked at the files and they have r/w permissions.

**Comment by legluondunet** [comment] 2020-06-19 06:09
@Salamandar when you copy files from CD, they are read-only, ou have to use chmod command to change that.

**Comment by legluondunet** [comment] 2020-06-19 06:14
@Salamandar when you ask Lutris to copy files from a CD, they keep their read-only properties, you have to use chmod command to change that. I see you changed the script in that way recently, I validated your changes. Could we now close this issue?

**Comment by Salamandar** [comment] 2020-06-19 09:19
Okay, I wrongly read the install script, the error's mine. 
I read in the Yaml file :
```
- copy:
    dst: $GAMEDIR/drive_c/UbiSoft/Rayman2/Data/
```
So I thought the Data dir was copied as a directory… But no, the Data dir is created by the exe installer with rw permissions  ><'

@legluondunet I guess that fixed the issue (my local edit did the trick).

**Closed** 2020-06-19 09:19 UTC
