### ISSUE TITLE
Allow Itch.io games as a source on lutris.

### ISSUE THREAD

**Issue by protodrew** [lutris/lutris#3512] opened 2021-04-17 23:46 UTC
We have an [itch.io](https://lutris.net/games/itchio/) launcher on lutris from the community, but no way to see our libraries and download/play them in lutris directly.

**Comment by oddstr13** [comment] 2021-04-20 20:25
Duplicate of #243

**Comment by protodrew** [comment] 2021-04-20 21:25
My apologies, I didn't see that in my cursory search of the issues.

**Closed** 2021-04-20 21:27 UTC
