### ISSUE TITLE
[Wiki] Blizzard App - Update Dependencies for ArchLinux

### ISSUE THREAD

**Issue by Maddosaurus** [lutris/lutris#1350] opened 2018-11-14 09:55 UTC
I've had the problem that the launcher kept on crashing right after sign in.  
The debug logs indicated I am missing some dependencies:
`Cannot open shared library /usr/lib32/alsa-lib/libasound_module_pcm_pulse.so ((null): libdbus-1.so.3: wrong ELF class: ELFCLASS64)`

Interestingly enough, I had `lib32-alsa-plugins` (multilib) installed, which didn't fix the issue.  
Installing `lib32-libpulse` (multilib) fixed the problem.  

_Proposal_: Maybe add both libs as "Other dependencies" or under "Issues with Blizzard App" combined with the error message.

_System_: Arch Linux x64 / Kernel 4.19.1-arch1-1-ARCH / Cinnamon 4.0.1 / Nvidia GTX980 (410.73)

And btw: Thanks for lutris <3

**Comment by JanGalek** [comment] 2018-11-15 14:20
I added to wiki ;), Thanks

**Comment by strycore** [comment] 2018-12-20 10:48
Likely a duplicate of https://github.com/lutris/lutris/issues/1303

Please test on next branch and reopen if not fixed.

**Closed by strycore** 2018-12-20 10:48 UTC
