### ISSUE TITLE
Winesteam/Wine runner problems

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#680] opened 2017-10-28 16:49 UTC
Latest lutris from master, gentoo amd64.

# Problem №1 (winesteam runner):
`$GAMEDIR` is unset (set to default `None`) for no reason and this causing any wine commands such as creating prefix and settings registry to fail.
[collapselog.zip](https://github.com/lutris/lutris/files/1450342/collapselog.zip)
`collapse.yaml`:
```
name: Collapse
game_slug: collapse1
version: Steam
slug: collapse1-steam
runner: winesteam

script:
  game:
    appid: 289620
    prefix: $GAMEDIR/prefix
  installer:
  - task:
      name: create_prefix
      prefix: $GAMEDIR/prefix
  - task:
      name: set_regedit
      prefix: $GAMEDIR/prefix
      path: HKEY_CURRENT_USER\Software\Wine\DllRedirects
      key: wined3d
      value: wined3d-csmt.dll
      type: REG_SZ
```

# Problem №2 (wine runner):
`detect_prefix_arch` function is always returns `win32` and wine commands fails in `win64` prefix unless i specify `arch: win64` in every task.
[twd3log.zip](https://github.com/lutris/lutris/files/1450288/twd3log.zip)
`twd3.yaml`:
```
name: twd3
game_slug: twd3
version: Wine
slug: twd3-64bit
runner: wine

script:
  files:
  - installer: "N/A:Select the game's setup file"
  game:
    exec: drive_c/Game/game.exe
    prefix: $GAMEDIR/prefix
  installer:
  - task:
      description: Setting up wine prefix
      name: create_prefix
      prefix: $GAMEDIR/prefix
      arch: win64
  - task:
      description: 'Installing twd3

      Make sure to close installer after installation finishes

      After exiting, wait a bit for lutris to finish'
      executable: $installer
      name: wineexec
      prefix: $GAMEDIR/prefix
  - task:
      name: set_regedit
      prefix: $GAMEDIR/prefix
      path: HKEY_CURRENT_USER\Software\Wine\DllRedirects
      key: wined3d
      value: wined3d-csmt.dll
      type: REG_SZ
```

@strycore @daniel-j

**Comment by soredake** [comment] 2017-11-06 15:19
Tried with wine, doesn't work too.
Log:
```
INFO     2017-11-06 17:17:38,649 [lutriswindow]:Installing $HOME/Documents/lutris/twd3_64.yaml
ERROR    2017-11-06 17:17:45,528 [wine]:No user.reg found after prefix creation. Prefix might not be valid
ERROR    2017-11-06 17:17:50,572 [wine]:No user.reg found after prefix creation. Prefix might not be valid
```

**Comment by strycore** [comment] 2018-05-08 08:53
Couldn't reproduce the 1st issue (just changed the steamid from the example script), guess it's fixed now.

**Comment by strycore** [comment] 2018-05-08 09:06
wineexec will now default to the architecture of the wine executable.

**Comment by AccountOneOff** [comment] 2018-05-09 03:09
Reinstalled Witcher 3 DXVK and I can confirm the first problem (#805) described didn't happen.

**Comment by AccountOneOff** [comment] 2018-06-14 19:00
[ERROR:2018-06-14 11:44:47,420:wine]: No user.reg found after prefix creation. Prefix might not be valid
    [ERROR:2018-06-14 11:51:26,185:wine]: No user.reg found after prefix creation. Prefix might not be valid
    [ERROR:2018-06-14 11:51:26,276:wineregistry]: Unexisting registry None/prefix/user.reg
    [ERROR:2018-06-14 11:51:26,276:jobs]: Error while completing task <bound method winesteam.prelaunch of Winesteam runner (LutrisConfig(level=game, game_config_id=hanako-honor-blade-steam-1529001887, runner=winesteam))>: [Errno 2] No such file or directory: 'None/prefix/user.reg'

***

Just happened again. Installer:

    game:
      appid: 349510
      prefix: $GAMEDIR/prefix
    installer:
    - task:
        name: create_prefix
        prefix: $GAMEDIR/prefix
    system:
      env:
        DXVK_HUD: '1'
    winesteam:
      dxvk: true
      dxvk_version: 0.54

I had a game update that I paused and resumed after installing the game. Might be related.

**Comment by soredake** [comment] 2018-06-17 19:10
@AccountOneOff same with this installer https://lutris.net/games/install/8747/view
@strycore

**Comment by daniel-j** [comment] 2018-06-18 07:04
@soredake hey, that's an installer I made the other day! :D

I can't reproduce the issue myself, but reopening the issue since it doesn't seem fixed.

**Comment by AccountOneOff** [comment] 2019-03-04 00:06
FWIW I haven't had this occur once since my last comment.

**Comment by soredake** [comment] 2019-03-07 14:36
I still experiencing this.

**Comment by soredake** [comment] 2019-03-20 07:23
Also happens with https://lutris.net/games/resident-evil-6-biohazard-6/

**Comment by strycore** [comment] 2019-03-20 17:13
Please re-create the ticket, this one's a mess.

**Closed by strycore** 2019-03-20 17:13 UTC
Labels: can't reproduce
