### ISSUE TITLE
"Stop Steam after game exits" doesn't work as expected

### ISSUE THREAD

**Issue by TiZ-EX1** [lutris/lutris#2077] opened 2019-04-22 19:27 UTC
Hi there. Since I've got a nice new computer, I'm configuring things fresh, and deciding to use Lutris for library management instead of using my own custom solution. Instead I'm trying to use prelaunch and postexit scripts to do the things I was using it to do before. With my PR, I've got things mostly as I like them! :)

One thing that is throwing me for a loop though is that "Stop Steam after game exits" is not doing what I expect it to do. In my old script, if Steam was not already running, I would sit around and wait for the `SteamChildMonit` process to die, and after it did, I'd close Steam.

The configuration option here suggests the same functionality, but that doesn't seem to be the case. If I start games from Lutris without having Steam open beforehand, I have to close Steam before the game is considered stopped. A quick peek at the steam runner shows that it doesn't really do anything concerning `SteamChildMonit`--in fact, it doesn't appear anywhere in the repo. The only thing it does is if you click the stop button in Lutris, then it will stop Steam after it has stopped the game.

If you don't keep Steam open all the time--I guess most users do--then this results in a pretty ugly wrinkle.

**Comment by AccountOneOff** [comment] 2019-04-23 00:14
Duplicate of #1588

**Closed by AccountOneOff** 2019-04-23 00:14 UTC
