### ISSUE TITLE
No launch argument filtering

### ISSUE THREAD

**Issue by JeremyStepp** [lutris/lutris#2182] opened 2019-06-06 07:41 UTC
**Describe the bug**

When only one quotation mark i s added to and argument python throws an unhanded error and the game stays "launching" forever. There may be more errors like this that can happen.

**Expected behavior**

For Lutris to detect the error before the arguments are saved or at least catch the error and tell the user.

**Steps to reproduce**

- Add a command line argument with open quotation marks. Ex. --foo"
- Launch the game

**Lutris debugging output**
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 299, in configure_game
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 897, in play
    for arg in shlex.split(arguments):
  File "/usr/lib/python3.6/shlex.py", line 305, in split
    return list(lex)
  File "/usr/lib/python3.6/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib/python3.6/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.6/shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

**Comment by tannisroot** [comment] 2019-06-07 04:16
Duplicate of https://github.com/lutris/lutris/issues/2081

**Closed by tannisroot** 2019-06-07 04:16 UTC
Labels: duplicate
