### ISSUE TITLE
Pango-CRITICAL

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#671] opened 2017-10-08 20:27 UTC
I causes Lutris to crash. 

Opened the game config window, and pressed the Change button on the identifier, and pressed CTRL+V and made Lutris crash:

`(lutris:10361): Pango-CRITICAL **: pango_layout_move_cursor_visually: assertion 'old_index >= 0 && old_index <= layout->length' failed`

**Comment by strycore** [comment] 2017-10-09 16:44
@TingPing I'm assigning the issue to you since you might have an easier time finding out the cause of the issue, if you don't have time or can't find what's causing the bug, you can reassign it to me.

**Closed** 2017-10-09 18:47 UTC
Labels: bug

**Comment by strycore** [comment] 2017-10-09 18:49
Thanks @TingPing :+1:
