### ISSUE TITLE
Remove all Xrandr usage

### ISSUE THREAD

**Issue by strycore** [lutris/lutris#489] opened 2017-02-14 08:33 UTC
LibGnomeDesktop has all the functionality to avoid a dependency on xrandr and it might do a better job for handling resolution changes.

**Comment by TingPing** [comment] 2017-02-14 17:00
On a related note, if x11 features are required we should probably mark that as the required backend as currently it runs under Wayland if available.

**Comment by strycore** [comment] 2017-02-14 17:42
What I'm hoping for is that LibGnomeDesktop will provide an abstraction over X11 and Wayland. Currently,I think it only works with X.

**Comment by TingPing** [comment] 2017-02-14 18:42
I'm not sure what you are exactly trying to do, but I am pretty confident it isn't possible on Wayland as you have no information or control over other applications windows. Now that I mention it forcing using X11 won't even help if the user is on Wayland because XWayland effectively sandboxes things too.

**Comment by TingPing** [comment] 2017-02-14 18:48
Ah you use it to get screen modes, I can confirm that works with Gnome on Wayland.

**Comment by strycore** [comment] 2017-02-14 18:48
What lutris is currently doing is detecting screen resolution changes so it can be restored when the game quits. It also can set a custom resolution before starting a game. Those shouldn't require any control over other windows so it should be ok.

Note that I currently have no plans of supporting Wayland in Lutris, it is not mature and it is unfit for gaming. I'll reconsider in a few years (most likely 2020)

**Comment by TingPing** [comment] 2017-02-14 18:49
> Note that I currently have no plans of supporting Wayland in Lutris, it is not mature and it is unfit for gaming. I'll reconsider in a few years (most likely 2020)

For what its worth everything gaming related has landed. Relative pointers, SDL2 support, etc. Is it less mature, sure, will it take 3 years for things to catch up.. no.

**Comment by strycore** [comment] 2017-02-14 18:52
Wayland isn't usable yet with the Nvidia driver. It's very experimental and 3 years to go from experimental to stable doesn't seem irrealistic.

**Comment by TingPing** [comment] 2017-02-14 18:56
Next version of Gnome on Wayland supports the Nvidia driver. I see no reason 1 year from now all users won't be able to simply play games.

**Comment by strycore** [comment] 2017-02-14 19:19
I'll have to get a first positive experience using Wayland, so far it has not been the case. Even after that, I have to make sure everything works so it will take some time.

**Closed** 2019-03-20 17:24 UTC
