### ISSUE TITLE
Can't use feral gamemode button on lutris using opensuse tumbleweed

### ISSUE THREAD

**Issue by barfin** [lutris/lutris#2418] opened 2019-10-22 06:38 UTC
**Describe the bug**
feral gamemode button on lutris cannot be enabled even if gamemode packages are installed and it's functional

**Expected behavior**

Feral gamemode button should be enabled and be usable

**Current behavior**

it's not enabled and cannot be used

**Steps to reproduce**

- use this command to install gamemode " sudo zypper install gamemoded libgamemode* "
- open lutris and as you can see game mode button is not enabled

**System information**
https://gist.github.com/barfin/006ecc586670f0f02b7c05a794be80c2

**Screenshots**
![Screenshot_20191022_095951](https://user-images.githubusercontent.com/37030489/67262751-b9cbad80-f4b2-11e9-84df-022d1bebb1b5.png)
**as you can see all feral gamemode packages are installed i tested it outside of lutris and it worked  but the button is not enabled**

**Comment by Adehom** [comment] 2019-10-23 12:34
Hello @barfin 
You need to add in Preference the result of the next command :

![image](https://user-images.githubusercontent.com/55432370/67392435-cf1f0580-f5a0-11e9-95ef-08e4415b3e6a.png)

![image](https://user-images.githubusercontent.com/55432370/67392698-49e82080-f5a1-11e9-89e7-3a249c35ed11.png)
When you launch a game, you can see gamemode is active 
![image](https://user-images.githubusercontent.com/55432370/67393005-d72b7500-f5a1-11e9-98bf-5fe79dfecb76.png)

**Comment by barfin** [comment] 2019-10-24 02:27
> Hello @barfin
> You need to add in Preference the result of the next command :
> 
> ![image](https://user-images.githubusercontent.com/55432370/67392435-cf1f0580-f5a0-11e9-95ef-08e4415b3e6a.png)
> 
> ![image](https://user-images.githubusercontent.com/55432370/67392698-49e82080-f5a1-11e9-89e7-3a249c35ed11.png)
> When you launch a game, you can see gamemode is active
> ![image](https://user-images.githubusercontent.com/55432370/67393005-d72b7500-f5a1-11e9-98bf-5fe79dfecb76.png)

thank you nice temporary solution but this is still a bug :dancer:

**Comment by Adehom** [comment] 2019-10-28 10:19
Hello @barfin 
I find the bug.
You need to change the line 192 : "condition":system.LINUX_SYSTEM.is_feature_supported("GAMEMODE"),
by
"condition": bool(system.find_executable("gamemoded")),
you can delete the key add previously.
Can you try it and give me a fill back before commit it

**Comment by barfin** [comment] 2019-10-28 11:42
> Hello @barfin
> I find the bug.
> You need to change the line 192 : "condition":system.LINUX_SYSTEM.is_feature_supported("GAMEMODE"),
> by
> "condition": bool(system.find_executable("gamemoded")),
> you can delete the key add previously.
> Can you try it and give me a fill back before commit it ?

line 192 in which file?

**Comment by Adehom** [comment] 2019-10-28 11:47
My Bad, I forget to say it.
in lutris/sysoptions.py

**Comment by barfin** [comment] 2019-10-28 12:36
> My Bad, I forget to say it.
> in lutris/sysoptions.py

ok looks like it's fine now

**Comment by AccountOneOff** [comment] 2019-10-31 23:18
Duplicate of #2172

**Closed by AccountOneOff** 2019-10-31 23:18 UTC
