### ISSUE TITLE
Restore screen on existing game changes resolution back when loading any steam game

### ISSUE THREAD

**Issue by colutti** [lutris/lutris#4898] opened 2023-06-09 22:22 UTC
### Bug description

When I activate the option to revert the screen resolution back when exiting game and I run any game, while the game is still loading the resolution is set back to the original resolution. I think it might be related with the Feral GameMode/Nvidia Prime option since I have both activated. I guess that because when i run a game with those options enable, lutris actually runs gamemode passing the arguments and since it calls steam and them exists, lutris thinks that I exited the game and reverts the resolution. 

### How to Reproduce

1. Go to the settings
2. Enable the Restore resolution, feral mode and nvidia
3. Select a different resolution on "Change Resolution to"
4. Run any game
5. Lutris will revert the resolution back to the original while the game is still loading

I have only tested this with Steam games.

### Expected behavior

It should only revert the resolution back to the original value when the game exists.

### Log output

```shell
INFO     2023-06-10 00:19:57,857 [startup.init_lutris:173]:Starting Lutris 0.5.12
INFO     2023-06-10 00:19:57,910 [startup.check_driver:57]:Using NVIDIA drivers 525.105.17 for x86_64
INFO     2023-06-10 00:19:57,910 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 3050 Laptop GPU
INFO     2023-06-10 00:19:57,911 [startup.check_driver:77]:GPU: 10DE:25A5 1043:1FFF (nvidia drivers)
INFO     2023-06-10 00:19:57,911 [startup.check_driver:77]:GPU: 1002:1636 1043:1FFF (amdgpu drivers)
DEBUG    2023-06-10 00:19:58,066 [lutriswindow.update_store:448]:Showing 33 games
INFO     2023-06-10 00:19:58,086 [startup.update_runtimes:218]:Startup complete
INFO     2023-06-10 00:20:05,397 [runner.use_runtime:299]:Runtime disabled by system configuration
INFO     2023-06-10 00:20:05,407 [runner.use_runtime:299]:Runtime disabled by system configuration
INFO     2023-06-10 00:20:05,407 [runner.use_runtime:299]:Runtime disabled by system configuration
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/colutti/.cache/lutris/shaders/steam"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:DRI_PRIME="1"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:__NV_PRIME_RENDER_OFFLOAD="1"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:__GLX_VENDOR_LIBRARY_NAME="nvidia"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:__VK_LAYER_NV_optimus="NVIDIA_only"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:game_name="God of War"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/home/colutti/.local/lib/python3.10/site-packages:/usr/local/lib/python3.10/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2023-06-10 00:20:08,705 [command.start:141]:LUTRIS_GAME_UUID="090582da-57f9-4b64-b931-093881dce089"
Discord ID: None
INFO     2023-06-10 00:20:08,712 [game.start_game:586]:Discord RPC Disabled or Discord APP ID Not Present
Started initial process 172634 from gamemoderun /usr/games/steam steam://rungameid/1593500
Start monitoring process.
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
steam.sh[172634]: Running Steam on pop 22.04 64-bit
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
steam.sh[172634]: STEAM_RUNTIME is enabled automatically
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
setup.sh[172706]: Steam runtime environment up-to-date!
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
steam.sh[172634]: Steam client's requirements are satisfied
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
DEBUG    2023-06-10 00:20:09,159 [command.on_stop:195]:Process 172632 has terminated with code 0
DEBUG    2023-06-10 00:20:10,718 [game.beat:693]:Game thread stopped
WARNING  2023-06-10 00:20:10,718 [game.on_game_quit:730]:Game still running (state: running)
INFO     2023-06-10 00:20:10,718 [game.stop:704]:Stopping God of War (steam)
DEBUG    2023-06-10 00:20:10,718 [game.stop_game:664]:God of War (steam) has run for 2 seconds
WARNING  2023-06-10 00:20:10,718 [game.stop_game:666]:The game has run for a very short time, did it crash?
DEBUG    2023-06-10 00:20:10,725 [game.on_game_quit:748]:God of War stopped at sáb, 10 jun 2023 00:20:10
DEBUG    2023-06-10 00:20:10,725 [game.save:299]:Saving God of War (steam) with config ID steam-1593500-1686322428
INFO     2023-06-10 00:20:22,853 [application.do_shutdown:898]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Pop!_OS 22.04 jammy
Arch:            x86_64
Kernel:          6.2.6-76060206-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 4800H with Radeon Graphics
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.0 GB
Swap:            36.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.105.17
OpenGL Core:     4.6.0 NVIDIA 525.105.17
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.105.17
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment] 2023-06-09 22:57
Duplicate of at least 2 different tickets which I don't feel like searching right now but be assured, we know.

**Closed by strycore** 2023-06-09 22:57 UTC
