### ISSUE TITLE
[Feature Request] Periodically check if the executable of a game still exists, if not - remove the game from the library

### ISSUE THREAD

**Issue by Smart-Helper** [lutris/lutris#4022] opened 2022-01-29 12:12 UTC
So i use Lutris as my Launcher for every game. At this point i just collect all the games from Steam, Epic, GOG, Humble and DRM-Free Windows Games from their folders, and put them into Lutris. This works amazing and is my Launcher for everything at this point.

When i install a game via Steam i have to "install" it again inside Lutris, which instantly finishes, and just puts the game in the library.

But when i want to uninstall a steam game for example, i can't do that from within Lutris and have to do that via Steam. After that i have to go into Lutris and remove the entry from there aswell. This can be quite cumbersome as i am that kind of person who piles up dozens of games, realizes half a year later i havent played any of them and uninstall them again. I then have to keep track of all the games i just uninstalled and remove them from Lutris.

If Lutris would check if the executable for every entry still exists at startup for example, it could automatically remove those entries from the library. That way i could uninstall dozens of games in one session from steam, restart lutris and they're all gone aswell and i dont have to remove them by hand.

And if there was an error and the executable was just replaced or something, you just simply add them in Lutris again and you're good to go.

Thanks, and have a nice day

**Comment by telanus** [comment] 2022-01-30 08:40
This seems as a duplicate of https://github.com/lutris/lutris/issues/829. Also methinks just removing games from the library is not the way we should go.

**Comment by strycore** [comment] 2022-02-03 22:33
we're not removing games from the library, this is a dumb idea.

**Closed by strycore** 2022-02-03 22:33 UTC

**Comment by Smart-Helper** [comment] 2022-02-04 06:08
@strycore Calm down there a bit.
This is NOT the proper way to interact with your users / community.

You should NOT just call something a dumb idea, just because it doesnt align with what you personally want.

There are alternatives to what i described, like marking those games with an icon to quickly show where executables are missing.

I guess this is just another case of "love the product, hate the company / person behind this".
I repeat - this is NOT the proper way to communicate here.
_____________________
@telanus i used the search function but didnt find anything similar. Good to know. But since @strycore seems quite stubborn to ignore user feedback i guess it doesnt matter at the end. Sad.

**Comment by strycore** [comment] 2022-02-05 01:32
Lutris is not a company, It is my personal project, don't come expecting the same type of language.

I'm not getting paid for it and I have to take responsibility for all the code that gets merged in.
In the past, I've been much more open to external ideas, this has resulted in buggy code, inconsistencies and more difficulty for me to maintain the project.
If I weren't the only one in charge of maintaining the code, things would be different.

**Comment by Smart-Helper** [comment] 2022-02-05 09:45
Thats why i said "love the product hate the company / **_person_** behind this"

And i am not expecting the same type of language from you as i expect from a company. I expect some human decency and some polite manners. Outright calling an idea dumb just because it's not the way you imagine things is far from the mentioned...

To your second point: I am sure there would be more than enough people in the linux gaming community who would love to help you out and participate in the maintenance and development if you would shout out for some help.

You as an open source developer who tries to make a big and good project for gaming are depending on user input. If you disregard everything from the users as dumb, then your project will soon be just a thing for only you to use. And that would be very sad and a great loss for the community. Because you made an awesome project that many people love. Including me. But if you behave like that, you will lose respect in the community.
