### ISSUE TITLE
Steam x64 version some games don't have the "install" button

### ISSUE THREAD

**Issue by nenoro** [lutris/lutris#792] opened 2018-03-11 12:33 UTC
Heya team Lutris.

i hope you'll understand what i'm saying (sorry for my english).

So when i run "manage runners" to Steam i click install, window's pop up and i see the url who's downloading wine.3.0-i386, after installation i launch steam > i take a look of my library and i see for now only Life is Strange - Before the Storm doesn't have the "install" button. i right click on the game and i have an error message like i was using Steam Linux:
"can't install {game} because region no available blah blah"

I try by using witcher 3's script you made (only test with this one) > launch it > game install/run > i take a look of my library and i see Life is Strange - Before the Storm's "install" button is showing up.

So i think:
> by running steam via Witcher 3, steam is fully x64
> by running steam lutris, steam is acting like i'm using Steam Linux.

So my suggestion is can you change the url direction to use wine.3.0-x86_64 instead of -i386 ?

thanks for reading

**Comment by Adam-Cass** [comment] 2018-03-21 22:47
This seems to be a duplicate of #786

**Comment by nenoro** [comment] 2018-03-24 20:40
i find another solution, i use wine.

I saw lutris file, i can't use a full 64 bits version.

**Comment by Zeioth** [comment] 2018-05-01 17:13
Please close this issue.
Duplicated of #655

**Comment by strycore** [comment] 2018-05-03 03:52
winesteam now defaults to 64bit

**Closed by strycore** 2018-05-03 03:52 UTC
