### ISSUE TITLE
New Steam Library/Account Stuff Causes All Installed Steam Games to Show up Twice

### ISSUE THREAD

**Issue by gardotd426** [lutris/lutris#3731] opened 2021-10-12 00:40 UTC
After upgrading to 0.5.9 and re-syncing my Steam account using the left panel, every installed Steam game shows up in Lutris twice:

![Screenshot_20211011_203748](https://user-images.githubusercontent.com/54234607/136871389-16ad21a8-5e7d-42e2-9daa-714cd110380a.png)

Obviously just removing the old config entries from ~/.config/lutris/games/ doesn't do anything, and I can't remove ~/.local/share/lutris/pga.db because that would cause all non-Steam games' entries to be removed (I've learned this the hard way before). 

[lutris-issue-report.json.tar.gz](https://github.com/lutris/lutris/files/7326022/lutris-issue-report.json.tar.gz)

Distro: Arch Linux
Lutris version: 0.5.9

**Comment by neilunger** [comment] 2021-10-14 21:48
Also having this issue, where refresh adds another copy.

**Comment by strycore** [comment] 2021-10-17 02:35
Fixed in 0.5.9.1

**Closed** 2021-10-17 02:35 UTC

**Comment by Brixus3** [comment] 2021-10-24 02:07
Anyone find a fix for this? Or at least how to safely remove the duplicates?

**Comment by wolfmanx** [comment] 2021-12-30 10:06
I can confirm, that this issue is not fixed. All installed Steam games are duplicated with version 0.5.9.1.

Since it's Christmas and still not fixed, here is a workaround to get rid of the duplicates from failed Steam updates.

There are 2 errors here.

1.  Some game entries in the database do not produce a valid *Game* object:

        ERROR    2021-12-30 10:36:47,614 [steam.add_installed_games:174]:error: missing appid for (game: {'system': {}, 'steam': {}, 'game': {}}) (db: {'id': 122, 'name': 'Europa Universalis III', 'slug': 'europa-universalis-iii', 'installer_slug': 'steam', 'parent_slug': '', 'platform': 'Linux', 'runner': 'steam', 'executable': '', 'directory': '', 'updated': '', 'lastplayed': 1607757128, 'installed': 1, 'installed_at': 1602995509, 'year': 2007, 'steamid': 25800, 'gogid': 0, 'configpath': 'europa-universalis-iii-1602995509', 'has_custom_banner': 0, 'has_custom_icon': 0, 'playtime': 0.0038888888888888888, 'humblestoreid': '', 'hidden': 0, 'service': 'steam', 'service_id': '25800'})
        ERROR    2021-12-30 10:36:47,933 [steam.add_installed_games:174]:error: missing appid for (game: {'system': {}, 'steam': {}, 'game': {}}) (db: {'id': 215, 'name': 'Star Control: Origins', 'slug': 'star-control-origins', 'installer_slug': 'steam', 'parent_slug': '', 'platform': 'Linux', 'runner': 'steam', 'executable': '', 'directory': '', 'updated': '', 'lastplayed': 1603180504, 'installed': 1, 'installed_at': 1603177439, 'year': 2018, 'steamid': 271260, 'gogid': 0, 'configpath': 'star-control-origins-1603177439', 'has_custom_banner': 0, 'has_custom_icon': 0, 'playtime': 0.005555555555555556, 'humblestoreid': '', 'hidden': 0, 'service': 'steam', 'service_id': '271260'})

    This leads to a *KeyError* exception, which leaves all the steam games in the DB without deleting duplicates.

    This can be fixed by catching the *KeyError* in `lutris/services/steam.py` (`/usr/lib/python3/dist-packages/lutris/services/steam.py`), by modifying method *SteamService.add\_installed\_games*

        db_games = get_games(filters={"runner": "steam"})
        for db_game in db_games:
            steam_game = Game(db_game["id"])
            appid = steam_game.config.game_level["game"]["appid"]
            if appid not in installed_appids:
                steam_game.remove(no_signal=True)

    to catch the exception:

        db_games = get_games(filters={"runner": "steam"})
        for db_game in db_games:
            steam_game = Game(db_game["id"])
            try:
                appid = steam_game.config.game_level["game"]["appid"]
                if appid not in installed_appids:
                    steam_game.remove(no_signal=True)
            except KeyError:
                logger.error("%s", "error: missing appid for (game: {0}) (db: {1})".format(steam_game.config.game_level, db_game))

2.  Due to the rapid updates during the steam update, GTK fails with memory corruptions and segfaults.

    This can be avoided by disabling the game window during steam game updates.

    In `lutris/gui/lutriswindow.py` (`/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py`), in method *LutrisWindow.update\_store*

        def update_store(self, *_args, **_kwargs):
            self.game_store.store.clear()

    add a line with `return False`

        def update_store(self, *_args, **_kwargs):
            return False            # |:here:| disable for steam updates
            self.game_store.store.clear()

    to avoid any rapid GTK window updates while steam games are added/deleted.

    No games are displayed at all after startup! However the  
    steam update works and duplicates are removed. Simply exit Lutris, re-enable game window updates and start it again.
