### ISSUE TITLE
The Battle.net source is unavailable because Google protobuf could not be loaded

### ISSUE THREAD

**Issue by plexecutor** [lutris/lutris#5654] opened 2024-10-15 13:31 UTC
### Bug description

I am trying to add battle.net as a source but it is missing from the sources list. I have both protobuf and python-protobuf installed, but this is the output I get when launching Lutris:
```
$ lutris -d
2024-10-15 09:24:27,710: The Battle.net source is unavailable because Google protobuf could not be loaded: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
```
I have both protobuf and python-protobuf packages installed:
```
$ pacman -Qs protobuf
local/protobuf 28.2-3
    Protocol Buffers - Google's data interchange format
local/python-protobuf 28.2-3
    Python 3 bindings for Google Protocol Buffers
```

This sounds to me like Lutris is looking for an older protobuf package. I downgraded to protobuf 3.20.x and even 3.19.x but it still was not working. What version of protobuf is Lutris expecting to be installed?

### How to Reproduce

Be an arch linux user
Install protobuf and python-protobuf
Launch Lutris
Observe the sources list missing battle.net

### Expected behavior

Battle.net should be in the sources list since the dependencies outlined in the readme are met.

### Log output

```shell
$ lutris -d
2024-10-15 09:30:05,230: Unable to run command, qdbus not found
2024-10-15 09:30:05,311: The Battle.net source is unavailable because Google protobuf could not be loaded: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
INFO     2024-10-15 09:30:05,426 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-10-15 09:30:05,605 [startup.run_all_checks:120]:NVIDIA GeForce RTX 3060 Ti (10de:2489 1458:4076 nvidia) Driver 560.35.03
DEBUG    2024-10-15 09:30:05,728 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-10-15 09:30:05,729 [xrandr._get_vidmodes:18]:Retrieving 40 video modes from XrandR
DEBUG    2024-10-15 09:30:05,763 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-10-15 09:30:05,784 [api.check_stale_runtime_versions:52]:Modified at Tue 15 Oct 2024 08:27:11 AM , will update after Tue 15 Oct 2024 02:27:11 PM 
DEBUG    2024-10-15 09:30:05,789 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.11.3-zen1-1-zen
Desktop: KDE
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 7 5800X 8-Core Processor
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 62.7 GB
Swap: 0.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 560.35.03
OpenGL Core: 4.6.0 NVIDIA 560.35.03
OpenGL ES: OpenGL ES 3.2 NVIDIA 560.35.03
Vulkan Version: 1.3.295
Vulkan Drivers: NVIDIA GeForce RTX 3060 Ti (1.3.280)
```

**Comment by strycore** [comment] 2024-10-15 17:28
Duplicate of #5330

**Closed by strycore** 2024-10-15 17:28 UTC
