### ISSUE TITLE
Client endlessly waiting for zombie process to terminate before terminating itself

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/lutris#366] opened 2016-09-27 18:20 UTC
It's happened multipled times to me that a game thread won't properly end when the game is quit and when trying to quit Lutris, the latter will fail to terminate the thread and will keep running in the background. It's happened mostly with Wine games.

Well that's just guess work. I'll try to get more information the next time it happens.

**Comment by telanus** [comment] 2016-09-27 18:31
I've noticed it also with wine games: http://i.imgur.com/Kxww5x5.png

**Comment by strycore** [comment] 2016-09-28 00:47
Well I got Spelunky which is one of the only wine games that will crash on exit and a bunch of mysterious games so I can't reproduce. (I can for Spelunky but that doesn't count, this game has to be forced to quit even when run from the terminal)

**Comment by telanus** [comment] 2016-09-28 03:25
I play-tested a bit. and most wine games I ran don't have problems. One I did find was my old pirate copy of Counter-Strike: Condition Zero exits and then Lutris dumps this on the terminal 

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/batapete/src/lutris-master/lutris/thread.py", line 87, in run
    line = line.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 894: invalid start byte

**Comment by strycore** [comment] 2016-09-28 05:19
Ok, this has nothing to do with the issue with zombies but somehow it failed decoding the Counter Strike output. Latest commit should fix this.

**Comment by telanus** [comment] 2016-10-02 06:00
I get this on the terminal 

`DEBUG    2016-10-02 07:57:03,781 [game]:Duck Tales stopped at Sun, 02 Oct 2016 07:57:03`
`INFO     2016-10-02 07:57:20,741 [lutriswindow]:Duck Tales is still running, stopping it`
`DEBUG    2016-10-02 07:57:20,746 [thread]:Killing process Process 11254`

**Comment by strycore** [comment] 2016-10-03 19:44
Which Duck Tales game is this? The NES one?

**Comment by telanus** [comment] 2016-10-04 01:57
@strycore it's the Amiga IPF version

**Comment by strycore** [comment] 2016-10-05 22:25
Running the same game, the process seems to quit normally:

`DEBUG    2016-10-05 15:23:40,558 [thread]:10430	Z	fs-uae
DEBUG    2016-10-05 15:23:40,559 [thread]:All children terminated
DEBUG    2016-10-05 15:23:42,059 [thread]:No children left in thread, exiting
DEBUG    2016-10-05 15:23:43,559 [game]:Game thread stopped
DEBUG    2016-10-05 15:23:43,559 [game]:Duck Tales - The Quest for Gold v1.0 stopped at Wed, 05 Oct 2016 15:23:43
`

**Comment by strycore** [comment] 2016-10-07 00:42
@telanus I fixed the fact that the game was still detected as running when stopping Lutris.
Other than that, I don't seem to be able to reproduce this bug at all.

**Comment by strycore** [comment] 2016-10-27 20:00
Closing for lack of information

**Closed by strycore** 2016-10-27 20:00 UTC
Labels: needs confirmation
