### ISSUE TITLE
Any ge- and lutris- wine builds aren't working

### ISSUE THREAD

**Issue by VortexAcherontic** [lutris/lutris#2255] opened 2019-08-01 17:19 UTC
**Describe the bug**
I'm having this issue since the first ge-* builds came up and was hoping for future releases to work again. And today I tested the new lutris-* wine build but those aren't working either.

This affects any ge-* build as well as any lutris-* wine builds.

But since I found no other issue targeting this problems I think this affects my distro only or at least I have some missing dependencies I'm not aware of.

[Error log ge builds](https://pastebin.com/K71vQaSx)

[Error log lutris builds](https://pastebin.com/EAffjZKA)

**Expected behavior**

That it just works.

**Current behavior**

Any program refuses to launch with those wine builds

**Steps to reproduce**
- try any ge-* or lutris-* wine builds

**Lutris debugging output**

[ge builds](https://pastebin.com/aJDZ7iSn)
[lutris builds](https://pastebin.com/5bhkmY2y)

**System information**
[Pastebin](https://pastebin.com/x2ra36q8)

**Comment by Saroufim** [comment] 2019-08-01 23:49
Try ge-protonified-4.9. Does it work? If it does, you and I might have the same issue. All other ge- builds don't work for me except this one.

**Comment by VortexAcherontic** [comment] 2019-08-02 18:11
[ge-protonified-4.9](https://pastebin.com/Ya8AXpC0) isn't working either :(

**Comment by tannisroot** [comment] 2019-08-08 14:48
What linux distribution are you using atm?

**Comment by VortexAcherontic** [comment] 2019-08-08 17:11
@tannisroot I'm running openSUSE Leap 15.1 I also can check if this issue persist with Tumbleweed if it helps something :)

**Comment by Saroufim** [comment] 2019-08-08 18:19
Fedora Silverblue here

**Comment by tannisroot** [comment] 2019-08-08 18:26
>  I'm running openSUSE Leap 15.1
Yeah, I think this distro might be a bit too old for these builds. We switched to building on Ubuntu 18.04 with newer builds and I guess some of the stuff in them is just not backwards compatible.

**Comment by VortexAcherontic** [comment] 2019-08-08 18:41
"too old"? openSUSE Leap 15.1 was released this year on the 8th March o.O

Maybe it would help if you guys could post information about which glib version eg. is used for building those wine builds so I can try to get a newer version out of security repos.

GLib tend to be the only issue I had with various packages and games around the web but that was workaroundable in the past. :D
Leap offers glibc 2.26

**Comment by VortexAcherontic** [comment] 2019-08-08 19:06
@tannisroot Okay just tested the lutris-4.12.1 build on my Tumbleweed machine and can confirm it works. Hm... I wonder what could stop it from working on Leap x.x

**Comment by tannisroot** [comment] 2019-08-08 19:24
According to Ubuntu Packages, Ubuntu 18.04 bionic ships with glibc version 2.27: https://packages.ubuntu.com/source/bionic/glibc

**Comment by VortexAcherontic** [comment] 2019-08-08 20:05
Meh I tried to update to 2.29 but that would break to much stuff on suse including some core libraries. :/

**Comment by tannisroot** [comment] 2019-08-12 15:45
There's not much we can do about this issue with Tumbleweed so closing.

**Closed by tannisroot** 2019-08-12 15:45 UTC

**Comment by VortexAcherontic** [comment] 2019-08-14 18:09
@tannisroot Well glibc was only an assumption why it is not working with openSUSE Leap no warranty for this.

In Tumbleweed everything runs fine which may be an hint that this might be caused by some older libraries. But since Leap is 15.1 is a rather new distro I feel like there should be some sort of support.
I admit in case of older libraries there isn't really much you can do, except of also including vanilla wine builds into Lutris which would be nice anyway.

At least I would appreciate any help you guys could give me to narrow down the issue. But I don't really know where to start, rather then testing various distros and see if it happens as well but I don't thinks this will lead to any solution :D

So do you have any other tips for me I can try to see what causes the issue. Rather than closing the issue shrugging? :)

**Comment by GloriousEggroll** [comment] 2019-08-14 20:46
There is a lutris forum post regarding this which I have already provided an answer for:

https://forums.lutris.net/t/gloriouseggroll-ge-protonified-4-x-wine-versions-fail-because-of-requirement-for-too-new-glibc-version/6160

Specifically the issue is related to 32 bit glibc (and 32 bit libraries in general) on 15.1:

You may need to change distros or downgrade to 15.0. Per 15.1 documentation:
Note: No Support for Building 32-bit Applications

openSUSE Leap does not support compilation of 32-bit applications. It only offers runtime support for 32-bit binaries.

https://doc.opensuse.org/documentation/leap/reference/html/book.opensuse.reference/cha.64bit.html 1

This means no one on OBS will be able to make 32 bit builds for openSUSE 15.1

**Comment by VortexAcherontic** [comment] 2019-08-14 22:05
Thank you a lot :)

**Comment by GloriousEggroll** [comment] 2019-08-15 00:26
> Thank you a lot :)
> 
> And yeah, I'm aware of the 32bit thing with openSUSE :D
> 
> Unfortunately I switched from Tumbleweed to Leap for my main machine because I had sometimes broken applications after an update like the NV Diver, Open Broadcasting Software, Audacity eg. and was forced to wait for several weeks to have those packages fixed.
> 
> But maybe I'll give Tumbleweed as my main machine a chance again :D

Give Fedora a try ;)

**Comment by VortexAcherontic** [comment] 2019-08-17 13:24
> > Thank you a lot :)
> > And yeah, I'm aware of the 32bit thing with openSUSE :D
> > Unfortunately I switched from Tumbleweed to Leap for my main machine because I had sometimes broken applications after an update like the NV Diver, Open Broadcasting Software, Audacity eg. and was forced to wait for several weeks to have those packages fixed.
> > But maybe I'll give Tumbleweed as my main machine a chance again :D
> 
> Give Fedora a try ;)

Na, I just upgraded Leap 15.1 to Tumbleweed with no issues :D
