### ISSUE TITLE
Impossible to launch EPIC Games Store

### ISSUE THREAD

**Issue by JulienDlq** [lutris/lutris#4784] opened 2023-03-26 08:40 UTC
### Bug description

I’m not able anymore to launch EPIC Games Store.

### How to Reproduce

1. Open Lutris
2. Double-Click on EPIC Games Store to launch it
3. See that it tries then fails without showing anything

### Expected behavior

EPIC Games Store is launched and running.

### Log output

```shell
INFO     2023-03-26 10:31:19,800 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-03-26 10:31:19,825 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-03-26 10:31:19,899 [startup.check_driver:57]:Using NVIDIA drivers 525.89.02 for x86_64
INFO     2023-03-26 10:31:19,899 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 1660 Ti
INFO     2023-03-26 10:31:19,899 [startup.check_driver:77]:GPU: 10DE:2182 1043:86A5 (nvidia drivers)
DEBUG    2023-03-26 10:31:20,035 [lutriswindow.update_store:448]:Showing 0 games
INFO     2023-03-26 10:31:20,043 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-03-26 10:31:22,311 [lutriswindow.update_store:448]:Showing 16 games
DEBUG    2023-03-26 10:31:23,243 [grid.on_item_activated:57]:Item activated: 41
DEBUG    2023-03-26 10:31:23,444 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-03-26 10:31:23,496 [game.start_prelaunch_command:408]:Prelaunch command /home/loup/Scripts/Lutris/azerforce.sh launched in the background
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/media/loup/disque1to/Lutris/epic-games-store"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:LD_LIBRARY_PATH="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib:/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib64:/usr/lib64:/usr/lib:/usr/lib/gcc/x86_64-pc-linux-gnu/12:/usr/lib/llvm/15/lib64:/usr/lib/gcc/x86_64-pc-linux-gnu/12/32:/usr/lib64/fltk:/usr/lib/llvm/16/lib64:/usr/lib/llvm/16/lib:/usr/lib/llvm/15/lib:/usr/lib/rust/lib:/lib:/lib64:/home/loup/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/loup/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/i386/lib:/home/loup/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/i386/usr/lib:/home/loup/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/loup/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/amd64/lib:/home/loup/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:DXVK_HUD="compiler"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:MESA_GL_VERSION_OVERRIDE="4.4COMPAT"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:WINEARCH="win64"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:WINE="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/bin/wine"
DEBUG    2023-03-26 10:31:23,496 [command.start:141]:WINE_MONO_CACHE_DIR="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/mono"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/gecko"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib64/gstreamer-1.0/:/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:WINEPREFIX="/media/loup/disque1to/Lutris/epic-games-store"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:WINEESYNC="1"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/loup/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:PROTON_EAC_RUNTIME="/home/loup/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:game_name="Epic Games Store"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/usr/lib/python3.10/site-packages"
DEBUG    2023-03-26 10:31:23,497 [command.start:141]:LUTRIS_GAME_UUID="eb022098-73c5-450d-a752-4a6c4060b4ff"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/media/loup/disque1to/Lutris/epic-games-store"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:LD_LIBRARY_PATH="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib:/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib64:/usr/lib64:/usr/lib:/usr/lib/gcc/x86_64-pc-linux-gnu/12:/usr/lib/llvm/15/lib64:/usr/lib/gcc/x86_64-pc-linux-gnu/12/32:/usr/lib64/fltk:/usr/lib/llvm/16/lib64:/usr/lib/llvm/16/lib:/usr/lib/llvm/15/lib:/usr/lib/rust/lib:/lib:/lib64:/home/loup/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/loup/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/i386/lib:/home/loup/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/i386/usr/lib:/home/loup/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/loup/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/amd64/lib:/home/loup/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:DXVK_HUD="compiler"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:MESA_GL_VERSION_OVERRIDE="4.4COMPAT"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:WINEARCH="win64"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:WINE="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/bin/wine"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:WINE_MONO_CACHE_DIR="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/mono"
DEBUG    2023-03-26 10:31:23,499 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/gecko"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib64/gstreamer-1.0/:/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:WINEPREFIX="/media/loup/disque1to/Lutris/epic-games-store"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:WINEESYNC="1"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/loup/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:PROTON_EAC_RUNTIME="/home/loup/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:game_name="Epic Games Store"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/usr/lib/python3.10/site-packages"
DEBUG    2023-03-26 10:31:23,500 [command.start:141]:LUTRIS_GAME_UUID="de31bd12-b776-4cd6-bf4c-bb30eddef01c"
Discord ID: None
INFO     2023-03-26 10:31:23,514 [game.start_game:586]:Discord RPC Disabled or Discord APP ID Not Present
Started initial process 115513 from /home/loup/Scripts/Lutris/azerforce.sh
Start monitoring process.
Started initial process 115515 from /home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/bin/wine /media/loup/disque1to/Lutris/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl -SkipBuildPatchPrereq
Start monitoring process.
esync: up and running.
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
DEBUG    2023-03-26 10:31:23,664 [command.on_stop:195]:Process 115509 has terminated with code 0
Initial process has exited (return code: 0)
wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 0214), starting debugger...
wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 0224), starting debugger...
Monitored process exited.
Exit with return code 0
DEBUG    2023-03-26 10:31:27,613 [command.on_stop:195]:Process 115510 has terminated with code 0
DEBUG    2023-03-26 10:31:37,522 [game.beat:693]:Game thread stopped
WARNING  2023-03-26 10:31:37,522 [game.on_game_quit:730]:Game still running (state: running)
INFO     2023-03-26 10:31:37,522 [game.stop:704]:Stopping Epic Games Store (wine)
DEBUG    2023-03-26 10:31:37,523 [game.stop_game:664]:Epic Games Store (wine) has run for 14 seconds
INFO     2023-03-26 10:31:37,536 [game.on_game_quit:738]:Running post-exit command: /home/loup/Scripts/Lutris/bépoforce.sh
DEBUG    2023-03-26 10:31:37,536 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-03-26 10:31:37,536 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-03-26 10:31:37,536 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/media/loup/disque1to/Lutris/epic-games-store"
DEBUG    2023-03-26 10:31:37,536 [command.start:141]:LD_LIBRARY_PATH="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib:/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib64:/usr/lib64:/usr/lib:/usr/lib/gcc/x86_64-pc-linux-gnu/12:/usr/lib/llvm/15/lib64:/usr/lib/gcc/x86_64-pc-linux-gnu/12/32:/usr/lib64/fltk:/usr/lib/llvm/16/lib64:/usr/lib/llvm/16/lib:/usr/lib/llvm/15/lib:/usr/lib/rust/lib:/lib:/lib64:/home/loup/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/loup/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/i386/lib:/home/loup/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/i386/usr/lib:/home/loup/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/loup/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/amd64/lib:/home/loup/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/loup/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:DXVK_HUD="compiler"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:MESA_GL_VERSION_OVERRIDE="4.4COMPAT"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:WINEARCH="win64"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:WINE="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/bin/wine"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:WINE_MONO_CACHE_DIR="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/mono"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/gecko"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib64/gstreamer-1.0/:/home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:WINEPREFIX="/media/loup/disque1to/Lutris/epic-games-store"
DEBUG    2023-03-26 10:31:37,537 [command.start:141]:WINEESYNC="1"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/loup/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:PROTON_EAC_RUNTIME="/home/loup/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:WINE_LARGE_ADDRESS_AWARE="1"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:game_name="Epic Games Store"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/bin:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/usr/lib/python3.10/site-packages"
DEBUG    2023-03-26 10:31:37,538 [command.start:141]:LUTRIS_GAME_UUID="395c15f8-8f3b-4549-bf06-0200843c9f71"
DEBUG    2023-03-26 10:31:37,539 [game.on_game_quit:748]:Epic Games Store stopped at dim., 26 mars 2023 10:31:37
DEBUG    2023-03-26 10:31:37,539 [game.save:299]:Saving Epic Games Store (wine) with config ID epic-games-store-latest-1633865616
Started initial process 115679 from /home/loup/Scripts/Lutris/bépoforce.sh
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
DEBUG    2023-03-26 10:31:37,705 [command.on_stop:195]:Process 115677 has terminated with code 0
```

### System Information

```shell
[System]
OS:              Gentoo 2.13 n/a
Arch:            x86_64
Kernel:          6.2.8-gentoo-x86_64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Physical cores:  8
Logical cores:   8

[Memory]
RAM:             31.3 GB
Swap:            32.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 525.89.02
OpenGL Core:     4.6.0 NVIDIA 525.89.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 525.89.02
Vulkan:          Supported
```

### Media (optional)

![EPICfail](https://user-images.githubusercontent.com/18351090/227764850-68ea90a5-5f6f-4177-8ae7-e91ea5dd2cab.gif)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by rhighs** [comment] 2023-03-26 21:52
Same happening here. Tried both `v0.5.4` and `v0.6.2`  for the DXVK NVAPI version value

**Comment by legluondunet** [comment] 2023-04-17 09:06
Hello @JulienDlq , in your log I read:
`Started initial process 115515 from /home/loup/.local/share/lutris/runners/wine/lutris-fshack-6.14-4-x86_64/bin/wine`
The wine version you use is too old.
Test with a more recent Lutris wine version, like lutris-GE-Proton7-43-x86_64, verify that you use latest dvxk, nvapi...set this components to default version.
If the issue persists, please repost a new debug log.

**Comment by strycore** [comment] 2023-05-12 00:20
Closing this as I can't reproduce and the issue was created with an ancient Wine build

**Closed by strycore** 2023-05-12 00:20 UTC
