### ISSUE TITLE
Migrate all services to sidebar categories and deprecate service dialog

### ISSUE THREAD

**Issue by neroden** [lutris/lutris#2887] opened 2020-05-18 00:06 UTC
GOG game import attempts give "No games were added. 1 game is already in the library".

(Found on Planescape: Torment Enhanced Edition, Planescape: Torment, Wizardry 6, Wizardry 7 Gold, Neverwinter Nights: Enhanced Edition -- probably others, at that point I stopped testing)

This is... confusing, to say the least.   And clearly incorrect.  The games are definitely not in my Lutris library either before or after.

Console output (for Planescape: Torment):
<code>
DEBUG    2020-05-17 20:01:52,342 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-05-17 20:01:52,609 [api.get_game_api_page:134]:No game found for 1207658887
</code>

At the very least I would expect an informative error message like "Lutris does not support this game", rather than the completely bogus error message which I actually got.  This is the bug in the Lutris codebase (on version 0.5.6) and a new release should be pushed ASAP to fix the bogus error message, which is *extremely* confusing.  

More confusingly, I'm pretty sure I installed Planescape:Torment on another computer using Lutris a couple of weeks ago, so probably the games ought to work; mismatch between Lutris.net's database and GOG's database?

**Comment by neroden** [comment] 2020-05-18 00:16
The failure to find games seems to be the same underlying error as in issue #2374, which is also not fixed (where the hell are the devs?!?)  They were getting a more informative error message, though....

**Comment by xordspar0** [comment] 2020-05-18 20:14
Try unchecking "Installed games only" in the hamburger menu. Maybe it was added once already but failed to install. If you find it there, you can try clicking on it and then clicking the "Install" button.

Just looking at the Planescape: Torment install script for GOG, it looks like that's one of the old GOG scripts that requires you to download the game yourself and then tell Lutris where the .exe file is.

> Is lutris an abandoned project?

No. Maybe the issue that you linked to isn't fixed yet because no one knows how to fix it or no one has had time to look at it yet.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment] 2020-05-18 23:47
I have this problem as well. I wanted to use Lutris instead of minigalaxy so that the games installation process would create (.desktop) shortcuts in my programs lists. But I can't even install Fort Triumph from GOG using Lutris due to this reported issue.

**Comment by neroden** [comment] 2020-05-19 15:41
> Try unchecking "Installed games only" in the hamburger menu. Maybe it was added once already but failed to install. If you find it there, you can try clicking on it and then clicking the "Install" button.
It definitely wasn't installed before, ever.  Fresh computer.

> Just looking at the Planescape: Torment install script for GOG, it looks like that's one of the old GOG scripts that requires you to download the game yourself and then tell Lutris where the .exe file is.

And that would have been a helpful error message.  Which I did not get.  "Please download from GOG before running installation script" would have been a fine error message.

> > Is lutris an abandoned project?
> 
> No. Maybe the issue that you linked to isn't fixed yet because no one knows how to fix it or no one has had time to look at it yet.
This is a trivial-to-fix issue for someone who understands the codebase (which I do not), but is also of critical severity since it completely breaks Lutris for very large numbers of people, and does so with an inaccurate and misleading error message!

If the devs aren't looking at this they aren't prioritizing correctly.  They need to get their asses in gear or it *is*, in essence, an abandoned project.

**Comment by strycore** [comment] 2020-05-19 16:41
@neroden please calm down. Lutris is not an abandoned project. We have very few resources to allocate to the development of the project so things make take some time.

The reason why this is happening is that when doing the import process, Lutris only adds games it recognizes. It makes an API call to the websites with the GOG game IDs, matches those IDs with Lutris games then returns a list of Lutris games to import.
The problem is that the matching between GOG IDs and Lutris games is not fully complete so not all games import. With Humble Bundle, it's far worse.

The plan is two fold. First, make lutris import every game from GOG/Humble/Other, whether it's matched to a lutris game or not. This will make sure all games are imported and if the games are not matched with the GOG ID, then matching by name is a pretty decent fallback.

2nd is to have data sources that update GOG IDs much more often and having some tools to help with the matching of Lutris games, this is done on the website side.

**Comment by byte1024** [comment] 2020-05-19 18:13
I would like to also point out that if Lutris is for whatever reason not finding a game on gog.com that you can just install the [gog galaxy](https://lutris.net/games/gog-galaxy/) and have access to all your gog.com games regardless.

Maybe you don't want that but its available and _should_ require no complaining.

**Comment by neroden** [comment] 2020-05-21 16:30
How hard is it to fix the ERROR MESSAGE so that it it gives informative feedback?  I mean, "Failed to download" would have been so much more helpful than "Game already in library".

And, byte1024, how the hell do I install the Gog Galaxy client on Linux when there isn't one for Linux?  Wine?

**Comment by strycore** [comment] 2020-05-21 17:25
> how hard is it to fix the ERROR MESSAGE so that it it gives informative feedback?

Apparently too hard for you to fix it and send a PR.

**Comment by xordspar0** [comment] 2020-05-21 17:56
### Relevant Code

This is where the GOG syncer calls the Lutris API to correlate the GOG games with Lutris's database:

https://github.com/lutris/lutris/blob/master/lutris/services/gog.py#L326-L344

The results of that function get returned to this widget, which activates when the API call is done:

https://github.com/lutris/lutris/blob/master/lutris/gui/widgets/services.py#L164-L187

### Problem

Whenever the number of added games is less than the number of games the user wanted to add, that means that there was an error with the ones that didn't get added. Currently Lutris assumes that the reason is because they're already in the user's library.

### Possible Solutions

* A general message like "1 game had an error" could work, but then the common case where the game is already in the user's library would say that there's an error when everything is fine.

* A simple solution would be to have the syncer report how many games failed with errors. The message could say, "3 games imported. 2 failed with errors (see logs for details). 1 was already in the library."

* The syncer could pass along a reason for each failure. The little popup at the top of the window isn't a good place to report details about what went wrong. Maybe a window should pop up and display a report instead?

**Comment by xordspar0** [comment] 2020-05-21 21:18
Sorry, anything I said that was unhelpful was because of ignorance, not because I was trying to come up with half assed solutions.

Are you saying that we can leave the error message as it is as long as the underlying issues get fixed? I thought it would be helpful to improve the error message even with the solutions you mentioned, but if you don't think so that's ok.

**Comment by Chugajstyr** [comment] 2020-05-25 23:48
I've similar issue - tried to import to Lutris from my GOG library Deus Ex: Human Revolution - Director’s Cut, [Deus Ex: Mankind Divided - Digital Deluxe Edition](https://www.gog.com/game/deus_ex_mankind_divided_deluxe_edition). Lutris said that games already in library, but they not appear in list. Debug output said:
`[api.get_game_api_page:134]:No game found for 1296690054, 1370227705
`

> 2nd is to have data sources that update GOG IDs much more often and having some tools to help with the matching of Lutris games, this is done on the website side.

This did only members of Lutris team, I can't do it, right? Until I found this topic, I thought that to fix this I need use [Lutris API](https://lutris.net/api/games?format=api) and add to game database gogslug value - I tried to do it for "Deus Ex: Human Revolution - Director’s Cut" with html-form on API page. Strange, but game data in database not changed, and no errors like "Permission denied" or similar - instead returned Json response with status "200 OK":
` HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
} `

Since I was not able to found Lutris API documentation, I still not sure how to use it.

**Comment by neroden** [comment] 2020-05-26 00:25
So, out of general scholarly interest, I'm reading through the code which xordspar kindly pointed me to, and attempting to chase the routines across the codebase.  They're poorly commented and I don't know Python so this isn't trivial for me, though it would be trivial for the developer of a maintained project.  

Filing a patch is a pretty unreasonable thing to request of someone the first day he tried to use your project; most people wouldn't even go to the trouble of filing a bug report, they'd just give up on you.

It looks like the improperly handled errors are in lutris/api.py at get_api_games -- if I'm not mistaken (I don't know the codebase or Python), this is the code which sees the error:
 
<code>
        else:
            logger.error("No page found in %s", response_data["next"])
            break
        response_data = get_game_api_page(game_slugs, page=next_page, query_type=query_type)
        if not response_data:
            logger.warning("Unable to get response for page %s", next_page)
            break
</code>

This code needs to add the failed responses to a list and pass the list up so that the callers are aware of the error, which is an function interface change.  (Putting the failures in the log and nowhere else is not correct error handling.)  This seems reasonably straightforward though it would take me some practice with Python to nail the syntax.

**Comment by gsantner** [comment] 2020-05-30 08:07
Copy-pasting from #2067 that got forgotten and kept closed:

---

I bought [Dungeon Siege Collection](https://www.gog.com/game/dungeon_siege_collection) today and at import screen the game shows up correctly. Also importer tells me everything imported. But actually it didn't import and game doesn't show up in game list. I've tried this more than 5 times now and it simply doesn't work.

I always get the "51 imported, 14 already there" notification, so seems like 14 only imported OK and are the maxmimum number of picked up my available GoG Games.  
Only 20% imported games actually is quite miserable though for the case that Lutris/DB seems to know the games (otherwise it wouldn't show names and Icons).

![Screenshot_20200430-000509](https://user-images.githubusercontent.com/6735650/80651516-567c9280-8a76-11ea-9246-2d0abf3b62b3.png)

**Comment by strycore** [comment] 2020-08-04 06:18
I am starting development on the `sidebar-services` branch. The plan is to remove the "Import games" dialog completely and show games from various services in an appropriate filter on the sidebar.

This changes some major things in the way the UI works. Right now, GameStore is tightly coupled to our sqlite database so at this moment, we don't have the capability of showing stuff that's not in our database. That coupling needs to go and game lists have to be given to the GameStore by the main ui, without the GameStore ever knowing about the database or some UI filters. That would allow us to load games from other sources.

Of course, we also need a way to link games from various services to lutris games. If a game has never been launched, we have no reason keeping it in our local database. But if it was, we want to keep track of information like the playtime or be about to customize the runtime configuration of the game. Let's take locally installed Linux games for example because it is the simplest case. They would count as installed but Lutris shouldn't know about them until they are launched. Launching the game should result in the creation of a lutris game (what we currently call "import") in the lutris database. 

We also shouldn't rely on lutris installers being present, like it is mentioned in #1754

**Comment by strycore** [comment] 2020-08-17 05:54
Closed by #3089

**Closed** 2020-10-06 06:30 UTC

**Comment by gsantner** [comment] 2020-10-06 07:47
@strycore 
Thanks for working on this!

Tried on master, minor issue: gog icon seems to be too big / icon dimension not limited

![Screenshot_20201006-091037](https://user-images.githubusercontent.com/6735650/95173351-d5f65680-07b8-11eb-9814-817da1402c30.png)
