### ISSUE TITLE
[Feature] Integrate MangoHud

### ISSUE THREAD

**Issue by Medath** [lutris/lutris#2840] opened 2020-05-05 00:47 UTC
https://github.com/flightlessmango/MangoHud

It's a HUD for Vulkan and OpenGL applications that is able to display various performance statistics in-game. Optimally it would be distributed with the runtime so it doesn't need to be manually installed by the user.
This could be used for adding a "Display frames per second" game option in Lutris that enables/disables an fps display. If advanced options are enabled the user would also be able to tweak the MangoHud configuration as desired. It's also a useful tool for people benchmarking games on Linux, having this in Lutris would make it a bit easier

**Comment by byte1024** [comment] 2020-05-05 21:51
Interesting idea.

Considering through mangohud, Lutris can crash, I would wrap that bad boy so it wouldn't bring Lutris down with it. No reason to take a hit on stability.

**Comment by Medath** [comment] 2020-05-06 10:50
Lutris itself wouldn't run through MangoHud, so it shouldn't be an issue. At worst it would affect the stability of the games where it has been enabled

**Comment by byte1024** [comment] 2020-05-06 20:40
> Lutris itself wouldn't run through MangoHud, so it shouldn't be an issue. At worst it would affect the stability of the games where it has been enabled

That would be nice if that was all, but the reason why I posted that is because some are running mangohud, and it is causing Lutris to fail to start. In other words, its taking Lutris down badly.

If it doesn't for you right now great, but that doesn't mean it won't. There would be no reason to add mangohud only for Lutris to have more random problems so its best to wrap it so if it fails that it doesn't affect Lutris.

Of course, the devs might hate the idea especially if its causing start issues and people keep posting new issues about Lutris not starting because of it.

**Comment by Medath** [comment] 2020-05-10 22:19
> That would be nice if that was all, but the reason why I posted that is because some are running mangohud, and it is causing Lutris to fail to start. In other words, its taking Lutris down badly.

In case you're talking about [this](https://github.com/flightlessmango/MangoHud/issues/160), it should be no problem. Lutris wouldn't install, run, or configure MangoHud globally but only on a per-game basis. It would be no different than running `mangohud path/to/game/binary` in a terminal. If MangoHud then crashes it could crash the game, but not Lutris.

**Comment by byte1024** [comment] 2020-05-12 19:35
> In case you're talking about [this](https://github.com/flightlessmango/MangoHud/issues/160), it should be no problem. Lutris wouldn't install, run, or configure MangoHud globally but only on a per-game basis. It would be no different than running `mangohud path/to/game/binary` in a terminal. If MangoHud then crashes it could crash the game, but not Lutris.

No, I'm talking about this one for example: https://github.com/lutris/lutris/issues/2866 where running mangohud causes Lutris to fail to start.

Obviously, they're not separated in a way that if Mangohud has a problem that it won't affect Lutris.

**Comment by Medath** [comment] 2020-05-13 15:49
That user started Lutris through MangoHud (or more specifically, had MangoHud enabled globally). The correct and safe way would be to do it the other way around, start MangoHud through Lutris, for example by adding `mangohud` to the "Command prefix" option in Lutris' system options. Enabling MangoHud that way would be safe and could at worst crash the launched game, but not Lutris itself

**Comment by strycore** [comment] 2020-05-14 00:48
So no one is able to determine the cause of the crash?

**Comment by xordspar0** [comment] 2020-05-14 13:35
Is it a user setting in MangoHud that causes the crash? I just installed the latest version, 0.3.5, on my Arch system and I can't reproduce it.

**Comment by strycore** [comment] 2020-05-16 17:35
People have reported that enabling Mangohud with Goverlay was causing the crash.
But maybe this has been fixed upstream.

**Comment by strycore** [comment] 2020-07-12 06:08
I've added a mangohud option but I haven't had great success with it. It needs more work to get it integrated properly.

**Comment by RandoNandoz** [comment] 2020-08-20 16:16
Wouldn't having the user install MangoHud and then having an option to turn it on be better, like how feral gamemode is a toggleable option? Maybe MangoHud could be a weak dependency of lutris?

**Comment by strycore** [comment] 2020-10-06 04:44
Fixed in #3186

**Closed by strycore** 2020-10-06 04:44 UTC
