### ISSUE TITLE
League of legends on Manjaro won't work because plugin manager cannot load a dll

### ISSUE THREAD

**Issue by samskhan** [lutris/lutris#2130] opened 2019-05-12 12:19 UTC
Hello, 

I installed lutris on my manjaro machine with KDE, had nvidia version 418.56, installed all the wine packages lutris reccomended. When i first ran it, the updater screen comes on, updates till it hits 100% but then nothing happens, the client never comes up. I checked the logs and this is the issue I am seeing: 

```
Running /home/delilah/.local/share/lutris/runners/wine/tkg-4.6-x86_64/bin/wine /home/delilah/Games/league-of-legends/drive_c/Riot Games/League of Legends/LeagueClient.exe
LeagueClient.exe(00000009): ALWAYS| Application Version:9.9.272.6103 - CL:2726103 - Build Date:Apr 29 2019 - Build Time:14:06:37
LeagueClient.exe(0000002B): ALWAYS| Tracing worker thread running.
LeagueClient.exe(00000009): ALWAYS| Running LeagueClient version 9.9.272.6103
LeagueClient.exe(0000002B): ALWAYS| Keeping up to 10 tracing logs.
LeagueClient.exe(0000002B): ALWAYS| Tracing CompactJsonWriter at C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-05-12T08-09-36_8_LeagueClient-tracing.json
LeagueClient.exe(00000009): ALWAYS| Phase Begin - Init
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Loaded plugin manifest file plugin-manifest.json.
LeagueClient.exe(00000009): ALWAYS| Begin Launch Ux Process
LeagueClient.exe(00000009): ALWAYS| End Launch Ux Process
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Mounted all WadFiles in 101.156 milliseconds.
LeagueClient.exe(00000009):  ERROR|             Plugin Manager| Could not load Plugin rcp-be-gcloud-voice-chat from Plugins\rcp-be-gcloud-voice-chat\rcp-be-gcloud-voice-chat.dll.
LeagueClient.exe(00000009): ALWAYS| Failed to load and start modules.
LeagueClient.exe(00000009): ALWAYS| Phase End - Init - duration was 703.80ms
Waiting on children
Waiting on children
2019-05-12 08:09:38,192: Unable to read stat for process 2563
2019-05-12 08:09:38,193: Unable to read stat for process 2563
All children gone
Exit with returncode 0
```

Not sure why plugin manager is not able to load that dll file. I tried removing and reinstalling but i get the same error. Any help will be appreciated.

**Comment by strycore** [comment] 2019-05-12 15:59
please format your console output correctly, this is unreadable.

**Comment by vlakam** [comment] 2019-05-13 00:52
Btw, this is how league works, even on Windows. Client stucks for a long time on a 100%. I'm using Manjaro and playing LoL via Lutris with no actions whatsoever.

**Comment by strycore** [comment] 2019-05-13 05:10
Thanks for formatting the console output.

There seems to be people with similar issues: https://www.reddit.com/r/leagueoflinux/comments/94l87n/still_cant_play_have_tried_everything/

not sure if related though, the missing dll seem to be for an audio chat plugin and should not affect the startup of the game.

**Comment by SanderJSA** [comment] 2019-05-14 18:03
I had the same issue, installing steam_native got me to the client, launching a game still crashes.  
Found it here : https://www.reddit.com/r/leagueoflinux/comments/boede9/arch_linux_client_wont_start/

**Comment by rafifos** [comment] 2019-05-15 23:58
Riot Games broke the game (again) on the last patch. The game crashes after champ select, there is already a bug filled at [WineHQ Bugzilla](https://bugs.winehq.org/show_bug.cgi?id=47198).

And regarding to your issue, it stucks on 100% for a while, even on small updates, you can see it doing it's stuff with `top, htop, System Monitor` and similar software, it might be easier to visualize if you set the "dependencies" (or similar) view on.

**Comment by tannisroot** [comment] 2019-05-16 08:29
Not a bug in Lutris client, closing.

**Closed by tannisroot** 2019-05-16 08:29 UTC
Labels: installer, missing information
