### ISSUE TITLE
problem login humbleBundle not work (lutris 0.5.10.1)

### ISSUE THREAD

**Issue by ludo77** [lutris/lutris#4277] opened 2022-05-14 11:55 UTC
### Bug description

When I connect to humble bundle on lutris(version 0.5.10.1), I enter my login/password. Then when I click on connect, nothing happens. I don't see my list of humble bundle games in lutris.
While in the issue 4099, there are people where their login/password says that it works for them.
Can you help me?
Thanks

### How to Reproduce

Connect to humble bundle on lutris
Enter my login/password
When click on connect, nothing happens. I don't see my list of humble bundle games in lutris.

### Expected behavior

not working

### Log output

```shell
''
```

### System Information

```shell
''
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment] 2022-05-17 18:05
Closing as duplicate of #4099 (I've re-opened it)

**Closed by strycore** 2022-05-17 18:05 UTC
Labels: needs triage
