### ISSUE TITLE
Memory leaking

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#778] opened 2018-03-01 10:54 UTC
The last few days when Lutris was running it's memory usage was about 150-160MB (or so says the system monitor), but with the [fixes](https://github.com/lutris/lutris/commit/07552d8641af0b76f1a0fc71f1a4f25f5ac44396) in, the memory usage skyrocketed to almost 2GB, today I terminated Lutris when it reached 1GB (of memory used).

**Comment by telanus** [comment] 2018-03-02 09:41
After re.downloading from git I had Lutris running for about 2 hours, and it memory usage grew to 1.6GB, modifies api.py (with # added before import re) and it ran for 2 hours at 161MB.

![16gb](https://user-images.githubusercontent.com/19357986/36892796-92ad7c1e-1e0e-11e8-8cbb-f3eee9fb5498.png)
![161mb](https://user-images.githubusercontent.com/19357986/36892798-9303c722-1e0e-11e8-9c84-0c0431acf9d6.png)

**Comment by strycore** [comment] 2018-03-06 06:03
how many games do you have in your library?

**Comment by telanus** [comment] 2018-03-06 07:20
@strycore too many :smile_cat: according to here 1358 that's in my lutris library, but a lot isn't installed, but according to Dolphin there is 1,327 items in my /.congig/lutris/game folder

**Comment by telanus** [comment] 2018-05-22 15:21
I tested again today, and it's still there.

**Comment by xalmat** [comment] 2019-02-04 04:51
Just as a follow-up, 0.5.0.1 still contains a rather large memory leak. I'm in the process of removing games from my library (due to the duplicate entries bug), and every time I do, memory usage _increases_.

**Comment by tannisroot** [comment] 2019-04-18 08:19
@strycore this is still a valid issue and it's ridiculous. Not only it sometimes can take up a whole gig, but it also leaves these useless processes that don't close by themselves:
![image](https://user-images.githubusercontent.com/10602045/56346804-9ce4b380-61cb-11e9-89f4-56b0f12c0dde.png)
![image](https://user-images.githubusercontent.com/10602045/56346860-ad952980-61cb-11e9-94a6-c375bbbf6f9b.png)

**Comment by strycore** [comment] 2019-04-18 16:01
I have no way to repro this.

**Comment by tannisroot** [comment] 2019-04-24 20:03
Try enabling logging for all of your most frequently played games and try to keep Lutris opened as long as possible. I suspect the issue is that Lutris doesn't really clear the logs and instead just keeps them in memory until you close it.

**Comment by vahtos** [comment] 2019-08-09 16:51
@strycore This issue can be reproduced without starting a single game. I've captured a video of it (https://streamable.com/f0bj4). I don't think it is logging related as there are no lines being output by the logger. I'd guess this is an issue of garbage collection. Are we ever deleting Game and Game Panel objects and such?

**Comment by telanus** [comment] 2019-12-10 05:34
Is anyone still having this problem or can we close it?

**Comment by strycore** [comment] 2019-12-10 16:12
Let's close it, there's nothing to back this issue up and no good repro steps.

**Closed by strycore** 2019-12-10 16:12 UTC
Labels: can't reproduce, low priority, missing information, need help, needs confirmation
