### ISSUE TITLE
Winesteam Problems

### ISSUE THREAD

**Issue by telanus** [lutris/lutris#789] opened 2018-03-09 10:51 UTC
I setup lutris yesterday evening for winesteam. But I've rub into problems.

1) When I try to run a game from lutris itself, it won't start but will write this on the terminal:

https://pastebin.com/xkUeKBp0

2) When running steam first (via lutris) and then running a game it writes this to the terminal

https://pastebin.com/PtFZgRpA

**Comment by manuelVo** [comment] 2018-03-22 09:10
This is a regression of 1158414. If the Prefix Architecture (option under Game Settings) is set to `auto` lutris tries to fetch the `default_auto_prefix` setting - which does not exist. It should either look for `default_win32_prefix` or `default_win64_prefix` if `auto` is selected.

A possible workaround is setting the Prefix Architecutre in Game Settings to either `32-bit` or `64-bit`. However I'd advise you'll use Version `v0.4.14` for now since that version doesn't have that bug (and there seems to be more wrong than this bug in the winesteam runner in the current master (as of c1e3887)).

**Comment by telanus** [comment] 2018-03-22 15:47
@manuelVo thanx, that seems to have worked :dancing_women:

**Comment by strycore** [comment] 2018-05-09 07:52
Should be fixed in current master

**Closed by strycore** 2018-05-09 07:52 UTC
