### ISSUE TITLE
Lutris fails to start (Ubuntu 20.04 nightly 03-14-2020)

### ISSUE THREAD

**Issue by Zenzou** [lutris/lutris#2657] opened 2020-03-15 00:07 UTC
I assume this is a Ubuntu 20.04 nightly issue and not a Lutris problem, but I figured I would report it just in case it is not.
Lutris fails to start with no error pop ups, terminal output has it hanging during download of d9vk.
<pre><font color="#005FD7">lutris</font>
2020-03-14 17:04:14,907: Running Lutris 0.5.4
2020-03-14 17:04:14,908: Using Intel
2020-03-14 17:04:14,908: Running Mesa driver 20.0.0 on Mesa Intel(R) HD Graphics 520 (SKL GT2) (0x1916)
2020-03-14 17:04:14,908: GPU: 8086:1916 1028:06DF using i915 drivers
2020-03-14 17:04:14,979: Vulkan is supported
2020-03-14 17:04:14,981: Updating DXVK versions
Traceback (most recent call last):
  File &quot;/usr/lib/python3/dist-packages/lutris/gui/application.py&quot;, line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File &quot;/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py&quot;, line 102, in __init__
    self.game_store = self.get_store()
  File &quot;/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py&quot;, line 315, in get_store
    game_store = GameStore(
  File &quot;/usr/lib/python3/dist-packages/lutris/gui/views/store.py&quot;, line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object &apos;TreeModelSort&apos; has no attribute &apos;sort_new_with_model&apos;
2020-03-14 17:04:15,378: Updating D9VK versions
</pre>

**Comment by connectety** [comment] 2020-03-15 00:21
Not a maintainer or anything, 
but this seams to be a duplicate of https://github.com/lutris/lutris/issues/2656

**Comment by nordcomputer** [comment] 2020-03-15 14:50
Same problem here with Debian Testing:

> 2020-03-15 15:44:44,899: Running Lutris 0.5.4
2020-03-15 15:44:44,900: Using NVIDIA drivers 440.64 for x86_64
2020-03-15 15:44:44,900: GPU: GeForce GTX 970
2020-03-15 15:44:44,900: GPU: 10DE:13C2 10B0:13C2 using nvidia drivers
2020-03-15 15:44:44,974: Vulkan is supported
2020-03-15 15:44:44,975: Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 321, in get_store
    self.show_installed_first,
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2020-03-15 15:44:45,567: Updating D9VK versions

**Comment by ernstp** [comment] 2020-03-17 18:07
Got the same error with Lutris 0.5.4 but running directly from git didn't have any issue.

**Comment by jstaf** [comment] 2020-03-18 01:11
Seeing this on Fedora 32 beta.

**Comment by Minc3** [comment] 2020-03-18 06:27
Having the same issue on Ubuntu 20.04

**Comment by Minc3** [comment] 2020-03-18 06:47
> Having the same issue on Ubuntu 20.04

it's gtk api changes, you can fix it by changing
Gtk.TreeModelSort.sort_new_with_model => Gtk.TreeModelSort.new_with_model
in usr/lib/python3/dist-packages/lutris/gui/views/store.py

**Comment by h-2** [comment] 2020-03-18 22:53
Also on Devuan Unstable. Workaround works.

**Comment by strycore** [comment] 2020-03-18 23:05
Fixed in master.

**Closed by strycore** 2020-03-18 23:05 UTC
