### ISSUE TITLE
Games fail to launch since 0.5.10

### ISSUE THREAD

**Issue by weaseal** [lutris/lutris#4219] opened 2022-04-14 07:14 UTC
### Bug description

All games fail to launch since lutris 0.5.10. See `lutris -d` in section below.

host info:
```
Linux desktop 5.13.0-39-generic #44-Ubuntu SMP Thu Mar 24 15:35:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Wine version is lutris-7.2-fshack.

All games work OK again after downgrading back to Lutris 0.5.9.1

### How to Reproduce

1. Upgrade lutris to 0.5.10
2. Games fail to launch with error message `'NoneType' object has no attribute 'lower'`

### Expected behavior

The games should launch like they did in 0.5.9.1

### Log output

```shell
$ lutris -d
INFO     2022-04-13 23:54:54,731 [startup.init_lutris:173]:Starting Lutris 0.5.10
WARNING  2022-04-13 23:54:54,752 [libretro.get_libretro_cores:24]:No folder at /home/user/.local/share/lutris/runners/retroarch/
INFO     2022-04-13 23:54:54,773 [startup.check_driver:65]:Running AMD Mesa driver 21.2.6 on AMD Radeon RX 5700 XT (NAVI10, DRM 3.41.0, 5.13.0-39-generic, LLVM 12.0.1) (0x731f)
INFO     2022-04-13 23:54:54,773 [startup.check_driver:77]:GPU: 1002:731F 1682:5701 (amdgpu drivers)
DEBUG    2022-04-13 23:54:54,788 [application.show_update_runtime_dialog:292]:Skipping initialization
DEBUG    2022-04-13 23:54:54,843 [lutriswindow.update_store:437]:Showing 4 games
ERROR    2022-04-13 23:54:56,005 [nvidia.get_nvidia_glx_path:42]:Unable to load libGLX_nvidia.so.0
WARNING  2022-04-13 23:54:56,005 [nvidia.get_nvidia_dll_path:90]:Unable to locate libGLX_nvidia
ERROR    2022-04-13 23:54:56,008 [jobs.target:36]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f06f408ce50>>: <class 'AttributeError'> 'NoneType' object has no attribute 'lower'
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 819, in prelaunch
    self.setup_dlls(
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 776, in setup_dlls
    if dll_manager.version.lower() != "manual":
ERROR    2022-04-13 23:54:56,008 [game.configure_game:457]:'NoneType' object has no attribute 'lower'
ERROR    2022-04-13 23:56:40,414 [game.configure_game:460]:Game prelaunch unsuccessful
```

### System Information

```shell
[System]
OS:              Ubuntu 21.10 impish
Arch:            x86_64
Kernel:          5.13.0-39-generic
Desktop:         ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.2 GB
Swap:            32.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 5700 XT (NAVI10, DRM 3.41.0, 5.13.0-39-generic, LLVM 12.0.1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.2.6
OpenGL Core:     4.6 (Core Profile) Mesa 21.2.6
OpenGL ES:       OpenGL ES 3.2 Mesa 21.2.6
Vulkan:          Supported
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by mihailim** [comment] 2022-04-14 08:15
Does it work if you deactivate dgvoodoo2 support in the Lutris preferences?

**Comment by danieljohnson2** [comment] 2022-04-14 08:41
This looks very like issue #4216, for which a fix has been merged. Maybe 0.5.10.1 will fix this for you when it is available. You could try the 'master' branch to see if that works. (Don't try to install it; download it and run it's bin/lutris script from the command line).

That issue was caused by Lutris having no versions of some WINE component installed, and the fix will allow Lutris to continue to try to handle this. If it can't download the thing, you should at least get a better error.

Issue #4216 was ultimately resolved (for that user) by deleting the ~/.local/share/lutris, ~/.cache/lutris and ~/.config/lutris directories, which forces Lutris to reinstall everything on startup. But (a) you'd have to set up *everything* all over again and (b) without those directories, we won't be able to research this further.

So I'd ask you to try the master branch first if you could.

**Comment by strycore** [comment] 2022-04-14 23:22
Closing as duplicate.

**Closed** 2022-04-14 23:22 UTC
Labels: needs triage
