### ISSUE TITLE
Wine prefixes fail to create on NTFS drives

### ISSUE THREAD

**Issue by BunnyApocalypse** [lutris/lutris#1809] opened 2019-02-25 01:01 UTC
New report from Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1680433

There are some permissions on viewing this bug, so if you need additional info, just tell me what you need.

Version-Release number of selected component:
lutris-0.5.0.1-5.fc29

Additional info:
reporter:       libreport-2.10.0
cmdline:        /usr/bin/python3 -s /usr/bin/lutris
crash_function: save
exception_type: OSError
executable:     /usr/bin/lutris
interpreter:    python3-3.7.2-4.fc29.x86_64
kernel:         4.20.10-200.fc29.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
registry.py:153:save:OSError: Invalid Wine prefix path %s, make sure to create the prefix before saving to a registry

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 587, in run_winecfg
    self.prelaunch()
  File "/usr/lib/python3.7/site-packages/lutris/runners/wine.py", line 674, in prelaunch
    prefix_manager.configure_joypads()
  File "/usr/lib/python3.7/site-packages/lutris/util/wine/prefix.py", line 148, in configure_joypads
    self.clear_registry_key(key)
  File "/usr/lib/python3.7/site-packages/lutris/util/wine/prefix.py", line 49, in clear_registry_key
    registry.save()
  File "/usr/lib/python3.7/site-packages/lutris/util/wine/registry.py", line 153, in save
    raise OSError("Invalid Wine prefix path %s, make sure to "
OSError: Invalid Wine prefix path %s, make sure to create the prefix before saving to a registry

Local variables in innermost frame:
self: <lutris.util.wine.registry.WineRegistry object at 0x7f6e11def0f0>
path: '/mnt/nt_data/Games/world-of-tanks/user.reg'
prefix_path: '/mnt/nt_data/Games/world-of-tanks'

**Comment by strycore** [comment] 2019-03-02 22:26
I assume /mnt/nt_data/ is a NTFS drive? can you check on that?

**Comment by BunnyApocalypse** [comment] 2019-03-02 22:33
Yes, it is an NTFS drive.

**Comment by strycore** [comment] 2019-03-03 01:00
Yeah, people really shouldn't install their games on NTFS drives, we'll have some warning about that soon.

**Comment by tannisroot** [comment] 2019-03-03 08:08
Shall I close this as duplicate of https://github.com/lutris/lutris/issues/1313?

**Comment by strycore** [comment] 2019-03-28 03:49
yeah, this can be safely closed as duplicate.

**Closed by strycore** 2019-03-28 03:49 UTC
