### ISSUE TITLE
Install of Settlers ii fails by succeeding. returncode 0

### ISSUE THREAD

**Issue by Jemsterr** [lutris/lutris#2230] opened 2019-07-11 14:35 UTC
Installing Settlers ii from gog.com (both by downloading .. multiple times) and then by using the manually downloaded installer.

Here is the log..
[Settlers II Install.log](https://github.com/lutris/lutris/files/3382532/Settlers.II.Install.log)

And then it just sits there... Cancelling is the only option.  Looking at the source, it seems that it doesn't see that wine has finished installing the game, to move on the the next section "cleaning".  

Unfortunately, I don't know how to fix that.  Hopefully someone here can?

**Comment by tihadot** [comment] 2019-07-28 18:55
I faced similar issues while trying to install Vampire - The Masquerade: Bloodlines from GOG (https://lutris.net/games/vampire-the-masquerade-bloodlines/).

Arch Linux:
`Linux 5.2.3-arch1-1-ARCH #1 SMP PREEMPT Fri Jul 26 08:13:47 UTC 2019 x86_64 GNU/Linux`
`lutris 0.5.2.2-1`

What _did_ work for me was replacing wine with wine-staging. I'm not entirely sure, but it was the only difference I am aware of between several failed and one successful installation.

**Comment by linuxrecon** [comment] 2019-08-13 20:11
I have this problem as well with all GOG installers so far, including Hitman Contracts, Anno 1404, Grim Dawn and Thief Gold ...

**Comment by AccountOneOff** [comment] 2019-08-17 22:29
Duplicate of #2173

**Closed by AccountOneOff** 2019-08-17 22:29 UTC
