### ISSUE TITLE
Process monitor kills LeagueofLegends

### ISSUE THREAD

**Issue by jannikac** [lutris/lutris#1367] opened 2018-11-23 14:53 UTC
I just installed the lates Lutris on my system and LeagueOfLegends via the latest install script at:
[https://lutris.net/games/league-of-legends/](url)
System: 4.19.2-arch1-1-ARCH
Package: Lutris from community repository Lutris 0.4.23-1
Wine Version: staging-3.18-x86_64
Modifications in Lutris: DXVK enabled in Runner options but disabling it yields same results.
Log: [https://pastebin.com/xwnCSh6M](url)

Problem: The process monitor kills the game process even though it would be starting without it. (See log for further reference)

What I've tried: 
1. Disabling the process monitor in System options works, the game runs successfully.
2. Excluding the process LeagueClient.exe works aswell.

Although I've found a solution on how to fix this issue it seems like its a workaround solution and it worked a week ago without making these tweaks. This is my first Github Issue. I'm not 100% sure it belongs here though, correct me if I'm wrong. I hope I provided enough detail.

**Comment by strycore** [comment] 2018-11-23 18:30
This doesn't teach us anything new so I'll just mark it as a duplicate of #973.

**Closed by strycore** 2018-11-23 18:30 UTC

**Comment by strycore** [comment] 2018-11-23 18:31
(Please note there is no problem with the ticket itself, it's just an issue that has been discussed a lot already)

**Comment by jannikac** [comment] 2018-11-23 20:12
Hm okay, thank you saw that one but I thought it was different since it wasn't fixed by excluding some processes in the process monitor.
