### ISSUE TITLE
Winetricks not launching

### ISSUE THREAD

**Issue by ChiefGyk3D** [lutris/lutris#4910] opened 2023-06-18 16:48 UTC
### Bug description

Winetricks is not launching from GUI 

### How to Reproduce

Attempt to open Winetricks on a game

### Expected behavior

it opens Winetricks

### Log output

```shell
chiefgyk3d@Project-NOS:~$ lutris -d
INFO     2023-06-18 12:45:24,863 [startup.init_lutris:173]:Starting Lutris 0.5.12
INFO     2023-06-18 12:45:24,900 [startup.check_driver:57]:Using NVIDIA drivers 535.54.03 for x86_64
INFO     2023-06-18 12:45:24,900 [startup.check_driver:61]:GPU: NVIDIA GeForce RTX 3070
INFO     2023-06-18 12:45:24,900 [startup.check_driver:77]:GPU: 10DE:2484 1043:87C1 (nvidia drivers)
DEBUG    2023-06-18 12:45:25,027 [lutriswindow.update_store:448]:Showing 43 games
INFO     2023-06-18 12:45:25,065 [startup.update_runtimes:218]:Startup complete
DEBUG    2023-06-18 12:45:29,257 [wine.use_lutris_runtime:121]:/home/chiefgyk3d/.local/share/lutris/runners/wine/lutris-GE-Proton8-8-x86_64/bin/wine is provided by Lutris, using runtime
DEBUG    2023-06-18 12:45:29,303 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-06-18 12:45:29,303 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/chiefgyk3d/Games/battlenet"
DEBUG    2023-06-18 12:45:29,303 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
DEBUG    2023-06-18 12:45:29,303 [command.start:141]:LD_LIBRARY_PATH="/home/chiefgyk3d/.local/share/lutris/runners/wine/lutris-GE-Proton8-8-x86_64/lib:/home/chiefgyk3d/.local/share/lutris/runners/wine/lutris-GE-Proton8-8-x86_64/lib64:/lib/x86_64-linux-gnu:/lib/i386-linux-gnu:/lib:/lib32:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/i386-linux-gnu/i686/sse2:/lib/i386-linux-gnu/sse2:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib64:/lib64:/usr/lib:/usr/lib64:/usr/lib32:/usr/lib64:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/chiefgyk3d/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/chiefgyk3d/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/chiefgyk3d/.local/share/lutris/runtime/steam/i386/lib:/home/chiefgyk3d/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/chiefgyk3d/.local/share/lutris/runtime/steam/i386/usr/lib:/home/chiefgyk3d/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/chiefgyk3d/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/chiefgyk3d/.local/share/lutris/runtime/steam/amd64/lib:/home/chiefgyk3d/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/chiefgyk3d/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-06-18 12:45:29,303 [command.start:141]:DXVK_HUD="compiler"
DEBUG    2023-06-18 12:45:29,303 [command.start:141]:DXVK_STATE_CACHE_PATH="/home/chiefgyk3d/Games/battlenet"
DEBUG    2023-06-18 12:45:29,303 [command.start:141]:STAGING_SHARED_MEMORY="1"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:__GL_SHADER_DISK_CACHE_SKIP_CLEANUP="1"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:WINEARCH="win64"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:WINE="/home/chiefgyk3d/.local/share/lutris/runners/wine/lutris-GE-Proton8-8-x86_64/bin/wine"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:WINE_MONO_CACHE_DIR="/home/chiefgyk3d/.local/share/lutris/runners/wine/lutris-GE-Proton8-8-x86_64/mono"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/chiefgyk3d/.local/share/lutris/runners/wine/lutris-GE-Proton8-8-x86_64/gecko"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:GST_PLUGIN_SYSTEM_PATH_1_0="/home/chiefgyk3d/.local/share/lutris/runners/wine/lutris-GE-Proton8-8-x86_64/lib64/gstreamer-1.0/:/home/chiefgyk3d/.local/share/lutris/runners/wine/lutris-GE-Proton8-8-x86_64/lib/gstreamer-1.0/"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:WINEPREFIX="/home/chiefgyk3d/Games/battlenet"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:WINEESYNC="1"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:WINEFSYNC="1"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:WINEDLLOVERRIDES="d3d10core,d3d11,d3d12,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvml=n;winemenubuilder="
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:SHELL="/bin/bash"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:SESSION_MANAGER="local/Project-NOS:@/tmp/.ICE-unix/8316,unix/Project-NOS:/tmp/.ICE-unix/8316"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:QT_ACCESSIBILITY="1"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:COLORTERM="truecolor"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:PYENV_SHELL="bash"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:XDG_CONFIG_DIRS="/etc/xdg/xdg-pop:/etc/xdg"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:SSH_AGENT_LAUNCHER="gnome-keyring"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:XDG_MENU_PREFIX="gnome-"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:GNOME_DESKTOP_SESSION_ID="this-is-deprecated"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:GTK_IM_MODULE="ibus"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:MANDATORY_PATH="/usr/share/gconf/pop.mandatory.path"
DEBUG    2023-06-18 12:45:29,304 [command.start:141]:GNOME_SHELL_SESSION_MODE="pop"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:XMODIFIERS="@im=ibus"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:DESKTOP_SESSION="pop"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:GTK_MODULES="gail:atk-bridge"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:PWD="/home/chiefgyk3d"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:LOGNAME="chiefgyk3d"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:XDG_SESSION_DESKTOP="pop"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:XDG_SESSION_TYPE="x11"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:GPG_AGENT_INFO="/run/user/1000/gnupg/S.gpg-agent:0:1"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:SYSTEMD_EXEC_PID="8335"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:XAUTHORITY="/run/user/1000/gdm/Xauthority"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:WINDOWPATH="2"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:HOME="/home/chiefgyk3d"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:USERNAME="chiefgyk3d"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:LANG="en_US.UTF-8"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:XDG_CURRENT_DESKTOP="pop:GNOME"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:VTE_VERSION="6800"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:GNOME_TERMINAL_SCREEN="/org/gnome/Terminal/screen/8bc6af21_25fb_41da_ad6e_1415177abcd6"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:LESSCLOSE="/usr/bin/lesspipe %s %s"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:XDG_SESSION_CLASS="user"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:TERM="xterm-256color"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:DEFAULTS_PATH="/usr/share/gconf/pop.default.path"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:LESSOPEN="| /usr/bin/lesspipe %s"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:LIBVIRT_DEFAULT_URI="qemu:///system"
DEBUG    2023-06-18 12:45:29,305 [command.start:141]:USER="chiefgyk3d"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:GNOME_TERMINAL_SERVICE=":1.156"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:DISPLAY=":1"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:SHLVL="1"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:QT_IM_MODULE="ibus"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:XDG_RUNTIME_DIR="/run/user/1000"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:PYENV_ROOT="/home/chiefgyk3d/.pyenv"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:XDG_DATA_DIRS="/usr/share/pop:/usr/share/gnome:/home/chiefgyk3d/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:PATH="/home/chiefgyk3d/.local/share/lutris/runtime/winetricks:/home/chiefgyk3d/.pyenv/shims:/home/chiefgyk3d/.pyenv/bin:/home/chiefgyk3d/.cargo/bin:/home/chiefgyk3d/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/chiefgyk3d/.local/bin:/home/chiefgyk3d/.local/bin"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:GDMSESSION="pop"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:_="/usr/games/lutris"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/games:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/home/chiefgyk3d/.local/lib/python3.10/site-packages:/usr/local/lib/python3.10/dist-packages:/usr/lib/python3/dist-packages"
DEBUG    2023-06-18 12:45:29,306 [command.start:141]:LUTRIS_GAME_UUID="ec61d008-020c-4082-83df-c29f746c35c3"
Started initial process 21516 from /home/chiefgyk3d/.local/share/lutris/runtime/winetricks/winetricks --unattended
Start monitoring process.
------------------------------------------------------
warning: You are running winetricks-20220411-next, latest upstream is winetricks-20230212!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
Executing mkdir -p /home/chiefgyk3d/Games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411-next - sha256sum: 50b745d7f46ead56fd0c9e6d753d53ea0ae368c988434c25d65fec66307e5d4f with wine-5.12-23491-gd48c657a136 (Staging) and WINEARCH=win64
zenity: symbol lookup error: /lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: gst_codec_utils_caps_get_mime_codec
winetricks GUI enabled, using zenity 
zenity: symbol lookup error: /lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37: undefined symbol: gst_codec_utils_caps_get_mime_codec
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
```

### System Information

```shell
OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: X570 AORUS PRO WIFI -CF 
   /////76767//7676767//////////////      Kernel: 6.2.6-76060206-generic 
  /////767676///*76767///////////////     Uptime: 9 mins 
 ///////767676///76767.///7676*///////    Packages: 3364 (dpkg), 81 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 1920x1080, 1080x1920, 192 
///////////76767676//////7676//////////   DE: GNOME 42.5 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: AMD Ryzen 9 5950X (32) @ 3.400GH 
    /////767676767676767676767/////       GPU: NVIDIA GeForce RTX 3070 
      ///////////////////////////         Memory: 4840MiB / 64212MiB
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment] 2023-06-18 17:05
This is a dupe of #4231.

I have tried to work around the problem; but I can't get the server side of the fix deployed. It looks like this is going nowhere.

**Closed by danieljohnson2** 2023-06-18 17:05 UTC

**Comment by strycore** [comment] 2023-06-21 00:46
> I have tried to work around the problem; but I can't get the server side of the fix deployed. It looks like this is going nowhere.

What part can't you get deployed? You don't have access to the website backend?

**Comment by danieljohnson2** [comment] 2023-06-21 08:21
I can't deploy the updated winetricks runtime package. The buildbot script can't upload it because I lack credentials to do it. If there's a manual way to do this with the Admin UI on the website, I don't know how.

**Comment by strycore** [comment] 2023-06-21 19:00
The buildbot doesn't have the ability to upload to Github but you do have the permissions on the winetricks repo. With access to the Django backend, you can make a new release.

**Comment by danieljohnson2** [comment] 2023-06-21 21:24
If the buildbot script I have doesn't do this, then I don't know how to do it. If it's on lutris.net/admin, I could not find it.
