### ISSUE TITLE
"Use discrete graphics" option toggles between two dedicated GPUS

### ISSUE THREAD

**Issue by BouleuxA** [lutris/lutris#5409] opened 2024-04-09 07:57 UTC
```
[System]
OS:              Pop!_OS 22.04 jammy
Arch:            x86_64
Kernel:          6.8.0-76060800daily20240311-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            20.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 550.67
OpenGL Core:     4.6.0 NVIDIA 550.67
OpenGL ES:       OpenGL ES 3.2 NVIDIA 550.67
Vulkan Version:  1.3.204
Vulkan Drivers:  NVIDIA GeForce RTX 2060 (1.3.277), NVIDIA GeForce GTX 750 Ti (1.3.277)
```
The PC I'm on uses two dedicated NVIDIA GPUs : an RTX 2060 (seen as device 0 by the X server settings) and a GTX 750 Ti (device 1 in X server settings). When the global "Use discrete graphics" toggle is ON, every game launched with Lutris renders on the 750 Ti, as shown by the usage of this card maxing out and the lower performance. The video output is displayed on a monitor that is plugged into the 2060. When this toggle is OFF, games run on the 2060.

I have been able to reproduce this with two different games, on different wine versions. I guess this is not the expected behaviour, as "Use discrete graphics" shouldn't have an effect on a computer without integrated graphics ?

**Comment by danieljohnson2** [comment] 2024-04-09 08:00
This option has been removed from Lutris for the next release and has been replaced with a different drop-down.

Please download the [latest master](https://github.com/lutris/lutris) and run the ``bin/lutris`` script within; no need to install. Try the new drop-down; does that work better?

**Comment by BouleuxA** [comment] 2024-04-09 08:32
Running lutris -d outputs this :
`INFO     2024-04-09 10:25:45,701 [application.do_command_line:479]:Starting Lutris 0.5.17
ERROR    2024-04-09 10:25:46,935 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' died with <Signals.SIGSEGV: 11>.
INFO     2024-04-09 10:25:46,935 [startup.run_all_checks:120]: (10de:1380 1043:84be nvidia) Driver 550.67
ERROR    2024-04-09 10:25:48,127 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' died with <Signals.SIGSEGV: 11>.
INFO     2024-04-09 10:25:48,128 [startup.run_all_checks:120]: (10de:1f08 1462:3755 nvidia) Driver 550.67
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:649:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
ERROR    2024-04-09 10:25:48,154 [system.read_process_output:188]:['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
INFO     2024-04-09 10:25:48,154 [startup.run_all_checks:120]: (simple-framebuffer) Driver None
DEBUG    2024-04-09 10:25:48,397 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-04-09 10:25:48,425 [api.check_stale_runtime_versions:52]:Modified at mar. 09 avril 2024 10:14:58, will update after mar. 09 avril 2024 16:14:58
DEBUG    2024-04-09 10:25:48,430 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
`

The GPU dropdown shows the Auto (default) option, and 3 options with no text. However, using the Auto option, the game launches using the 2060 just fine. 

System info shows this :
`Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Pop!_OS 22.04 jammy
Arch: x86_64
Kernel: 6.8.0-76060800daily20240311-generic
Desktop: pop:GNOME
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 5600X 6-Core Processor
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 31.3 GB
Swap: 20.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 550.67
OpenGL Core: 4.6.0 NVIDIA 550.67
OpenGL ES: OpenGL ES 3.2 NVIDIA 550.67
Vulkan Version: 1.3.204
Vulkan Drivers: NVIDIA GeForce RTX 2060 (1.3.277), NVIDIA GeForce GTX 750 Ti (1.3.277)`

**Comment by danieljohnson2** [comment] 2024-04-09 08:38
Well it's good that the 2060 is fine, I guess. But that log is saying that your installation of Vulkan is broken, I think, and I expect some games are going to break because of it.

**Comment by BouleuxA** [comment] 2024-04-09 08:42
Could it be that there is an issue with my python install/running a lutris that's not a distro package ? Because the installed lutris 0.5.16 does not show this error. I guess I will see later down the line if I have problems, but I've never had any vulkan issue yet.

**Comment by danieljohnson2** [comment] 2024-04-09 08:43
I doubt it; try running ``vulkaninfo`` at the terminal. I think that's what is crashing on you.

**Comment by danieljohnson2** [comment] 2024-04-09 08:52
Hmm. Lutris does ``vulkaninfo --summary`` with some environment variables set to select the ICD. I think the problem with "ICD 5" in particular, though I don't know what that corresponds to.

Some web searches I've done suggest that the issue could be with the Vulkan support for your integrated graphics, but I don't have a lot to go on.

**Comment by BouleuxA** [comment] 2024-04-09 09:05
I have the same web searches results, but I don't have integrated graphics on my CPU.
I also have a hard time figuring out what ICD 5 could refer to - only thing out of order in `vulkaninfo --summary` is that it finds a device called `llvmpipe` running on the mesa driver, I believe that's VM stuff though. I'm going to dig a little bit.

**Comment by strycore** [comment] 2024-04-09 20:22
You have a configuration with 2 Nvidia GPUs which has not been tested by anyone. To make things worse, I believe the GTX 750 works on different drivers than the 2060. 

> Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:649:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER

This error message is a clear sign there is something wrong retrieving vulkaninfo. All Lutris does is call the `vulkaninfo --summary` with a given ICD file set in environment variables. 

Try to reproduce this message in a shell, or try running individual functions of the Lutris code in a Python shell.

**Comment by BouleuxA** [comment] 2024-04-10 20:32
I checked and both the 2060 and the 750Ti are supported on the latest Nvidia driver.
For the rest, that might honestly be above my skill level.
For what it's worth, I tried the code below :
```
from lutris.util.graphics import vkquery
print(vkquery.is_vulkan_supported)
print(vkquery.get_vulkan_api_version())
print(vkquery.get_device_info())
```
that returned the following output :
```
<functools._lru_cache_wrapper object at 0x789ce4229bc0>
4206796
[DeviceInfo(name='NVIDIA GeForce RTX 2060', api_version=4206869), DeviceInfo(name='NVIDIA GeForce GTX 750 Ti', api_version=4206869)]

```
I haven't been able to find what vulkaninfo refers to as ICD 5.

**Comment by BouleuxA** [comment] 2024-04-12 09:47
For the bash script : intel_hasvk_icd.i686, intel_icd.i686, lvp_icd.i686, radeon_icd.i686, virtio_icd.i686, virtio_icd.x86_64 fail with 
```
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:649:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
```
with virtio_icd.x86_64 showing the extra warning :

```
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
```
intel_icd.x86_64, radeon_icd.x86_64 fail because vulkaninfo can't find corresponding GPU (of which there are none) :
```
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR: [Loader Message] Code 0 : setup_loader_tramp_phys_devs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
ERROR at ./vulkaninfo/vulkaninfo.h:230:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED

```
lvp_icd.x86_64 properly displays its vulkaninfo.
**nvidia_icd displays the vulkaninfo, but segmentation faults right at the end :**
```
...<Vulkaninfo>...

VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures:
------------------------------------------------------
	shaderZeroInitializeWorkgroupMemory = true


Erreur de segmentation (core dumped)

```

The python code instantly dies by SIGSESV, with both cards :
```
2024-04-12 11:35:11,177: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' died with <Signals.SIGSEGV: 11>.
```

**Comment by danieljohnson2** [comment] 2024-04-12 21:06
Does look like your drivers are børked.

So vulkaninfo is crashing, but is Lutris? It sounded like we weren't.

But Lutris does use the Vulkan API, and that exposes us to crashing just like vulkaninfo.

But... if you set the env-var ``LUTRIS_NO_VKQUERY`` on the latest code, we don't use vulkan. Please try this with 0.5.17:

``LUTRIS_NO_VKQUERY=1 lutris``

Does that make anything better? If is helps, it suggests that @strycore is right- we should avoid touching the C API ourselves. Using vulkaninfo instead could protect us.

**Comment by BouleuxA** [comment] 2024-04-13 14:00
When starting lutris 0.5.17 without the `LUTRIS_NO_VKQUERY` env-var, vulkaninfo dies with SIGSESV, but Lutris runs fine. Lutris' system information shows the proper Graphics information (for drivers, hardware, and vulkan version). Games run fine. Only effect I can find is that the "GPU" dropdown menu in Display shows "Auto (default)" and 3 empty options. Selecting any of those empty options makes games crash on launch.


Running 0.5.17 with `LUTRIS_NO_VKQUERY=1 ./lutris` shows the exact same symptoms, with vulkaninfo still dying :

```
~/lutris/bin$ LUTRIS_NO_VKQUERY=1 ./lutris
2024-04-13 15:57:37,484: Starting Lutris 0.5.17
2024-04-13 15:57:38,699: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' died with <Signals.SIGSEGV: 11>.
2024-04-13 15:57:38,700:  (10de:1380 1043:84be nvidia) Driver 550.67
2024-04-13 15:57:39,892: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' died with <Signals.SIGSEGV: 11>.
2024-04-13 15:57:39,892:  (10de:1f08 1462:3755 nvidia) Driver 550.67
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ./vulkaninfo/vulkaninfo.h:649:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
2024-04-13 15:57:39,919: ['vulkaninfo', '--summary'] command failed: Command '['vulkaninfo', '--summary']' returned non-zero exit status 1.
2024-04-13 15:57:39,919:  (simple-framebuffer) Driver None

```

**Comment by danieljohnson2** [comment] 2024-04-13 15:07
Well, clearly this proves beyond a shadow of a doubt that my ``vkquery.py`` code is flawless and @strycore was a mutton-head for besmirching it. :stuck_out_tongue_winking_eye:

Since vulkaninfo crashes, our code to get the names of the GPUs is failing, and that's not too shocking. Lutris is going to have a hard time configuring your GPUs like this.

I think maybe this is really not our bug, and you are probably going to have to fix your drivers to get things working right.

**Comment by BouleuxA** [comment] 2024-04-16 19:09
Yes, this is probably on my end. I will look into it ! Thank you both for your time.

**Comment by danieljohnson2** [comment] 2024-04-16 20:34
While I think there is some issue with the Lutris GPU selector, we've got other issues about it. I think we can close this one.

**Closed by danieljohnson2** 2024-04-16 20:34 UTC
