### ISSUE TITLE
Respect server-side decoration on wayland

### ISSUE THREAD

**Issue by tusooa** [lutris/lutris#4433] opened 2022-08-17 20:35 UTC
lutris: everything is forced into the title bar, looks very crowded, and missing important compositor features (say, window actions menu, pin on every desktop, always show on top (all under kwin-wayland))
![image](https://user-images.githubusercontent.com/299873/185237371-d992ef83-4de1-4fb4-a2f5-9b49817c9ecd.png)

firefox, and other gtk programs: respects compositor's decoration, and the title bar contains things it is supposed to contain, all actions provided by compositor are available.
![image](https://user-images.githubusercontent.com/299873/185237421-7d58b0ff-f4cc-445d-b5cb-3165ccf55efc.png)

**Comment by danieljohnson2** [comment] 2022-08-17 20:55
It's not clear to me what Wayland has to do with this.

Some programs do offer multiple UIs like this, but it's a high effort thing to do, and not something GNOME really supports. The GNOME guys are... *opinionated*. Perhaps too much so; distributions have an interest having a visual branding that isn't just GNOME.

But I wouldn't want Lutris to make this change. It shouldn't have to support a Windows 95 style UI just because some users prefer that; that's asking too much. It has the UI it has, and it'll be a better one if the developers don't have to maintain a second.

I won't close this yet in case @strycore is more sympathetic. But I'm against it.

**Comment by tusooa** [comment] 2022-08-17 22:20
Oh, i thought on xorg it would respect server-side decoration.

>support a Windows 95 style UI

it's barely "don't mess up with the title bar" because that's a window manager / compositor thing.

**Comment by tusooa** [comment] 2022-08-17 22:34
a viable ***workaround*** is https://github.com/PCMan/gtk3-nocsd

**Comment by danieljohnson2** [comment] 2022-08-17 22:38
I don't think it work well with server-side decoration anywhere; it hasn't got an alternate UI to display in that case.

If your window manager does not respect the CSD thing, you just get both a title-bar and a header-bar; looks pretty awkward and isn't too compact. I don't think anyone really wants this.

**Comment by tusooa** [comment] 2022-08-17 22:42
![image](https://user-images.githubusercontent.com/299873/185256285-6d1b7ac9-e4bb-440e-8612-71ee335a6312.png)
this is good enough for me. better than the ugly non-standard title bar.

**Comment by strycore** [comment] 2022-08-17 22:44
I can think of one use case where the header bar could benefit being its own widget. When the Lutris client is made full-screen, the header bar disappears, so there's no way to access a bunch of controls.

But that's a pretty limited edge case. Like @danieljohnson2 said, we're not going to maintain 2 sets of UI components. We follow the GTK recommendations because Lutris is a GTK program. 

Lutris is far from being the only program using header bar, you can't just go around and tell application developers to change their designs because you're unhappy with how the toolkit was designed.

**Comment by danieljohnson2** [comment] 2022-08-17 22:44
Well, okay. If that works for you.

From what I hear, many people who dislike the GNOME header bar really complain about its bulk. Doubling up like that makes it worse instead of better.

**Comment by danieljohnson2** [comment] 2022-08-17 22:45
I think if you have a workaround and @strycore is not buying this, we can close this feature request.

**Closed by danieljohnson2** 2022-08-17 22:45 UTC
