### ISSUE TITLE
enable esync/fsync by default

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#2601] opened 2020-01-16 09:50 UTC
Proton does this.

**Comment by odysseywestra** [comment] 2020-01-18 10:30
duplicate of #2270 I believe

**Comment by tannisroot** [comment] 2020-03-04 08:34
@odysseywestra it's a different option.
Regarding the issue itself: Esync is not really there yet in terms of compatibility, especially with buggy software (in fact many GOG game leak descriptors and will crash with Esync enabled), I think it's best to leave things as it is for now.

**Closed by tannisroot** 2020-03-04 08:34 UTC
