### ISSUE TITLE
ARM Architecture

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#418] opened 2016-10-18 04:39 UTC
This wouldn't work on ARM architectures, correct? Raspberry Pi, RPi3?

**Comment by strycore** [comment] 2016-10-18 04:43
some people would like to disagree with that…
ping @daniel-j :D

**Comment by daniel-j** [comment] 2016-10-18 05:45
Lutris runs just fine on ARM, since it's all python! The runners however are for x86 architecture only, and not all runners have ARM versions, so I suppose most can be compiled for ARM (armv7).

Here is a screenshot of me installing Wine Steam (wine running in an x86 emulator) on Raspbian, RPi 3.
![screenshot](https://i.imgbox.com/1L9pahxx.png)
Here is [another screenshot](http://i.imgur.com/oWu0ZSR.png) of me playing an old windows game, runs really well. Launched with Lutris.

**Comment by RobLoach** [comment] 2016-10-18 14:26
So we'd have to add some ARM compilation to https://github.com/lutris/buildbot  for the runners.

**Comment by daniel-j** [comment] 2016-10-18 14:37
Yes. And add some ARM games to lutris website! 👾 
Right now you can't specify architecture for install scripts. Native scripts can have exe and exe64, but that's for x86 only.

**Comment by gsantner** [comment] 2018-03-25 10:36
Was there something going on on this since december?

**Comment by strycore** [comment] 2018-03-26 14:59
@gsantner I haven't received any contribution regarding ARM support, no.

**Comment by Bartimaz** [comment] 2019-01-17 20:03
@daniel-j how did u get lutris on the pi

**Comment by strycore** [comment] 2019-02-03 15:55
I'm going to close this until I think it's worth working on it again.

**Closed by strycore** 2019-02-03 15:55 UTC

**Comment by slappymcphee** [comment] 2019-06-06 01:04
We are running a retrogaming project on a couple ARM based boards and I would love to get Lutris running on them. They are more premium than the Raspberry Pi so I am assuming or hoping that performance is much improved. Any way that this can get reopened?

**Comment by slappymcphee** [comment] 2019-06-06 01:04
> I'm going to close this until I think it's worth working on it again.

We are running a retrogaming project on a couple ARM based boards and I would love to get Lutris running on them. They are more premium than the Raspberry Pi so I am assuming or hoping that performance is much improved. Any way that this can get reopened?

**Comment by slappymcphee** [comment] 2019-06-25 20:15
> I'm going to close this until I think it's worth working on it again.

Can this be looked at again more in-depth for ARM?

**Comment by matoro** [comment] 2019-06-26 13:17
@slappymcphee There's nothing stopping it from working right now, you just won't be able to download emulators/cores on demand from the buildbot.  You can get around this by installing them with the system package manager, and then setting a custom command line for the game - I already do this to use a more recent version of retroarch on x86.

**Comment by slappymcphee** [comment] 2019-06-26 14:30
> @slappymcphee There's nothing stopping it from working right now, you just won't be able to download emulators/cores on demand from the buildbot. You can get around this by installing them with the system package manager, and then setting a custom command line for the game - I already do this to use a more recent version of retroarch on x86.

Actually it is broken. Cannot install either the Debian nor Ubuntu packages. When you try to use them it fails. I will have to capture and provide info later today.

**Comment by slappymcphee** [comment] 2019-06-27 18:29
> @slappymcphee There's nothing stopping it from working right now, you just won't be able to download emulators/cores on demand from the buildbot. You can get around this by installing them with the system package manager, and then setting a custom command line for the game - I already do this to use a more recent version of retroarch on x86.

@matoro  Actually it is broken. Cannot install either the Debian nor Ubuntu packages. When you try to use them it fails. I will have to capture and provide info later today.

**Comment by strycore** [comment] 2019-06-28 04:35
There's an ARM build for SUSE on the OBS repo, maybe that's worth testing.

**Comment by Skidushe** [comment] 2019-08-10 23:39
Can confirm the builds [here](https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris) do work with the builds for ARM and opensuse [here](https://en.opensuse.org/HCL:Raspberry_Pi3). Ended up with lutris working dead easy on my RPI3B . 
Unfortunately the whole point of getting it failed when I realised the game was never compiled for AMD anyway and I do not want to install android haha

**Comment by strycore** [comment] 2019-08-11 01:39
yeah, the problem is going to be with the games and runners themselves. We can ship armv7 binaries for most runners though.

**Comment by pktiuk** [comment] 2020-05-04 14:34
For ARM version it would be good to add support for box86 as runner. It runs quite well with many gemes on raspberry pi 4.
https://github.com/ptitSeb/box86
