### ISSUE TITLE
Origin can't download any games

### ISSUE THREAD

**Issue by frbrz** [lutris/lutris#2774] opened 2020-04-19 01:48 UTC
**Describe the bug**

Origin is waiting for permission. Can't download any game. 
I can not download any games because I get an error: "Origin needs to download files and is waiting for permission. Please choose "Yes" when Windows prompts you for permission.", but the thing is, I don't get the Windows prompts. 

In https://answers.ea.com/t5/EA-General-Questions/Origin-needs-to-download-files/m-p/5143222#M192216 they say "Make sure you are the administrator, run the setup file Origin with Admin rights "
But I don't know how to do that in Lutris.

**Expected behavior**

Origin should instal my games.

**Current behavior**

Origin isn't able to install any games.

**Steps to reproduce**

- Install origin with this script https://lutris.net/games/battlefield-4/ 
- Or this script https://lutris.net/games/origin/
- Try to install any game

**Lutris debugging output**

I don't see any output inside my terminal.

**System information**

Again. I don't see any ouput. But these are my stats running neofetch:

OS: Linux Mint 19.3 Tricia x86_64 
Kernel: 5.3.0-46-generic 
Resolution: 1920x1080 
DE: Cinnamon 4.4.8 
WM: Mutter (Muffin) 
CPU: Intel i7-7500U (4) @ 3.500GHz 
GPU: NVIDIA GeForce 940MX 
Memory: 15899MiB

**Comment by tannisroot** [comment] 2020-04-19 19:13
> I don't see any output inside my terminal.
You must have missed a step then.
Anyway I can't reproduce the issue and I can't help without any logs, closing.

**Closed by tannisroot** 2020-04-19 19:13 UTC

**Comment by frbrz** [comment] 2020-04-19 19:19
Don't close. I installed Lutris again and now I see output when running `lutris -d`. Give me time.

**Comment by frbrz** [comment] 2020-04-19 19:28
lutris-issue-report.json
```
{
  "comment": "Origin is waiting for permission. Can't download any game.\nI can not download any games because I get an error: \"Origin needs to download files and is waiting for permission. Please choose \"Yes\" when Windows prompts you for permission.\", but the thing is, I don't get the Windows prompts.\nIn https://answers.ea.com/t5/EA-General-Questions/Origin-needs-to-download-files/m-p/5143222#M192216 they say \"Make sure you are the administrator, run the setup file Origin with Admin rights \"\nBut I don't know how to do that in Lutris.\n",
  "system": {
    "nvidia_driver": {
      "nvrm": {
        "vendor": "NVIDIA",
        "platform": "UNIX",
        "arch": "x86_64",
        "version": "435.21",
        "date": "Sun Aug 25 08:17:57 CDT 2019"
      }
    },
    "nvidia_gpus": [
      {
        "Model": "GeForce 940MX",
        "IRQ": "134",
        "GPU UUID": "GPU-3e4c0164-3a15-a6d7-010a-5daf9109e650",
        "Video BIOS": "82.08.59.00.8c",
        "Bus Type": "PCIe",
        "DMA Size": "40 bits",
        "DMA Mask": "0xffffffffff",
        "Bus Location": "0000:04:00.0",
        "Device Minor": "0",
        "Blacklisted": "No"
      }
    ],
    "gpus": [
      {
        "DRIVER": "nvidia",
        "PCI_ID": "10DE:134D",
        "PCI_SUBSYS_ID": "103C:81D4",
        "PCI_CLASS": "30200",
        "PCI_SLOT_NAME": "0000:04:00.0",
        "MODALIAS": "pci:v000010DEd0000134Dsv0000103Csd000081D4bc03sc02i00"
      },
      {
        "DRIVER": "i915",
        "PCI_ID": "8086:5916",
        "PCI_SUBSYS_ID": "103C:81D4",
        "PCI_CLASS": "30000",
        "PCI_SLOT_NAME": "0000:00:02.0",
        "MODALIAS": "pci:v00008086d00005916sv0000103Csd000081D4bc03sc00i00"
      }
    ],
    "env": {
      "COLORTERM": "truecolor",
      "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus,guid=4055fc9d24d270c4ed4ab1435e9c8089",
      "DBUS_STARTER_ADDRESS": "unix:path=/run/user/1000/bus,guid=4055fc9d24d270c4ed4ab1435e9c8089",
      "DBUS_STARTER_BUS_TYPE": "session",
      "DEFAULTS_PATH": "/usr/share/gconf/cinnamon.default.path",
      "DESKTOP_SESSION": "cinnamon",
      "DISPLAY": ":0",
      "GDMSESSION": "cinnamon",
      "GDM_LANG": "en_US",
      "GNOME_DESKTOP_SESSION_ID": "this-is-deprecated",
      "GPG_AGENT_INFO": "/run/user/1000/gnupg/S.gpg-agent:0:1",
      "GTK_MODULES": "gail:atk-bridge",
      "GTK_OVERLAY_SCROLLING": "1",
      "HOME": "/home/frbrz",
      "IM_CONFIG_PHASE": "1",
      "INVOCATION_ID": "66a01585723e4123a6009374b698e08e",
      "JOURNAL_STREAM": "9:31971",
      "LANG": "en_US.UTF-8",
      "LANGUAGE": "en_US",
      "LC_ADDRESS": "es_AR.UTF-8",
      "LC_IDENTIFICATION": "es_AR.UTF-8",
      "LC_MEASUREMENT": "es_AR.UTF-8",
      "LC_MONETARY": "es_AR.UTF-8",
      "LC_NAME": "es_AR.UTF-8",
      "LC_NUMERIC": "es_AR.UTF-8",
      "LC_PAPER": "es_AR.UTF-8",
      "LC_TELEPHONE": "es_AR.UTF-8",
      "LOGNAME": "frbrz",
      "MANAGERPID": "1329",
      "MANDATORY_PATH": "/usr/share/gconf/cinnamon.mandatory.path",
      "PATH": "/home/frbrz/.config/nvm/13.8.0/bin:/home/frbrz/.fzf/bin:/home/frbrz/.yarn/bin:/home/frbrz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
      "PWD": "/home/frbrz",
      "QT_ACCESSIBILITY": "1",
      "QT_QPA_PLATFORMTHEME": "qt5ct",
      "SESSION_MANAGER": "local/Envy:@/tmp/.ICE-unix/1341,unix/Envy:/tmp/.ICE-unix/1341",
      "SHELL": "/usr/bin/fish",
      "SHLVL": "1",
      "SSH_AGENT_PID": "1408",
      "SSH_AUTH_SOCK": "/run/user/1000/keyring/ssh",
      "TERM": "xterm-256color",
      "TILIX_ID": "5986c279-20e7-4a15-a83c-a37d10e46ca6",
      "USER": "frbrz",
      "VTE_VERSION": "5202",
      "XAUTHORITY": "/home/frbrz/.Xauthority",
      "XDG_CONFIG_DIRS": "/etc/xdg/xdg-cinnamon:/etc/xdg",
      "XDG_CURRENT_DESKTOP": "X-Cinnamon",
      "XDG_DATA_DIRS": "/usr/share/cinnamon:/usr/share/gnome:/home/frbrz/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop",
      "XDG_GREETER_DATA_DIR": "/var/lib/lightdm-data/frbrz",
      "XDG_RUNTIME_DIR": "/run/user/1000",
      "XDG_SEAT": "seat0",
      "XDG_SEAT_PATH": "/org/freedesktop/DisplayManager/Seat0",
      "XDG_SESSION_DESKTOP": "cinnamon",
      "XDG_SESSION_ID": "c1",
      "XDG_SESSION_PATH": "/org/freedesktop/DisplayManager/Session0",
      "XDG_SESSION_TYPE": "x11",
      "XDG_VTNR": "7"
    },
    "missing_libs": {
      "OPENGL": [
        [],
        []
      ],
      "VULKAN": [
        [],
        []
      ],
      "WINE": [
        [],
        []
      ],
      "GAMEMODE": [
        [
          "libgamemodeauto.so"
        ],
        [
          "libgamemodeauto.so"
        ]
      ]
    },
    "cpus": [
      {
        "processor": "0",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz",
        "stepping": "9",
        "microcode": "0xca",
        "cpu MHz": "500.048",
        "cache size": "4096 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "0",
        "cpu cores": "2",
        "apicid": "0",
        "initial apicid": "0",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "5799.77",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "1",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz",
        "stepping": "9",
        "microcode": "0xca",
        "cpu MHz": "500.057",
        "cache size": "4096 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "1",
        "cpu cores": "2",
        "apicid": "2",
        "initial apicid": "2",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "5799.77",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "2",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz",
        "stepping": "9",
        "microcode": "0xca",
        "cpu MHz": "500.063",
        "cache size": "4096 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "0",
        "cpu cores": "2",
        "apicid": "1",
        "initial apicid": "1",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "5799.77",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      },
      {
        "processor": "3",
        "vendor_id": "GenuineIntel",
        "cpu family": "6",
        "model": "142",
        "model name": "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz",
        "stepping": "9",
        "microcode": "0xca",
        "cpu MHz": "500.038",
        "cache size": "4096 KB",
        "physical id": "0",
        "siblings": "4",
        "core id": "1",
        "cpu cores": "2",
        "apicid": "3",
        "initial apicid": "3",
        "fpu": "yes",
        "fpu_exception": "yes",
        "cpuid level": "22",
        "wp": "yes",
        "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d",
        "bugs": "cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit",
        "bogomips": "5799.77",
        "clflush size": "64",
        "cache_alignment": "64",
        "address sizes": "39 bits physical, 48 bits virtual",
        "power management": ""
      }
    ],
    "drives": [
      {
        "name": "sda",
        "fstype": null,
        "label": null,
        "uuid": null,
        "mountpoint": null,
        "children": [
          {
            "name": "sda1",
            "fstype": "vfat",
            "label": null,
            "uuid": "75CA-D461",
            "mountpoint": "/boot/efi"
          },
          {
            "name": "sda2",
            "fstype": "ext4",
            "label": null,
            "uuid": "44df82a1-9d5c-4019-9390-c309f5f22808",
            "mountpoint": "/"
          }
        ]
      },
      {
        "name": "sr0",
        "fstype": null,
        "label": null,
        "uuid": null,
        "mountpoint": null
      }
    ],
    "ram": {
      "MemTotal": "16280764",
      "MemFree": "2893040",
      "MemAvailable": "12123820",
      "Buffers": "1005992",
      "Cached": "7256932",
      "SwapCached": "0",
      "Active": "6229868",
      "Inactive": "5432416",
      "Active(anon)": "3267692",
      "Inactive(anon)": "204388",
      "Active(file)": "2962176",
      "Inactive(file)": "5228028",
      "Unevictable": "836",
      "Mlocked": "64",
      "SwapTotal": "2097148",
      "SwapFree": "2097148",
      "Dirty": "3988",
      "Writeback": "0",
      "AnonPages": "3400292",
      "Mapped": "883244",
      "Shmem": "223636",
      "KReclaimable": "1382604",
      "Slab": "1458984",
      "SReclaimable": "1382604",
      "SUnreclaim": "76380",
      "KernelStack": "15664",
      "PageTables": "76580",
      "NFS_Unstable": "0",
      "Bounce": "0",
      "WritebackTmp": "0",
      "CommitLimit": "10237528",
      "Committed_AS": "10830092",
      "VmallocTotal": "34359738367",
      "VmallocUsed": "56680",
      "VmallocChunk": "0",
      "Percpu": "1392",
      "HardwareCorrupted": "0",
      "AnonHugePages": "0",
      "ShmemHugePages": "0",
      "ShmemPmdMapped": "0",
      "CmaTotal": "0",
      "CmaFree": "0",
      "HugePages_Total": "0",
      "HugePages_Free": "0",
      "HugePages_Rsvd": "0",
      "HugePages_Surp": "0",
      "Hugepagesize": "2048",
      "Hugetlb": "0",
      "DirectMap4k": "601716",
      "DirectMap2M": "12912640",
      "DirectMap1G": "3145728"
    },
    "dist": [
      "Linux Mint",
      "19.3",
      "Tricia"
    ],
    "arch": "x86_64",
    "kernel": "5.3.0-46-generic",
    "glxinfo": {
      "opengl_profile_mask": "(none)",
      "direct_rendering": "Yes",
      "opengl_es_profile_shading_language_version": "OpenGL ES GLSL ES 3.20",
      "opengl_core_profile_shading_language_version": "4.60 NVIDIA",
      "opengl_context_flags": "(none)",
      "opengl_vendor": "NVIDIA Corporation",
      "opengl_renderer": "GeForce 940MX/PCIe/SSE2",
      "screen": "0",
      "name_of_display": ":0",
      "opengl_es_profile_version": "OpenGL ES 3.2 NVIDIA 435.21",
      "display": ":0",
      "opengl_version": "4.6.0 NVIDIA 435.21",
      "opengl_core_profile_context_flags": "(none)",
      "opengl_shading_language_version": "4.60 NVIDIA",
      "opengl_core_profile_version": "4.6.0 NVIDIA 435.21",
      "opengl_core_profile_profile_mask": "core profile"
    }
  }
}
```

**Comment by frbrz** [comment] 2020-04-19 19:30
Bah, I'm tired of this stupid tool. Close the issue I don't care.

**Comment by byte1024** [comment] 2020-04-20 00:34
> Bah, I'm tired of this horriblly made tool. Nothing works, not even debug. Close the issue I don't care.

Actually, it works very well for not even being at 1.0 yet.

Since, they didn't say anything, I might as well add that I also didn't see this problem. Permissions don't work the way mentioned like they do on Windows.

There's actually a bunch of posts on this already from previous research that I don't have in front of me right now. One was mentioned to try removing all of Lutris, wine prefix, etc. and start clean.

There should be no prompt for that from what I remember. The Origin installer is also still a bit flaky with Wine as I have updates that fail but then only install on the next start of Origin.

The debug logs apparently don't go further than Lutris. So once Wine takes over, the Lutris logs don't take that in, which is something that would be really nice if there was a setting that did do that. Steam and Proton does that but Lutris doesn't as far as I can see.

You could try Origin with just Wine though but Wine by itself requires quite a bit of knowledge and the same possible problems will still exist.

**Comment by Contex-wine** [comment] 2020-05-09 09:40
@frbrz I've been debugging this the last few days here: https://bugs.winehq.org/show_bug.cgi?id=49102.
**Solution**: Re-enable IPv6 in your kernel (remove `ipv6.disable=1` from your kernel command line).

**Comment by frbrz** [comment] 2020-05-14 10:27
I will try it next month @Contex-wine, I'm very stressed and too much is happening right now. Thank you for your efforts. I had IPv6 disabled, has you noticed.
