### ISSUE TITLE
Epic Games games not showing up on lutris

### ISSUE THREAD

**Issue by Chrispy4949** [lutris/lutris#5532] opened 2024-07-11 13:42 UTC
### Bug description

Everytime I try to refesh lutris for my epic games list to reload it always comes up with the error message: module "PIL.Image" has no attribute 'Resampling'

### How to Reproduce

1. Go to 'Lutris'
2. Click on 'Epic Games Refresh'
3. See ![Screenshot_2024-07-11_21-33-15](https://github.com/lutris/lutris/assets/175131440/94275e00-e804-49b2-a0ef-5a740754b259)

### Expected behavior

I should see my list of installed games from epic

### Log output

```shell
2024-07-11 21:41:08,887: Command 'wine' not found on your system
2024-07-11 21:41:08,887: Command 'fluidsynth' not found on your system
2024-07-11 21:41:09,073: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'
INFO     2024-07-11 21:41:09,234 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-07-11 21:41:09,282 [startup.run_all_checks:120]:Intel UHD Graphics 620 (8086:5917 17aa:225d i915) Driver 23.2.1
ERROR    2024-07-11 21:41:09,283 [startup.check_libs:62]:i386 libgnutls.so.30 missing (needed by gnutls)
DEBUG    2024-07-11 21:41:09,492 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-07-11 21:41:09,574 [xrandr._get_vidmodes:18]:Retrieving 43 video modes from XrandR
DEBUG    2024-07-11 21:41:09,700 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-07-11 21:41:09,765 [api.check_stale_runtime_versions:52]:Modified at Thu 11 Jul 2024 08:40:46 PM, will update after Fri 12 Jul 2024 02:40:46 AM
DEBUG    2024-07-11 21:41:09,869 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-07-11 21:41:10,702 [http._request:88]:POST https://lutris.net/api/users/library?since=1720704667
DEBUG    2024-07-11 21:41:23,758 [base.wipe_game_cache:441]:Deleting egs cache /home/christian/.cache/lutris/egs-library.json
DEBUG    2024-07-11 21:41:23,758 [base.wipe_game_cache:175]:Deleting games from service-games for egs
ERROR    2024-07-11 21:41:30,541 [jobs.target:32]:Error while completing task <function BaseService.start_reload.<locals>.do_reload at 0x7d46d470e950>: <class 'AttributeError'> module 'PIL.Image' has no attribute 'Resampling'
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 143, in do_reload
    self.load_icons()
  File "/usr/lib/python3/dist-packages/lutris/services/base.py", line 172, in load_icons
    service_media.render()
  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 85, in render
    self._render_filename(filename)
  File "/usr/lib/python3/dist-packages/lutris/services/egs.py", line 47, in _render_filename
    thumb_image = thumbnail_image(thumb_image, self.remote_size)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 238, in thumbnail_image
    base_image = base_image.resize((width, height), resample=Image.Resampling.BICUBIC)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
^C
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: NO
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Linux Mint 21.3 Virginia
Arch: x86_64
Kernel: 6.5.0-41-generic
Desktop: XFCE
Display Server: x11
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 15.4 GB
Swap: 2.0 GB
[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
OpenGL Core: 4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
OpenGL ES: OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3.1~22.04.2
Vulkan Version: 1.3.204
Vulkan Drivers: Intel(R) UHD Graphics 620 (KBL GT2) (1.3.255)
```

**Comment by danieljohnson2** [comment] 2024-07-11 22:46
This sounds a lot like issue #5445. It looks like this is a Linux Mint thing, you need to install a module manually via ``pip``.

**Comment by danieljohnson2** [comment] 2024-11-04 12:48
Closing as a duplicate of #5445; that issue has a lot more information.

**Closed** 2024-11-04 12:48 UTC
