### ISSUE TITLE
Tooltips are not displayed in KDE Plasma

### ISSUE THREAD

**Issue by potatoleek** [lutris/lutris#4868] opened 2023-05-23 02:11 UTC
### Bug description

In KDE Plasma, tooltips are not displayed when hovering over options. I believe the issue is isolated to KDE Plasma because I cannot replicate the issue in a different desktop environment in the same distro.

### How to Reproduce

1. Go to the Configure menu of any runner.
2. Hover over any option. No tooltip is displayed.

### Expected behavior

A tooltip explaining the option should be displayed.

### Log output

```shell
INFO     2023-05-22 19:02:30,630 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-05-22 19:02:30,632 [startup.check_driver:65]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-05-22 19:02:30,632 [startup.check_driver:69]:GPU: NVIDIA GeForce GTX 745
INFO     2023-05-22 19:02:30,632 [startup.check_driver:85]:GPU: 10DE:1382 10DE:1065 (nvidia drivers)
INFO     2023-05-22 19:02:30,633 [startup.check_driver:85]:GPU:   (simple-framebuffer drivers)
DEBUG    2023-05-22 19:02:30,881 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-22 19:02:30,946 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-05-22 19:02:33,537 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-05-22 19:02:33,596 [application.show_window:339]:Showing window RunnerConfigDialogwine
```

### System Information

```shell
[System]
OS:              Fedora Linux 38 KDE Plasma
Arch:            x86_64
Kernel:          6.2.15-300.fc38.x86_64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             11.6 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 745/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 530.41.03
OpenGL Core:     4.6.0 NVIDIA 530.41.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 530.41.03
Vulkan Version:  1.3.243
Vulkan Drivers:  NVIDIA GeForce GTX 745 (1.3.236)
```

### Media (optional)

Fedora KDE: No tooltip.
![kde](https://github.com/lutris/lutris/assets/62977714/7f341527-a093-4a6f-98f8-5265fdde85ff)

Fedora Xfce: Tooltip is displayed.
![xfce](https://github.com/lutris/lutris/assets/62977714/82de5812-8ab4-498d-8433-51da6853090d)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment] 2023-05-23 08:25
Well, that looks like a KDE bug, but I can't find a specific bug that matches it. They've had bugs with flickering tooltips and tooltips with no text, though. Not sure what's going on.

For what it's worth, I've committed a fix for the goofy looking 'Advanced' switch in the header bar. I'm sure that helps a lot.

**Comment by strycore** [comment] 2023-05-24 10:05
On Kubuntu 20.04, the tooltips are displayed 
![image](https://github.com/lutris/lutris/assets/280336/ed5b65c1-7c9d-4dea-820a-f6e5b079d323)

**Comment by potatoleek** [comment] 2023-05-26 04:35
I agree that the issue cannot be reproduced in all KDE systems, so I did some more testing. I have determined that the issue happens on my Fedora 38 KDE system only when using X11. When I switch to Wayland, the tooltips are displayed. I can reproduce this on my primary system as well as a new virtual machine built just for this test.

**Comment by strycore** [comment] 2023-05-30 17:49
Is this also the case for other Gtk apps? If so, this should be reported in the Plasma bugtracker.
We don't do anything fancy with tooltips. There's no reason for a bug to affect Lutris only.

**Comment by potatoleek** [comment] 2023-06-01 08:54
Does [Pinta](https://flathub.org/apps/com.github.PintaProject.Pinta) count as a GTK app? The tooltips are working correctly in that app.

**Comment by strycore** [comment] 2023-06-01 09:06
It seems to be using Gtk 4. 
Another sign we should start migrating to Gtk 4...

**Comment by strycore** [comment] 2024-01-09 06:15
I've been on Plasma and Wayland for a while. I could never reproduce this issue. 
It could be a bug in Plasma or the Nvidia driver.

**Closed by strycore** 2024-01-09 06:15 UTC
Labels: can't reproduce, not our bug
