### ISSUE TITLE
Error when you try to run a game or app

### ISSUE THREAD

**Issue by leillo1975** [lutris/lutris#4223] opened 2022-04-14 23:45 UTC
### Bug description

Since the last update, when I try to open a game or app on Lutris, nothing happens , and after some seconds apport lauch a reporting error popup.
Another thing I see is that on the bottom of the Lutris window, there are not the controls of the app or game (to configure, to kill wine processes, to use winetricks...).

 

### How to Reproduce

1. Go to 'Lutris window'
2. Click on 'a game or app'
3. See 'an apport reporting error popup'

### Expected behavior

show the controls on the bottom of the Lutris window

### Log output

```shell
leo@PC-LEO:~$ lutris 
2022-04-15 01:35:20,237: Starting Lutris 0.5.10
2022-04-15 01:35:20,274: Using NVIDIA drivers 510.54 for x86_64
2022-04-15 01:35:20,274: GPU: Unknown
2022-04-15 01:35:20,274: GPU: 10DE:2488 1458:404C (nvidia drivers)
2022-04-15 01:35:20,324: Startup complete
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 399, in update_revealer
    self.game_bar = GameBar(game, self.game_actions, self.application)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/game_bar.py", line 61, in __init__
    self.update_view()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/game_bar.py", line 86, in update_view
    self.play_button = self.get_play_button()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/game_bar.py", line 226, in get_play_button
    popover = self.get_popover(self.get_game_buttons(), popover_button)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/game_bar.py", line 233, in get_game_buttons
    displayed = self.game_actions.get_displayed_entries()
  File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 141, in get_displayed_entries
    and not steam_shortcut.all_shortcuts_set(self.game)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/shortcut.py", line 48, in all_shortcuts_set
    shortcut_found = [
  File "/usr/lib/python3/dist-packages/lutris/util/steam/shortcut.py", line 50, in <listcomp>
    if game.name in s['AppName']
KeyError: 'AppName'
```
```


### System Information

```shell
[System]
OS:              Ubuntu 21.10 impish
Arch:            x86_64
Kernel:          5.13.19-051319-generic
Desktop:         ubuntu:GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.3 GB
Swap:            2.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 510.54
OpenGL Core:     4.6.0 NVIDIA 510.54
OpenGL ES:       OpenGL ES 3.2 NVIDIA 510.54
Vulkan:          Supported
```

### Media (optional)

![Captura de pantalla de 2022-04-15 01-44-32](https://user-images.githubusercontent.com/551821/163494137-048ee58d-6f5c-42b6-b018-3112691f0dd0.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment] 2022-04-15 08:55
This looks like yet another dupe of #4195, a very popular bug. Though I don't think other people are getting the apport dialog you do, so that's different.

Anyway, a fix for this has been merged, I think.

Can you try the master branch and see if it helps? Don't install it, just download it and run the bin/lutris script from the command line.

**Comment by leillo1975** [comment] 2022-04-15 21:18
YES! Thanks a lot for the fix, it works!

**Comment by danieljohnson2** [comment] 2022-04-15 21:26
Maybe close this issue?

**Closed** 2022-04-16 01:33 UTC
Labels: needs triage
