### ISSUE TITLE
blank installation script dialog box

### ISSUE THREAD

**Issue by silverhikari** [lutris/lutris#3290] opened 2020-11-16 20:38 UTC
**Describe the bug**

when using a yml script such as the mod manger 2 script i get a dialog box with only the cache button and nothing else.

**Steps to reproduce**
1. download yml script from https://github.com/rockerbacon/lutris-skyrimse-installers
2. in terminal do 'lutris -i /pathtoscript/modorganizer2.yml
3. tab popsup empty
**Lutris debugging output (Optional)**

INFO     2020-11-16 15:28:56,053 [application.do_command_line:319]:Lutris 0.5.8
INFO     2020-11-16 15:28:56,055 [startup.check_driver:61]:Using NVIDIA drivers 455.38 for x86_64
INFO     2020-11-16 15:28:56,055 [startup.check_driver:65]:GPU: GeForce GTX 670
INFO     2020-11-16 15:28:56,055 [startup.check_driver:81]:GPU: 10DE:1189 3842:2678 (nvidia drivers)
DEBUG    2020-11-16 15:28:56,645 [__init__.read_script:37]:Loading script(s) from /home/silver/Downloads/modorganizer2.yml
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 456, in do_command_line
    self.show_installer_window(installers)
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 252, in show_installer_window
    self.show_window(
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 246, in show_window
    window_inst = window_class(application=self, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 97, in __init__
    self.choose_installer()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 123, in choose_installer
    self.validate_scripts()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 115, in validate_scripts
    script[item] = script.get(item) or ""
AttributeError: 'str' object has no attribute 'get'
DEBUG    2020-11-16 15:28:56,767 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-11-16 15:28:56,984 [http.get:73]:GET https://lutris.net/api/runtimes/icons

**System information (Optional)**
https://pastebin.com/nDRYppWp
**Screenshots (Optional)**

![Screenshot_20201116_152958](https://user-images.githubusercontent.com/25397212/99305120-5761ef80-2821-11eb-8bb5-cf845a9ae0bc.png)

**Comment by leycec** [comment] 2020-11-20 05:49
**Yikes.** @AshenPaladin just reported the exact same issue with our own previously working Lutris installers at leycec/aokana-linux#2. Sadly, this appears to be a regression in Lutris 0.5.8 (released five days ago) of #3227 – a similar issue thought to be resolved a month ago. `</sigh>`

@strycore: Since this regressed, would it be feasible to add a new functional test to the Lutris test suite exercising installation of external scripts from the command line via `lutris -i`? It'd be sweet if we could definitively nail this down! :hammer:

**Comment by dhollinger** [comment] 2020-11-24 02:13
I wasn't sure if this was a bug or not. I can get an installer to work if the entire thing is wrapped with a top level key of `results`:

Example of my local installer for  Torchlight:
```yaml
results:
  - game_slug: torchlight
    name: Torchlight
    runner: linux
    slug: torchlight-humble
    version: Humble
    humbleid: torchlight
    humblestoreid: torchlight
    humblestoreid_real: torchlight
    script:
      files:
      - game: 'N/A: Please select the .sh install file downloaded from humblebundle.com'
      - sdl: 'https://github.com/dhollinger/lutris_installers/releases/download/v1.0.0/libSDL2-2.0.so.0.tar.gz'
      game:
        exe: $GAMEDIR/Torchlight/Torchlight.bin.x86_64
      installer:
      - execute:
          args: -u -r -l -d $GAMEDIR -b $GAMEDIR --nox11 --packager dpkg --ignore-failed-deps
          file: game
      - extract:
          file: sdl
          dst: $GAMEDIR/Torchlight/lib64
```

**Comment by leycec** [comment] 2020-11-25 04:53
Noice catch, @dhollinger. Since you're a stalwart repository contributor (*...and thanks so much for that!*), would you happen to know if this backward-compatibility breaking change with respect to the YAML file format is intentional or not? If so, I'll reluctantly refactor my scripts housed across the various GitHub Lutris script repositories I maintain (e.g., [here](https://github.com/leycec/fsnrnue), [here](https://github.com/leycec/aokana-linux)) to suite Lutris 0.5.8's new dastardly requirements.

That said, preserving backward compatibility with the prior YAML file format would be *vastly* preferable. I only maintain a few Lutris scripts, so this isn't much of a personal hardship for me. But there are a few GitHub repositories cataloguing hundreds (if not more) of Lutris scripts. Breaking all of the existing Lutris scripts in the wild would be... **non-ideal.** :disappointed:

**Comment by leycec** [comment] 2020-11-26 03:25
**The silence is ominous.** So, we're officially breaking backward compatibility with the prior file format then, aren't we?

Although I can live with that, it'll be a bitter pill to swallow for the Lutris developer community as a whole. @clad (i.e., the developer of [lutris-skyrimse-installers](https://github.com/rockerbacon/lutris-skyrimse-installers)) has already downgraded back to Lutris 0.5.7, for example. That's obviously *not* a sustainable path forward, but one we can hardly fault users for preferring.

Personally, I'm just annoyed that the new file format makes less rational sense than the prior file format. I mean, really: a new mandatory top-level `results:` list of script installers? Why? Why `results:`? Script installers aren't *output*; they're *input.* And why a list? Do we really expect developers to bundle multiple script installers in a single YAML file and, if so, why? Wouldn't passing a single YAML file listing multiple script installers to Lutris via the `lutris -i` command-line option just unconditionally run each of those installers one after the other? What's the real-world use case for that?

*Anyway.* I'll begrudgingly do it. I imagine everyone else will follow suite shortly, too. But the next time we're contemplating breaking backward compatibility in so drastic a manner, it'd be awesome to at least get a bit of public forewarning and community buy-in around the breakage. `</sigh>`

**Comment by dhollinger** [comment] 2020-11-26 03:52
@leycec It is a holiday week in the US and a Pandemic is still going on. Give them time to take a look and potentially respond.

This issue _only_ affects those using `lutris -i`. The average lutris user does not use offline installers anyway and those users have to take priority. The functionality for uploading and installing using the Lutris website has not changed. You're making a big deal out of nothing. If you can't wait, then submit a PR that reverts or makes the old functionality compatible.

BTW - I do **NOT** speak for the Lutris community. I primarily work on installers that I submit to the site.

**Comment by leycec** [comment] 2020-11-27 03:12
> ...a Pandemic is still going on.

...in those nations that ignore science, yes. Others have successfully eradicated SARS-CoV-2. One of those two approaches is preferable.

> You're making a big deal out of nothing.

Invalidation much? Irrevocably breaking all GitHub-hosted Lutris scripts repositories *is* a big deal for those of us that maintain and use those repositories. I happen to value backward compatibility, because needlessly breaking it wastes everyone's time.

> If you can't wait...

...why wait? I'm refactoring the handful of scripts I maintain to conform to the new format. This isn't a burden for me. It's only a burden for all of the *other* repositories housing a non-trivial number of now-defunct scripts.

> ...then submit a PR that reverts or makes the old functionality compatible.

I didn't break this horse and I'm certainly not fixing it. [My open-source commitments lie elsewhere.](https://github.com/beartype/beartype) The onus of responsibility lies with whoever *did* break it – as well as whoever reviewed and merged that breakage.

**Closed** 2020-11-27 22:20 UTC
