### ISSUE TITLE
[0.5.9.1] Library is empty on startup while "Show Side Panel" is disabled

### ISSUE THREAD

**Issue by Mershl** [lutris/lutris#3762] opened 2021-10-19 19:27 UTC
## Description
Noticed that after the update to 0.5.9.1 my library of locally installed games was empty. Found the culprit: If "Show Side Panel" is disabled on startup the library will be displayed empty.

I suspect that the previously selected Source is restored if the Side Panel is enabled but not if the Side Panel is disabled.

**Start: Library is fully shown**
![image](https://user-images.githubusercontent.com/520251/137976901-8d8afba4-0f95-4745-ba6d-2e3bce86a848.png)

**Now disabling "Show Side Panel". Library is still fully shown**
![image](https://user-images.githubusercontent.com/520251/137976671-a0fd8b86-379f-4239-a685-e5982bddc813.png)

**Close Lutris. Open Lutris**
![image](https://user-images.githubusercontent.com/520251/137976744-d906b671-ff42-460d-83f0-a87c1013003c.png)

**Enabling "Show Side Panel" now will instantly show all games again. Nothing else done besides enabling "Show Side Panel"**
![image](https://user-images.githubusercontent.com/520251/137976901-8d8afba4-0f95-4745-ba6d-2e3bce86a848.png)

**Comment by tannisroot** [comment] 2021-11-16 06:01
closing as dupe of https://github.com/lutris/lutris/issues/3800 which is more recent but is also more detailed

**Closed by tannisroot** 2021-11-16 06:01 UTC
