### ISSUE TITLE
[Move game] "Browse files" stuck on initial installation directory

### ISSUE THREAD

**Issue by Mershl** [lutris/lutris#3121] opened 2020-08-29 20:17 UTC
**Describe the bug**
"Browse files" tries to open the initial installation directory instead of the working directory or directory of the current executable. The installation directory is not editable and thus the "Browse files" becomes unusble once the directory path of the executable changes once.

**Steps to reproduce**
- Mount game disc
- Add game...
- Set executable to an temporary available path (e.g. /run/media/.../installer.exe)
- Run and install the game to ~/Games/the_bottle/Program Files/Game/game.exe
- Unmount game disc
- Edit game and set executable to the installed executable
- Right click the game in Lutris, choose "Browse files".
- Error message: "Can't open /run/media/... . The folder doesn't exist."

This is an extravagant usecase. But the same applies when moving or renaming the game directory after the first setup and pointing the executable to the new location.

**Expected behaviour**
"Browse files" opens the working directory (which by default is the folder of the current executable).

**System information**
Tested with Lutris 0.5.7.1

**Related commit**
3517d86a8323c2b96a92862b72831b4fe6a212d5

**Comment by Zebouski** [comment] 2020-09-22 03:32
I experienced the same issue after moving a game's files to a new folder (from HDD to SSD). I do not see anywhere in the Lutris GUI nor the dotfiles where the old path is being retrieved from, so I don't even know how to workaround the problem. The play button and all works just fine, it's only the Browse Files button that is broken

Here's pics of my example, i moved the game from /media/local to /media/local-s:
![image](https://user-images.githubusercontent.com/11151284/93841687-5fa70f80-fc62-11ea-8802-1de6ddcae134.png)
![image](https://user-images.githubusercontent.com/11151284/93841707-72214900-fc62-11ea-826a-7595a05f2d36.png)

**Comment by strycore** [comment] 2020-10-07 08:57
Closing as duplicate of #1754 and #2439

**Closed by strycore** 2020-10-07 08:57 UTC
