### ISSUE TITLE
Checking for updates should go in background

### ISSUE THREAD

**Issue by burner1024** [lutris/lutris#3809] opened 2021-11-06 06:12 UTC
In case of network issues, it takes minutes for Lutris to start.

**Comment by tannisroot** [comment] 2021-11-09 23:12
What sort of network issues?

**Comment by burner1024** [comment] 2021-11-10 00:29
Any sort? What does it matter?

**Comment by tannisroot** [comment] 2021-11-16 01:56
If I plug the cable (a network issue) I can't reproduce the issue.

**Comment by burner1024** [comment] 2021-11-16 04:19
Try GPRS.

**Comment by tannisroot** [comment] 2021-11-16 04:34
It's very unfortunate that you have such a poor connection, but Lutris runtime is essential for proper functionality of Lutris, we can't just skip it, otherwise no games will function properly.

**Comment by burner1024** [comment] 2021-11-16 04:50
Uhm. You just said it works fine without any network at all.

**Comment by tannisroot** [comment] 2021-11-16 04:59
That's because my runtime was downloaded before I unplugged the cable.

**Comment by burner1024** [comment] 2021-11-16 05:04
Mine was too. The issue isn't about downloading it the first time, but about updates.

**Comment by tannisroot** [comment] 2021-11-16 06:07
Maybe we should introduce a time out of some sort for edge cases like this.

**Comment by burner1024** [comment] 2021-11-16 07:04
Timeouts ought to be present, but I think they solve a different issue. You'd still have to wait out the entire timeout before using the application.
Imagine your OS not allowing you to do anything every time it checks, downloads and installs updates. That would be pretty annoying, wouldn't it?

**Comment by tannisroot** [comment] 2021-11-16 07:29
I suppose it should only stall with the splash screen during the initial startup and do further updates in background instead.

**Comment by strycore** [comment] 2022-02-17 22:59
lutris doesn't check for upgrades at every startup anymore, different delays are set for different types of updates but this will greatly improve restarts of the client. 

To have updates in the background, we would need a global download manager, like Steam has.

**Comment by FallingSnow** [comment] 2022-05-04 22:38
`lutris 0.5.10.1` still experiences this issue.

**Comment by anohren** [comment] 2022-08-05 22:47
I'vr been waiting serveral minutes (5+?) for Lutris to start while it's "checking for runtime updates". The whole thing feels pretty pointless when you *know* beforehand that you have no internet connection. Even after disconnecting WiFi altogether it still keeps "checking" without being aware of the absence of a connection. 

I'm done navigating to GitHub, to this issue section, searching issues, and composing this message — Lutris still hasn't launched. 

This gives me bad Steam vibes, which forces me to stare at 250 MB downloads when launching, practically guaranteeing that I've forgotten whatever I was about to do when I tried to launch the application. In fact, by now I've forgotten exactly why I launched Lutris.

**Comment by danieljohnson2** [comment] 2022-08-05 23:10
Updating in the background is tricky; it's not very safe to replace a runtime while it is in use, and Lutris does not really work if it starts when no runtimes are installed. You could try to download in the background and install upon restart- if all runtimes had been installed already. But this is complicated.

The simplest thing that might help here might just be a 'Stop' button that would stop the download process and hope for the best.

**Comment by FallingSnow** [comment] 2022-08-05 23:23
I think the initial runtime should be bundled, then you can download an updated runtime in the background if possible and use that on next app start. Kind of like how web browsers do updates.

**Comment by burner1024** [comment] 2022-08-06 05:17
> Updating in the background is tricky; it's not very safe to replace a runtime while it is in use, and Lutris does not really work if it starts when no runtimes are installed. You could try to download in the background and install upon restart- if all runtimes had been installed already. But this is complicated.

This issue is about when you already have runtimes, and Lutris tries to download updates.

Self-update is a common feature in various software, often much more complicated than Lutris, for example Windows and various Linux distributions. You don't need to re-invent the wheel here, just present the user with options for update checking:
1. Auto download and apply
2. Check and notify about available updates, allow to launch update manually.
3. Never check, allow to check and launch update manually.

Just implementing this switch is enough to take of of user pain from this issue.

Options 2 and 3 are self explanatory and interactive, so you don't have to worry about anything being in use.
Option 1 (which is current, the only option) can be improved by 
a) Downloading in background.
b) Installing on next launch - provided that previous download is verified to be complete, of course.

**Comment by danieljohnson2** [comment] 2022-08-06 08:40
Well, I still like my innovative 'Stop' button concept. And my new octagonal wheels will be the next world-wide craze too, just you wait.

**Comment by anohren** [comment] 2022-08-06 10:25
The problem with this issue is, I think, that it:

1. prescribes one solution (in the title even)
2. Is now labeled "wontfix", making further discussion pointless (?)

I think the most constructive way forward would be to create a new issue that just describes the problem, without mandating background updates.

**Comment by burner1024** [comment] 2022-08-06 12:29
I don't think I'm in position to mandate anything here. I can change the title if you like =).
Right now I have good connection, so not really affected by this issue, but you can see that other people are.
So... up to developers to make decisions.

**Comment by anohren** [comment] 2022-08-06 14:49
What I mean is that since the core developer has apparently already made the decision for this issue thread (wontfix) perhaps it's a good idea to remove one low-hanging reason for such a decision (prescribing the solution), and while we're at it why not create a new issue that isn't already branded with wontfix. That said, I don't know the relationale for the label. 

Anyway, what I described is a separate bug so I'll probably create a separate issue since it doesn't seem like it's going to be solved through this one.

**Closed** 2022-08-10 20:52 UTC
Labels: wontfix
