### ISSUE TITLE
Download tasks should stop when install is cancelled

### ISSUE THREAD

**Issue by akapps** [lutris/lutris#3443] opened 2021-02-24 19:53 UTC
If game installation is cancelled by the user while still downloading files, the install window is closed but the downloads continue in the background.
One must explicitly cancel each DL **before** stopping the installation. The only way to stop them afterward is by closing Lutris.

**Comment by strycore** [comment] 2021-02-24 22:22
Duplicate of other tickets. Not useful.

**Closed by strycore** 2021-02-24 22:22 UTC

**Comment by akapps** [comment] 2021-03-03 18:05
I haven't found an issue that describes this problem. There seems to be others related to the downloader though.

I initially opened this ticket because I think I can try submit a patch for this specific part. Perhaps I should have opened the PR without creating an issue - sorry for that.

Related PR: #3453
