### ISSUE TITLE
Searching lutris.net from client searches forever. (master)

### ISSUE THREAD

**Issue by aTosser** [lutris/lutris#2586] opened 2020-01-07 19:07 UTC
When using the "Search on lutris.net" button **on the master branch**, the search never completes and results do not show up.
(The game library oddly shows up)

**Expected behavior**

Search results from lutris.net

**Current behavior**

![Lutris-search-spinner](https://user-images.githubusercontent.com/38044923/71921204-68989500-3156-11ea-8741-37e593cfd303.gif)

**Lutris debugging output**

The terminal output of `lutris -d`.

```
INFO     2020-01-07 14:03:57,876 [application.do_command_line:219]:Running Lutris 0.5.4
INFO     2020-01-07 14:03:57,877 [startup.check_driver:55]:Using NVIDIA drivers 440.44 for x86_64
INFO     2020-01-07 14:03:57,877 [startup.check_driver:60]:GPU: GeForce GTX 1660 Ti
INFO     2020-01-07 14:03:57,877 [startup.check_driver:79]:GPU: 10DE:2182 3842:1266 using nvidia drivers
INFO     2020-01-07 14:03:57,897 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-01-07 14:03:57,899 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2020-01-07 14:03:58,202 [store.get_missing_media:208]:Requesting missing icons from API for 13 games
DEBUG    2020-01-07 14:03:58,202 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-01-07 14:03:58,204 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2020-01-07 14:03:58,510 [api.get_game_api_page:132]:Loaded 6 games from page 1
DEBUG    2020-01-07 14:04:01,935 [lutriswindow.search_games:807]:website search for :
DEBUG    2020-01-07 14:04:01,938 [store.get_missing_media:208]:Requesting missing icons from API for 13 games
DEBUG    2020-01-07 14:04:01,938 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-01-07 14:04:02,649 [api.get_game_api_page:132]:Loaded 6 games from page 1
DEBUG    2020-01-07 14:04:10,213 [lutriswindow.search_games:807]:website search for :overwatch
DEBUG    2020-01-07 14:04:10,213 [http.get:65]:GET https://lutris.net/api/games?search=overwatch
DEBUG    2020-01-07 14:04:10,868 [store.get_missing_media:208]:Requesting missing icons from API for 13 games
DEBUG    2020-01-07 14:04:10,868 [http.get:65]:GET https://lutris.net/api/games
DEBUG    2020-01-07 14:04:11,481 [api.get_game_api_page:132]:Loaded 6 games from page 1
```

**Comment by tannisroot** [comment] 2020-01-08 16:32
The issue was caused by https://github.com/lutris/lutris/commit/5cf8361ea59d103fc5a465c28eb5316df6f45015, or https://github.com/lutris/lutris/pull/1553 by @Polynomdivision

**Comment by Polynomdivision** [comment] 2020-01-09 19:04
> or #1553 by @Polynomdivision
That would suprise me quite a bit as I in my PR did only touch the UI code and never even looked at the backend interactions.

**Comment by tannisroot** [comment] 2020-01-09 19:42
It's possible the regression occurred when strider was rebasing it against current master,

**Comment by strycore** [comment] 2020-03-18 17:34
> > or #1553 by @Polynomdivision
> 
> That would suprise me quite a bit as I in my PR did only touch the UI code and never even looked at the backend interactions.

Re-read your PR. You completely ignored and axed some aspects of the game filtering.
There was a `games` argument that suddenly went unused.
Of course this would have likely been caught if you used pylint.

**Comment by strycore** [comment] 2020-03-18 17:36
Marking this as solved but it may need some additional fixes.
The code is now a huge fucking mess.
I don't know how we're going to clean that up.

**Comment by tannisroot** [comment] 2020-03-18 21:33
@strycore seems like this is not entirely fixed - if you do a second search "on lutris.net", the spinning icon doesn't disappear

**Comment by strycore** [comment] 2020-03-18 21:55
As I said, this part of the project is an absolute clusterfuck. There are more than this issue if you poke at it a bit more.

**Comment by tannisroot** [comment] 2020-03-18 23:18
that bad huh :( i suppose this isn't that critical and can get moved to 0.5.6

**Comment by strycore** [comment] 2020-03-18 23:21
I mean, it's not *that* bad because it used to work. It just got broken very easily. 
That's what happens when applying bad design decisions on top of bad design decisions.
I'll close this issue because the client does not search forever anymore. Tickets can't be hijacked to represent other bugs.

**Closed by strycore** 2020-03-18 23:21 UTC
Labels: bug

**Comment by tannisroot** [comment] 2020-03-19 01:24
Ah, ofc, I just thought that the spinning circle was a part of it, I'll open a new one instead, sorry.
