### ISSUE TITLE
Banners are not automatically downloaded anymore

### ISSUE THREAD

**Issue by tuxrinku** [lutris/lutris#3458] opened 2021-03-06 08:00 UTC
Since a few months, banners stopped from being automatically added to a new installed game, even tho the "View on Lutris.net" button points correctly to the game page.

**Comment by JoshStrobl** [comment] 2021-10-12 08:05
Testing on 0.5.9 and issue is still present. After refreshing my Steam library, external games are now detected however the banners for them are never pulled down, resulting in some less-than-ideal results.

![image](https://user-images.githubusercontent.com/156574/136916776-a27964a5-5a84-4ffa-83ec-9d73c54fa363.png)

Interestingly though, if I go to the "Steam" section under Sources and scroll down to the installed games, the banners show up. They just aren't being downloaded.

![image](https://user-images.githubusercontent.com/156574/136916929-a34a3114-fd01-4bc8-8509-2a1a2dc7b6c9.png)

**Comment by tannisroot** [comment] 2021-11-18 02:04
Why not just convert bigger banners to smaller ones for now if the format differs?

**Comment by Lrss** [comment] 2021-11-18 08:14
I think this might be a duplicate of this issue #3730, what is the debug messages when trying to fetch banners for those games?

**Comment by tannisroot** [comment] 2021-11-18 09:05
Oh no it's not, this one is due to a switch to a new banner format for steam games.

**Comment by danieljohnson2** [comment] 2021-11-27 19:47
I'm seeing this problem quite a bit, but I do not use Steam. It is mostly GOG games for me. I've been experimenting with this.

It appears to me that Lutris installs its banners at a few specific points- after a successful install, when reloading the Lutris library, that sort of thing. This is fiddly and its not surprising it misses things. It also downloads *too many* banners sometimes- like when searching Lutris, it loads every banner for every game that matched the search (that is has not got already).

If you are trying to spare the hamster whose hamster wheel powers your web-server, that is not ideal.

I think it would be better to download banners (and icons) only when they are rendered; this way only visible banners are loaded. This can be done by triggering the download via a CellRenderer. Of course care must be taken not to double-download things due to repeated rendering, or download repeatedly when errors occur. And you want to still do them asynchronously.

That goes beyond a bug-fix though. Does this sort of change interest the Lutris team? I could put together a PR.

**Comment by strycore** [comment] 2022-03-10 01:20
With our current system, all banners and cover arts should get downloaded and shown:
- Media is downloaded after game installation
- Media is downloaded after adding a game manually
- Missing media will be reattempted every 24h when the client starts

**Closed by strycore** 2022-03-10 01:20 UTC

**Comment by DanMan** [comment] 2022-07-09 13:57
> Missing media will be reattempted every 24h when the client starts

That should be at least documented somewhere obvious, or it's just going to result in feature requests. I suppose it also requires the "identifier" to match the one on lutris.net? If so, that also isn't self-explanatory but important, if you manually add a game.

**Comment by sokorototo** [comment] 2022-08-02 18:48
Would be nice if there was a button in "Configure" that just says fetch banner art. Then it just shows a preview in the "Game Info" tab. An easy way to force banner art to get fetched

**Comment by awsms** [comment] 2022-08-05 08:09
>Missing media will be reattempted every 24h when the client starts

I digged everywhere to find this piece of info, and I found it on this very random github issue..
May I ask if manual refresh of image assets is in your goals for future releases?

**Comment by jaredballou** [comment] 2022-08-22 23:02
I'm having the same issue. As far as default behavior, I'd much rather get a weird stretched image than a wall of grey rectangles :)

**Comment by sokorototo** [comment] 2022-08-23 00:40
A simple `Fetch|Refresh Banner Art` button to refresh banners would be great. Even better if it reports if it was unable to do so

**Comment by ngdangtu-vn** [comment] 2023-09-27 12:12
I got this problem in 2023. And it only happens on the second install. Before, I installed it with the default repo of the OS, everything seems working very fine. But when I reinstalled OS, and decided to use git source code. Problem about banners appeared. Any advices guys?
