### ISSUE TITLE
Lutris Website Steam Sync Issue with Already Installed Games

### ISSUE THREAD

**Issue by BaronKrause** [lutris/lutris#2101] opened 2019-05-02 15:33 UTC
If you setup Lutris Steam Account sync on the website and import your library and sync it to the desktop client, any games that were already installed through steam but not yet added to lutris can no longer be synced with lutris, since there is now already an entry for it (even though that entry is grayed out since there is no installed game associated with it). Its as if it added the entry, saw it was installed but not added to lutris and then flagged that game as disabled/deleted.

The installed games show up as they should in the import options, but importing them does nothing to the already existing entry that it obtained from the web sync.

You can manually go in and add the app id and anything else it needs, but I can't imagine this is the desired behavior as I would assume this same issue would occur every time you go to install a new natively ran steam game (either native or proton through steam).

If anything import should be able to update those games that were synced from your steam library on the website. I'm guessing this was designed before proton was big, assuming all your steam games would want a lutris installed windows based steam bottle for everything?

It seemed like it might of been kind cool to have the entire library visible right through lutris but in the end I ended up disabling the site sync and manually deleting all the games from the library (1 by 1, and it had to be done both on the site and client) to prevent further issues and just adding games to my lutris library on the site that I want to be installed through lutris, and then setting the lutris client to auto import installed steam games.

**Comment by codeman101** [comment] 2019-05-03 07:03
I've noticed this issue as well. I just assumed it was because Lutris doesn't have install scripts for all the games in library so it therefore doesn't recognize all the games.

**Comment by pmadhikar** [comment] 2019-05-11 17:10
I'm having this issue to. Anything we can do to help find the problem?

**Comment by codeman101** [comment] 2019-05-11 22:51
I would fork this and try to resolve it but I don't know how to do that without affecting my actual install.

**Comment by tannisroot** [comment] 2019-05-16 09:05
This is a duplicate of https://github.com/lutris/lutris/issues/1999

**Closed by tannisroot** 2019-05-16 09:05 UTC
