### ISSUE TITLE
lutris refuses to launch dolphin runner something to do with libraries.

### ISSUE THREAD

**Issue by EuroBlue** [lutris/lutris#5630] opened 2024-10-02 18:33 UTC
### Bug description

Lutris is not opening the Dolphin Emulator.
When opening through terminal this is the output:
`$ ./dolphin-emu
./dolphin-emu: error while loading shared libraries: libavformat.so.60: cannot open shared object file: No such file or directory`
then i tried this:
`LD_LIBRARY_PATH=~/.local/share/lutris/runners/dolphin/lib:~/.local/share/lutris/runtime/lib64 ./dolphin-emu
./dolphin-emu: error while loading shared libraries: libswscale.so.7: cannot open shared object file: No such file or directory`
I found no solution online so i went here.
Lutris version:
0.5.17
Found this issue but the support was denied do to his inferior Distro
https://github.com/lutris/lutris/issues/5382

### How to Reproduce

1. Open Lutris
2. Install Dolphin
3. Click on the Dolphin play button on the side panel 
4. See that nothing happened

### Expected behavior

The Launch of the dolphin emulator.

### Log output

```shell
2024-10-02 20:30:35,599: Command 'fluidsynth' not found on your system
2024-10-02 20:30:35,872: The Battle.net source is unavailable because Google protobuf could not be loaded: No module named 'google'

(lutris:88502): Gtk-WARNING **: 20:30:35.914: Theme parsing error: gtk-dark.css:2553:51: Using one color stop with linear-gradient() is deprecated.

(lutris:88502): Gtk-WARNING **: 20:30:36.083: Theme parsing error: gtk-dark.css:2553:51: Using one color stop with linear-gradient() is deprecated.
INFO     2024-10-02 20:30:36,110 [application.do_command_line:479]:Starting Lutris 0.5.17
INFO     2024-10-02 20:30:36,202 [startup.run_all_checks:120]:NVIDIA GeForce GTX 1070 (10de:1b81 10b0:1b81 nvidia) Driver 560.35.03
DEBUG    2024-10-02 20:30:36,361 [xrandr.get_resolutions:91]:Retrieving resolution list
DEBUG    2024-10-02 20:30:36,364 [xrandr._get_vidmodes:18]:Retrieving 35 video modes from XrandR
DEBUG    2024-10-02 20:30:36,433 [path_cache._update_missing_games:114]:Checking for missing games
DEBUG    2024-10-02 20:30:36,459 [api.check_stale_runtime_versions:52]:Modified at Wed 02 Oct 2024 20:28:55 , will update after Thu 03 Oct 2024 02:28:55 

(lutris:88502): Gtk-WARNING **: 20:30:36.460: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop
ERROR    2024-10-02 20:30:36,472 [style_manager._call_cb:87]:Error reading color-scheme: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/lutris/style_manager.py", line 80, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)
DEBUG    2024-10-02 20:30:36,473 [lutriswindow.create_runtime_updater_cb:1244]:Runtime up to date
DEBUG    2024-10-02 20:30:37,435 [http._request:88]:POST https://lutris.net/api/users/library?since=1727893735
Started initial process 88539 from /home/euroblue/.local/share/lutris/runners/dolphin/dolphin-emu
Start monitoring process.
/home/euroblue/.local/share/lutris/runners/dolphin/dolphin-emu: error while loading shared libraries: libavformat.so.60: cannot open shared object file: No such file or directory
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
DEBUG    2024-10-02 20:30:41,718 [monitored_command.on_stop:228]:Process 88537 has terminated with code 32512
INFO     2024-10-02 20:30:59,897 [application.do_shutdown:1051]:Shutting down Lutris
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: NO
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.11.1-zen1-1-zen
Desktop: 
Display Server: wayland
[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 15.5 GB
Swap: 20.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 560.35.03
OpenGL Core: 4.6.0 NVIDIA 560.35.03
OpenGL ES: OpenGL ES 3.2 NVIDIA 560.35.03
Vulkan Version: 1.3.295
Vulkan Drivers: NVIDIA GeForce GTX 1070 (1.3.280)
```

**Comment by danieljohnson2** [comment] 2024-10-02 19:53
This looks like a duplicate of #5620

**Comment by EuroBlue** [comment] 2024-10-03 14:32
Forgot to mention that the official dolphin-emu package in the arch extra repository works perfectly.

**Comment by EuroBlue** [comment] 2024-10-15 01:27
ping.

**Comment by danieljohnson2** [comment] 2024-11-04 12:29
Closing this as a duplicate of #5620. That one seems to have more information on it, so let's take this there.

**Closed** 2024-11-04 12:29 UTC
