### ISSUE TITLE
[FR / UX] Please to add information that your library is empty.

### ISSUE THREAD

**Issue by pyroxar** [lutris/lutris#2348] opened 2019-09-15 14:20 UTC
When i installed lutris, I was thinking that something is wrong. I needed time to find option to import games but many others users will be thinking that something goes wrong because nothing goes show.
**Screenshots**
![obraz](https://user-images.githubusercontent.com/23406555/64922882-6f308480-d7d4-11e9-9ce8-3589e2726dc2.png)

![obraz](https://user-images.githubusercontent.com/23406555/64922880-6d66c100-d7d4-11e9-8fc9-b42e8df75b7e.png)

**Comment by tannisroot** [comment] 2019-09-15 19:57
Duplicate of https://github.com/lutris/lutris/issues/1984

**Closed by tannisroot** 2019-09-15 19:57 UTC
