### ISSUE TITLE
Installation issues for the Wine Steam runner

### ISSUE THREAD

**Issue by SwimmingTiger** [lutris/lutris#3344] opened 2020-12-04 04:44 UTC
**Describe the bug**

Even if the wine version lutris-5.7.11 has been installed, it will still be downloaded again when installing the Wine Steam runner.

In addition, the installation status of the Wine Steam runner often does not synchronize well with the UI. Even if the installation is complete, the UI is as if not installed. You need to restart Lutris to see the status that the Wine Steam is installed.

I think the issue starts from 0.5.7.1. But this issue also has a certain probability in 0.5.7.

In lutris 0.5.8.1, the probability of this issue is 100%.

**Steps to reproduce**

- Install the wine version lutris-5.7.11
   ![ScreenShot](https://user-images.githubusercontent.com/4986069/101121531-55729b80-362b-11eb-9937-15069ed49b4e.png)
- Install the Wine Steam runner, you will see the wine version lutris-5.7.11 be downloaded again.
   ![ScreenShot](https://user-images.githubusercontent.com/4986069/101121722-ca45d580-362b-11eb-8ada-c0ee97ab9600.png)
- When the download is complete, the progress bar does not reach 100%
   ![ScreenShot](https://user-images.githubusercontent.com/4986069/101122205-e302bb00-362c-11eb-9d09-557e90a2ca48.png)
- The installation appears to be over. There is no wine related process in the background. But Lutris UI looks like Wine Steam is not installed.
   ![ScreenShot](https://user-images.githubusercontent.com/4986069/101122418-720fd300-362d-11eb-9a38-4e5e387588cc.png)
- Restart Lutris, we can finally see the Wine Steam runner is installed.
   ![ScreenShot](https://user-images.githubusercontent.com/4986069/101122564-bef3a980-362d-11eb-9b8b-aca0af2efb4e.png)

**Lutris debugging output (Optional)**

[lutris.log](https://github.com/lutris/lutris/files/5640649/lutris.log)

**System information (Optional)**

```
[System]
OS:              uos 20 Home n/a
Arch:            x86_64
Kernel:          5.8.13-050813-generic
Desktop:         Deepin
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 4900H with Radeon Graphics
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             62.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          X.Org
OpenGL Renderer: AMD RENOIR (DRM 3.38.0, 5.8.13-050813-generic, LLVM 7.0.1)
OpenGL Version:  4.5 (Compatibility Profile) Mesa 19.2.6
OpenGL Core:     4.5 (Core Profile) Mesa 19.2.6
OpenGL ES:       OpenGL ES 3.2 Mesa 19.2.6
Vulkan:          Supported
```

**Comment by strycore** [comment] 2020-12-24 20:59
Please don't use the winesteam runner. It's going away really soon

**Comment by soredake** [comment] 2020-12-25 09:51
> Please don't use the winesteam runner. It's going away really soon

Is it going to be replaced by something?

**Comment by strycore** [comment] 2020-12-29 01:58
It's been replaced by Proton already. We're going to improve support for Proton instead of trying to maintain a Windows install of Steam which works very poorly.
I am not aware of any game that works on WineSteam but not on Proton.

**Comment by soredake** [comment] 2020-12-29 08:22
> It's been replaced by Proton already. We're going to improve support for Proton instead of trying to maintain a Windows install of Steam which works very poorly.
> I am not aware of any game that works on WineSteam but not on Proton.

All games that use ceg cannot work under proton at this time https://github.com/ValveSoftware/Proton/issues/753

**Comment by strycore** [comment] 2021-05-01 02:40
With the direction Lutris services are taking, it will be possible to keep WineSteam around. It will disappear as a runner but will be implemented as a service (such as what we have for Humble Bundle or GOG). This will require to have a working wine installer here: https://lutris.net/games/steam/ because the client installation won't be handled by Lutris anymore. 

Instead of having your WineSteam prefix in ~/.local/share/lutris/runners/winesteam, it would go in ~/Games/steam. Then Lutris would be able to interact with this Steam prefix. Most of the code for handling this is already written but it needs to be moved around to  accommodate as a service instead of a runner.

**Comment by strycore** [comment] 2021-08-05 07:35
Closed in 0.5.9
I was able to install all problematic Proton games (CEG games) in the same Steam for Windows install.
There seems to be a regression in the latest Wine build for Steam login but that's a lutris-wine issue, it works well on lutris-wine 6.1

**Closed by strycore** 2021-08-05 07:35 UTC
Labels: QA

**Comment by strycore** [comment] 2021-08-05 07:36
We're not removing the winesteam runner in this version but it is planned to be removed in the future. You should be able to move your prefix from the runners dir to your Steam for Windows install.

**Comment by Maryplays57** [comment] 2021-11-27 23:16
One of my programs actually won't work under proton. I've only been able to get it to function properly on Wine Steam. It's Clickteam Fusion. I am unable to build or run applications on the proton version, but it works fine on Wine Steam. At least it did, now I can't get Wine Steam to launch at all, so my project for my team is on hold. Please do not remove Wine Steam, I need it.

**Comment by strycore** [comment] 2021-11-27 23:51
https://lutris.net/games/steam/
