### ISSUE TITLE
Lutris sometimes crashes when clicking on a game's System Options

### ISSUE THREAD

**Issue by LinUwUxCat** [lutris/lutris#5221] opened 2024-01-07 18:33 UTC
As said in the title, lutris sometimes but not always crashes when clicking on a game's System Options tab in Configure.

To reproduce: 
- Right click on a game and click configure
- Click on the System Options tab
- Lutris may crash. If it doesn't, close the Configure window and try again

When running `lutris -d`, I get different errors. The first time i got 
```
Pango:ERROR:../pango/pango/pango-layout.c:2601:pango_layout_get_cursor_pos: assertion failed: (index >= layout_line->start_index)
Bail out! Pango:ERROR:../pango/pango/pango-layout.c:2601:pango_layout_get_cursor_pos: assertion failed: (index >= layout_line->start_index)
fish: Job 1, 'lutris -d' terminated by signal SIGABRT (Abort)
```
then the next time i got
```
fish: Job 1, 'lutris -d' terminated by signal SIGSEGV (Address boundary error)
```
then the third time i got 
```
corrupted size vs. prev_size
fish: Job 1, 'lutris -d' terminated by signal SIGABRT (Abort)
```

Video : 

https://github.com/lutris/lutris/assets/46047705/40c0208f-5478-43b8-82b2-da585531e52a

Lutris version : lutris-0.5.14
OS : CachyOS (arch-based)

**Comment by danieljohnson2** [comment] 2024-01-07 19:10
This sounds like #5092. Never figured out what caused that, but we found a workaround- use a fixed list of locales instead of invoking ``locale`` at all for the locale option on that tab.

Please try the latest master branch. Download it, and run the bin/lutris script within- no need to install anything. Try your system options there. Still crashy?

**Comment by strycore** [comment] 2024-01-08 04:39
Yes, this is a duplicate of #5092

**Closed by strycore** 2024-01-08 04:39 UTC
