### ISSUE TITLE
Lutris shows no driver installed notice when using (nvidia-)dkms driver 

### ISSUE THREAD

**Issue by ninelore** [lutris/lutris#2619] opened 2020-02-03 21:50 UTC
I recently switched form arch's `linux` kernel to the `linux-zen` kernel, which required me to use the dkms driver cus there is no normal one compatible with `linux-zen` Cus this replaces the normal nvidia driver, Lutris thinks there is none. 

I know i can check a ignore box but lutris should be also looking for dkms drivers when checking on vulkan drivers

thanks

**Comment by strycore** [comment] 2020-02-04 02:44
Please have a look at this file and have a look at how Lutris is detecting drivers.
Then look in your system to see how your driver is setup.
Once you have this information, report it back here. We cannot help you without it.

**Comment by tannisroot** [comment] 2020-02-07 00:32
I've installed nvidia-dkms package and wasn't able to reproduce this.
I suspect that the issue was caused by not rebooting after installing the package, as installation of nvidia driver requires it.

**Comment by ninelore** [comment] 2020-02-07 20:46
I wasn't be able to gather the information requested by strycore yet due to work. I'll have them in 1-2 days

**Comment by ninelore** [comment] 2020-02-09 11:02
I think i found the Issue. in the Script mentioned by @strycore there is the function `get_nvidia_driver_info()`, which reads `/proc/driver/nvidia/version`

`version` returns the 5th item of that array.

This is the Output from my `cat /proc/driver/nvidia/version`
```
NVRM version: NVIDIA UNIX x86_64 Kernel Module 440.48.02 Tue Jan 14 06:22:51 UTC 2020
```

If i see this right `is_outdated()` will fail because `get_nvidia_driver_info()`'s `version` will just retune "Module"

**Comment by tannisroot** [comment] 2020-03-04 08:43
@ninelore not really, the script starts counting from 0, so `version` will return the 6th item, which is your version.

**Comment by byte1024** [comment] 2020-04-07 19:15
> no driver installed

Is that **exactly** what it says? I can't find that anywhere in the code.

If you know exactly what it says, it can be searched for in the code and then you work backwards from there as that's the actual error in the code that is being outputted. Its better to do that than looking through stuff unnecessarily.

**Comment by strycore** [comment] 2020-04-10 03:23
Going to close this as a system glitch. Most Nvidia drivers installed out there (on Ubuntu for example) are DKMS.
If there is still an issue, it's not caused by the DKMS driver. If you find additional detail and still experience the same problem, please reopen.

**Closed by strycore** 2020-04-10 03:23 UTC
Labels: can't reproduce, missing information

**Comment by ninelore** [comment] 2020-04-10 08:20
Yeah its not reproducible for me anymore. Thanks for your time tho.
