### ISSUE TITLE
Newly installed game gets displayed in the library twice if it was previously removed

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2351] opened 2019-09-15 20:52 UTC
Reproduction steps:
1. Launch Lutris session
2. Install a game so that it gets added to the library 
3. Remove it from library (and just in case remove game files as well)
4. Install the game again
Expected behavior: game gets displayed in the library once
Observed behavior: it gets displayed twice.

**Comment by ZeikoFr** [comment] 2019-09-18 13:52
Which game caused this issue ? I've tried on a random game but can't reproduce a duplication while following the step you provide.

**Comment by tannisroot** [comment] 2019-09-18 19:34
@ZeikoFr Origin

**Comment by ZeikoFr** [comment] 2019-09-19 16:04
Origin the EA Launcher for games ? I will check this in the coming week.

**Comment by ZeikoFr** [comment] 2019-09-23 09:18
Can't reproduce even with Origin on Debian 10.

**Comment by tannisroot** [comment] 2019-09-23 12:01
Maybe you closed Lutris when reproducing it? Because this all needs to be done in a single session.

**Comment by ZeikoFr** [comment] 2019-09-23 13:09
I've done all the test in a sngle session, also tried in manjaro and still can't reproduce, can you give some info on your system ? OS and such :smile:

**Comment by tannisroot** [comment] 2019-09-23 17:36
> also tried in manjaro and still can't reproduce
Which Lutris version are you using? Because I am using latest 0.5.3.

**Comment by ZeikoFr** [comment] 2019-09-25 14:20
> > also tried in manjaro and still can't reproduce
> 
> Which Lutris version are you using? Because I am using latest 0.5.3.

Okay, i'm running 5.2.2.1 on manjaro and on Debian 10 with 0.5.3 but I still doesn't get your issue :/

**Comment by ZeikoFr** [comment] 2019-09-30 12:32
Can you give me the exact OS version you're running ?

**Comment by tannisroot** [comment] 2019-09-30 20:16
I use Arch Linux and it doesn't have versions.

**Comment by ZeikoFr** [comment] 2019-10-09 12:09
> I use Arch Linux and it doesn't have versions.

Hi again, I tried on Arch with 0.5.3 but still can't have the game displayed twice

**Comment by manuelVo** [comment] 2019-10-09 12:36
I failed to reproduce this as well using Arch and the current version of lutris from master (a136c4cd). Maybe you could provide more detailed information about how exactly you cause this issue (do you install via the search in lutris or via the lutris homepage, which checkboxes do you set when removing the game, is lutris set to display all games or only installed games, etc.)

**Comment by xavatar** [comment] 2019-10-26 08:18
Same issue with Warframe.
LinuxMint 19.2

**Comment by legluondunet** [comment] 2019-10-26 09:59
I noted this issue three times last weeks:
1) I installed a new game
2) when the install finished the game displayed twice in Lutris
3) after Lutris restart, no more duplicate

**Comment by strycore** [comment] 2019-11-15 04:49
Cannot reproduce, moving to 0.5.5

**Comment by tannisroot** [comment] 2019-11-15 21:22
I can't reproduce this either anymore. I think it got fixed somewhere in 0.5.4.

**Comment by strycore** [comment] 2019-11-16 16:48
Closing this ticket then

**Closed by strycore** 2019-11-16 16:48 UTC
Labels: bug
