### ISSUE TITLE
In case of several N/A fields, Lutris can pick the wrong one

### ISSUE THREAD

**Issue by d3nwah** [lutris/lutris#5171] opened 2023-12-06 21:39 UTC
Hi!

Case in point: https://lutris.net/games/install/15464/view
This script seems to need two files to be selected by the user in order to work.

Here's how the prompt looks without being logged into GoG (correctly):
![image](https://github.com/lutris/lutris/assets/6751254/06a760e3-c78b-41aa-b799-8075d46df6c2)

And how it is when logged in:
![image](https://github.com/lutris/lutris/assets/6751254/725b1d9a-5a9f-4352-8dbe-60fc9509180f)
Notice the last file was replaced with the autoinstaller for some reason (breaking the script). This behavior doesn't seem to be explained in the Installer documentation, so opening this ticket as bug.

Could be also the cause of https://github.com/lutris/lutris/issues/5166 , though I'm not 100% sure about that.

**Comment by d3nwah** [comment] 2023-12-06 21:39
lutris-0.5.14

**Comment by d3nwah** [comment] 2023-12-06 21:42
There's nothing interesing in `lutris -d` output as the bug occurs:

```DEBUG    2023-12-06 22:41:11,783 [api.get_game_installers:256]:Fetching installer https://lutris.net/api/installers/thief-gold-gog-newdark
DEBUG    2023-12-06 22:41:11,783 [http._request:88]:GET https://lutris.net/api/installers/thief-gold-gog-newdark
DEBUG    2023-12-06 22:41:11,985 [application.show_window:359]:Showing window InstallerWindowthief-gold
DEBUG    2023-12-06 22:41:13,834 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-12-06 22:41:14,553 [interpreter.get_runners_to_install:258]:Default wine version is wine-ge-8-25
DEBUG    2023-12-06 22:41:15,229 [gog.get_extras:320]:Download extras for GOG ID 1207658997 and its DLCs
INFO     2023-12-06 22:41:15,230 [gog.get_game_details:286]:Getting game details for 1207658997
DEBUG    2023-12-06 22:41:15,230 [http._request:88]:GET https://api.gog.com/products/1207658997?expand=downloads&locale=en-US
INFO     2023-12-06 22:41:15,577 [gog.get_game_details:286]:Getting game details for 1207658997
DEBUG    2023-12-06 22:41:15,578 [http._request:88]:GET https://api.gog.com/products/1207658997?expand=downloads&locale=en-US
```

**Comment by strycore** [comment] 2023-12-06 22:15
You seem to be describing the normal behavior of Lutris and also seem to be confused what auto installers are.

**Comment by strycore** [comment] 2023-12-12 01:56
Ah no, I see the issue. There are 2 N/A fields in the installer and Lutris is picking the last one.

A silly workaround but it should work: I swapped the patch and the GOG setup in the file list.
Another fix would be to provide a URL for the patch file. Usually, those are freely distributed, unlike the GOG setup files.

**Comment by QmwJlHuSg9pa** [comment] 2023-12-26 09:10
I think this is a dupe of #5119 (fixed for next release).

**Comment by strycore** [comment] 2023-12-26 23:57
Ok, good to know. I'll close this one.

**Closed by strycore** 2023-12-26 23:57 UTC
Labels: bug
