### ISSUE TITLE
Lutris won't to start both with gui and with terminal

### ISSUE THREAD

**Issue by TeoColuccio** [lutris/lutris#2684] opened 2020-03-25 01:49 UTC
Until same days ago it worked very well.. I'm on debian testing. It's the same, xorg or wayland. If I launch it by terminal, it stay locked here for the first time after a fresh install.
https://pastebin.com/LC1sk2qS
Needless to say, I tried to uninstall it with purge, remove the folders manually on the home and also to start as root, but nothing. I don't really know what happened.
ps lutris -d it's the same too.

**Comment by connectety** [comment] 2020-03-25 12:18
This is a common reappearance of #2554, which is caused by an API-changes in a GTK+ in 3.24.12 / 3.24.13.
The error was fixed with the commit 12a458d.

**Closed** 2020-03-26 23:59 UTC
Labels: duplicate

**Comment by TeoColuccio** [comment] 2020-03-27 00:01
> This is a common reappearance of #2554, which is caused by an **API-change** in a GTK+ **minor version** (3.24.12 / 3.24.13).
> The error was fixed with the commit [12a458d](https://github.com/lutris/lutris/commit/12a458db3c590c3f1972594e091a24cb4d65b610), which sadly is only available in git (maybe there will be a release soon).
> For the time being, **maybe** [edit the files manually](https://github.com/lutris/lutris/issues/2554#issuecomment-587212725).
> Some distros also offer a fix in their distribution of lutris.

Yes, now it's work. Thanks for the help
