### ISSUE TITLE
Steam library sync should use local files only

### ISSUE THREAD

**Issue by SmashleyG** [lutris/lutris#266] opened 2016-04-10 03:41 UTC
I have synced my Steam account with lutris.net. My steam account is set to public. I have connected the lutris client with my lutris account and synced library. 

I am running Kubuntu 15.10, the Steam client is installed and I am able to play games fine. 

I can see all my games in the lutris client, but it does not pick up which ones I have installed already. 

Let me know what information you require and I will supply.

**Comment by Xodetaetl** [comment] 2016-04-15 10:28
You've done everything correctly and it should work indeed.
Please run `lutris -d` in a terminal and paste the output here.

**Comment by SmashleyG** [comment] 2016-04-16 04:51
ashley@Smashdesktop:~$ lutris -d
INFO     2016-04-16 14:49:37,986 [service]:Welcome to Lutris
DEBUG    2016-04-16 14:49:38,030 [lutriswindow]:Loading view
DEBUG    2016-04-16 14:49:38,031 [lutriswindow]:Connecting signals
DEBUG    2016-04-16 14:49:38,090 [lutriswindow]:Getting game list
DEBUG    2016-04-16 14:49:40,451 [runtime]:Runtime lib64 up to date
DEBUG    2016-04-16 14:49:40,452 [runtime]:Runtime lib32 up to date
DEBUG    2016-04-16 14:49:40,452 [runtime]:Runtime steam up to date
INFO     2016-04-16 14:49:40,453 [lutriswindow]:Connected as SmashleyG
DEBUG    2016-04-16 14:49:40,455 [sync]:Syncing game library
DEBUG    2016-04-16 14:49:40,456 [sync]:131 games in local library
DEBUG    2016-04-16 14:49:40,456 [api]:Fetching game library
DEBUG    2016-04-16 14:49:42,627 [sync]:130 games in remote library (inc. unpublished)
DEBUG    2016-04-16 14:49:42,677 [sync]:0 games updated
DEBUG    2016-04-16 14:49:42,683 [system]:Executing which steam
DEBUG    2016-04-16 14:49:50,458 [system]:Executing which steam
DEBUG    2016-04-16 14:50:00,460 [system]:Executing which steam
DEBUG    2016-04-16 14:50:10,459 [system]:Executing which steam
DEBUG    2016-04-16 14:50:20,461 [system]:Executing which steam
DEBUG    2016-04-16 14:50:30,461 [system]:Executing which steam

**Comment by Xodetaetl** [comment] 2016-04-16 09:38
No error in there.
Can you give me an example of a game that Lutris doesn't detect as installed in Steam?
Is it installed in the default Steam location or a custom folder?

**Comment by SmashleyG** [comment] 2016-04-17 01:54
CSS:GO, Shadows of Mordor, basically all of my steam games. 

I have them installed on another drive and link to it via the steam client.

**Comment by RobLoach** [comment] 2016-04-17 03:52
"Installed games only" isn't checked, right?

**Comment by SmashleyG** [comment] 2016-04-17 06:49
It is not, if I did set it, there would be no games showing in the lutris client at all. Its not picking up that they are installed, it does show my steam library.

**Comment by strycore** [comment] 2016-04-17 22:19
The Steam Library syncing is out of cause here as it happens on the website. What seems to be the problem is how we pick up games located in external library folders.

@SmashleyG can you paste the content of  .local/share/Steam/SteamApps/libraryfolders.vdf ?

**Comment by SmashleyG** [comment] 2016-04-18 09:35
The file was not under the same path as you posted, it was actually under .steam/steam/steamapps/

...
"LibraryFolders"
{
	"TimeNextStatsReport"		"1461026127"
	"ContentStatsID"		"-5714585100310916387"
	"1"		"/media/ashley/LinuxData/Games/SteamApps"
}
...

**Comment by Xodetaetl** [comment] 2016-04-19 13:36
We were looking for Steam in `.local/share/steam` and `.steam`, but not `.steam/steam`. I'll fix that.

**Comment by Xodetaetl** [comment] 2016-04-25 10:34
Fixed in 0c4521ac030fb60a2506d1748c4c7538b143dc1a

**Comment by SmashleyG** [comment] 2016-07-01 10:52
Hi, I still haven't had lutris pick up my games, do I need to do anything?, or am I waiting for an update to lutris?

**Comment by strycore** [comment] 2016-07-02 00:34
I'll have to have a look at what's going on with the library sync from the website. I'll report back.

**Comment by driminicus** [comment] 2016-07-24 00:16
I think I have the same issue. None of the games installed via steam on a secondary hard drive show up. 
libraryfolders.vdf is located at ~/.steam/steam/steamapps/libraryfolders.vdf and contains:

"LibraryFolders"
{
	"TimeNextStatsReport"		"1469560532"
	"ContentStatsID"		"521315490616507056"
	"1"		"/media/Data/games/SteamLibrary"
}

lutris -d gives: 
INFO     2016-07-24 02:13:45,787 [service]:Welcome to Lutris
DEBUG    2016-07-24 02:13:45,835 [lutriswindow]:Loading view
DEBUG    2016-07-24 02:13:45,836 [lutriswindow]:Connecting signals
DEBUG    2016-07-24 02:13:45,873 [lutriswindow]:Getting game list
DEBUG    2016-07-24 02:13:45,950 [runtime]:Runtime steam up to date
DEBUG    2016-07-24 02:13:45,950 [runtime]:Runtime lib64 up to date
DEBUG    2016-07-24 02:13:45,950 [runtime]:Runtime lib32 up to date
INFO     2016-07-24 02:13:45,950 [lutriswindow]:Connected as Driminicus
DEBUG    2016-07-24 02:13:45,951 [sync]:Syncing game library
DEBUG    2016-07-24 02:13:45,951 [sync]:102 games in local library
DEBUG    2016-07-24 02:13:45,952 [api]:Fetching game library
DEBUG    2016-07-24 02:13:46,399 [sync]:99 games in remote library (inc. unpublished)
DEBUG    2016-07-24 02:13:46,413 [sync]:0 games updated
DEBUG    2016-07-24 02:13:46,416 [system]:Executing which steam
DEBUG    2016-07-24 02:13:46,421 [system]:Executing which /opt/wine-staging/bin/wine
DEBUG    2016-07-24 02:13:55,953 [system]:Executing which steam
DEBUG    2016-07-24 02:13:55,958 [system]:Executing which /opt/wine-staging/bin/wine
(so basically the same)

**Comment by strycore** [comment] 2016-08-04 00:53
All locally installed games should now be detected by Lutris, whether they are in the lutris.net library or not

**Closed by strycore** 2016-08-04 00:53 UTC
Labels: bug, high priority

**Comment by SmashleyG** [comment] 2016-08-05 03:42
I will give it a try tonight and report back.

Regards,

SmashleyG

**Comment by SmashleyG** [comment] 2016-08-06 03:39
I can confirm this is working now. Thank you strycore.

**Comment by strycore** [comment] 2016-08-06 03:55
Great, we can expect a new release tomorrow then!!

**Comment by SmashleyG** [comment] 2016-08-06 03:58
Strycore, it picks up my library now , but does not pick up which ones are installed. :-S

**Comment by strycore** [comment] 2016-08-06 04:06
hmm? That is strange, it should pick them!

**Comment by strycore** [comment] 2016-08-06 04:07
Anyway, even if the feature isn't 100% working, Lutris 0.4.0 is just around the corner as well so we can fix that before the next release

**Comment by SmashleyG** [comment] 2016-08-06 04:18
Looking forward to it :)

**Comment by strycore** [comment] 2016-08-06 04:23
So if you want to test things, it's currently in the 'next' branch. 0.4.0 is basically the same as 0.3.8 but using Python 3 so be ready to install some dependencies.

I added a command line switch --list-steam-games which will list every detected Steam game and whether they are installed or not.

**Comment by SmashleyG** [comment] 2016-08-06 06:32
Is this the command to change branches "git checkout next" ?

**Comment by strycore** [comment] 2016-08-06 06:39
yes, that's the one

**Comment by Arandolf** [comment] 2020-04-22 07:29
I don't like to necropost, but i think i have the same problem. I have some games locally installed with steam, and i synced my steam library.  It shows me the steam library games, but not as installed. Can you help me?

**Comment by AlexanderRavenheart** [comment] 2020-04-23 08:23
> I don't like to necropost, but i think i have the same problem. I have some games locally installed with steam, and i synced my steam library. It shows me the steam library games, but not as installed. Can you help me?

Then please don't necropost. Open a new issue describing your situation in detail. Don't forget to include all necessary information such as Lutris version and Distribution.
