### ISSUE TITLE
GTA V No DirectX 10 or DirectX 11 found

### ISSUE THREAD

**Issue by N3rdB01** [lutris/lutris#2889] opened 2020-05-18 18:31 UTC
Having an issue with my laptop for some reason not using DirectX 10 or 11. The machine ran windows 10 prior to my install of Pop! OS which i am on version 20.04 video card installed is a Intel® HD Graphics 3000 (SNB GT2). 
The following is the system info directly from Lutris:
[System]
OS:              Pop!_OS 20.04 focal
Arch:            x86_64
Kernel:          5.4.0-7626-generic
Desktop:         pop:GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             15.6 GB
Swap:            4.0 GB

[Graphics]
Vendor:          Intel Open Source Technology Center
OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
OpenGL Version:  3.0 Mesa 20.0.4
OpenGL Core:     3.3 (Core Profile) Mesa 20.0.4
OpenGL ES:       OpenGL ES 3.0 Mesa 20.0.4
Vulkan:          Not Supported

I have tried to find drivers but cannot seem to find any. But I am not sure it is because of the driver. Should be able to run DirectX 10 at least.

**Comment by byte1024** [comment] 2020-05-18 20:33
The HD Graphics 3000 supports max of dx10.1

https://www.intel.com/content/www/us/en/support/articles/000005524/graphics-drivers.html?eu-cookie-notice

Since you're new to Linux, directx is technically a Microsoft thing. Linux is native opengl and also Vulkan.

To use directx applications, you have to use Wine (which Lutris includes). There are various ways that this works there.

One is winetricks which can install various directx versions and you can see this in Lutris as well in the additional config menu for an application/game.

Another way is from DXVK which takes dx and runs it through Vulkan and there's also WineD3D as well for example.

Your GPU there probably doesn't support Vulkan so you can't use DXVK. You can use winetricks, the application installer, and wineD3D. opengl to get a compatible ability to run an application.

This probably shouldn't actually be a Lutris issue though (unfamiliar with Linux issue) and so probably should be closed.

**Comment by N3rdB01** [comment] 2020-05-18 20:38
Well unfortunately I have tried running winetricks to install directx 10
and 11 I do not see wineD3D listed is this something then that should be
moved to opengl?

**Comment by byte1024** [comment] 2020-05-18 20:42
> Well unfortunately I have tried running winetricks to install directx 10 and 11 I do not see wineD3D listed is this something then that should be moved to opengl?

WineD3D is part of Wine itself and you can toggle it on or off in Lutris config for application/game under runner options tab. It can be overridden as well such as by DXVK as an example.

**Comment by byte1024** [comment] 2020-05-18 20:46
> Well unfortunately I have tried running winetricks to install directx 10 and 11 I do not see wineD3D listed is this something then that should be moved to opengl?

WineD3D is part of Wine itself. It can be overridden such as by DXVK as an example.

It can also be possible to disable it otherwise, but I'm not sure if Lutris supports that. If I did see that setting there, I'm not seeing it now.

In any case, its default so if DXVK and VKD3D are not being used then WineD3D should be in use.

**Comment by N3rdB01** [comment] 2020-05-18 20:48
Ok so neither DXVK nor VKD3D should be activated.

**Comment by byte1024** [comment] 2020-05-18 20:50
> Ok so neither DXVK nor VKD3D should be activated.

The only other thing I will note here is that if some application/game isn't working then its likely a Wine problem. Its hit or miss as to what works though more stuff works today but a lot doesn't.

**Comment by N3rdB01** [comment] 2020-05-18 20:50
That you for that information. Making sure both were not active did the
trick. It might be beneficial to have it listed somewhere or maybe when
standard installer runs look for vulkan compatibility?

**Comment by byte1024** [comment] 2020-05-18 20:51
> That you for that information. Making sure both were not active did the trick. It might be beneficial to have it listed somewhere or maybe when standard installer runs look for vulkan compatibility?

Suppose that should be dealt with by the Lutris EGS installer script.

**Comment by xordspar0** [comment] 2020-05-19 13:33
> or if its to be taken up with the script dev

Yeah, this is something that the installer script can control, so maybe it would be best to report it to the installer script: https://lutris.net/games/grand-theft-auto-v/

**Comment by strycore** [comment] 2020-05-19 16:22
You are NOT going to run GTA V on this underpowered, nearly 10 year old integrated GPU on Linux. I can assure you that.

To stop giving you false hopes, I'm going to close this ticket.

**Comment by strycore** [comment] 2020-05-19 16:23
Also, do not mess up install scripts for old hardware like that.

**Closed by strycore** 2020-05-19 16:22 UTC

**Comment by N3rdB01** [comment] 2020-05-19 16:24
Well I am running in this gpu

**Comment by strycore** [comment] 2020-05-19 16:25
Maybe you can play it on Windows but in order to play it on Linux, you need Vulkan.

**Comment by N3rdB01** [comment] 2020-05-19 16:26
Hmm well it seems to work. Not sure why but it is.

**Comment by strycore** [comment] 2020-05-19 16:33
At best, you might be able to launch the game wined3d and get unplayable framerates.

**Comment by RafaelAmauri** [comment] 2021-07-06 22:36
I'm having the same problem, and my GPU is far from being considered obsolete. I have an RX 580 8GB. 

Disabling DXVK woks, but gives me less than desirable framerates, unfortunately. Other versions of the Lutris runner don't work or just give me the same error message as @N3rdB01's, which is weird, cause I played a lot of GTA V back when the EGS gave it away for free and I remember not having any issues at all.

CPU: Ryzen 5 5600X
GPU: AMD RX 580 8GB
Mesa: 21.1.4-1
Distro: Arch Linux
Kernel: 5.13 (compiled from source, but I also tested with 5.12.14 and 5.10-LTS and the problem is still the same)

**Comment by Synaxis** [comment] 2022-11-01 15:04
strange BUG
also here on ubuntu 22.04 nvidia mx 450

**Comment by hashnil** [comment] 2022-12-13 05:37
also here on mint lmde 5  nvidia gt 710

**Comment by LibertyDrew13** [comment] 2023-01-07 12:58
Well....perhaps this ticket is best left open, so that people can help each other as this forum was designed....rather than to have restrictive mods close comments that are helpful to the community, though annoying to them.....even a bunch of GTA dolts with older hardware and....ew....Linux (shout-out to omg! Linux) should have the opportunity to "screw up" scripts for older hardware...(thought that was sort of the point of open source tinkering and a cooperative community who believe more in the power of free use and best use rather than new use and shiny proprietary hardware that comes out every 6 months rendering the last version obsolete. Can you imagine a Microsoft only world...or a world In which one company is the internet and they charge by the hour for use? I can (shout out to Stephen Case and AOL $12.70/hr).   I grew up in that era and railed against that type of crap....so keep the post open. Who cares if people want to tinker around and see if they can do what was previously not able to be done. There is, after all, no short of interest in this post as is easy to see. 
  Thanks for understanding Ms. Moderator and thanks for all your work And contribution keeping the trolls and weirdos at bay......

**Comment by veerverma828** [comment] 2024-01-21 06:57
This issue should not be closed 😿
