### ISSUE TITLE
Lutris not running flatpak installed openRCT2, only shows "install_type"

### ISSUE THREAD

**Issue by gituser823** [lutris/lutris#5379] opened 2024-03-25 04:05 UTC
hello,

I installed OpenRCT2 via Flathub manually, because both CD installers from https://lutris.net/games/rollercoaster-tycoon-2/ did not work (maybe you can fix those too).

I can run the game just fine from the terminal with 

flatpak run io.openrct2.OpenRCT2

although getting these errors:

```
sh: line 1: xdg-mime: command not found
Object conflict: '/app/bin/../share/openrct2/object/rct2/audio/rct2.audio.base.json'
               : '/app/bin/../share/openrct2/object/rct2/audio/rct2.audio.base.rctc.json'
1 object conflicts found.
```

Trying to launch it from Lutris though I only get a window saying "install_type".

I literally only added the flathub games name "io.openrct2.OpenRCT2" when setting it up in lutris.

Also when I click on the shortcut and "configuration" nothing opens, but i dont know if this is expected or not.

OS:
Linux Mint Debian Edition 6

Lutris v0.5.12

Thanks!

**Comment by danieljohnson2** [comment] 2024-03-25 20:25
I think this is a dupe of #4952, and is fixed. You are on a pretty old Lutris; you should update to a recent version, and I think you will be okay. You can install it from the releases page [here](https://github.com/lutris/lutris/releases) or you could use flatpak.

If you can still repro this on 0.5.16, file a new issue and I'll take a look. Do provide a debug log if you do so, please. ``lutris -d`` is your friend.

**Closed by danieljohnson2** 2024-03-25 20:25 UTC
