### ISSUE TITLE
GOG import doesn't pick up bundled games

### ISSUE THREAD

**Issue by gavandor** [lutris/lutris#2067] opened 2019-04-20 13:29 UTC
This is for GOG games that are sold as a single item but give you multiple library entries.
They show up separately in the import list and can be selected, but aren't actually picked up.

Examples where this is happening:
[Blackwell Bundle](https://www.gog.com/game/blackwell_bundle)
[STAR WARS™: TIE Fighter Special Edition](https://www.gog.com/game/star_wars_tie_fighter_special_edition)
[STAR WARS™: X-Wing Special Edition](https://www.gog.com/game/star_wars_xwing_special_edition)
[Ultima™ 7 The Complete Edition](https://www.gog.com/game/ultima_7_complete)

**Comment by skyace65** [comment] 2019-04-22 22:48
I had this exact problem when I bought [Master of Orion 1+2](https://www.gog.com/game/master_of_orion_1_2) on GOG. I couldn't import them until a mod on Discord added them to Lutris themselves.

**Comment by strycore** [comment] 2019-04-23 23:14
this is a duplicate of another bug that we already have, don't remember the number and it's most likely on the website repo.

**Closed by strycore** 2019-04-23 23:14 UTC

**Comment by gsantner** [comment] 2020-04-29 22:07
I encounter the issue still on latest Lutris release version.

I bought [Dungeon Siege Collection](https://www.gog.com/game/dungeon_siege_collection) today and at import screen the game shows up correctly. Also importer tells me everything imported. But actually it didn't import and game doesn't show up in game list. I've tried this more than 5 times now and it simply doesn't work.


![Screenshot_20200430-000509](https://user-images.githubusercontent.com/6735650/80651516-567c9280-8a76-11ea-9246-2d0abf3b62b3.png)

@strycore 
May I ask for reopen? Or reference/reopen the original issue?

**Comment by strycore** [comment] 2020-04-30 23:07
This is another issue and yes, this will get solved soon

**Comment by gsantner** [comment] 2020-05-30 08:05
#2887
