### ISSUE TITLE
After System Crash (from Navi bug) Lutris Refuses to Launch after Reboot

### ISSUE THREAD

**Issue by gardotd426** [lutris/lutris#2632] opened 2020-02-18 10:57 UTC
**Describe the bug**
I've had Lutris installed on this system for 4 months, and it's worked perfectly fine. However, I recently got an RX 5600 XT, which is a Navi GPU and suffers from [this well-known bug](https://gitlab.freedesktop.org/drm/amd/issues/892#note_411733). Until kernel 5.6, the system would just freeze and I would be forced to do a hard reset. Well they added a workaround to "enable" the GPU to reset itself, but now when the issue happens the system just crashes instead of freezing. At any rate, if this happens while Lutris is open (which it only happens while Lutris is open because it only happens while running games), upon reboot Lutris absolutely will not launch. Launching it through a terminal with `lutris -d` does nothing, it just gives that (I'm assuming normal) error message about "no module named 'yaml'" which it always says even when its working. But that's it, it just freezes, there's literally no other output, and I can't even kill it with CTRL+C, I have to actually exit the terminal, or open another one and enter `killall lutris`. 
The only thing I could find on any forums were someone having a similar issue had posted on the lutris forums and mentioned they had the same problem where it wouldn't launch and trying to launch it from the terminal gave no output and they couldn't kill it with CTRL+C. However, the only suggested fix was to remove the ~/.config/lutris folder and try again. Someone else there said it solved their problem, but I'd already tried that, it was the first thing I tried. It doesn't work. 

**Expected behavior**
Lutris launches

**Current behavior**
Literally nothing. 

**Steps to reproduce**

- Have a navi card
- Have lutris open while the system does the hard reset thing
- Upon reboot, try to launch Lutris

**Lutris debugging output**

Again, literally nothing. 

Things I've tried:
- Uninstalling lutris with `sudo pacman -Rns lutris` which removes all configuration files, and reinstalling
- Removing `~/.config/lutris` as well as `~/.cache/lutris`
- Copying the config folder from my Manjaro installation. 
- Trying the `lutris-git` package from the AUR. It doesn't work at all.
- Literally the only thing that allows me to launch lutris again is restoring from a timeshift snapshot of my system from yesterday (before the issue happened for the first time). After restoring that snapshot, Lutris launched fine. However, it happened again, and once again nothing worked and the only thing I could do was go back to the snapshot again. That's really annoying, I can't be restoring snapshots every time there's a crash. 

System: Arch Linux.
Kernel: 5.6-rc 
Lutris version: 0.5.4-1

Also, I'm not asking for any help on the crashes, that's just a bug with Navi and there's nothing that can really be done about it right now. But there's no reason why after a crash Lutris will just completely refuse to launch. I tried removing the ~/.cache/lutris folder because it seems like some sort of log is being stored during the crash that is screwing lutris up and making it fail to launch, but removing the cache folder does nothing and I don't know where else it might be.

**Comment by JostBrand** [comment] 2020-02-19 09:40
Not sure if its related to your GPU got a Nvidia Card.
Yesterday it worked now i got this output:
```
2020-02-19 10:36:58,060: Running Lutris 0.5.4
2020-02-19 10:36:58,061: Using NVIDIA drivers 440.59 for x86_64
2020-02-19 10:36:58,061: GPU: GeForce GTX 1080
2020-02-19 10:36:58,061: GPU: 10DE:1B80 10DE:119E using nvidia drivers
2020-02-19 10:36:58,083: Vulkan is supported
2020-02-19 10:36:58,084: Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2020-02-19 10:36:58,688: Updating D9VK versions


```

**Comment by gardotd426** [comment] 2020-02-19 09:43
Mine started freezing at that spot too after removing the cache and config
files.

**Comment by gbschenkel** [comment] 2020-03-01 05:47
Having the same issue on Slackware x64 current_with_PAM to launch, the debug show as follow, the only thing show up is the window to support Lutris, soon I close it, it show the traceback on shell and the message about updating D9VK. I need use CTRL+C to stop it from doing nothing.

```
INFO     2020-03-01 02:40:21,086 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-03-01 02:40:21,086 [startup.check_driver:54]:Using NVIDIA drivers 440.59 for x86_64
INFO     2020-03-01 02:40:21,087 [startup.check_driver:60]:GPU: GeForce GTX 1080
INFO     2020-03-01 02:40:21,088 [startup.check_driver:77]:GPU: 10DE:1B80 3842:6286 using nvidia drivers
INFO     2020-03-01 02:40:21,133 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-03-01 02:40:25,283 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib64/python3.8/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib64/python3.8/site-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib64/python3.8/site-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
INFO     2020-03-01 02:40:25,635 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
```

**Comment by gbschenkel** [comment] 2020-03-01 06:58
I used the commit b029c5c82cdca6e23ad2c069713dd1de and I was able to launch Lutris without problem.

```
INFO     2020-03-01 03:49:14,062 [application.do_command_line:236]:Running Lutris 0.5.4
INFO     2020-03-01 03:49:14,062 [startup.check_driver:54]:Using NVIDIA drivers 440.59 for x86_64
INFO     2020-03-01 03:49:14,062 [startup.check_driver:60]:GPU: GeForce GTX 1080
INFO     2020-03-01 03:49:14,063 [startup.check_driver:77]:GPU: 10DE:1B80 3842:6286 using nvidia drivers
INFO     2020-03-01 03:49:14,108 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-03-01 03:49:16,079 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2020-03-01 03:49:16,302 [http.get:65]:GET https://lutris.net/api/runtime
INFO     2020-03-01 03:49:20,805 [application.do_shutdown:481]:Shutting down Lutris
```

I am making the script available for Slackware current in the link bellow:
https://gitlab.com/gbschenkel/slackbuilds/-/tree/current/games/lutris-git/

**Comment by tannisroot** [comment] 2020-03-04 08:06
Yeah this is a known issue and I don't think it was caused by a driver update.

**Closed by tannisroot** 2020-03-04 08:06 UTC
