### ISSUE TITLE
Lutris missing all games from my library on Fedora 32

### ISSUE THREAD

**Issue by tuxtergames** [lutris/lutris#2765] opened 2020-04-17 20:39 UTC
Describe the bug

After install clean Fedora 32 and install Lutris my library don't appear, then I decided to erase my entire home, and reconfigure everything, then after reboot everything gone.

Expected behavior

Play my Games like Fedora 31

See the message "Failed to launch them game"

No, i can't see my games

What is the current behavior?

Just a brown interface without any games

Steps to reproduce

Install Lutris
configure it
reboot  system
 games gone

lutris output
[Lutris.log](https://github.com/lutris/lutris/files/4495135/Lutris.log)
json
[lutris-issue-report.tar.gz](https://github.com/lutris/lutris/files/4495136/lutris-issue-report.tar.gz)

**Comment by tuxtergames** [comment] 2020-04-17 20:40
this is what i Saw when open lutris 
![image](https://user-images.githubusercontent.com/26095484/79612182-8f118900-80d2-11ea-9e92-5bb81c0f6bc4.png)

**Comment by Steinhagen** [comment] 2020-04-17 22:58
If I were to guess, your issue is related to the change in the PGA introduced in Lutris 5.6. Quoting from the changelog:

* Convert play time from string to float in the database. Do not downgrade back to older versions or you'll experience issues.

My advice, update Lutris to 5.6 and your issue should be fixed.

**Comment by byte1024** [comment] 2020-04-17 23:50
That could be a good guess.

To inject some humor. When I looked at it, thought it was specifically code for PGA Tour Golf games that required some dedicated code blocks lol. That's badly named in my opinion.

`game = PgaGame(pga_game)`

Never make a comment for those games. I don't even know what a pga game is besides that.

**Comment by Steinhagen** [comment] 2020-04-18 00:07
Again, if I were to guess, I'm pretty sure he modified his repositories to have the latest and greatest on Fedora 31.

**Comment by strycore** [comment] 2020-04-18 19:28
I don't know what going on here. Seems like the migration was executed properly and then the old client was run. 
There's something wrong with this setup. It doesn't have anything to do with the Python version or professional golf (or Personal Game Archives either).
Line 132 in /usr/lib/python3.8/site-packages/lutris/gui/views/store.py should say "float", if it has "str" then something has gone very wrong.

**Comment by byte1024** [comment] 2020-04-18 20:24
The Fedora updates has 5.6 in testing right now that this person could try as well which appears to be working https://bodhi.fedoraproject.org/updates/FEDORA-2020-5c61675ada

It could be as Steinhagen suggests. The lutris log for this issue shows Lutris 0.5.5. I wouldn't hazard a further guess until 5.6 is tried.

I feel like you were continuing my joke "(or Personal Game Archives either)" :-)

**Comment by strycore** [comment] 2020-04-18 21:14
Sounds about right. If someone did some testing for 0.5.6 then went back to 0.5.5, they would experience this bug.

PGA originally came from Ubuntu PPAs but replacing Packages with Games. The problem is that Lutris uses the "pga" table in the database to store games that are not archived. The archive part of Lutris is not done yet although we do have a game cache now, so that's progress!

**Comment by buxel** [comment] 2020-04-19 10:55
Is there a way to trigger the migration manually? I just upgraded from 0.5.5 to 0.5.6 and have exactly the same problem.

**Comment by tuxtergames** [comment] 2020-04-19 12:47
Tks all reply here, after lasts updates of F32 and upgrade to 0.5.6 solve my problem here, tks folks.

**Closed** 2020-05-01 00:06 UTC
