### ISSUE TITLE
Re-re-re-add Proton to available wine versions

### ISSUE THREAD

**Issue by nettnikl** [lutris/lutris#3375] opened 2021-01-23 10:54 UTC
Hello, I know it sounds fairly adventurous, but I think you should revert "Revert "Revert "Revert "Remove Proton from available supported wine versions"""" ( https://github.com/lutris/lutris/commit/36c855afdc1f4cd841277e58c783836696f89564), as currently not all games are compatible with the Lutris wine prefixes.

For example the current GE build is able to run GTA V, while the Lutris builds i tested (also the latest Lutris Wine build 6.0-rc1) had issues with freezing about 4 seconds whenever pressing buttons on the keyboard.
Other users also experience this using Lutris Wine 6.0-rc1, and also worked around it by using the GE build. (https://lutris.net/games/grand-theft-auto-v/, https://forums.lutris.net/t/gta5-freezes-when-a-keyboard-key-is-pressed-arch-linux/11269, https://old.reddit.com/r/Lutris/comments/ki8ucs/gtav_freeze_on_key_press_for_multiple_seconds/)
It seems to be a common issue.

As proton builds are not fully supported ootb atm, as far as I understand (as the correct ENV is not set, that Proton needs (https://github.com/GloriousEggroll/proton-ge-custom#manual)), it could be marked experimental (if it will be) or deprecated.

My current workaround is to downgrade Lutris, and use the ge build. That works flawlessly, even without further modifications to the environment.

**Comment by strycore** [comment] 2021-01-23 22:47
If you have a look at the source code (hint `grep PROTON`) you might find that there is some way to bring Proton versions back without downgrading.
I also experienced the freezing issue in some games, and wasn't sure it was related to the new wine build but this seems to confirm it.
We'll try to push a build fixing this issue as soon as possible. Maybe try an older lutris build instead of Proton, you might have some better luck with that.

I have to close this issue because I get shouted at every time I bring back Proton.

**Closed by strycore** 2021-01-23 22:47 UTC

**Comment by VortexAcherontic** [comment] 2021-02-24 10:07
Hey there I know this is a closed issue but I like to bring it back up because since yesterday the Rockstar Game Launcher had an update which makes the Launcher unable to connect to the Rockstar game servers and therefore get a timeout after a minute or so with Wine 5.7-11 and probably older ones too I did not tested all older versions since everything was fine with 5.7 until yesterday.

Using lutris wine 6.0 make the launcher functioning again but introduces also the freezing issue when pressing keys on the keyboard while Gamepads and Mouse work fine BUT this issue is also present with vanilla Wine 6.2 since I tested it too, the game runs and also the launcher works properly but also the upstream wine suffer from this issue. So it is not an issue dedicated to your wine build.

In order to make the game functioning properly again I had to use Proton 6.1 GE 2 by symlinking the dist folder of 6.1-GE-2 to the wine runners of Lutris so it adapts Proton as a valid Wine build.

Things work again pretty well, Keyboard, Gamepads, Mouse and the Launcher.

Maybe it is possible to merge the GE fixes also into your wine builds? Since I feel pretty uncomfortable with hacking Proton builds into Lutris this way ^^"

**Comment by jeffereyweatherill** [comment] 2021-02-24 16:07
> In order to make the game functioning properly again I had to use Proton 6.1 GE 2 by symlinking the dist folder of 6.1-GE-2 to the wine runners of Lutris so it adapts Proton as a valid Wine build.

I'm having the same issue, could you please explain how to "symlink the dist folder of 6.1-GE-2 to the wine runners of Lutris"? I've located the dist folder, but am unsure where to add it as a wine runner.

**Comment by strycore** [comment] 2021-02-24 22:35
for fucks sake....
since you are really unable to process even the slightest hint I give here how you launch lutris with proton:

`LUTRIS_ENABLE_PROTON=1 lutris`

Now have fun fucking up your games using a another runner than the one we have tested and worked on. 🖕

**Comment by strycore** [comment] 2021-02-24 22:39
@VortexAcherontic we'll have to pinpoint the source of that regression. If you can create a bug report describing what you said in the lutris/wine repo, that would be help us track the issue.

**Comment by VortexAcherontic** [comment] 2021-04-04 12:04
@strycore Just to let you know, with your latest 6.4 wine build the issues described in my [former comment](https://github.com/lutris/lutris/issues/3375#issuecomment-784962033) are solved now.

Also I would like to ask you to keep comments a little more civil next time someone is describing issues they had with the (tested) Lutris wine builds but not with Proton.

If I use Proton on certain games and then experiencing issues I know you guys are not responsible for it and hardly can keep track of it working nicely with Lutris not only because it is tied towards the Steam runtime and not the Lutris runtime and therefore would not have had reported any Proton related issues to you then.

Thank you in advance and especially for the 6.4 release I couldn't be happier.
