### ISSUE TITLE
Close Lutris after CLI rungame/rungameid

### ISSUE THREAD

**Issue by RobLoach** [lutris/lutris#578] opened 2017-06-06 01:31 UTC
When using `lutris lutris:rungame/%`, the Lutris window stays open after the game has quit. Would be great to:

1. Not have Lutris pop up at all
2. Quit Lutris after it was run

Originally reported in https://github.com/RobLoach/lutris-kodi-addon/issues/14 by @solbero . Another solution might be a `--no-gui` option or something.

## Testing

1. Open up your terminal
2. Run `lutris lutris:rungame/tuxracer`
3. Lutris window pops up and runs the game
4. When you quit the game, Lutris stays open.

**Comment by solbero** [comment] 2017-08-30 18:15
Implementing a feature which is similar in behaviour to Steam’s `steam steam://rungameid/####` would be a boon for people using Lutris on a HTPC. When launching games with the above command, the Steam GUI is never shown on screen.

As @RobLoach points out, as of now the Lutris GUI is left open after the user exits a game. For HTPC usage this is not ideal if the user is using a gamepad for navigation and gaming. As implemented, the user has to use a mouse and keyboard or simulate a mouse with the gamepad to close the GUI or assign ALT+F4 to a gamepad button.

**Comment by lefty420** [comment] 2017-11-27 22:31
I would also love a no gui mode. Any plans to include such a feature?

**Comment by strycore** [comment] 2017-11-27 22:37
@lefty420 this specific issue will be fixed in next release, other than that, there are no immediate plans to add other command line only features.

**Comment by lefty420** [comment] 2017-11-28 10:07
Thanks a lot :) That would make a massive difference when loading from other front ends. Well I can keep the keyboard in the draw at least ;)

**Comment by arustler** [comment] 2018-01-15 21:49
Awesome! Can’t wait for next release.

**Comment by sorsasampo** [comment] 2018-04-02 05:47
This would be very nice. Closely related, I think Lutris should immediately exit if the given game does not exist, instead of showing the UI and a traceback in console.

**Comment by tannisroot** [comment] 2019-02-13 18:06
This has regressed.
I am not sure if it still relevant as the workflow in 0.5.x has changed, but I will add it to 0.5.1 milestone so that we don't forget about it.

**Comment by seirl** [comment] 2019-03-11 19:42
@tannisroot Could you clarify what you mean by "new workflow"? As you mentioned, it regressed and my scripts now launch a lutris window instead of the game directly. Should I launch my games in a different fashion in 0.5.x?

**Comment by tannisroot** [comment] 2019-03-11 20:51
@seirl no, I've clarified this with strider and it's definitely a bug. Sorry for any inconvenience this might be causing.

**Comment by Vedrillan** [comment] 2019-03-19 19:29
@tannisroot Is it me or is this issue still in milestone 0.4.15 but not in 0.5.1 ? :p

**Comment by Vedrillan** [comment] 2019-03-20 20:25
I have made a proposal with PR #1885, it might not fix everything because I do not fully know what should be the excepted behavior, but at least Lutris window is not opening when running a game from command line or launchers.

**Comment by strycore** [comment] 2019-03-20 21:37
Thanks for the PR!

**Comment by AccountOneOff** [comment] 2019-03-26 05:20
It's popping up with 0.5.1.3

https://streamable.com/8z62x

**Comment by tannisroot** [comment] 2019-03-26 10:39
It was probably brought back by: https://github.com/lutris/lutris/commit/2efa72823b1b073e6a07cf4286a6d9089caff600

**Comment by strycore** [comment] 2019-03-26 17:40
It's not a probability, the fix for that ticket was crap.

**Comment by Vedrillan** [comment] 2019-03-26 23:26
That's not very nice x)

Issue remains that the do_activate method will show the window unconditionally, which judging by this ticket is not the expected behavior, so I moved it to the install command, which should now:
* not show the window for rungame/rungameid action, unless the provided game is not installed
* show the window in any other cases

You can review my new proposal in #1947.

**Comment by tway42** [comment] 2019-03-26 23:54
> That's not very nice x)

Yeah, in case you didn't know @strycore is the textbook example of toxicity in FOSS. Just look at how he welcomes newbie contributors when they send patches: https://github.com/lutris/lutris/pull/1243

I'd strongly suggest avoiding communication with him when possible until he grows up and learns how to behave professionally. There are a ton of cool welcoming projects to contribute to. Don't reward his hostility, you'll learn nothing by internalizing his abusive feedback anyway.

**Comment by strycore** [comment] 2019-03-27 01:43
> That's not very nice x)
> 
> Issue remains that the do_activate method will show the window unconditionally, which judging by this ticket is not the expected behavior, so I moved it to the install command, which should now:
> 
>     * not show the window for rungame/rungameid action, unless the provided game is not installed
> 
>     * show the window in any other cases
> 
> 
> You can review my new proposal in #1947.

No one's at fault here, I reviewed and merged the PR without catching the issue so I'm to blame as well. It's just that there were a lot of oversights and the specs for that feature are not clearly defined. Every one just wants to solve their own use case as the bigger picture isn't defined anywhere.

The whole thing is going to be addressed in the next release as the Patreon as reached the StatusNotifierItem goal. This goal re-introduces a "tray icon" and aims to solve window showing/hiding issues (whether the tray icon is enabled or not).

**Comment by strycore** [comment] 2019-03-27 02:36
> > That's not very nice x)
> 
> Yeah, in case you didn't know @strycore is the textbook example of toxicity in FOSS. Just look at how he welcomes newbie contributors when they send patches: #1243
> 
> I'd strongly suggest avoiding communication with him when possible until he grows up and learns how to behave professionally. There are a ton of cool welcoming projects to contribute to. Don't reward his hostility, you'll learn nothing by internalizing his abusive feedback anyway.

Turns out that handling a project at the scale of Lutris is not a simple task, and on top of that, it lacks the salary a professional environment and I get to reviews patches that wouldn't be accepted in a professional environment. So yeah, I might sometimes lose it and get harsher than necessary.
I am fully aware of the way I handled some issues, and while I know that this isn't the right way to address them, I have a hard time regretting any of that behavior. I did what I felt necessary and within my reach when working on a project with a huge growing list of issues. The project is now where I expected it to be when I released 0.5.0. The code base is still far from perfect and the issue count on github is still far too high but that will get improved in the future 0.5.x releases. As the overall quality of the code increase it will become less likely that we receive workarounds or hacks around existing legacy code.
It won't get easier to get contributions in Lutris but I can now review and handle them without being overwhelmed by the chaotic state of the project. Yeah, I told a bunch of people to shut up and let me fix a huge mess I was mostly responsible for, I don't handle high stress situations like that, especially if I'm not getting paid for it. The solution I found was to make the project less stressful, which I achieved, maybe at the price of losing some contributors but at least I've not burned out.
We still have a QA problem and the PR submission process has to be improved but as long as feel like the project is under control, I'm much more likely to be chill.

**Comment by strycore** [comment] 2019-04-04 07:00
This ticket is halfway fixed, the client will not show up when running with rungame but lutris will still be running when the game exits. It's not a huge issue, it even means faster startup times. This will receive a more complete fix with the tray icon / avoiding window duplicates tickets.

**Closed by strycore** 2019-04-04 07:00 UTC
