### ISSUE TITLE
[DEBIAN 12 KDE] Missing dependency python3-gi-cairo / No banners with the .deb

### ISSUE THREAD

**Issue by Xdavius** [lutris/lutris#4900] opened 2023-06-12 11:26 UTC
### Bug description

The games banner won't be shown on the app.

RESOLUTION : 

Adding python3-gi-cairo as dependency of lutris in the .deb

### How to Reproduce

Install Fresh Debian 12 KDE
Install Lutris with .deb or deb-get
Install a game (by searching an installer from lutris, ex: battle.net)
Install OK
No banner apper, juste the name.

### Expected behavior

The game banner is shown, on the main lutris page, over the name of the game.

### Log output

```shell
davius@Debian:~$ lutris
2023-06-12 13:25:18,678: Starting Lutris 0.5.13
2023-06-12 13:25:18,679: Running Mesa/X.org Mesa driver 22.3.6 on llvmpipe (LLVM 15.0.6, 256 bits) (0xffffffff)
2023-06-12 13:25:18,679: GPU: 15AD:0405 15AD:0405 (vmwgfx drivers)
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'


davius@Debian:~$ lutris -d
INFO     2023-06-12 13:26:26,339 [startup.init_lutris:209]:Starting Lutris 0.5.13
INFO     2023-06-12 13:26:26,341 [startup.check_driver:73]:Running Mesa/X.org Mesa driver 22.3.6 on llvmpipe (LLVM 15.0.6, 256 bits) (0xffffffff)
INFO     2023-06-12 13:26:26,341 [startup.check_driver:85]:GPU: 15AD:0405 15AD:0405 (vmwgfx drivers)
DEBUG    2023-06-12 13:26:26,477 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-12 13:26:26,528 [lutris.get_missing_game_ids:191]:Checking for missing games
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

### System Information

```shell
[System]
OS:              Debian GNU/Linux 12 bookworm
Arch:            x86_64
Kernel:          6.1.0-9-amd64
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600 6-Core Processor
Physical cores:  4
Logical cores:   4

[Memory]
RAM:             3.8 GB
Swap:            0.0 GB

[Graphics]
Vendor:          Mesa/X.org
OpenGL Renderer: llvmpipe (LLVM 15.0.6, 256 bits)
OpenGL Version:  4.5 (Compatibility Profile) Mesa 22.3.6
OpenGL Core:     4.5 (Core Profile) Mesa 22.3.6
OpenGL ES:       OpenGL ES 3.2 Mesa 22.3.6
Vulkan Version:  1.3.239
Vulkan Drivers:
```

### Media (optional)

![Screenshot_20230612_132231](https://github.com/lutris/lutris/assets/66792063/54a4f02c-fc07-4a87-8d1f-9da65279882c)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment] 2023-06-12 20:50
This is a dupe of #4857 for sure. It's fixed in the master. You've already found the workaround.

**Closed by danieljohnson2** 2023-06-12 20:50 UTC

**Comment by strycore** [comment] 2023-06-13 01:07
Was this the deb from the releases page or the one from OBS?

**Comment by Xdavius** [comment] 2023-06-13 02:13
> Was this the deb from the releases page or the one from OBS?

Release page one. (Don't understand OBS, I don't know what you are talking about, sorry)

**Comment by Xdavius** [comment] 2023-06-13 02:14
> This is a dupe of #4857 for sure. It's fixed in the master. You've already found the workaround.

Yes, it's the same. Sorry, I haven't found it when I was searching for an identical issue.

**Comment by strycore** [comment] 2023-06-13 05:49
> > Was this the deb from the releases page or the one from OBS?
> 
> Release page one. (Don't understand OBS, I don't know what you are talking about, sorry)

OBS is the OpenSUSE Build System, this is where we have our Debian repo. Instructions on how to add it are described in our download page: https://lutris.net/downloads
