### ISSUE TITLE
WoW crashes on 660ti.

### ISSUE THREAD

**Issue by Zerophase** [lutris/lutris#5211] opened 2024-01-01 21:42 UTC
WoW randomly freezes and crashes. Believe it has something to do with the 660ti era of graphics cards. I'm on Arch Linux by the way. My Lutris logs for the game are recently empty. Would launching from a desktop shortcut cause that?  Here are some old logs from while this issue was also occuring.

https://www.reddit.com/r/Lutris/comments/187w6io/wow_crashing_does_anyone_know_how_to_fix/

**Comment by danieljohnson2** [comment] 2024-01-01 21:56
Looks like a problem in the game or in Wine.

But you could get more log output by running lutris from a terminal. Run one, and use the command ``lutris -d``

Maybe that will provide more information.

**Comment by strycore** [comment] 2024-01-02 06:50
It is likely to be caused by the GPU which only supports Vulkan 1.2 ( https://www.techpowerup.com/gpu-specs/geforce-gtx-660-ti.c364 )

We have code to fallback to older version of DXVK / VKD3D but it is still imperfect. Try running the game with an older version of VKD3D. I believe VKD3D 2.6 is the last one supported by your GPU.

**Comment by strycore** [comment] 2024-01-02 06:52
Wait the Lutris subreddit is back? Who maintains it?

**Comment by strycore** [comment] 2024-01-05 23:36
Closing because we have said all that there is to say.

**Closed by strycore** 2024-01-05 23:36 UTC

**Comment by Zerophase** [comment] 2024-01-07 08:42
The logs from until the game freezes.

2024-01-06 13:01:22,099: Command 'vulkaninfo' not found on your system
2024-01-06 13:01:22,099: Command 'fluidsynth' not found on your system
2024-01-06 13:01:22,642: Starting Lutris 0.5.14
2024-01-06 13:01:22,644: Using NVIDIA drivers 470.199.02 for x86_64
2024-01-06 13:01:22,644: GPU: NVIDIA GeForce GTX 660 Ti
2024-01-06 13:01:22,644: GPU: 10DE:1183 1043:841F (nvidia drivers)
2024-01-06 13:01:22,697: Vulkan reports that the 'NVIDIA GeForce GTX 660 Ti' device has API version of 1.2.175. 1.3.0 is required for the latest DXVK.
2024-01-06 13:01:22,699: vulkaninfo not available, unable to list GPUs
2024-01-06 13:01:22,700: vulkaninfo not available, unable to list GPUs
Started initial process 378034 from /home/zerophase/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /home/zerophase/Games/world-of-warcraft/drive_c/Program Files (x86)/Battle.net/Battle.net.exe --exec=launch WoW --exec=focus play
Start monitoring process.
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
Initial process has exited (return code: 256)
wine client error:5c8: wine client error:4e8: write: Bad file descriptor
wine client error:29c: write: Bad file descriptor
wine client error:2c4: write: Bad file descriptor
Monitored process exited.
Exit with return code 256
2024-01-06 14:50:47,479: Game still running (state: running)
2024-01-06 14:50:47,479: Stopping World of Warcraft (wine)
Started initial process 4038543 from /home/zerophase/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /home/zerophase/Games/world-of-warcraft/drive_c/Program Files (x86)/Battle.net/Battle.net.exe --exec=launch WoW --exec=focus play
Start monitoring process.
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
Initial process has exited (return code: 256)
wine client error:4a4: write: Bad file descriptor
wine client error:5e4: write: Bad file descriptor
wine client error:688: write: Bad file descriptor
wine client error:568: write: Bad file descriptor
wine client error:2cc: Monitored process exited.
Exit with return code 256
2024-01-06 19:57:24,988: Game still running (state: running)
2024-01-06 19:57:24,988: Stopping World of Warcraft (wine)
Started initial process 593289 from /home/zerophase/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /home/zerophase/Games/world-of-warcraft/drive_c/Program Files (x86)/Battle.net/Battle.net.exe --exec=launch WoW --exec=focus play
Start monitoring process.
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
Initial process has exited (return code: 256)
wine client error:4f8: write: Bad file descriptor
wine client error:640: wine client error:6dc: write: Bad file descriptor
wine client error:5b8: write: Bad file descriptor
wine client error:29c: write: Bad file descriptor
wine client error:2c8: write: Bad file descriptor
Monitored process exited.
Exit with return code 256
2024-01-06 22:52:53,840: Game still running (state: running)
2024-01-06 22:52:53,841: Stopping World of Warcraft (wine)
Started initial process 1416709 from /home/zerophase/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /home/zerophase/Games/world-of-warcraft/drive_c/Program Files (x86)/Battle.net/Battle.net.exe --exec=launch WoW --exec=focus play
Start monitoring process.
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
Initial process has exited (return code: 256)
wine client error:4fc: write: Bad file descriptor
wine client error:640: write: Bad file descriptor
wine client error:6dc: write: Bad file descriptor
wine client error:6e4: write: Bad file descriptor
wine client error:648: wine client error:5b4: write: Bad file descriptor
wine client error:2a4: write: Bad file descriptor
wine client error:2cc: write: Bad file descriptor
Monitored process exited.
Exit with return code 256
2024-01-07 02:38:42,370: Game still running (state: running)
2024-01-07 02:38:42,370: Stopping World of Warcraft (wine)`

**Comment by danieljohnson2** [comment] 2024-01-07 11:56
I see a warning in there that your Vulkan is a bit old- 1.2.175. You need 1.3 to use the latest DXVK, and maybe that's what you need for this game?

Maybe you can get more recent drivers for your graphics card?

**Comment by strycore** [comment] 2024-01-08 23:31
> Maybe you can get more recent drivers for your graphics card?

It is pretty crucial that you get a clear understanding of API features in GPUs. 

Older GPUs can't just support the latest APIs  with driver updates. 
Just like a Riva TNT2 isn't going to support DirectX 12, a 660 Ti isn't going to support Vulkan 1.3 no matter which driver you install. 
Without acknowledging this, you are prone to making mistakes in how Lutris detects and handles Vulkan.

Make sure to look up GPUs at techpowerup.com to see what features they support.

**Comment by Zerophase** [comment] 2024-01-11 14:18
> > Maybe you can get more recent drivers for your graphics card?
> 
> It is pretty crucial that you get a clear understanding of API features in GPUs.
> 
> Older GPUs can't just support the latest APIs with driver updates. Just like a Riva TNT2 isn't going to support DirectX 12, a 660 Ti isn't going to support Vulkan 1.3 no matter which driver you install. Without acknowledging this, you are prone to making mistakes in how Lutris detects and handles Vulkan.
> 
> Make sure to look up GPUs at techpowerup.com to see what features they support.

Yeah, I might just need to buy a newer GPU to resolve the crashes.

My driver has been held back a bit since there were issues with other packages breaking from the newer NVidia driver for my card. If I remember correctly it was Cinnamon. Might be fixed by now. I should update. I don't believe that would resolve the issues, though.

I believe WoW runs fine on Windows with this card still. It certainly did in the past. Shouldn't earlier versions of Vulcan or DirectX translation to Vulcan be able to support the game on Linux? Wouldn't this be an issue with the Proton or Wine translation layer?

**Comment by Zerophase** [comment] 2024-01-12 04:00
Updated my driver and so far no crashes. They are random, though.

**Comment by strycore** [comment] 2024-01-13 00:38
> Shouldn't earlier versions of Vulcan or DirectX translation to Vulcan be able to support the game on Linux? 

If your GPU supports Vulkan 1.2 then yes, you'll be able to use older version of VKD3D and DXVK

> Wouldn't this be an issue with the Proton or Wine translation layer?

No, this is strictly about Vulkan, your GPU and your drivers. Wine doesn't matter here.
