### ISSUE TITLE
Remove D9VK option

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#2525] opened 2019-12-16 17:51 UTC
Since D9VK is now merged with DXVK.
Should be noted that before doing this, we need to fix all installers that use D9VK, which should be simple enough to do through some script.

**Comment by soredake** [comment] 2019-12-16 18:26
What about option to enable/disable d3d9 support from dxvk? Some games are work better wine wine d3d9

**Comment by tannisroot** [comment] 2019-12-16 18:27
Some? Which exactly?

**Comment by soredake** [comment] 2019-12-16 18:33
Oblivion, last time i tried (a month ago) with d9vk game crashes more often and fps is way worse than with wine d3d9, and with d9vk game cryostasis (checked a couple of day ago) is crashing at specific point of the game, but not with wine d3d9

**Comment by tannisroot** [comment] 2019-12-16 18:36
Message me on Discord.

**Comment by tuxutku** [comment] 2019-12-27 17:04
> Since D9VK is now merged with DXVK.

What about the older versions of dxvk?

**Comment by strycore** [comment] 2019-12-28 00:43
> What about the older versions of dxvk?

what about them? it's still possible to use the older versions of DXVK but if the intent is to use D9VK then just use the current build. This change would remove the ability to use pre-merge D9VK but I believe that this is not needed as the version merged in DXVK is more mature and bug free than what has existed before.
In the unlikely eventuality where a game would *require* an old version of D9VK due to a regression then I would suggest setting up D9VK from within the lutris installer. This has been done before, when D9VK wasn't an option in lutris.

**Comment by tannisroot** [comment] 2019-12-28 00:44
> In the unlikely eventuality where a game would require an old version of D9VK due to a regression
in that situation, I would actually suggest to file a bug report instead so that the regression get fixed in the next release.

**Comment by strycore** [comment] 2019-12-28 00:46
Yes, that is the preferred option of course. The setup of D9VK in an installer would just be a workaround until the regression is fixed in the current release.

**Closed** 2019-12-28 18:02 UTC

**Comment by yuusou** [comment] 2020-04-01 17:37
D9VK has support for Vulkan 1.0 GPUs but DXVK does not.
Up until yesterday my GTX 780M played Guild Wars 2 perfectly fine with D9VK but skips the GPU on DXVK.

**Comment by tannisroot** [comment] 2020-04-02 07:23
@yuusou just update your drivers/system, your card can support Vulkan 1.1 and newer just fine

**Comment by yuusou** [comment] 2020-04-02 07:57
@tannisroot the newer drivers do not support 880M or older GPUs. These are stuck on some iteration of nvidia's 390 blob.

**Comment by tannisroot** [comment] 2020-04-02 12:03
That's not true. Last version that supports this GPU is 418.113, which should support Vulkan 1.1..

**Comment by yuusou** [comment] 2020-04-02 19:39
@tannisroot you're right, thank you for that. Ubuntu doesn't have that version in it's repositories but the Nvidia binary blob of that version works fine with DXVK.

**Comment by tannisroot** [comment] 2020-04-03 09:19
You shouldn't install nvidia drivers from .run files if that's what you did. Instead use packages from Proprietary Graphics Drivers PPA: https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa
