### ISSUE TITLE
Lutris segfaults when I browse settings for my games

### ISSUE THREAD

**Issue by OlegAckbar** [lutris/lutris#5225] opened 2024-01-12 17:28 UTC
When I browse settings for my games sometime Lutris can crash with segmentation fault. I'm on Arch Linux with Lutris lutris-0.5.14
Here's a coredump:
[core.python3.1000.a6c697e2dc1846faa0ac3fa20b32c258.12589.1705079693000000.zip](https://github.com/lutris/lutris/files/13922294/core.python3.1000.a6c697e2dc1846faa0ac3fa20b32c258.12589.1705079693000000.zip)
```
          PID: 12589 (python3)
           UID: 1000 (oleg)
           GID: 1000 (oleg)
        Signal: 11 (SEGV)
     Timestamp: Fri 2024-01-12 20:14:53 MSK (8min ago)
  Command Line: python3 /usr/bin/lutris
    Executable: /usr/bin/python3.11
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-net.lutris.Lutris-f8a602ad8548447398c5825773c64f2d.scope
          Unit: user@1000.service
     User Unit: app-net.lutris.Lutris-f8a602ad8548447398c5825773c64f2d.scope
         Slice: user-1000.slice
     Owner UID: 1000 (oleg)
       Boot ID: a6c697e2dc1846faa0ac3fa20b32c258
    Machine ID: d7429de9dc7e4c6c80d4c871bef446d9
      Hostname: oleg-pc
       Storage: /var/lib/systemd/coredump/core.python3.1000.a6c697e2dc1846faa0ac3fa20b32c258.12589.1705079693000000.zst (present)
  Size on Disk: 14.1M
       Message: Process 12589 (python3) of user 1000 dumped core.
                
                Stack trace of thread 12968:
                #0  0x00007f9066cbad77 malloc (libc.so.6 + 0x9cd77)
                #1  0x00007f9066098763 g_malloc (libglib-2.0.so.0 + 0x62763)
                #2  0x00007f9062b25561 n/a (libgtk-3.so.0 + 0x125561)
                #3  0x00007f9062b2a7d9 n/a (libgtk-3.so.0 + 0x12a7d9)
                #4  0x00007f9062b2cf90 gtk_css_provider_load_from_data (libgtk-3.so.0 + 0x12cf90)
                #5  0x00007f906637f4f6 n/a (libffi.so.8 + 0x74f6)
                #6  0x00007f906637bf5e n/a (libffi.so.8 + 0x3f5e)
                #7  0x00007f906637eb73 ffi_call (libffi.so.8 + 0x6b73)
                #8  0x00007f90661de6d1 n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x2b6d1)
                #9  0x00007f90661dd090 n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x2a090)
                #10 0x00007f90661d00aa n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x1d0aa)
                #11 0x00007f9066fda8ec _PyObject_MakeTpCall (libpython3.11.so.1.0 + 0x1da8ec)
                #12 0x00007f9066fe4c23 _PyEval_EvalFrameDefault (libpython3.11.so.1.0 + 0x1e4c23)
                #13 0x00007f906702d36f n/a (libpython3.11.so.1.0 + 0x22d36f)
                #14 0x00007f90661db18d n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x2818d)
                #15 0x00007f9065fc46c0 g_closure_invoke (libgobject-2.0.so.0 + 0x146c0)
                #16 0x00007f9065ff2a36 n/a (libgobject-2.0.so.0 + 0x42a36)
                #17 0x00007f9065fe0a45 g_signal_emitv (libgobject-2.0.so.0 + 0x30a45)
                #18 0x00007f90661c8cf5 n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x15cf5)
                #19 0x00007f9066fe1098 n/a (libpython3.11.so.1.0 + 0x1e1098)

                #20 0x00007f9066ff2987 PyObject_Vectorcall (libpython3.11.so.1.0 + 0x1f2987)
                #21 0x00007f9066fe4c23 _PyEval_EvalFrameDefault (libpython3.11.so.1.0 + 0x1e4c23)
                #22 0x00007f906702d36f n/a (libpython3.11.so.1.0 + 0x22d36f)
                #23 0x00007f90661e154a n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x2e54a)
                #24 0x00007f9065fc46c0 g_closure_invoke (libgobject-2.0.so.0 + 0x146c0)
                #25 0x00007f9065ff2a36 n/a (libgobject-2.0.so.0 + 0x42a36)
                #26 0x00007f9065fe3a42 n/a (libgobject-2.0.so.0 + 0x33a42)
                #27 0x00007f9065fe3c77 g_signal_emit_valist (libgobject-2.0.so.0 + 0x33c77)
                #28 0x00007f9065fe3d34 g_signal_emit (libgobject-2.0.so.0 + 0x33d34)
                #29 0x00007f9062afdd13 n/a (libgtk-3.so.0 + 0xfdd13)
                #30 0x00007f9062afe440 gtk_combo_box_set_active_iter (libgtk-3.so.0 + 0xfe440)
                #31 0x00007f9062affa3c gtk_combo_box_set_active_id (libgtk-3.so.0 + 0xffa3c)
                #32 0x00007f906637f4f6 n/a (libffi.so.8 + 0x74f6)
                #33 0x00007f906637bf5e n/a (libffi.so.8 + 0x3f5e)
                #34 0x00007f906637eb73 ffi_call (libffi.so.8 + 0x6b73)
                #35 0x00007f90661de6d1 n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x2b6d1)
                #36 0x00007f90661dd090 n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x2a090)
                #37 0x00007f90661d00aa n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x1d0aa)
                #38 0x00007f9066fda8ec _PyObject_MakeTpCall (libpython3.11.so.1.0 + 0x1da8ec)
                #39 0x00007f9066fe4c23 _PyEval_EvalFrameDefault (libpython3.11.so.1.0 + 0x1e4c23)
                #40 0x00007f906702d36f n/a (libpython3.11.so.1.0 + 0x22d36f)
                #41 0x00007f9066fe8f3d _PyEval_EvalFrameDefault (libpython3.11.so.1.0 + 0x1e8f3d)
                #42 0x00007f906702d36f n/a (libpython3.11.so.1.0 + 0x22d36f)
                #43 0x00007f9066fe8f3d _PyEval_EvalFrameDefault (libpython3.11.so.1.0 + 0x1e8f3d)
                #44 0x00007f906702e223 n/a (libpython3.11.so.1.0 + 0x22e223)
                #45 0x00007f906702d540 n/a (libpython3.11.so.1.0 + 0x22d540)
                #46 0x00007f90670f0af8 n/a (libpython3.11.so.1.0 + 0x2f0af8)
                #47 0x00007f90670c8778 n/a (libpython3.11.so.1.0 + 0x2c8778)
                #48 0x00007f9066caa9eb n/a (libc.so.6 + 0x8c9eb)
                #49 0x00007f9066d2e7cc n/a (libc.so.6 + 0x1107cc)
                
                Stack trace of thread 12589:
                #0  0x00007f9066d2c73d syscall (libc.so.6 + 0x10e73d)
                #1  0x00007f9064f10cef n/a (libgdk-3.so.0 + 0x65cef)
                #2  0x00007f9064f49895 n/a (libgdk-3.so.0 + 0x9e895)
                #3  0x00007f9064f19d21 n/a (libgdk-3.so.0 + 0x6ed21)
                #4  0x00007f9064ef2ddd n/a (libgdk-3.so.0 + 0x47ddd)
                #5  0x00007f9064ef35e1 gdk_window_begin_draw_frame (libgdk-3.so.0 + 0x485e1)
                #6  0x00007f9062d5389c n/a (libgtk-3.so.0 + 0x35389c)
                #7  0x00007f9062befc8b gtk_main_do_event (libgtk-3.so.0 + 0x1efc8b)
                #8  0x00007f9064edeb77 n/a (libgdk-3.so.0 + 0x33b77)
                #9  0x00007f9064ef0b02 n/a (libgdk-3.so.0 + 0x45b02)
                #10 0x00007f9064ef5158 n/a (libgdk-3.so.0 + 0x4a158)
                #11 0x00007f9064ef5375 n/a (libgdk-3.so.0 + 0x4a375)
                #12 0x00007f9065fe3b73 n/a (libgobject-2.0.so.0 + 0x33b73)
                #13 0x00007f9065fe3c77 g_signal_emit_valist (libgobject-2.0.so.0 + 0x33c77)
                #14 0x00007f9065fe3d34 g_signal_emit (libgobject-2.0.so.0 + 0x33d34)
                #15 0x00007f9064eebfe9 n/a (libgdk-3.so.0 + 0x40fe9)
                #16 0x00007f9064ed869e n/a (libgdk-3.so.0 + 0x2d69e)
                #17 0x00007f90660913ee n/a (libglib-2.0.so.0 + 0x5b3ee)
                #18 0x00007f906608ff69 n/a (libglib-2.0.so.0 + 0x59f69)
                #19 0x00007f90660ee367 n/a (libglib-2.0.so.0 + 0xb8367)
                #20 0x00007f906608e162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
                #21 0x00007f9065e1bb66 g_application_run (libgio-2.0.so.0 + 0xdfb66)
                #22 0x00007f906637f4f6 n/a (libffi.so.8 + 0x74f6)
                #23 0x00007f906637bf5e n/a (libffi.so.8 + 0x3f5e)
                #24 0x00007f906637eb73 ffi_call (libffi.so.8 + 0x6b73)
                #25 0x00007f90661de6d1 n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x2b6d1)
                #26 0x00007f90661dd090 n/a (_gi.cpython-311-x86_64-linux-gnu.so + 0x2a090)
                #27 0x00007f9067016846 PyObject_Call (libpython3.11.so.1.0 + 0x216846)
                #28 0x00007f9066fe8f3d _PyEval_EvalFrameDefault (libpython3.11.so.1.0 + 0x1e8f3d)
                #29 0x00007f906709c484 n/a (libpython3.11.so.1.0 + 0x29c484)
                #30 0x00007f906709be6c PyEval_EvalCode (libpython3.11.so.1.0 + 0x29be6c)
                #31 0x00007f90670b9fc3 n/a (libpython3.11.so.1.0 + 0x2b9fc3)
                #32 0x00007f90670b63ea n/a (libpython3.11.so.1.0 + 0x2b63ea)
                #33 0x00007f90670cc723 n/a (libpython3.11.so.1.0 + 0x2cc723)
                #34 0x00007f90670cc095 _PyRun_SimpleFileObject (libpython3.11.so.1.0 + 0x2cc095)
                #35 0x00007f90670ca958 _PyRun_AnyFileObject (libpython3.11.so.1.0 + 0x2ca958)
                #36 0x00007f90670c51f8 Py_RunMain (libpython3.11.so.1.0 + 0x2c51f8)
                #37 0x00007f906708e79b Py_BytesMain (libpython3.11.so.1.0 + 0x28e79b)
                #38 0x00007f9066c45cd0 n/a (libc.so.6 + 0x27cd0)
                #39 0x00007f9066c45d8a __libc_start_main (libc.so.6 + 0x27d8a)
                #40 0x0000564a940c7045 _start (python3.11 + 0x1045)
                
                Stack trace of thread 12591:
                #0  0x00007f9066d20f6f __poll (libc.so.6 + 0x102f6f)
                #1  0x00007f90660ee2b6 n/a (libglib-2.0.so.0 + 0xb82b6)
                #2  0x00007f906608e162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
                #3  0x00007f906608e1b2 n/a (libglib-2.0.so.0 + 0x581b2)
                #4  0x00007f90660c1a05 n/a (libglib-2.0.so.0 + 0x8ba05)
                #5  0x00007f9066caa9eb n/a (libc.so.6 + 0x8c9eb)
                #6  0x00007f9066d2e7cc n/a (libc.so.6 + 0x1107cc)
                
                Stack trace of thread 12612:
                #0  0x00007f9066d2c73d syscall (libc.so.6 + 0x10e73d)
                #1  0x00007f90660e9cd3 g_cond_wait_until (libglib-2.0.so.0 + 0xb3cd3)
                #2  0x00007f906605b185 n/a (libglib-2.0.so.0 + 0x25185)
                #3  0x00007f906605b2e7 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x252e7)
                #4  0x00007f90660c437e n/a (libglib-2.0.so.0 + 0x8e37e)
                #5  0x00007f90660c1a05 n/a (libglib-2.0.so.0 + 0x8ba05)
                #6  0x00007f9066caa9eb n/a (libc.so.6 + 0x8c9eb)
                #7  0x00007f9066d2e7cc n/a (libc.so.6 + 0x1107cc)
                
                Stack trace of thread 12590:
                #0  0x00007f9066d2c73d syscall (libc.so.6 + 0x10e73d)
                #1  0x00007f90660e92f7 g_cond_wait (libglib-2.0.so.0 + 0xb32f7)
                #2  0x00007f906605b1b4 n/a (libglib-2.0.so.0 + 0x251b4)
                #3  0x00007f90660c3a8e n/a (libglib-2.0.so.0 + 0x8da8e)
                #4  0x00007f90660c1a05 n/a (libglib-2.0.so.0 + 0x8ba05)
                #5  0x00007f9066caa9eb n/a (libc.so.6 + 0x8c9eb)
                #6  0x00007f9066d2e7cc n/a (libc.so.6 + 0x1107cc)
                
                Stack trace of thread 12592:
                #0  0x00007f9066d20f6f __poll (libc.so.6 + 0x102f6f)
                #1  0x00007f90660ee2b6 n/a (libglib-2.0.so.0 + 0xb82b6)
                #2  0x00007f9066090b97 g_main_loop_run (libglib-2.0.so.0 + 0x5ab97)
                #3  0x00007f9065e4e19c n/a (libgio-2.0.so.0 + 0x11219c)
                #4  0x00007f90660c1a05 n/a (libglib-2.0.so.0 + 0x8ba05)
                #5  0x00007f9066caa9eb n/a (libc.so.6 + 0x8c9eb)
                #6  0x00007f9066d2e7cc n/a (libc.so.6 + 0x1107cc)
                ELF object binary architecture: AMD x86-64
```

**Comment by danieljohnson2** [comment] 2024-01-13 00:03
I suspect this may be a dupe of #5092, since the locale drop down is present in the game drop down as well.

The master branch has an update that is supposed to work around this problem (and tame the absolutely enormous locale drop-down). Please download the latest code and run the 'bin/lutris' script with. No need to install anything. Try to access the preferences; make sure you visit all the tabs. Still crashy?

**Comment by OlegAckbar** [comment] 2024-01-13 22:16
@danieljohnson2 yes, that seemed to be the issue, can't reproduce it on master branch.

**Comment by danieljohnson2** [comment] 2024-01-14 01:01
And 0.5.15 just went out. I think we're done here; closing.

**Closed by danieljohnson2** 2024-01-14 01:01 UTC
Labels: can't reproduce
