### ISSUE TITLE
Winesteam exits after login; doesn't show normal steam window (UPDATE - see comments)

### ISSUE THREAD

**Issue by Cether-Skye** [lutris/lutris#960] opened 2018-07-03 04:18 UTC
As it says in the title; and this is if I can even get past login, which is a bug reported in another issue.

I'm not sure what information would be helpful to include here since I'm new to using Lutris, and I've only tried following some online tutorials on how to install windows games with Lutris and wine. So if you've any additional basic tips/data requests, I'd be happy to listen/provide. For now, I suppose system specs and basic repro steps will suffice.

**System specs:**
OS: Ubuntu 18.0.4.0 (only 64 bit versions)
Desktop: Latest Gnome
CPU: i7 8700k
Graphics: Nvidia GTX 1080 Ti, driver ver 396
Monitor: Single, 2560x1440p G-Sync 165hz Dell

**Repro steps:**
1) Install Lutris according to [these instructions](https://lutris.net/downloads/)
2) Open Lutris and go to Lutris > manage runners > install winesteam (leave all configs as default)
3) Close and reopen Lutris after installation
4) Run winesteam
5) Login (I had 2FA enabled)
6) Wait a minute or two

**Observed result:**
Usual steam update window shows. Downloads some stuff. Exits - searching for processes like 'steam' in system monitor will occasionally show results that disappear after a few minutes. Occasionally the process will turn into a zombie and refuse to be killed until Lutris is closed.

I've tried using different wine versions but it seems the winesteam installer always insists on using staging 3.7 as it downloads that first. I've also tried ticking off the option to close steam after a game exits. No dice. I've also messed with DXVK settings but again, no results. When I attempt to install games using the scripts available on the main Lutris site, I see similar behavior, and the window running the installation script spins endlessly with no error.

Thoughts?

UPDATE - problem seems to be caused by Wine missing dependencies only available through a manual installation?

**Comment by Cether-Skye** [comment] 2018-07-04 21:38
Update - it seems my issue has been resolved by installing the latest version of wine-staging on my system. According to the author of [this video](https://www.youtube.com/watch?v=XfzWHjr2QyA), Lutris doesn't install all the dependencies necessary to make wine run.

Although, that deserves its own issue - shouldn't the Lutris client install all Wine dependencies, not just Wine itself, when using it to install new versions?

**Comment by strycore** [comment] 2018-08-16 06:47
We can't reliably provide wine as a dependency for all distros but we can detect that wine is not installed and prompt the user to install it with a link to our wiki. That's mostly implemented and will be available in 0.4.19. Closing as duplicate of #761

**Closed by strycore** 2018-08-16 06:47 UTC
