### ISSUE TITLE
BUG: League of legends hangs due Lutris WINE.

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#2103] opened 2019-05-02 20:43 UTC
League of legensd in lutris using latest installer (https://lutris.net/games/install/3552/view) results in bugsplash after the installation (https://user-images.githubusercontent.com/11302521/57105482-c43a9500-6d22-11e9-9beb-4004e269a193.png) if evecuted again it tried to repair itself (https://i.imgur.com/FZqoW7w.png) and hangs on `DEBUG    2019-05-02 22:37:57,786 [lutriswindow.on_game_updated:698]:Updating game League of Legends (wine)`. -> Suspect WINE issue.

![image](https://user-images.githubusercontent.com/11302521/57105482-c43a9500-6d22-11e9-9beb-4004e269a193.png)

## SYSTEM-INFO
![image](https://user-images.githubusercontent.com/11302521/57105497-ce5c9380-6d22-11e9-9ce4-7bd70a455f4f.png)

Logs from bugsplat: https://drive.google.com/drive/folders/1XKTQc_z8NB-0gB-CjVA4ck87AwrDSUZB?usp=sharing

lutris log: http://dpaste.com/05TBKC1

---

## SELF-DIAGNOSIS
![image](https://user-images.githubusercontent.com/11302521/57107541-2d70d700-6d28-11e9-9a7b-5b5a989584db.png)

Issue not present on my system using `wine-4.7 (Staging)` from gentoo as 
```
app-emulation/wine-staging-4.7_p1-r1:4.7_p1::bobwya  USE="X alsa fontconfig jpeg mono mp3 opencl opengl osmesa png pulseaudio realtime run-exes samba sdl2 ssl threads truetype udev vkd3d vulkan xcomposite xml -capi -cups -custom-cflags -dos -faudio -ffmpeg -gecko -gphoto2 -gsm -gstreamer -kerberos -lcms -ldap -ncurses -netapi -nls -odbc -openal -oss -pcap -perl -pipelight (-prefix) -prelink -s3tc -scanner (-selinux) -test -themes -udisks -v4l -vaapi -xinerama" ABI_X86="32 64 (-x32)" 0 KiB
```

Conclusion: Lutris WINE issue.

**Comment by AccountOneOff** [comment] 2019-05-03 01:30
>Conclusion: Lutris WINE issue.

Nope, if you look at the Wine log you posted you'd see that the issue is due to missing Wine dependencies.

```
0009:err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
0009:err:winediag:load_gssapi_krb5 Failed to load libgssapi_krb5, Kerberos SSP support will not be available.
0009:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0009:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
```

**Comment by strycore** [comment] 2019-05-03 02:26
this is a bug with how Lutris is packaged on Bedrock Linux, that wouldn't happen if the dependencies were correctly installed. Closing as this is a distribution specific issue.

**Closed by strycore** 2019-05-03 02:26 UTC

**Comment by Kreyren** [comment] 2019-05-03 03:18
That issue is present on debian buster that is sandboxed and running lutris, suspecting it beeing issue with packaging on debian then assuming that i'm investigating on request from community member that has same issue on ubuntu.. investigating
