### ISSUE TITLE
Cod2 Steam Transparent Textures Intel HD 5500

### ISSUE THREAD

**Issue by sdsddsd1** [lutris/lutris#2128] opened 2019-05-11 17:30 UTC
Hello,
I installed Call of Duty 2 with Lutris from Steam. The game starts single and multiplayer. But the graphics are transparent like a wallhack sort of.
First atempt on Manjaro. Second atempt on Swagarch. First the game ran fine but then the same issue again.
My hardware is a HP Elitebook 840 G2 with HD 5500 graphics.

Thanks

**Comment by telanus** [comment] 2019-05-12 19:31
Think it might be a driver issue as mine runs fine: 
![2019-05-12 0857](https://user-images.githubusercontent.com/19357986/57586915-22266400-74fd-11e9-9dac-9c4352794bc0.png)

Just played for 90 minutes

**Comment by tannisroot** [comment] 2019-05-16 08:31
This is not a bug in Lutris client and is probably due to the fact that Broadwell iGPUs only have partial Vulkan support. Try disabling DXVK and trying out wined3d.
Closing

**Closed by tannisroot** 2019-05-16 08:31 UTC
