### ISSUE TITLE
Lutris uses 100% of one core after game ends

### ISSUE THREAD

**Issue by HamishTPB** [lutris/lutris#573] opened 2017-05-20 10:39 UTC
Distro: Antergos
Lutris: 0.4.10 (Arch aur)

Info from Lutris script:
Desktop Info for Lutris

Environment variables:
DESKTOP_SESSION=i3
GDMSESSION=i3
SHELL=/bin/bash

Distribution:
Linux polarbear 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux

Running desktop processes:
56 kdevtmpfs
21457 kdeinit5
21466 kded5

OpenGL info:
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 660/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 381.22
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 381.22
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 381.22
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

RAM info:
              total        used        free      shared  buff/cache   available
Mem:           7.8G        3.6G        1.1G        191M        3.1G        3.7G
Swap:          9.0G        1.2M        9.0G

CPU info:
model name      : AMD FX(tm)-8350 Eight-Core Processor

Wine info:
Wine installed system wide: /usr/bin/wine
Version: wine-2.8

Symptoms:
When I run a game from Lutris, even  if the game runs fine, once the game ends then Lutris uses 100% of one of my CPU cores until I quit Lutris, sometimes Lutris hangs there and I have to kill it too. CPU usage becomes normal again once Lutris is closed/killed.

**Comment by HamishTPB** [comment] 2017-05-20 12:32
I just did another test: the system was taking 90-100% CPU on one core while running a MAME game (fairly normal) As soon as I quit the game Lutris started using 100% on a different core and stayed solid at 100% (the CPU fan started working very loud and very hard) until I quit Lutris. I don't know if this helps but I know it is best to give as much info as possible for bug reports. The same thing happens with other runners too (even if the game fails to run).

**Comment by HamishTPB** [comment] 2017-05-20 12:47
I have tested several runners now with the same result. Even Steam native.

I tried running a game on steam manually and it used 100% of one core for the game.
When I run the same game via Lutris the game takes 100% of a core and Lutris take 100% of another core and the fan goes crazy again. Lutris still doesn't release the CPU core until closed even after the game is.

**Comment by strycore** [comment] 2017-05-22 22:36
I managed to reproduce the issue, and it will be fixed in next release.

**Comment by Leeo97one** [comment] 2017-06-03 15:03
The problem is still present for me in the 0.4.11.1 version.

**Comment by Leeo97one** [comment] 2017-06-05 18:51
@strycore 
In fact, the problem is still present if you run Steam (or Wine Steam) from the left menu (right-click → Run) and close it.

**Comment by HamishTPB** [comment] 2017-06-05 19:15
Odd - If I do that (manually run winesteam then close it) I do get the bug again but it has gone in normal use.

**Comment by strycore** [comment] 2017-06-05 21:11
It's not odd, not odd at all, all of this makes sense (to me at least ;) I'll push a fix soon :p

**Comment by setzer22** [comment] 2017-08-13 10:50
Should this be fixed by now? I am getting the same issue as the OP in 0.4.13. After closing any game, CPU usage goes to 100%

**Comment by kozec** [comment] 2017-12-08 18:22
Hello, I'm getting same problem with 0.4.10 and wine runner.

**Comment by strycore** [comment] 2018-05-09 05:51
Still not sure if 100% fixed.

**Comment by Medath** [comment] 2018-10-28 13:08
Is someone still able to reproduce this?

**Comment by HamishTPB** [comment] 2018-10-29 14:22
I haven't seen the problem for quite some time.

**Comment by strycore** [comment] 2018-10-29 20:28
The process monitor will be re-architectured, this will eventually get rid of any possible remaining issues. Marking this one as closed since I haven't noticed this issue in particular in a while

**Closed by strycore** 2018-10-29 20:28 UTC
Labels: bug, high priority
