### ISSUE TITLE
Sandboxing not working after prefix update during same launch

### ISSUE THREAD

**Issue by telans** [lutris/lutris#2206] opened 2019-06-21 04:08 UTC
**Describe the bug**

Sandboxing directories works like a charm until the prefix of the application needs updating. 
![Screenshot_20190621_160729](https://user-images.githubusercontent.com/45819748/59896969-b5c54b80-943e-11e9-8a86-2bbfe33ae57f.png)

Either due to wine version update or changing the runner etc. When this happens wine (lutris?) fails to detect the sandbox directory and the below happens: (My Games should be inside sandbox/My Documents/)
![Screenshot_20190621_155623](https://user-images.githubusercontent.com/45819748/59896584-3aaf6580-943d-11e9-98e7-9a294731fa86.png)

Relaunching after the prefix updated fixes this issue.

**Expected behavior**

Lutris/wine should maintain the sandboxed directories after a prefix update, I think this might require re-linking the directories after the prefix has finished updating, but before the selected application is launched.

**Current behavior**

When launching an application and it requiring updating the wine version, any program files created by the application will land outside of the sandbox directory. Relaunching after this works as it should.

**Steps to reproduce**

Set sandbox directory
Run wine/application and access doccuments through sandbox directory
Change wine version for application under runner options
Notice files created/accessed inside application and outside of sandbox directory

**Lutris debugging output**

[lutris-d-0.log](https://github.com/lutris/lutris/files/3312942/lutris-d-0.log) (requiring prefix update, sandbox failing)

[lutris-d-1.log](https://github.com/lutris/lutris/files/3312941/lutris-d-1.log) (no prefix update, sandbox working)

Note that there is not mention of sandboxing in these logs that I could see.

**System information**

[lutris-issue-report.log](https://github.com/lutris/lutris/files/3312953/lutris-issue-report.log) (removed some info)

**Comment by tannisroot** [comment] 2020-03-22 20:57
We had numerous sandbox fixes since this issue came out and I can't reproduce this, so closing.

**Closed by tannisroot** 2020-03-22 20:57 UTC
