### ISSUE TITLE
Enabling runners without installing

### ISSUE THREAD

**Issue by moll** [lutris/lutris#1154] opened 2018-10-06 12:33 UTC
Hey,

I'm using the system's (Arch Linux) package manager to install various emulators. There fortunately is a setting in all runners to use a custom executable, however I can't seem to find a way to enable runners without having Lutris install its own binaries first. Deleting the runner's folder in `.local/share/lutris` seems to have no adverse effect, but that seems a bit silly for a workflow. :)

Thanks!

**Comment by Kreyren** [comment] 2018-10-07 04:29
@moll What exactly are you trying to do? `Disable Lutris Runtime` in  GAME > Configure > System options not a solution?

**Comment by AlexanderRavenheart** [comment] 2018-10-07 06:41
The issue is the fact that the current flow is to download the runner, then customize it to not use the downloaded one but use the system installed one and then delete the downloaded one. That is the only way to have a runner appear in Lutris that uses the system installed executable instead of the Lutris provided one and it should not be so.

**Comment by Kreyren** [comment] 2018-10-07 06:47
Agreed if true

**Comment by bebop350** [comment] 2018-10-08 03:09
It doesn't seem necessary to download the runner to specify a system installed runner. I've added several runners (namely gzdoom and dosbox, and tested with Reicast) by pointing the runner config to the desired program and then refreshing the runners or restarting Lutris. Maybe I missed some files but I can't find where anything was downloaded. Unless it's an issue with the latest version of Lutris, as I'm still using an older version.

**Comment by AlexanderRavenheart** [comment] 2018-10-08 06:15
The runner config is only accessible after installing a runner from Lutris.

**Comment by bebop350** [comment] 2018-10-08 21:18
> The runner config panel is only accessible after installing a runner from Lutris GUI.

It seems one can configure any runner even if that runner is not installed (no need to download anything).

Perhaps you mean you must have at least one runner installed to access the "manage runners" section?

**Comment by moll** [comment] 2018-10-08 21:21
You can't pick a runner in any game config before it's enabled and it's enabled only when it's installed. ;)

**Comment by strycore** [comment] 2018-10-09 07:12
we can provide something to install runners from the system

**Comment by moll** [comment] 2018-10-09 09:09
What is necessary to install? Isn't just specifying a path to a shared executable sufficient?

**Comment by moll** [comment] 2018-10-09 16:00
Hehe, it's funny how many times the crux of this issue needs reiterating. @Medath, no-one's disputed being able to configure them. See https://github.com/lutris/lutris/issues/1154#issuecomment-427983071

**Comment by Medath** [comment] 2018-10-09 16:45
I'm not sure if I understand your issue. After configuring a custom executable (On a completely fresh Lutris config) the runner appears in my list and I can use it without issues while my runners folder is still empty (tested with ppsspp installed from the Solus Software Center and absolutely no Lutris runners downloaded).

**Comment by moll** [comment] 2018-10-09 17:17
Hmm, you're right. My bad. That is indeed true once you set a custom executable path. I confirmed looking at `lutris/runners/runner.py` that `is_installed`, for almost all runners, only checks whether an executable exists. Executable paths themselves by default seem to be hardcoded to relative paths to runners in `~/.local/share/lutris/runners`. I suppose my initial confusion was because I was expecting Lutris to pick the runner's executable up from `$PATH` and didn't expect I'd have to set the path, and that it be hidden under advanced options. I guess I finally did so only after installing the Lutris runtime for that runner, deleting it manually, the runner failing and then going in to fix it.

From a technical issue this seems to now turn to a user experience issue. The WINE runner seems to have a system option built-in that works out of the box. Maybe every runner could first see if it's installed system-wide. Or we could come up with a more informative flow to "enable and pick a path" for a system's runner.

**Comment by Sukid** [comment] 2018-11-25 00:45
Month old but yeah, I gotta say I agree with the above. While it's already possible without downloading them it would really be a lot better if Lutris could autodetect system installed emulators and add them already much like it does with Wine and native games.

**Comment by strycore** [comment] 2018-11-25 01:07
Please note that Lutris will **always** default to our builds, because that's the way the project is designed.
This ticket is about letting users override the default, not changing it.

**Comment by strycore** [comment] 2022-04-08 23:48
I believe this is fixed in 0.5.10 since we now show the "Configure" button at all times, allowing to set a custom exe for the runner.

**Closed by strycore** 2022-04-08 23:48 UTC
